# Generated by Django 5.1.7 on 2025-04-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('pat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('houseHoldNo', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('Sitio', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('pat_type', models.CharField(default='Regular', max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'patient_record',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('vacrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.patientrecord')),
            ],
            options={
                'db_table': 'vaccination_record',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_bp_systolic', models.CharField(max_length=100)),
                ('vital_bp_diastolic', models.CharField(max_length=100)),
                ('vital_temp', models.CharField(max_length=100)),
                ('vital_RR', models.CharField(max_length=100)),
                ('vital_o2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationrecord')),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('vachist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vachist_doseNo', models.CharField(max_length=100)),
                ('vachist_status', models.CharField(max_length=100)),
                ('vachist_pulseRate', models.CharField(max_length=100)),
                ('vachist_bp_systolic', models.CharField(max_length=100)),
                ('staff_id', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vitalsigns')),
            ],
            options={
                'db_table': 'vaccination_history',
            },
        ),
    ]
