# Generated by Django 5.1.6 on 2025-12-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('vacrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacrec_totaldose', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'vaccination_record',
            },
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('vachist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vachist_doseNo', models.PositiveIntegerField(default=0)),
                ('vachist_status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_administered', models.DateField()),
                ('signature', models.TextField(blank=True, default='', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vaccination_histories', to='administration.staff')),
                ('followv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.followupvisit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='administration.staff')),
                ('vac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='inventory.vaccinelist')),
                ('vacStck_id', models.ForeignKey(db_column='vacStck_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='inventory.vaccinestock')),
                ('vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.vitalsigns')),
                ('vacrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vaccinationrecord')),
            ],
            options={
                'db_table': 'vaccination_history',
            },
        ),
    ]
