# Generated by Django 5.1.6 on 2025-06-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('inventory', '0075_alter_antigentransaction_vacstck_id_and_more'),
        # ('vaccination', '0001_initial'),
    ]

    operations = [
    #     migrations.CreateModel(
    #         name='VaccinationRecord',
    #         fields=[
    #             ('vacrec_id', models.BigAutoField(primary_key=True, serialize=False)),
    #             ('vacrec_totaldose', models.PositiveIntegerField(default='0')),
    #             ('created_at', models.DateTimeField(auto_now_add=True)),
    #             ('updated_at', models.DateTimeField(auto_now=True)),
    #             # ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patientrecords.patientrecord')),
    #         ],
    #         options={
    #             'db_table': 'vaccination_record',
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name='VaccinationHistory',
    #         fields=[
    #             ('vachist_id', models.BigAutoField(primary_key=True, serialize=False)),
    #             ('vachist_doseNo', models.PositiveIntegerField(default='0')),
    #             ('vachist_age', models.CharField(default='', max_length=100)),
    #             ('vachist_status', models.CharField(default='Pending', max_length=100)),
    #             ('created_at', models.DateTimeField(auto_now_add=True)),
    #             ('assigned_to', models.PositiveIntegerField(blank=True, null=True)),
    #             # ('staff_id', models.PositiveIntegerField(default=1)),
    #             # ('followv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.followupvisit')),
    #             # ('vacStck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='inventory.vaccinestock')),
    #             ('vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.vitalsigns')),
    #             ('vacrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vaccinationrecord')),
    #         ],
    #         options={
    #             'db_table': 'vaccination_history',
    #         },
    #     ),
    ]
