# Generated by Django 5.1.7 on 2025-04-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='Province',
            new_name='province',
        ),
    ]
