# Generated by Django 5.1.7 on 2025-04-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_rename_province_patientrecord_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='houseHoldNo',
        ),
    ]
