# Generated by Django 5.1.6 on 2025-04-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesrecords',
            name='pat_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='serv_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vacStck_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vacrec_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vital_id',
        ),
        migrations.DeleteModel(
            name='PatientRecordSample',
        ),
        migrations.DeleteModel(
            name='ServicesRecords',
        ),
        migrations.DeleteModel(
            name='VaccinationRecord',
        ),
        migrations.DeleteModel(
            name='VaccinationHistory',
        ),
        migrations.DeleteModel(
            name='VitalSigns',
        ),
    ]
