# Generated by Django 5.1.7 on 2025-04-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_remove_patientrecord_householdno'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='householdno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
