# Generated by Django 5.1.6 on 2025-04-20 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0018_alter_patientrecord_pat_id'),
        ('vaccination', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesrecords',
            name='pat_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='serv_id',
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='patrec_id',
            field=models.ForeignKey(db_column='patrec_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patientrecords.patientrecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_RR',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_diastolic',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_systolic',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_o2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_temp',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PatientRecordSample',
        ),
        migrations.DeleteModel(
            name='ServicesRecords',
        ),
    ]
