# Generated by Django 5.1.7 on 2025-04-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_patientrecord_householdno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='Sitio',
            new_name='sitio',
        ),
    ]
