# Generated by Django 5.1.6 on 2025-04-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_remove_servicesrecords_pat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationhistory',
            old_name='vacStck_id',
            new_name='vacStck',
        ),
        migrations.RenameField(
            model_name='vaccinationhistory',
            old_name='vacrec_id',
            new_name='vacrec',
        ),
        migrations.RenameField(
            model_name='vaccinationhistory',
            old_name='vital_id',
            new_name='vital',
        ),
    ]
