# Generated by Django 5.1.7 on 2025-04-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_rename_sitio_patientrecord_sitio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='address',
        ),
    ]
