# Generated by Django 5.1.7 on 2025-04-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_remove_patientrecord_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vachist_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
