# Generated by Django 5.1.6 on 2025-04-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_rename_vacstck_id_vaccinationhistory_vacstck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='patrec_id',
        ),
        migrations.DeleteModel(
            name='VaccinationHistory',
        ),
        migrations.DeleteModel(
            name='VitalSigns',
        ),
        migrations.DeleteModel(
            name='VaccinationRecord',
        ),
    ]
