# Generated by Django 5.1.6 on 2025-04-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0075_alter_antigentransaction_vacstck_id_and_more'),
        ('patientrecords', '0018_alter_patientrecord_pat_id'),
        ('vaccination', '0007_remove_vaccinationrecord_patrec_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vital_bp_systolic', models.CharField(max_length=100)),
                ('vital_bp_diastolic', models.CharField(max_length=100)),
                ('vital_temp', models.CharField(max_length=100)),
                ('vital_RR', models.CharField(max_length=100)),
                ('vital_o2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('vacrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'vaccination_record',
            },
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('vachist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vachist_doseNo', models.CharField(max_length=100)),
                ('vachist_status', models.CharField(max_length=100)),
                ('vachist_age', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_id', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacStck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='inventory.vaccinestock')),
                ('vacrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vaccinationrecord')),
                ('vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vitalsigns')),
            ],
            options={
                'db_table': 'vaccination_history',
            },
        ),
    ]
