# Generated by Django 5.1.7 on 2025-04-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_vaccinationhistory_vachist_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='created_at',
        ),
        migrations.CreateModel(
            name='ServicesRecords',
            fields=[
                ('serv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serv_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.patientrecord')),
            ],
            options={
                'db_table': 'services_records',
            },
        ),
    ]
