# Generated by Django 5.1.7 on 2025-04-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0008_remove_vaccinationhistory_created_at_servicesrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vachist_bp_diastolic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
