# Generated by Django 5.1.6 on 2025-04-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vital',
        ),
        migrations.DeleteModel(
            name='VitalSigns',
        ),
    ]
