# Generated by Django 5.1.6 on 2025-04-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_remove_antigentransaction_antt_type_and_more'),
        ('vaccination', '0008_remove_vaccinationhistory_created_at_servicesrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vachist_bp_systolic',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vachist_pulseRate',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='pat_id',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='id',
        ),
        migrations.AddField(
            model_name='vaccinationhistory',
            name='assigned_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vacStck_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinestock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vacrec_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='serv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicesrecords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vitalsigns'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_RR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_diastolic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_systolic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_o2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
