# Generated by Django 5.1.6 on 2025-04-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0009_remove_vaccinationhistory_vachist_bp_systolic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesrecords',
            name='pat_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='serv_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vacStck_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vacrec_id',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vital_id',
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
        migrations.DeleteModel(
            name='ServicesRecords',
        ),
        migrations.DeleteModel(
            name='VaccinationRecord',
        ),
        migrations.DeleteModel(
            name='VaccinationHistory',
        ),
        migrations.DeleteModel(
            name='VitalSigns',
        ),
    ]
