<<<<<<<< HEAD:server-1/apps/administration/migrations/0002_initial.py
# Generated by Django 5.2 on 2025-04-17 14:24
========
# Generated by Django 5.1.7 on 2025-04-16 12:12
>>>>>>>> master:server-2/apps/vaccination/migrations/0010_vaccinationhistory_serv_id.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccination', '0009_vaccinationhistory_vachist_bp_diastolic'),
    ]

    operations = [
        migrations.AddField(
<<<<<<<< HEAD:server-1/apps/administration/migrations/0002_initial.py
            model_name='staff',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='profiling.residentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('feat', 'pos')},
========
            model_name='vaccinationhistory',
            name='serv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicesrecords'),
            preserve_default=False,
>>>>>>>> master:server-2/apps/vaccination/migrations/0010_vaccinationhistory_serv_id.py
        ),
    ]
