# Generated by Django 5.1.7 on 2025-04-16 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0009_vaccinationhistory_vachist_bp_diastolic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='serv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicesrecords'),
            preserve_default=False,
        ),
    ]
