# Generated by Django 5.1.6 on 2025-04-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0019_vitalsigns'),
        ('vaccination', '0009_remove_vaccinationhistory_vital_delete_vitalsigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.vitalsigns'),
        ),
    ]
