# Generated by Django 5.1.7 on 2025-04-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0010_vaccinationhistory_serv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='serv_id',
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='serv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicesrecords'),
            preserve_default=False,
        ),
    ]
