# Generated by Django 5.1.6 on 2025-04-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0010_vaccinationhistory_vital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccinationHistory',
        ),
    ]
