# Generated by Django 5.1.6 on 2025-04-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0074_remove_antigentransaction_antt_type_and_more'),
        ('vaccination', '0010_remove_servicesrecords_pat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('pat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('householdno', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('pat_type', models.CharField(default='Regular', max_length=100)),
            ],
            options={
                'db_table': 'patient_record',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vital_bp_systolic', models.CharField(blank=True, max_length=100, null=True)),
                ('vital_bp_diastolic', models.CharField(blank=True, max_length=100, null=True)),
                ('vital_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('vital_RR', models.CharField(blank=True, max_length=100, null=True)),
                ('vital_o2', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
        migrations.CreateModel(
            name='ServicesRecords',
            fields=[
                ('serv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serv_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.patientrecord')),
            ],
            options={
                'db_table': 'services_records',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('vacrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicesrecords')),
            ],
            options={
                'db_table': 'vaccination_record',
            },
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('vachist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vachist_doseNo', models.CharField(max_length=100)),
                ('vachist_status', models.CharField(max_length=100)),
                ('vachist_age', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_id', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacStck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinestock')),
                ('vacrec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationrecord')),
                ('vital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vitalsigns')),
            ],
            options={
                'db_table': 'vaccination_history',
            },
        ),
    ]
