# Generated by Django 5.1.6 on 2025-04-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_alter_antigentransaction_vacstck_id_and_more'),
        ('patientrecords', '0019_vitalsigns'),
        ('vaccination', '0011_delete_vaccinationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('vachist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vachist_doseNo', models.CharField(max_length=100)),
                ('vachist_status', models.CharField(max_length=100)),
                ('vachist_age', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_id', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacStck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='inventory.vaccinestock')),
                ('vacrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vaccinationrecord')),
                ('vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.vitalsigns')),
            ],
            options={
                'db_table': 'vaccination_history',
            },
        ),
    ]
