# Generated by Django 5.1.6 on 2025-04-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_remove_antigentransaction_antt_type_and_more'),
        ('vaccination', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vacStck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='inventory.vaccinestock'),
        ),
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vacrec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vaccinationrecord'),
        ),
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='vaccination.vitalsigns'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='serv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='vaccination.servicesrecords'),
        ),
    ]
