# Generated by Django 5.1.7 on 2025-04-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0011_remove_vaccinationhistory_serv_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vacrec_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationrecord'),
            preserve_default=False,
        ),
    ]
