# Generated by Django 5.1.7 on 2025-04-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0012_vaccinationhistory_vacrec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='pat_id',
        ),
    ]
