# Generated by Django 5.1.6 on 2025-04-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0012_alter_vaccinationhistory_vacstck_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesrecords',
            name='pat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vaccination.patientrecord'),
        ),
    ]
