# Generated by Django 5.1.7 on 2025-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0013_remove_vaccinationrecord_pat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vachist_bp_diastolic',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vachist_bp_systolic',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vachist_pulseRate',
        ),
    ]
