# Generated by Django 5.1.6 on 2025-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0013_alter_servicesrecords_pat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrecords',
            name='serv_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
