# Generated by Django 5.1.6 on 2025-04-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0014_servicesrecords_serv_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientRecord',
            new_name='PatientRecordSample',
        ),
    ]
