# Generated by Django 5.1.6 on 2025-04-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='patrec_id',
        ),
        migrations.DeleteModel(
            name='VaccinationHistory',
        ),
        migrations.DeleteModel(
            name='VaccinationRecord',
        ),
    ]
