# Generated by Django 5.1.7 on 2025-04-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0014_remove_vaccinationhistory_vachist_bp_diastolic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vitalsigns'),
        ),
    ]
