# Generated by Django 5.1.7 on 2025-04-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_remove_antigentransaction_antt_type_and_more'),
        ('vaccination', '0015_alter_vaccinationhistory_vital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vacStck_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinestock'),
            preserve_default=False,
        ),
    ]
