# Generated by Django 5.1.7 on 2025-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0016_vaccinationhistory_vacstck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='assigned_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
