# Generated by Django 5.1.7 on 2025-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0017_vaccinationhistory_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='id',
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_RR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_diastolic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_systolic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_o2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
