# Generated by Django 5.1.6 on 2025-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vachist_doseNo',
            field=models.PositiveIntegerField(default='0', max_length=100),
        ),
    ]
