# Generated by Django 5.1.6 on 2025-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0019_alter_vaccinationhistory_vachist_doseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vachist_doseNo',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
