# Generated by Django 5.1.6 on 2025-04-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0020_alter_vaccinationhistory_vachist_doseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
