# Generated by Django 5.1.6 on 2025-04-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0023_followupvisit_patrec'),
        ('vaccination', '0021_vaccinationhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='followv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_histories', to='patientrecords.followupvisit'),
        ),
    ]
