# Generated by Django 5.1.6 on 2025-04-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0022_vaccinationhistory_followv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='created_at',
        ),
    ]
