# Generated by Django 5.1.6 on 2025-04-22 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0025_remove_vaccinationhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
