# Generated by Django 5.1.6 on 2025-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0026_vaccinationhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='vachist_age',
            field=models.CharField(default='', max_length=100),
        ),
    ]
