# Generated by Django 5.1.6 on 2025-04-23 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0027_alter_vaccinationhistory_vachist_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vaccinationhistory',
            name='vachist_status',
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vacrec_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vacrec_totaldose',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
