# Generated by Django 5.1.6 on 2025-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0028_remove_vaccinationhistory_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='vachist_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
