# Generated by Django 4.2.20 on 2025-03-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('acc_username', models.CharField(max_length=200)),
                ('acc_email', models.CharField(max_length=200)),
                ('acc_password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
