# Generated by Django 5.2 on 2025-06-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0004_alter_position_pos_id'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgementReport',
            fields=[
                ('ar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar_type', models.CharField(max_length=200)),
                ('ar_title', models.CharField(max_length=500)),
                ('ar_created_at', models.DateField(auto_now_add=True)),
                ('ar_status', models.CharField(max_length=20)),
                ('ar_is_archive', models.BooleanField(default=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'acknowledgement_report',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('ir_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ir_type', models.CharField(max_length=200)),
                ('ir_add_details', models.TextField()),
                ('ir_time', models.TimeField()),
                ('ir_date', models.DateField(auto_now_add=True)),
                ('ir_street', models.CharField(max_length=100)),
                ('ir_is_archive', models.BooleanField(default=False)),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio')),
            ],
            options={
                'db_table': 'incident_report',
            },
        ),
        migrations.CreateModel(
            name='WeeklyAcknowledgementReport',
            fields=[
                ('wr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wr_created_at', models.DateField()),
                ('wr_is_archive', models.BooleanField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'weekly_acknowledgement_report',
            },
        ),
        migrations.CreateModel(
            name='WeeklyARComposition',
            fields=[
                ('wc', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.acknowledgementreport')),
                ('wr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.weeklyacknowledgementreport')),
            ],
            options={
                'db_table': 'weekly_ar_composition',
            },
        ),
    ]
