# Generated by Django 5.2 on 2025-12-16 04:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('profiling', '0002_requestregistrationcomposition_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('rte_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rte_logoLeft', models.URLField(null=True)),
                ('rte_logoRight', models.URLField(null=True)),
                ('rte_logoTop', models.URLField(null=True)),
                ('rte_headerText', models.TextField(null=True)),
                ('rte_type', models.CharField(max_length=50, null=True)),
                ('rte_prepared_by', models.CharField(max_length=100, null=True)),
                ('rte_recommended_by', models.CharField(max_length=100, null=True)),
                ('rte_approved_by', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'report_template',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('rt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rt_label', models.CharField(max_length=500)),
                ('rt_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'report_type',
            },
        ),
        migrations.CreateModel(
            name='ActionReport',
            fields=[
                ('ar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar_title', models.CharField(max_length=500)),
                ('ar_date_started', models.DateField()),
                ('ar_time_started', models.TimeField()),
                ('ar_date_completed', models.DateField()),
                ('ar_time_completed', models.TimeField()),
                ('ar_area', models.TextField()),
                ('ar_action_taken', models.TextField()),
                ('ar_result', models.TextField()),
                ('ar_created_at', models.DateField(default=datetime.date.today)),
                ('ar_status', models.CharField(default='UNSIGNED', max_length=20)),
                ('ar_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'action_report',
            },
        ),
        migrations.CreateModel(
            name='ARFile',
            fields=[
                ('arf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arf_name', models.CharField(max_length=500)),
                ('arf_type', models.CharField(max_length=50)),
                ('arf_path', models.CharField(max_length=500)),
                ('arf_url', models.URLField()),
                ('arf_is_supp', models.BooleanField(default=False)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_files', to='report.actionreport')),
            ],
            options={
                'db_table': 'ar_file',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('ir_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ir_add_details', models.TextField()),
                ('ir_time', models.TimeField(null=True)),
                ('ir_date', models.DateField(null=True)),
                ('ir_area', models.TextField(null=True)),
                ('ir_involved', models.IntegerField(default=0)),
                ('ir_severity', models.CharField(null=True)),
                ('ir_is_tracker', models.BooleanField(default=False)),
                ('ir_track_rep_id', models.CharField(null=True)),
                ('ir_track_lat', models.FloatField(null=True)),
                ('ir_track_lng', models.FloatField(null=True)),
                ('ir_track_user_lat', models.FloatField(null=True)),
                ('ir_track_user_lng', models.FloatField(null=True)),
                ('ir_track_user_contact', models.CharField(max_length=20, null=True)),
                ('ir_track_user_name', models.CharField(max_length=100, null=True)),
                ('ir_created_at', models.DateTimeField(auto_now_add=True)),
                ('ir_updated_at', models.DateTimeField(auto_now=True)),
                ('ir_is_archive', models.BooleanField(default=False)),
                ('ir_status', models.CharField(default='IN-PROGRESS', max_length=50)),
                ('ir_is_verified', models.BooleanField(default=False)),
                ('ir_remark', models.TextField(null=True)),
                ('rp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
                ('rt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.reporttype')),
            ],
            options={
                'db_table': 'incident_report',
            },
        ),
        migrations.AddField(
            model_name='actionreport',
            name='ir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_report', to='report.incidentreport'),
        ),
        migrations.CreateModel(
            name='IncidentReportFile',
            fields=[
                ('irf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('irf_name', models.CharField(max_length=500)),
                ('irf_type', models.CharField(max_length=50)),
                ('irf_path', models.CharField(max_length=100)),
                ('irf_url', models.URLField()),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='report.incidentreport')),
            ],
            options={
                'db_table': 'incident_report_file',
            },
        ),
        migrations.CreateModel(
            name='WeeklyAccomplishmentReport',
            fields=[
                ('war_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('war_created_at', models.DateField(default=datetime.date.today)),
                ('war_created_for', models.DateField(default=datetime.date.today)),
                ('war_status', models.CharField(default='UNSIGNED', max_length=50)),
                ('war_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'weekly_accomplishment_report',
            },
        ),
        migrations.CreateModel(
            name='WARFile',
            fields=[
                ('warf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warf_name', models.CharField(max_length=500)),
                ('warf_type', models.CharField(max_length=50)),
                ('warf_path', models.CharField(max_length=500)),
                ('warf_url', models.URLField()),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.weeklyaccomplishmentreport')),
            ],
            options={
                'db_table': 'war_file',
            },
        ),
        migrations.CreateModel(
            name='WeeklyARComposition',
            fields=[
                ('warc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.actionreport')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.weeklyaccomplishmentreport')),
            ],
            options={
                'db_table': 'weekly_ar_composition',
            },
        ),
    ]
