# Generated by Django 5.2 on 2025-06-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReportFile',
            fields=[
                ('irf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.incidentreport')),
            ],
            options={
                'db_table': 'incident_report_file',
            },
        ),
    ]
