# Generated by Django 5.2 on 2025-06-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_alter_address_add_external_sitio'),
        ('report', '0002_incidentreportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('rt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rt_label', models.CharField(max_length=500)),
                ('rt_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'report_type',
            },
        ),
        migrations.RemoveField(
            model_name='acknowledgementreport',
            name='ar_type',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='ir_street',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='ir_type',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='sitio',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgementreport',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reporttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reporttype'),
            preserve_default=False,
        ),
    ]
