# Generated by Django 5.2 on 2025-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reporttype_remove_acknowledgementreport_ar_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='ir_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
