# Generated by Django 5.2 on 2025-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_incidentreport_ir_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreportfile',
            name='file',
        ),
        migrations.AddField(
            model_name='incidentreportfile',
            name='irf_name',
            field=models.CharField(max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreportfile',
            name='irf_path',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreportfile',
            name='irf_type',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreportfile',
            name='irf_url',
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
