# Generated by Django 5.2 on 2025-06-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_incidentreportfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgementreport',
            name='ar_action_taken',
            field=models.TextField(default='Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgementreport',
            name='ar_date_completed',
            field=models.DateField(default='2025-06-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgementreport',
            name='ar_date_started',
            field=models.DateField(default='2025-06-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgementreport',
            name='ar_time_completed',
            field=models.TimeField(default='11:24:23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgementreport',
            name='ar_time_started',
            field=models.TimeField(default='11:24:23'),
            preserve_default=False,
        ),
    ]
