# Generated by Django 5.2 on 2025-06-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_acknowledgementreport_ar_action_taken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyacknowledgementreport',
            old_name='wr_created_at',
            new_name='war_created_at',
        ),
        migrations.RenameField(
            model_name='weeklyacknowledgementreport',
            old_name='wr_id',
            new_name='war_id',
        ),
        migrations.RenameField(
            model_name='weeklyacknowledgementreport',
            old_name='wr_is_archive',
            new_name='war_is_archive',
        ),
        migrations.RenameField(
            model_name='weeklyarcomposition',
            old_name='wr',
            new_name='war',
        ),
        migrations.RenameField(
            model_name='weeklyarcomposition',
            old_name='wc',
            new_name='warc',
        ),
        migrations.AlterField(
            model_name='acknowledgementreport',
            name='ar_status',
            field=models.CharField(default='Unsigned', max_length=20),
        ),
        migrations.CreateModel(
            name='ARFile',
            fields=[
                ('arf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arf_name', models.CharField(max_length=500)),
                ('arf_type', models.CharField(max_length=50)),
                ('arf_path', models.CharField(max_length=500)),
                ('arf_url', models.URLField()),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.acknowledgementreport')),
            ],
        ),
    ]
