# Generated by Django 5.2 on 2025-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_rename_wr_created_at_weeklyacknowledgementreport_war_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyacknowledgementreport',
            name='war_statis',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
