# Generated by Django 5.2 on 2025-06-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_weeklyacknowledgementreport_war_statis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyacknowledgementreport',
            old_name='war_statis',
            new_name='war_status',
        ),
    ]
