# Generated by Django 5.2 on 2025-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_rename_war_statis_weeklyacknowledgementreport_war_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyacknowledgementreport',
            name='war_status',
            field=models.CharField(default='Unsigned', max_length=50),
        ),
    ]
