# Generated by Django 5.2 on 2025-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_weeklyacknowledgementreport_war_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyacknowledgementreport',
            name='war_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
