# Generated by Django 5.2 on 2025-06-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_weeklyacknowledgementreport_war_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyarcomposition',
            old_name='warc',
            new_name='warc_id',
        ),
        migrations.AlterField(
            model_name='weeklyacknowledgementreport',
            name='war_created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
