# Generated by Django 5.2 on 2025-06-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_rename_warc_weeklyarcomposition_warc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgementreport',
            name='ir',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='report.incidentreport'),
            preserve_default=False,
        ),
    ]
