# Generated by Django 5.2 on 2025-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_position_pos_id'),
        ('report', '0013_acknowledgementreport_ir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('rt_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='WeeklyAcknowledgementReport',
            new_name='WeeklyAccomplishmentReport',
        ),
    ]
