# Generated by Django 5.2 on 2025-06-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_reporttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementreport',
            name='ir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.incidentreport'),
        ),
    ]
