# Generated by Django 5.2 on 2025-06-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_alter_acknowledgementreport_ir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementreport',
            name='rt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.reporttype'),
        ),
    ]
