# Generated by Django 5.2 on 2025-06-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_acknowledgementreport_rt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.AlterModelTable(
            name='arfile',
            table='ar_file',
        ),
    ]
