# Generated by Django 5.2 on 2025-06-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_acknowledgementreport_ar_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='WARFile',
            fields=[
                ('warf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warf_name', models.CharField(max_length=500)),
                ('warf_type', models.CharField(max_length=50)),
                ('warf_path', models.CharField(max_length=500)),
                ('warf_url', models.URLField()),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.weeklyaccomplishmentreport')),
            ],
            options={
                'db_table': 'war_file',
            },
        ),
    ]
