# Generated by Django 5.2 on 2025-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_warfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('rte_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rte_logoLeft', models.URLField()),
                ('rte_logoRight', models.URLField()),
                ('rte_headerText', models.TextField()),
                ('rte_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'report_template',
            },
        ),
    ]
