# Generated by Django 5.2 on 2025-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='rte_logoLeft',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='rte_logoRight',
            field=models.URLField(null=True),
        ),
    ]
