# Generated by Django 5.2 on 2025-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_alter_reporttemplate_rte_logoleft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='rte_headerText',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='rte_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
