# Generated by Django 5.2 on 2025-06-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '__first__'),
        ('report', '0022_alter_reporttemplate_rte_headertext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgementreport',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acknowledgementreport',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyaccomplishmentreport',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
            preserve_default=False,
        ),
    ]
