# Generated by Django 5.2 on 2025-06-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_acknowledgementreport_add_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weeklyaccomplishmentreport',
            table='weekly_accomplishment_report',
        ),
    ]
