# Generated by Django 5.2 on 2025-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_alter_weeklyaccomplishmentreport_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='rte_approved_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='rte_prepaired_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='rte_recommended_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
