# Generated by Django 5.2 on 2025-06-27 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_rename_rte_prepaired_by_reporttemplate_rte_prepared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyaccomplishmentreport',
            name='war_created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
