# Generated by Django 5.2 on 2025-06-28 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_alter_weeklyaccomplishmentreport_war_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementreport',
            name='ar_created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
