# Generated by Django 5.2 on 2025-06-28 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_alter_acknowledgementreport_ar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyaccomplishmentreport',
            name='war_created_for',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
