# Generated by Django 5.1.7 on 2025-06-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('file', '0001_initial'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ann_id', models.AutoField(primary_key=True, serialize=False)),
                ('ann_title', models.CharField(max_length=255)),
                ('ann_details', models.TextField()),
                ('ann_created_at', models.DateTimeField(auto_now_add=True)),
                ('ann_start_at', models.DateTimeField()),
                ('ann_end_at', models.DateTimeField()),
                ('ann_type', models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event'), ('reminder', 'Reminder')], default='general', max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'announcement',
                'ordering': ['-ann_created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('af_id', models.AutoField(primary_key=True, serialize=False)),
                ('ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='announcement.announcement')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            options={
                'db_table': 'announcement_file',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_mode', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=50)),
                ('ar_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=50)),
                ('ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='announcement.announcement')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'announcement_recipient',
                'unique_together': {('ann', 'rp')},
            },
        ),
    ]
