# Generated by Django 5.1.7 on 2025-07-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '__first__'),
        ('profiling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ann_id', models.AutoField(primary_key=True, serialize=False)),
                ('ann_title', models.TextField()),
                ('ann_details', models.TextField(max_length=255)),
                ('ann_created_at', models.DateField(auto_now_add=True)),
                ('ann_start_at', models.DateTimeField(blank=True, null=True)),
                ('ann_end_at', models.DateTimeField(blank=True, null=True)),
                ('ann_type', models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event')], max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'announcement',
                'ordering': ['-ann_created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('af_id', models.AutoField(primary_key=True, serialize=False)),
                ('af_name', models.TextField()),
                ('af_type', models.CharField(max_length=50)),
                ('af_path', models.TextField()),
                ('af_url', models.TextField()),
                ('ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
            ],
            options={
                'db_table': 'announcement_file',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_mode', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('public', 'Public')], max_length=50)),
                ('ar_age', models.CharField(blank=True, choices=[('youth', 'Youth'), ('adult', 'Adult'), ('senior', 'Senior Citizen')], max_length=50, null=True)),
                ('ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.position')),
                ('rp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'announcement_recipient',
            },
        ),
    ]
