# Generated by Django 4.2.20 on 2025-06-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ann_id', models.AutoField(primary_key=True, serialize=False)),
                ('ann_title', models.TextField()),
                ('ann_details', models.TextField(max_length=255)),
                ('ann_created_at', models.DateField(auto_now_add=True)),
                ('ann_start_at', models.DateTimeField()),
                ('ann_end_at', models.DateTimeField()),
                ('ann_type', models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event')], max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'announcement',
                'ordering': ['-ann_created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ar_type', models.CharField(choices=[('everyone', 'Everyone'), ('resident', 'All Residents'), ('staff', 'All Staff')], max_length=50)),
                ('ar_mode', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=50)),
                ('ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
                ('rp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'announcement_recipient',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('af_id', models.AutoField(primary_key=True, serialize=False)),
                ('af_name', models.TextField()),
                ('af_type', models.CharField(max_length=50)),
                ('af_path', models.TextField()),
                ('af_url', models.TextField()),
                ('ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
            ],
            options={
                'db_table': 'announcement_file',
            },
        ),
    ]
