# Generated by Django 4.2.20 on 2025-06-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('file', '0001_initial'),
        ('profiling', '0006_alter_address_add_external_sitio'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-ann_created_at']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='announcementfile',
            name='file_id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_files', to='file.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_announcements', to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='announcement.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='announcement.announcement'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('ann', 'rp')},
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
        migrations.AlterModelTable(
            name='announcementfile',
            table='announcement_file',
        ),
        migrations.AlterModelTable(
            name='announcementrecipient',
            table='announcement_recipient',
        ),
        migrations.RemoveField(
            model_name='announcementrecipient',
            name='rp_id',
        ),
    ]
