# Generated by Django 5.1.7 on 2025-07-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_mode',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('public', 'Public')], max_length=50),
        ),
    ]
