# Generated by Django 5.2 on 2025-04-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-ann_created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='announcementfile',
            options={'verbose_name': 'Announcement File', 'verbose_name_plural': 'Announcement Files'},
        ),
        migrations.AlterModelOptions(
            name='announcementrecipient',
            options={'verbose_name': 'Announcement Recipient', 'verbose_name_plural': 'Announcement Recipients'},
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
        migrations.AlterModelTable(
            name='announcementfile',
            table='announcement_file',
        ),
        migrations.AlterModelTable(
            name='announcementrecipient',
            table='announcement_recipient',
        ),
    ]
