# Generated by Django 5.1.7 on 2025-06-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('announcement', '0001_initial'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='announcementfile',
            name='file',
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_type',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_mode',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('resident', 'All Residents'), ('staff', 'All Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
    ]
