# Generated by Django 5.1.7 on 2025-06-09 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_details',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
    ]
