# Generated by Django 5.2 on 2025-12-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_status',
            field=models.CharField(default='INACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_files', to='announcement.announcement'),
        ),
    ]
