# Generated by Django 5.1.7 on 2025-06-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcementrecipient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementrecipient',
            name='recipient_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('resident', 'All Residents'), ('staff', 'All Staff'), ('individual', 'Individual Only')], max_length=20),
        ),
    ]
