# Generated by Django 5.1.7 on 2025-06-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_ann_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='staff',
        ),
    ]
