# Generated by Django 5.2 on 2025-04-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_id'),
        ('announcement', '0002_alter_announcement_options_and_more'),
        ('file', '0001_initial'),
        ('profiling', '0002_remove_father_rp_remove_family_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='rp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
    ]
