# Generated by Django 5.1.7 on 2025-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcementrecipient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
