# Generated by Django 5.1.7 on 2025-06-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('announcement', '0003_alter_announcement_ann_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrecipient',
            name='ar_age',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('adult', 'Adult'), ('senior citizen', 'Senior Citizen')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.position'),
        ),
    ]
