# Generated by Django 5.2 on 2025-04-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='announcementfile',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='announcementrecipient',
            old_name='rp_id',
            new_name='rp',
        ),
    ]
