# Generated by Django 5.1.7 on 2025-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcementrecipient_recipient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
