# Generated by Django 5.1.7 on 2025-06-12 14:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_ann_created_at'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('ann', 'rp')},
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='ar_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='announcementrecipient',
            name='recipient_type',
        ),
        migrations.RemoveField(
            model_name='announcementrecipient',
            name='staff',
        ),
    ]
