# Generated by Django 5.2 on 2025-04-25 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_rename_staff_id_announcement_staff_and_more'),
        ('file', '0001_initial'),
        ('profiling', '0002_remove_father_rp_remove_family_father_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-ann_created_at']},
        ),
        migrations.AlterModelOptions(
            name='announcementfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcementrecipient',
            options={},
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='announcement.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_files', to='file.file'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='announcement.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_announcements', to='profiling.residentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('ann', 'rp')},
        ),
    ]
