# Generated by Django 5.1.7 on 2025-06-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('announcement', '0004_announcementrecipient_ar_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementrecipient',
            name='position',
            field=models.ForeignKey(blank=True, db_column='position_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.position'),
        ),
    ]
