# Generated by Django 5.1.7 on 2025-06-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
        ('announcement', '0005_alter_announcementrecipient_unique_together_and_more'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='recipient_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('resident', 'All Residents'), ('staff', 'All Staff'), ('individual', 'Individual Only')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.RemoveField(
            model_name='announcementrecipient',
            name='ar_type',
        ),
    ]
