# Generated by Django 5.1.7 on 2025-06-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_announcementrecipient_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_age',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('adult', 'Adult'), ('senior', 'Senior Citizen')], max_length=50, null=True),
        ),
    ]
