# Generated by Django 5.1.7 on 2025-06-13 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_alter_announcementrecipient_unique_together_and_more'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementrecipient',
            old_name='recipient_type',
            new_name='ar_type',
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
