# Generated by Django 5.1.7 on 2025-06-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_position_pos_id'),
        ('announcement', '0006_alter_announcementrecipient_ar_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementrecipient',
            name='ar_type',
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.position'),
        ),
    ]
