# Generated by Django 5.1.7 on 2025-06-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_rename_recipient_type_announcementrecipient_ar_type_and_more'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file'),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_mode',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_type',
            field=models.CharField(),
        ),
    ]
