# Generated by Django 5.1.7 on 2025-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_announcement_ann_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_title',
            field=models.TextField(),
        ),
    ]
