# Generated by Django 4.2.20 on 2025-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_alter_announcement_ann_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_type',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_mode',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('resident', 'All Residents'), ('staff', 'All Staff')], max_length=50),
        ),
    ]
