# Generated by Django 5.1.7 on 2025-06-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_alter_announcement_ann_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementfile',
            name='file',
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='af_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_type',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_mode',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='announcementrecipient',
            name='ar_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('resident', 'All Residents'), ('staff', 'All Staff')], max_length=50),
        ),
    ]
