# Generated by Django 5.1.6 on 2025-12-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderRecipientListReporTemplate',
            fields=[
                ('rcpheader_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(default='Cebu', max_length=255)),
                ('doh_logo', models.URLField(default='https://miornhcxxzxecwnkgupq.supabase.co/storage/v1/object/public/manage-images/reports/cebucity_logo.png', null=True)),
                ('health_facility', models.CharField(default='Cebu City Health Department', max_length=255)),
                ('city', models.CharField(default='Cebu City', max_length=255)),
            ],
            options={
                'db_table': 'header_recipient_list_report_template',
            },
        ),
        migrations.CreateModel(
            name='BHWAttendanceRecord',
            fields=[
                ('bhwa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_working_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_approved', to='administration.staff')),
                ('noted_by', models.ForeignKey(db_column='noted_by', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_noted', to='administration.staff')),
                ('staff', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='administration.staff')),
            ],
            options={
                'db_table': 'bhw_attendance_record',
            },
        ),
        migrations.CreateModel(
            name='BHWDailyNotes',
            fields=[
                ('bhwdn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('disease_surv_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bm', models.ForeignKey(db_column='bm_id', on_delete=django.db.models.deletion.CASCADE, to='patientrecords.bodymeasurement')),
                ('staff', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='administration.staff')),
            ],
            options={
                'db_table': 'bhw_daily_notes',
            },
        ),
        migrations.CreateModel(
            name='BHWReferOrFollowUp',
            fields=[
                ('bhwrof_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('referred_follow_up_count', models.IntegerField(default=0)),
                ('bhwdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.bhwdailynotes')),
                ('ill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.illness')),
            ],
            options={
                'db_table': 'bhw_refer_or_follow_up',
            },
        ),
        migrations.CreateModel(
            name='MonthlyRecipientListReport',
            fields=[
                ('monthlyrcplist_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=7)),
                ('signature', models.TextField(blank=True, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('control_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('rcp_type', models.CharField(choices=[('FirstAid', 'FirstAid'), ('Medicine', 'Medicine')], max_length=20)),
                ('logo', models.URLField(default='https://miornhcxxzxecwnkgupq.supabase.co/storage/v1/object/public/manage-images/reports/cebucity_logo.png', null=True)),
                ('contact_number', models.CharField(default='(032) 232-6820; 232-6863', max_length=100)),
                ('location', models.CharField(default='General Maxilom Extension, Carreta, Cebu City', max_length=255)),
                ('department', models.CharField(default='Cebu City Health Department', max_length=255)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'monthly_recipient_list_report',
            },
        ),
        migrations.AddIndex(
            model_name='bhwdailynotes',
            index=models.Index(fields=['bhwdn_id', 'staff', 'created_at'], name='bhw_daily_n_bhwdn_i_09df75_idx'),
        ),
        migrations.AddIndex(
            model_name='bhwreferorfollowup',
            index=models.Index(fields=['bhwrof_id', 'bhwdn_id', 'ill_id'], name='bhw_refer_o_bhwrof__2fdbf8_idx'),
        ),
    ]
