# Generated by Django 5.2 on 2025-06-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetectionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('faces_detected', models.IntegerField(null=True)),
                ('embeddings', models.JSONField(null=True)),
                ('face_box', models.JSONField(null=True)),
                ('quality_score', models.FloatField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('rejection_reason', models.TextField(null=True)),
            ],
            options={
                'db_table': 'face_detection_request',
            },
        ),
    ]
