# Generated by Django 5.2 on 2025-08-28 05:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_serial_num', models.CharField(max_length=100)),
                ('inv_date', models.DateTimeField(default=datetime.date.today)),
                ('inv_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inv_nat_of_collection', models.CharField(max_length=250)),
                ('inv_status', models.CharField(default='Pending', max_length=50)),
                ('inv_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Annual_Gross_Sales',
            fields=[
                ('ags_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ags_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ags_maximum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ags_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ags_date', models.DateTimeField(default=datetime.date.today)),
                ('ags_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'annual_gross_sales',
            },
        ),
        migrations.CreateModel(
            name='Budget_Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_year', models.CharField(max_length=4)),
                ('plan_actual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_rpt_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_allotment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_cert_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_other_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_budgetaryObligations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balUnappropriated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_issue_date', models.DateField(default=datetime.date.today)),
                ('plan_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'budget_plan',
            },
        ),
        migrations.CreateModel(
            name='Income_Expense_Main',
            fields=[
                ('ie_main_year', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ie_main_tot_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ie_remaining_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ie_main_inc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ie_main_exp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ie_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'income_expense_main',
            },
        ),
        migrations.CreateModel(
            name='Income_Particular',
            fields=[
                ('incp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incp_item', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'income_particular',
            },
        ),
        migrations.CreateModel(
            name='Purpose_And_Rates',
            fields=[
                ('pr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pr_purpose', models.CharField(max_length=250)),
                ('pr_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_category', models.CharField(max_length=100)),
                ('pr_date', models.DateTimeField(default=datetime.date.today)),
                ('pr_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purpose_and_rate',
            },
        ),
        migrations.CreateModel(
            name='Budget_Plan_Detail',
            fields=[
                ('dtl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtl_budget_item', models.CharField(max_length=200)),
                ('dtl_proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dtl_budget_category', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'budget_plan_detail',
            },
        ),
        migrations.CreateModel(
            name='Budget_Plan_History',
            fields=[
                ('bph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bph_date_updated', models.DateTimeField(default=datetime.date.today)),
                ('bph_source_item', models.CharField(default='None')),
                ('bph_to_item', models.CharField(default='None')),
                ('bph_from_new_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bph_from_prev_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bph_to_new_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bph_to_prev_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bph_transfer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'budget_plan_history',
                'ordering': ['-bph_date_updated'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan_File',
            fields=[
                ('bpf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bpf_upload_date', models.DateTimeField(auto_now_add=True)),
                ('bpf_description', models.CharField(max_length=500)),
                ('bpf_type', models.CharField(max_length=100, null=True)),
                ('bpf_name', models.CharField(max_length=255, null=True)),
                ('bpf_path', models.CharField(max_length=500, null=True)),
                ('bpf_url', models.CharField(max_length=500, null=True)),
                ('plan_id', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'budget_plan_file',
            },
        ),
        migrations.CreateModel(
            name='Disbursement_File_Folder',
            fields=[
                ('dis_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('dis_year', models.CharField(max_length=4)),
                ('dis_name', models.CharField(default='', max_length=100)),
                ('dis_desc', models.CharField(default='', null=True)),
                ('dis_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'disbursement_file_folder',
            },
        ),
        migrations.CreateModel(
            name='Disbursement_Image',
            fields=[
                ('disf_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('disf_upload_date', models.CharField(default=datetime.date.today)),
                ('disf_is_archive', models.BooleanField(default=False)),
                ('disf_type', models.CharField(max_length=100, null=True)),
                ('disf_name', models.CharField(max_length=255, null=True)),
                ('disf_path', models.CharField(max_length=500, null=True)),
                ('disf_url', models.CharField(max_length=500, null=True)),
                ('dis_num', models.ForeignKey(blank=True, db_column='dis_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasurer.disbursement_file_folder')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'disbursement_image',
            },
        ),
        migrations.CreateModel(
            name='Expense_Particular',
            fields=[
                ('exp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exp_budget_item', models.CharField(max_length=200)),
                ('exp_proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exp_budget_category', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_particulars', to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'expense_particular',
            },
        ),
        migrations.CreateModel(
            name='Income_Expense_Tracking',
            fields=[
                ('iet_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('iet_serial_num', models.CharField(default='DEFAULT_SERIAL', max_length=100)),
                ('iet_datetime', models.DateTimeField(null=True)),
                ('iet_entryType', models.CharField(max_length=100)),
                ('iet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iet_actual_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('iet_additional_notes', models.CharField(max_length=100)),
                ('iet_receipt_image', models.CharField(blank=True, null=True)),
                ('iet_is_archive', models.BooleanField(default=False)),
                ('exp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.expense_particular')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'income_expense_tracking',
            },
        ),
        migrations.CreateModel(
            name='Expense_Log',
            fields=[
                ('el_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('el_proposed_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('el_actual_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('el_return_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('el_datetime', models.DateTimeField(null=True)),
                ('iet_num', models.ForeignKey(blank=True, db_column='iet_num', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.income_expense_tracking')),
            ],
            options={
                'db_table': 'expense_log',
            },
        ),
        migrations.CreateModel(
            name='Income_File_Folder',
            fields=[
                ('inf_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('inf_year', models.CharField(max_length=4)),
                ('inf_name', models.CharField(default='', max_length=100)),
                ('inf_desc', models.CharField(default='', null=True)),
                ('inf_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'income_file_folder',
            },
        ),
        migrations.CreateModel(
            name='Income_Image',
            fields=[
                ('infi_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('infi_upload_date', models.CharField(default=datetime.date.today)),
                ('infi_is_archive', models.BooleanField(default=False)),
                ('infi_type', models.CharField(max_length=100, null=True)),
                ('infi_name', models.CharField(max_length=255, null=True)),
                ('infi_path', models.CharField(max_length=500, null=True)),
                ('infi_url', models.CharField(max_length=500, null=True)),
                ('inf_num', models.ForeignKey(blank=True, db_column='inf_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasurer.income_file_folder')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'income_image',
            },
        ),
        migrations.CreateModel(
            name='Income_Tracking',
            fields=[
                ('inc_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('inc_serial_num', models.CharField(blank=True, max_length=100, null=True)),
                ('inc_transac_num', models.CharField(blank=True, max_length=100, null=True)),
                ('inc_datetime', models.DateTimeField(null=True)),
                ('inc_entryType', models.CharField(default='Income', max_length=100)),
                ('inc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inc_additional_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('inc_is_archive', models.BooleanField(default=False)),
                ('incp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.income_particular')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'income_tracking',
            },
        ),
        migrations.CreateModel(
            name='Income_Expense_File',
            fields=[
                ('ief_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ief_name', models.CharField(max_length=255)),
                ('ief_type', models.CharField(max_length=100)),
                ('ief_path', models.CharField(max_length=500)),
                ('ief_url', models.CharField(max_length=500)),
                ('iet_num', models.ForeignKey(blank=True, db_column='iet_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='treasurer.income_expense_tracking')),
                ('inc_num', models.ForeignKey(blank=True, db_column='inc_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='treasurer.income_tracking')),
            ],
            options={
                'db_table': 'income_expense_file',
            },
        ),
    ]
