# Generated by Django 5.1.7 on 2025-03-31 09:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_year', models.CharField(max_length=4)),
                ('plan_actual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_rpt_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_allotment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_cert_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_other_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_budgetaryObligations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balUnappropriated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_issue_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'Budget_Plan',
            },
        ),
        migrations.CreateModel(
            name='Budget_Plan_Detail',
            fields=[
                ('dtl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtl_budget_item', models.CharField(max_length=200)),
                ('dtl_proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'Budget_Plan_Detail',
            },
        ),
        migrations.CreateModel(
            name='Income_Expense_Tracking',
            fields=[
                ('iet_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('iet_serial_num', models.CharField(default='DEFAULT_SERIAL', max_length=100)),
                ('iet_date', models.DateField(default=datetime.date.today)),
                ('iet_entryType', models.CharField(max_length=100)),
                ('iet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iet_additional_notes', models.CharField(max_length=100)),
                ('iet_receipt_image', models.CharField()),
                ('inv_num', models.CharField(default=None, max_length=100)),
                ('dtl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan_detail')),
            ],
            options={
                'db_table': 'Income_Expense_Tracking',
            },
        ),
    ]
