# Generated by Django 5.1.7 on 2025-03-17 05:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_year', models.CharField(max_length=4)),
                ('plan_actual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_actual_rpt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_allotment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_cert_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_other_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_issue_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'Budget_Plan',
            },
        ),
        migrations.CreateModel(
            name='Capital_Outlays_And_Non_Office',
            fields=[
                ('con_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('con_capital_outlay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_clean_and_green', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_street_lighting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_rehab_multi_purpose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_sk_fund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_quick_response', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_disaster_training', models.DecimalField(decimal_places=2, max_digits=10)),
                ('con_disaster_supplies', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'Capital_Outlays_And_Non_Office',
            },
        ),
        migrations.CreateModel(
            name='Current_Expenditures_Maintenance',
            fields=[
                ('cem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cem_travel_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_training_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_office_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_accountable_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_medicine_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_water_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_electricity_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_telephone_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_membership_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_office_maintenance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_vehicle_maintenance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_fidelity_bond', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_insurance_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cem_misc_bond', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'Current_Expenditures_Maintenance',
            },
        ),
        migrations.CreateModel(
            name='Current_Expenditures_Personal',
            fields=[
                ('cep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cep_official_honoraria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_cash_gift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_midyear_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_yearend_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_tanod_honoraria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_lupon_honoraria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_brgy_workers_honoraria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_enhancement_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cep_leave_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'Current_Expenditures_Personal',
            },
        ),
        migrations.CreateModel(
            name='Other_Maint_And_Operating_Expense',
            fields=[
                ('ome_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ome_gad_program', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_senior_pwd_program', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_bcpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_badac_program', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_nutrition_program', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_aids_program', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_assembly_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ome_disaster_program', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'Other_Maint_And_Operating_Expense',
            },
        ),
    ]
