# Generated by Django 5.1.7 on 2025-04-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget_plan',
            table='budget_plan',
        ),
        migrations.AlterModelTable(
            name='budget_plan_detail',
            table='budget_plan_detail',
        ),
    ]
