# Generated by Django 5.1.7 on 2025-07-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Particular',
            fields=[
                ('exp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exp_budget_item', models.CharField(max_length=200)),
                ('exp_proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exp_budget_category', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_particulars', to='treasurer.budget_plan')),
            ],
            options={
                'db_table': 'expense_particular',
            },
        ),
    ]
