# Generated by Django 5.1.7 on 2025-04-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_plan',
            name='plan_calamityFund_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_localDev_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_miscExpense_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_personalService_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_skFund_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='budget_plan',
            table='budget_plan',
        ),
        migrations.AlterModelTable(
            name='budget_plan_detail',
            table='budget_plan_detail',
        ),
    ]
