# Generated by Django 5.2 on 2025-12-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bpr_id',
            field=models.ForeignKey(blank=True, db_column='bpr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussinesspermit_files', to='clerk.businesspermitrequest'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cr_id',
            field=models.ForeignKey(blank=True, db_column='cr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_invoices', to='clerk.clerkcertificate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nrc_id',
            field=models.ForeignKey(blank=True, db_column='nrc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_invoices', to='clerk.nonresidentcertificaterequest'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pay_id',
            field=models.ForeignKey(blank=True, db_column='pay_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_spay_invoices', to='clerk.servicechargepaymentrequest'),
        ),
    ]
