# Generated by Django 5.1.7 on 2025-05-23 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose_And_Rates',
            fields=[
                ('pr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pr_purpose', models.CharField(max_length=250)),
                ('pr_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_category', models.CharField(max_length=100)),
                ('pr_date', models.DateTimeField(default=datetime.date.today)),
                ('pr_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purpose_and_rate',
            },
        ),
        migrations.AddField(
            model_name='annual_gross_sales',
            name='ags_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annual_gross_sales',
            name='ags_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
