# Generated by Django 5.1.7 on 2025-03-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget_plan',
            old_name='plan_actual_rpt',
            new_name='plan_rpt_income',
        ),
        migrations.RenameField(
            model_name='current_expenditures_personal',
            old_name='cep_midyear_bonus',
            new_name='cep_mid_year_bonus',
        ),
        migrations.RenameField(
            model_name='current_expenditures_personal',
            old_name='cep_yearend_bonus',
            new_name='cep_year_end_bonus',
        ),
    ]
