# Generated by Django 5.1.7 on 2025-06-02 01:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_clerkbusinesspermit_documentspdf'),
        ('treasurer', '0002_purpose_and_rates_annual_gross_sales_ags_is_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_serial_num', models.CharField(max_length=100)),
                ('inv_date', models.DateTimeField(default=datetime.date.today)),
                ('inv_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inv_nat_of_collection', models.CharField(max_length=250)),
                ('rp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.clerkcertificate')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
