# Generated by Django 5.1.7 on 2025-04-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0002_alter_budget_plan_table_and_more'),
        ('treasurer', '0002_budget_plan_plan_calamityfund_limit_and_more'),
    ]

    operations = [
    ]
