# Generated by Django 5.1.7 on 2025-03-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0002_rename_plan_actual_rpt_budget_plan_plan_rpt_income_and_more'),
    ]

    operations = [
    ]
