# Generated by Django 5.1.7 on 2025-07-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0002_expense_particular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='dtl_id',
        ),
        migrations.AddField(
            model_name='income_expense_tracking',
            name='exp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.expense_particular'),
        ),
    ]
