# Generated by Django 5.1.7 on 2025-06-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0003_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='rp_id',
            new_name='cr_id',
        ),
    ]
