# Generated by Django 5.1.7 on 2025-04-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0003_merge_20250403_2150'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='income_expense_tracking',
            table='income_expense_tracking',
        ),
    ]
