# Generated by Django 5.2 on 2025-07-10 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0003_remove_income_expense_tracking_dtl_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement_file_folder',
            name='dis_desc',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='income_file_folder',
            name='inf_desc',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default=datetime.date.today),
        ),
    ]
