# Generated by Django 5.1.7 on 2025-03-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0003_auto_20250318_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_expenditures_maintenance',
            old_name='cem_fidelity_bond',
            new_name='cem_membership_dues',
        ),
        migrations.RemoveField(
            model_name='current_expenditures_maintenance',
            name='cem_insurance_expense',
        ),
        migrations.RemoveField(
            model_name='current_expenditures_maintenance',
            name='cem_membership_expense',
        ),
        migrations.RemoveField(
            model_name='current_expenditures_maintenance',
            name='cem_misc_bond',
        ),
        migrations.AddField(
            model_name='other_maint_and_operating_expense',
            name='ome_fidelity_bond',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='other_maint_and_operating_expense',
            name='ome_insurance_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='other_maint_and_operating_expense',
            name='ome_misc_bond',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
