# Generated by Django 5.2 on 2025-07-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0004_disbursement_file_folder_dis_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement_file_folder',
            name='dis_desc',
            field=models.CharField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='income_file_folder',
            name='inf_desc',
            field=models.CharField(default='', null=True),
        ),
    ]
