# Generated by Django 5.1.7 on 2025-04-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0004_alter_income_expense_tracking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_plan_detail',
            name='dtl_budget_category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
