# Generated by Django 5.1.7 on 2025-03-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0004_rename_cem_fidelity_bond_current_expenditures_maintenance_cem_membership_dues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_maint_and_operating_expense',
            name='ome_fidelity_bond',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='other_maint_and_operating_expense',
            name='ome_insurance_expense',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='other_maint_and_operating_expense',
            name='ome_misc_bond',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
