# Generated by Django 5.2 on 2025-06-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('file', '0001_initial'),
        ('treasurer', '0004_rename_rp_id_invoice_cr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement_File_Folder',
            fields=[
                ('dis_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('dis_year', models.CharField(max_length=4)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'disbursement_file_folder',
            },
        ),
        migrations.CreateModel(
            name='Disbursement_Image',
            fields=[
                ('disf_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('disf_upload_date', models.CharField(default='June 04, 2025')),
                ('dis_num', models.ForeignKey(blank=True, db_column='dis_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasurer.disbursement_file_folder')),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'disbursement_image',
            },
        ),
        migrations.CreateModel(
            name='Income_File_Folder',
            fields=[
                ('inf_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('inc_year', models.CharField(max_length=4)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'income_file_folder',
            },
        ),
        migrations.CreateModel(
            name='Income_Image',
            fields=[
                ('infi_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('infi_upload_date', models.CharField(default='June 04, 2025')),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('inf_num', models.ForeignKey(blank=True, db_column='inf_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasurer.income_file_folder')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'income_image',
            },
        ),
    ]
