# Generated by Django 5.2.3 on 2025-07-11 15:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('treasurer', '0005_alter_disbursement_file_folder_dis_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan_File',
            fields=[
                ('bpf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bpf_upload_date', models.CharField(default=datetime.date.today)),
                ('bpf_type', models.CharField(max_length=100, null=True)),
                ('bpf_name', models.CharField(max_length=255, null=True)),
                ('bpf_path', models.CharField(max_length=500, null=True)),
                ('bpf_url', models.CharField(max_length=500, null=True)),
                ('plan_id', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasurer.budget_plan')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'budget_plan_file',
            },
        ),
    ]
