# Generated by Django 5.1.7 on 2025-04-09 02:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0005_budget_plan_detail_dtl_budget_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_Particular',
            fields=[
                ('incp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incp_item', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'income_particular',
            },
        ),
        migrations.CreateModel(
            name='Income_Tracking',
            fields=[
                ('inc_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('inc_date', models.DateField(default=datetime.date.today)),
                ('inc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inc_additional_notes', models.CharField(max_length=100)),
                ('inc_receipt_image', models.CharField()),
                ('incp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.income_particular')),
            ],
        ),
    ]
