# Generated by Django 5.2 on 2025-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0005_disbursement_file_folder_disbursement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement_image',
            name='disf_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income_image',
            name='infi_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
