# Generated by Django 5.2 on 2025-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0006_disbursement_image_disf_is_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement_image',
            name='disf_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='income_image',
            name='inf_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 11, 2025'),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 11, 2025'),
        ),
    ]
