# Generated by Django 5.1.7 on 2025-04-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0006_income_particular_income_tracking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='income_tracking',
            table='income_tracking',
        ),
    ]
