# Generated by Django 5.2.3 on 2025-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0006_budgetplan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplan_file',
            name='bpf_upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
