# Generated by Django 4.2.20 on 2025-04-05 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0006_rename_ome_misc_bond_other_maint_and_operating_expense_ome_misc_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Plan_Detail',
            fields=[
                ('dtl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtl_budget_item', models.CharField(max_length=200)),
                ('dtl_proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Budget_Plan_Detail',
            },
        ),
        migrations.CreateModel(
            name='Income_Expense_Tracking',
            fields=[
                ('iet_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('iet_serial_num', models.CharField(default='DEFAULT_SERIAL', max_length=100)),
                ('iet_date', models.DateField(default=datetime.date.today)),
                ('iet_entryType', models.CharField(max_length=100)),
                ('iet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iet_additional_notes', models.CharField(max_length=100)),
                ('iet_receipt_image', models.CharField()),
                ('inv_num', models.CharField(default=None, max_length=100)),
                ('dtl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan_detail')),
            ],
            options={
                'db_table': 'Income_Expense_Tracking',
            },
        ),
        migrations.RemoveField(
            model_name='current_expenditures_maintenance',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='current_expenditures_personal',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='other_maint_and_operating_expense',
            name='plan',
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_balUnappropriated',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_budgetaryObligations',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Capital_Outlays_And_Non_Office',
        ),
        migrations.DeleteModel(
            name='Current_Expenditures_Maintenance',
        ),
        migrations.DeleteModel(
            name='Current_Expenditures_Personal',
        ),
        migrations.DeleteModel(
            name='Other_Maint_And_Operating_Expense',
        ),
        migrations.AddField(
            model_name='budget_plan_detail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='treasurer.budget_plan'),
        ),
    ]
