# Generated by Django 5.2.3 on 2025-07-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0007_alter_budgetplan_file_bpf_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplan_file',
            name='plan_id',
            field=models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan'),
        ),
    ]
