# Generated by Django 5.1.7 on 2025-04-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0007_alter_income_tracking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_tracking',
            name='inc_entryType',
            field=models.CharField(default='Income', max_length=100),
        ),
    ]
