# Generated by Django 5.2 on 2025-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0007_disbursement_image_disf_name_income_image_inf_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income_file_folder',
            old_name='inc_year',
            new_name='inf_year',
        ),
        migrations.RemoveField(
            model_name='disbursement_image',
            name='disf_name',
        ),
        migrations.RemoveField(
            model_name='income_image',
            name='inf_name',
        ),
        migrations.AddField(
            model_name='disbursement_file_folder',
            name='dis_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='income_file_folder',
            name='inf_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
