# Generated by Django 5.2 on 2025-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0008_rename_inc_year_income_file_folder_inf_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement_file_folder',
            name='dis_is_arhive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income_file_folder',
            name='inf_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
