# Generated by Django 5.2.3 on 2025-07-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0008_alter_budgetplan_file_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_plan',
            name='plan_calamityFund_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget_plan',
            name='plan_localDev_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget_plan',
            name='plan_miscExpense_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget_plan',
            name='plan_personalService_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget_plan',
            name='plan_skFund_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
