# Generated by Django 5.1.7 on 2025-04-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0008_income_tracking_inc_entrytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='inv_num',
        ),
    ]
