# Generated by Django 5.1.7 on 2025-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0009_remove_income_expense_tracking_inv_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_tracking',
            name='inv_num',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
