# Generated by Django 5.2.3 on 2025-07-30 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0009_alter_budget_plan_plan_calamityfund_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget_plan_history',
            options={'ordering': ['-bph_date_updated']},
        ),
        migrations.RemoveField(
            model_name='budget_plan',
            name='plan_calamityFund_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan',
            name='plan_localDev_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan',
            name='plan_miscExpense_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan',
            name='plan_personalService_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan',
            name='plan_skFund_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_actual_income',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_balUnappropriated',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_balance',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_budgetaryObligations',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_calamityFund_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_cert_fees',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_change_date',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_localDev_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_miscExpense_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_other_income',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_personalService_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_rpt_income',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_skFund_limit',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_tax_allotment',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_tax_share',
        ),
        migrations.RemoveField(
            model_name='budget_plan_history',
            name='bph_year',
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_amount_added',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_date_updated',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_new_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_source_item',
            field=models.CharField(default='None'),
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_to_item',
            field=models.CharField(default='None'),
        ),
        migrations.DeleteModel(
            name='Budget_Plan_Detail_History',
        ),
    ]
