# Generated by Django 5.2 on 2025-06-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0009_disbursement_file_folder_dis_is_arhive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursement_file_folder',
            old_name='dis_is_arhive',
            new_name='dis_is_archive',
        ),
    ]
