# Generated by Django 5.1.7 on 2025-06-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0010_rename_dis_is_arhive_disbursement_file_folder_dis_is_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 12, 2025'),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 12, 2025'),
        ),
        migrations.CreateModel(
            name='Income_Expense_File',
            fields=[
                ('ief_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ief_name', models.CharField(max_length=255)),
                ('ief_type', models.CharField(max_length=100)),
                ('ief_path', models.CharField(max_length=500)),
                ('ief_url', models.CharField(max_length=500)),
                ('iet_num', models.ForeignKey(blank=True, db_column='iet_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='treasurer.income_expense_tracking')),
                ('inc_num', models.ForeignKey(blank=True, db_column='inc_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='treasurer.income_tracking')),
            ],
            options={
                'db_table': 'income_expense_file',
            },
        ),
    ]
