# Generated by Django 5.1.7 on 2025-04-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0010_income_tracking_inv_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_tracking',
            name='inc_serial_num',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
