# Generated by Django 5.2.3 on 2025-07-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0010_alter_budget_plan_history_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget_plan_history',
            old_name='bph_amount_added',
            new_name='bph_from_new_balance',
        ),
        migrations.RenameField(
            model_name='budget_plan_history',
            old_name='bph_new_amount',
            new_name='bph_to_new_balance',
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
