# Generated by Django 5.2.3 on 2025-07-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0011_rename_bph_amount_added_budget_plan_history_bph_from_new_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_from_prev_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget_plan_history',
            name='bph_to_prev_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
