# Generated by Django 5.1.7 on 2025-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0011_income_tracking_inc_serial_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_Expense_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ie_main_year', models.CharField(max_length=4)),
                ('ie_main_tot_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ie_main_inc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ie_main_exp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'income_expense_main',
            },
        ),
        migrations.AlterField(
            model_name='income_tracking',
            name='inv_num',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
