# Generated by Django 5.1.7 on 2025-06-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0011_alter_disbursement_image_disf_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_tracking',
            name='inc_receipt_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
