# Generated by Django 5.1.7 on 2025-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0012_alter_income_tracking_inc_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_expense_tracking',
            name='iet_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='income_expense_tracking',
            name='iet_receipt_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
