# Generated by Django 5.2 on 2025-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0012_budget_plan_history_bph_from_prev_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplan_file',
            name='bpf_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
