# Generated by Django 5.1.7 on 2025-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0013_income_expense_tracking_iet_is_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_tracking',
            name='inc_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
