# Generated by Django 5.2 on 2025-08-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('treasurer', '0013_budgetplan_file_bpf_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_expense_tracking',
            name='staff_id',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='income_tracking',
            name='staff_id',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
    ]
