# Generated by Django 5.1.7 on 2025-06-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0014_income_tracking_inc_is_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='iet_date',
        ),
        migrations.AddField(
            model_name='income_expense_tracking',
            name='iet_actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='income_expense_tracking',
            name='iet_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 13, 2025'),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 13, 2025'),
        ),
    ]
