# Generated by Django 5.2 on 2025-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0014_income_expense_tracking_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inv_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inv_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
