# Generated by Django 5.1.7 on 2025-06-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0015_remove_income_expense_tracking_iet_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_tracking',
            name='iet_actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
