# Generated by Django 5.2 on 2025-08-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0015_invoice_inv_change_invoice_inv_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Log',
            fields=[
                ('el_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('el_return_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('el_datetime', models.DateTimeField(null=True)),
                ('iet_num', models.ForeignKey(blank=True, db_column='iet_num', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.income_expense_tracking')),
            ],
            options={
                'db_table': 'expense_log',
            },
        ),
    ]
