# Generated by Django 5.1.7 on 2025-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0016_alter_income_expense_tracking_iet_actual_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_main',
            name='id',
        ),
        migrations.AlterField(
            model_name='income_expense_main',
            name='ie_main_year',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
