# Generated by Django 5.2 on 2025-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0016_expense_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_log',
            name='el_actual_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_log',
            name='el_proposed_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
