# Generated by Django 5.1.7 on 2025-06-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0017_remove_income_expense_main_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_tracking',
            name='inc_date',
        ),
        migrations.AddField(
            model_name='income_tracking',
            name='inc_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 14, 2025'),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 14, 2025'),
        ),
    ]
