# Generated by Django 5.1.7 on 2025-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0018_remove_income_tracking_inc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 16, 2025'),
        ),
        migrations.AlterField(
            model_name='income_expense_main',
            name='ie_main_year',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 16, 2025'),
        ),
    ]
