# Generated by Django 5.1.7 on 2025-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0019_alter_disbursement_image_disf_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_plan',
            name='plan_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
