# Generated by Django 5.1.7 on 2025-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0020_budget_plan_plan_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_tracking',
            name='inc_transac_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income_tracking',
            name='inc_serial_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
