# Generated by Django 5.1.7 on 2025-06-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0021_income_tracking_inc_transac_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_tracking',
            name='inc_receipt_image',
        ),
        migrations.AlterField(
            model_name='income_tracking',
            name='inv_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.invoice'),
        ),
    ]
