# Generated by Django 5.1.7 on 2025-06-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0022_remove_income_tracking_inc_receipt_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_tracking',
            name='inv_num',
        ),
    ]
