# Generated by Django 5.1.7 on 2025-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0023_remove_income_tracking_inv_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_tracking',
            name='inc_additional_notes',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
