# Generated by Django 5.1.7 on 2025-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0024_alter_income_tracking_inc_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_tracking',
            name='inc_additional_notes',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
