# Generated by Django 5.1.7 on 2025-06-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_clerkbusinesspermit_documentspdf'),
        ('treasurer', '0026_alter_income_tracking_inc_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 17, 2025'),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 17, 2025'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cr_id',
            field=models.ForeignKey(db_column='cr_id', on_delete=django.db.models.deletion.CASCADE, to='clerk.clerkcertificate'),
        ),
    ]
