# Generated by Django 5.1.7 on 2025-06-17 06:15

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0027_alter_disbursement_image_disf_upload_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBudget_Plan',
            fields=[
                ('plan_id', models.BigIntegerField(blank=True, db_index=True)),
                ('plan_year', models.CharField(max_length=4)),
                ('plan_actual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_rpt_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_tax_allotment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_cert_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_other_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_budgetaryObligations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_balUnappropriated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_issue_date', models.DateField(default=datetime.date.today)),
                ('plan_personalService_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_miscExpense_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_localDev_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_skFund_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_calamityFund_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_is_archive', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical budget_ plan',
                'verbose_name_plural': 'historical budget_ plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBudget_Plan_Detail',
            fields=[
                ('dtl_id', models.BigIntegerField(blank=True, db_index=True)),
                ('dtl_budget_item', models.CharField(max_length=200)),
                ('dtl_proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dtl_budget_category', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasurer.budget_plan')),
            ],
            options={
                'verbose_name': 'historical budget_ plan_ detail',
                'verbose_name_plural': 'historical budget_ plan_ details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
