# Generated by Django 5.1.7 on 2025-06-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0028_historicalbudget_plan_historicalbudget_plan_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_expense_main',
            name='ie_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disbursement_image',
            name='disf_upload_date',
            field=models.CharField(default='June 18, 2025'),
        ),
        migrations.AlterField(
            model_name='income_image',
            name='infi_upload_date',
            field=models.CharField(default='June 18, 2025'),
        ),
    ]
