# Generated by Django 5.2 on 2025-07-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0012_income_expense_main_alter_income_tracking_inv_num'),
        ('treasurer', '0029_income_expense_main_ie_is_archive_and_more'),
    ]

    operations = [
    ]
