# Generated by Django 5.2 on 2025-12-16 04:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_staff_rp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('don_num', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('don_item_name', models.CharField(default='', max_length=100)),
                ('don_donor', models.CharField(default='Anonymous', max_length=100)),
                ('don_qty', models.IntegerField(default=1)),
                ('don_description', models.CharField(blank=True, max_length=200, null=True)),
                ('don_category', models.CharField(default='', max_length=100)),
                ('don_date', models.DateField(default=datetime.date.today)),
                ('don_status', models.CharField(default='', max_length=100)),
                ('don_dist_head', models.CharField(blank=True, max_length=100, null=True)),
                ('don_dist_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'donation',
            },
        ),
    ]
