# Generated by Django 5.1.7 on 2025-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('don_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('don_donorfname', models.CharField(max_length=100, null=True)),
                ('don_donorlname', models.CharField(max_length=100, null=True)),
                ('don_item_name', models.CharField(max_length=100, null=True)),
                ('don_qty', models.CharField(max_length=100, null=True)),
                ('don_description', models.CharField(max_length=200, null=True)),
                ('don_category', models.CharField(max_length=100, null=True)),
                ('don_receiver', models.CharField(max_length=100, null=True)),
                ('don_date', models.DateField()),
            ],
            options={
                'db_table': 'donation',
            },
        ),
    ]
