# Generated by Django 5.1.7 on 2025-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='don_qty',
            field=models.IntegerField(null=True),
        ),
    ]
