# Generated by Django 5.1.7 on 2025-03-27 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_don_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='don_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
