# Generated by Django 5.1.7 on 2025-07-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('donation', '0003_alter_donation_don_date'),
        ('profiling', '0002_requestregistration_acc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='don_donorfname',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='don_donorlname',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='don_receiver',
        ),
        migrations.AddField(
            model_name='donation',
            name='don_donor',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='per_id',
            field=models.ForeignKey(blank=True, db_column='per_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiling.personal'),
        ),
        migrations.AddField(
            model_name='donation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='don_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='don_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='don_item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='don_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OnlineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_transaction_id', models.CharField(max_length=100, unique=True)),
                ('od_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('od_payment_channel', models.CharField(choices=[('gcash', 'GCash'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('od_date_created', models.DateTimeField(auto_now_add=True)),
                ('od_payment_details', models.JSONField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'online_donation',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='od_transaction',
            field=models.OneToOneField(blank=True, db_column='od_transaction_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='donation.onlinedonation'),
        ),
    ]
