# Generated by Django 5.2 on 2025-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_donation_don_donorfname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='don_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='don_num',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
