# Generated by Django 5.2 on 2025-08-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donation_don_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='od_transaction',
        ),
        migrations.DeleteModel(
            name='OnlineDonation',
        ),
    ]
