# Generated by Django 5.2 on 2025-08-31 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('donation', '0006_remove_donation_od_transaction_delete_onlinedonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
    ]
