# Generated by Django 5.1.6 on 2025-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinerecord',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('REFERRED', 'Referred'), ('RECORED', 'Recorded'), ('PENDING', 'Pending')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='medicinerecord',
            table='medicine_record',
        ),
    ]
