# Generated by Django 5.1.6 on 2025-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicinerecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinerecord',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('REFERRED', 'Referred'), ('RECORDED', 'Recorded'), ('PENDING', 'Pending')], max_length=10),
        ),
    ]
