# Generated by Django 5.2 on 2025-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_assign_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
