# Generated by Django 5.2.1 on 2025-12-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('healthProfiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='healthProfiling.residentprofile'),
            preserve_default=False,
        ),
    ]
