# Generated by Django 5.1.6 on 2025-06-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('healthProfiling', '0002_solid_waste_mgmt_remove_household_hh_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='healthProfiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='administration.staff'),
        ),
    ]
