# Generated by Django 5.2.3 on 2025-06-19 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('healthProfiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='healthProfiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='administration.staff'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='administration.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('feat', 'pos')},
        ),
    ]
