# Generated by Django 5.1.6 on 2025-06-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='administration.staff'),
        ),
    ]
