# Generated by Django 5.2 on 2025-06-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_type',
        ),
    ]
