# Generated by Django 5.2 on 2025-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_staff_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(default='Health Staff', max_length=20),
        ),
    ]
