# Generated by Django 5.1.6 on 2025-06-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_staff'),
        # ('healthProfiling', '0007_address_household_add_personaladdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='healthProfiling.residentprofile'),
            preserve_default=False,
        ),
    ]
