# Generated by Django 5.2 on 2025-06-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_staff_staff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pos_category',
        ),
    ]
