# Generated by Django 5.2 on 2025-06-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_position_pos_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pos_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
