# Generated by Django 5.2 on 2025-06-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_position_pos_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pos_category',
        ),
        migrations.AddField(
            model_name='position',
            name='pos_group',
            field=models.CharField(default='Non-Grouped', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
