# Generated by Django 5.2 on 2025-07-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_position_pos_category_position_pos_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pos_category',
            field=models.CharField(default='BARANGAY POSITION', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='pos_is_predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_group',
            field=models.CharField(default='NON-GROUPED', max_length=100, null=True),
        ),
    ]
