# Generated by Django 5.2 on 2025-07-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_position_pos_category_position_pos_is_predefined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_category',
            field=models.CharField(default='HEALTH POSITION', max_length=100, null=True),
        ),
    ]
