# Generated by Django 5.1.6 on 2025-12-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=100)),
                ('day_description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'day',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceScheduler',
            fields=[
                ('ss_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meridiem', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('day_id', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_scheduler', to='servicescheduler.day')),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_scheduler', to='servicescheduler.service')),
            ],
            options={
                'db_table': 'service_scheduler',
            },
        ),
    ]
