# Generated by Django 5.2 on 2025-12-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_timestamp', models.DateTimeField()),
                ('act_type', models.CharField(max_length=100)),
                ('act_description', models.TextField()),
                ('act_module', models.CharField(help_text="Module/App name (e.g., 'treasurer', 'clerk', 'council')", max_length=50)),
                ('act_action', models.CharField(help_text="Action performed (e.g., 'create', 'update', 'delete')", max_length=50)),
                ('act_record_id', models.CharField(blank=True, help_text='ID of the affected record', max_length=100, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'activity_log',
                'managed': True,
                'indexes': [models.Index(fields=['act_module'], name='activity_lo_act_mod_68b2f1_idx'), models.Index(fields=['act_action'], name='activity_lo_act_act_3d65e8_idx'), models.Index(fields=['act_timestamp'], name='activity_lo_act_tim_4755a5_idx')],
            },
        ),
    ]
