# Generated by Django 5.2 on 2025-06-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_timestamp', models.DateTimeField()),
                ('act_type', models.CharField(max_length=100)),
                ('act_description', models.TextField()),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.feature')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
    ]
