# Generated by Django 5.1.6 on 2025-03-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feat_name', models.CharField(max_length=50)),
                ('feat_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assi_date', models.DateField()),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.feature')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.position')),
            ],
            options={
                'db_table': 'assignment',
                'unique_together': {('feat', 'pos')},
            },
        ),
    ]
