# Generated by Django 5.1.6 on 2025-03-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feat_name', models.CharField(max_length=50)),
                ('feat_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assi_date', models.DateField()),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.feature')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.position')),
            ],
            options={
                'db_table': 'assignment',
                'unique_together': {('feat', 'pos')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('assi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='administration.assignment')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='administration.staff')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.position')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
