# Generated by Django 5.1.6 on 2025-03-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=False)),
                ('create', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('assi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.assignment')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
    ]
