# Generated by Django 5.1.6 on 2025-03-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_permission_assi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='assi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='administration.assignment'),
        ),
    ]
