# Generated by Django 5.1.6 on 2025-03-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_permission_assi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='assi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.assignment'),
        ),
    ]
