# Generated by Django 5.1.6 on 2025-03-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_staff_staff_assign_date_alter_assignment_assi_date'),
        ('profiling', '0011_remove_household_hh_existing_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='profiling.residentprofile'),
            preserve_default=False,
        ),
    ]
