# Generated by Django 5.1.6 on 2025-03-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0016_remove_household_hh_existing_no_family_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='father',
            old_name='rp_id',
            new_name='rp',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='rp_id',
            new_name='rp',
        ),
        migrations.RenameField(
            model_name='mother',
            old_name='rp_id',
            new_name='rp',
        )
    ]
