# Generated by Django 4.2.20 on 2025-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
