# Generated by Django 5.1.7 on 2025-03-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital_outlays_and_non_office',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_nonoffice', to='treasurer.budget_plan'),
        ),
        migrations.AlterField(
            model_name='current_expenditures_maintenance',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='treasurer.budget_plan'),
        ),
        migrations.AlterField(
            model_name='current_expenditures_personal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='treasurer.budget_plan'),
        ),
        migrations.AlterField(
            model_name='other_maint_and_operating_expense',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to='treasurer.budget_plan'),
        ),
    ]
