# Generated by Django 5.1.7 on 2025-03-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_plan_detail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='treasurer.budget_plan'),
        ),
    ]
