# Generated by Django 5.1.7 on 2025-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0002_alter_capital_outlays_and_non_office_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_plan',
            name='plan_balUnappropriated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget_plan',
            name='plan_budgetaryObligations',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
