# Generated by Django 5.1.7 on 2025-03-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0002_alter_budget_plan_detail_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_tracking',
            name='iet_serial_num',
            field=models.CharField(default='DEFAULT_SERIAL', max_length=100),
        ),
    ]
