# Generated by Django 5.1.7 on 2025-03-27 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0003_alter_income_expense_tracking_iet_serial_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='iet_particulars',
        ),
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='inv_num',
        ),
        migrations.AddField(
            model_name='income_expense_tracking',
            name='dtl_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan_detail'),
        ),
    ]
