# Generated by Django 5.1.7 on 2025-03-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0004_remove_income_expense_tracking_iet_particulars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_tracking',
            name='dtl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan_detail'),
        ),
    ]
