# Generated by Django 5.1.7 on 2025-03-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0005_alter_other_maint_and_operating_expense_ome_fidelity_bond_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other_maint_and_operating_expense',
            old_name='ome_misc_bond',
            new_name='ome_misc_expense',
        ),
    ]
