# Generated by Django 5.1.7 on 2025-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0005_alter_income_expense_tracking_dtl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='dtl_id',
        ),
        migrations.AddField(
            model_name='income_expense_tracking',
            name='inv_num',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
