# Generated by Django 5.1.7 on 2025-03-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0006_remove_income_expense_tracking_dtl_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income_Expense_Tracking',
        ),
    ]
