# Generated by Django 5.1.7 on 2025-03-27 08:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0007_delete_income_expense_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_Expense_Tracking',
            fields=[
                ('iet_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('iet_serial_num', models.CharField(default='DEFAULT_SERIAL', max_length=100)),
                ('iet_date', models.DateField(default=datetime.date.today)),
                ('iet_entryType', models.CharField(max_length=100)),
                ('iet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iet_receiver', models.CharField(max_length=100)),
                ('iet_additional_notes', models.CharField(max_length=100)),
                ('iet_receipt_image', models.CharField()),
                ('inv_num', models.CharField(default=None, max_length=100)),
                ('dtl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurer.budget_plan_detail')),
            ],
            options={
                'db_table': 'Income_Expense_Tracking',
            },
        ),
    ]
