# Generated by Django 5.1.7 on 2025-03-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0008_income_expense_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_tracking',
            name='iet_receiver',
        ),
    ]
