# Generated by Django 5.2 on 2025-12-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('lp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpt_photo', models.URLField()),
                ('cpt_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('quote', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
            ],
            options={
                'db_table': 'landingpage',
            },
        ),
        migrations.CreateModel(
            name='LandingCarouselFIle',
            fields=[
                ('lcf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lcf_name', models.CharField(max_length=500)),
                ('lcf_type', models.CharField(max_length=50)),
                ('lcf_path', models.CharField(max_length=500)),
                ('lcf_url', models.URLField()),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_carousel_files', to='landing.landingpage')),
            ],
            options={
                'db_table': 'landingcarouselfile',
            },
        ),
    ]
