# Generated by Django 5.2 on 2025-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='test_attr',
            field=models.CharField(default='TEST', max_length=50),
        ),
    ]
