"""
<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
=======
>>>>>>> frontend/feature/treasurer
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
<<<<<<< HEAD

========
Django settings for tutorial project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
=======
"""

from pathlib import Path
>>>>>>> frontend/feature/treasurer
import sys, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
<<<<<<< HEAD
sys.path.append(os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g56qefvrrgnx_ygpsz-#!ao71tv@!fjk49mukq68@lh#p*6%t+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['192.168.56.1', 'localhost', '127.0.0.1']
=======
sys.path.append(os.path.join(BASE_DIR,'apps'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u@v&_cu2n+wn($h8gn&xluls+oem(#_rgfh2pnazb9@_tyn8nn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
>>>>>>> frontend/feature/treasurer


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.account',
    'apps.waste',
    'apps.profiling',
    'apps.administration'
========
    'rest_framework',
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py
=======
    'apps.treasurer',
    'corsheaders',
    'rest_framework'
>>>>>>> frontend/feature/treasurer
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
    'corsheaders.middleware.CorsMiddleware',
]

<<<<<<<< HEAD:backend/backend/settings.py
ROOT_URLCONF = 'backend.urls'
========
ROOT_URLCONF = 'tutorial.urls'
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py
=======
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'backend.urls'
>>>>>>> frontend/feature/treasurer

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
WSGI_APPLICATION = 'backend.wsgi.application'
========
WSGI_APPLICATION = 'tutorial.wsgi.application'

>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
=======
WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
>>>>>>> frontend/feature/treasurer

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
<<<<<<< HEAD
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT')
=======
        'NAME': 'CIUDAD-TEMP',
        'USER': 'postgres',
        'PASSWORD': 'hannahbisheen',
        'HOST': 'localhost',
        'PORT': '5433'
>>>>>>> frontend/feature/treasurer
    }
}


# Password validation
<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

========
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py

=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

>>>>>>> frontend/feature/treasurer
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
# https://docs.djangoproject.com/en/5.1/topics/i18n/
========
# https://docs.djangoproject.com/en/5.0/topics/i18n/
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py
=======
# https://docs.djangoproject.com/en/5.1/topics/i18n/
>>>>>>> frontend/feature/treasurer

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
# https://docs.djangoproject.com/en/5.1/howto/static-files/
========
# https://docs.djangoproject.com/en/5.0/howto/static-files/
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py
=======
# https://docs.djangoproject.com/en/5.1/howto/static-files/
>>>>>>> frontend/feature/treasurer

STATIC_URL = 'static/'

# Default primary key field type
<<<<<<< HEAD
<<<<<<<< HEAD:backend/backend/settings.py
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
========
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
>>>>>>>> frontend/feature/treasurer:backend/venv/Lib/site-packages/tutorial/settings.py

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT Authentication Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "DELETE"]
CORS_ALLOW_HEADERS = ["*"]
=======
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
>>>>>>> frontend/feature/treasurer
