# Generated by Django 5.1.6 on 2025-03-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_staff_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
