# Generated by Django 5.2 on 2025-12-16 04:06

import datetime
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_province', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_barangay', models.CharField(max_length=50)),
                ('add_street', models.CharField(max_length=50)),
                ('add_external_sitio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='RequestRegistration',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_created_at', models.DateTimeField(auto_now_add=True)),
                ('req_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'request_registration',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sitio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voter_name', models.CharField(max_length=200)),
                ('voter_address', models.TextField()),
                ('voter_category', models.CharField(max_length=5, null=True)),
                ('voter_precinct', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'voter',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bus_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_gross_sales', models.FloatField()),
                ('bus_location', models.TextField()),
                ('bus_status', models.CharField(default='Pending', max_length=20)),
                ('bus_date_of_registration', models.DateField(default=datetime.date.today)),
                ('bus_date_verified', models.DateField(null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff')),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='BusinessModification',
            fields=[
                ('bm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bm_updated_name', models.CharField(max_length=100, null=True)),
                ('bm_updated_gs', models.FloatField(null=True)),
                ('bm_updated_loc', models.TextField(null=True)),
                ('bm_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bm_status', models.CharField(default='PENDING', max_length=50)),
                ('bm_rejection_reason', models.TextField(null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.business')),
            ],
            options={
                'db_table': 'business_modification',
            },
        ),
        migrations.CreateModel(
            name='BusinessFile',
            fields=[
                ('bf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bf_name', models.CharField(max_length=500)),
                ('bf_type', models.CharField(max_length=50)),
                ('bf_path', models.CharField(max_length=500)),
                ('bf_url', models.URLField()),
                ('bf_created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_files', to='profiling.business')),
                ('bm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_files', to='profiling.businessmodification')),
            ],
            options={
                'db_table': 'business_file',
            },
        ),
        migrations.CreateModel(
            name='BusinessRespondent',
            fields=[
                ('br_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('br_date_registered', models.DateField(default=datetime.date.today)),
                ('br_lname', models.CharField(max_length=50)),
                ('br_fname', models.CharField(max_length=50)),
                ('br_mname', models.CharField(max_length=50, null=True)),
                ('br_sex', models.CharField(max_length=10)),
                ('br_dob', models.DateField()),
                ('br_contact', models.CharField(max_length=11)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'business_respondent',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_business', to='profiling.businessrespondent'),
        ),
        migrations.CreateModel(
            name='HistoricalPersonal',
            fields=[
                ('per_id', models.BigIntegerField(blank=True, db_index=True)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('per_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(blank=True, max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=20)),
                ('per_disability', models.CharField(blank=True, max_length=100, null=True)),
                ('per_is_deceased', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
            ],
            options={
                'verbose_name': 'historical personal',
                'verbose_name_plural': 'historical personals',
                'db_table': 'personal_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hh_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hh_nhts', models.CharField(max_length=50)),
                ('hh_date_registered', models.DateField(auto_now_add=True)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fam_indigenous', models.CharField(max_length=50)),
                ('fam_building', models.CharField(max_length=50)),
                ('fam_date_registered', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff')),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_set', to='profiling.household')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('per_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('per_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(blank=True, max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=20)),
                ('per_disability', models.CharField(blank=True, max_length=100, null=True)),
                ('per_is_deceased', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'personal',
                'indexes': [models.Index(fields=['per_lname', 'per_fname'], name='personal_per_lna_29932c_idx'), models.Index(fields=['per_contact'], name='personal_per_con_396812_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('pa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_addresses', to='profiling.personal')),
            ],
            options={
                'db_table': 'personal_address',
            },
        ),
        migrations.CreateModel(
            name='PersonalAddressHistory',
            fields=[
                ('pah_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_id', models.IntegerField()),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
            ],
            options={
                'db_table': 'personal_address_history',
            },
        ),
        migrations.CreateModel(
            name='PersonalModification',
            fields=[
                ('pm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pm_lname', models.CharField(max_length=50, null=True)),
                ('pm_fname', models.CharField(max_length=50, null=True)),
                ('pm_mname', models.CharField(max_length=50, null=True)),
                ('pm_suffix', models.CharField(max_length=50, null=True)),
                ('pm_dob', models.DateField(null=True)),
                ('pm_sex', models.CharField(max_length=50, null=True)),
                ('pm_status', models.CharField(max_length=50, null=True)),
                ('pm_edAttainment', models.CharField(max_length=50, null=True)),
                ('pm_religion', models.CharField(max_length=50, null=True)),
                ('pm_contact', models.CharField(max_length=50, null=True)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_modification', to='profiling.personal')),
            ],
            options={
                'db_table': 'personal_modification',
            },
        ),
        migrations.CreateModel(
            name='PersonalAddressModification',
            fields=[
                ('pam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_addresses', to='profiling.personalmodification')),
            ],
            options={
                'db_table': 'personal_address_modification',
            },
        ),
        migrations.CreateModel(
            name='RequestRegistrationComposition',
            fields=[
                ('rrc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rrc_fam_role', models.CharField(max_length=50)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_composition', to='profiling.requestregistration')),
            ],
            options={
                'db_table': 'request_registration_composition',
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('rp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rp_date_registered', models.DateField(auto_now_add=True)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='profiling.personal')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profiles', to='administration.staff')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.voter')),
            ],
            options={
                'db_table': 'resident_profile',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.CreateModel(
            name='HistoricalBusiness',
            fields=[
                ('bus_id', models.CharField(db_index=True, max_length=100)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_gross_sales', models.FloatField()),
                ('bus_location', models.TextField()),
                ('bus_status', models.CharField(default='Pending', max_length=20)),
                ('bus_date_of_registration', models.DateField(default=datetime.date.today)),
                ('bus_date_verified', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('br', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiling.businessrespondent')),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.staff')),
                ('rp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiling.residentprofile')),
            ],
            options={
                'verbose_name': 'historical business',
                'verbose_name_plural': 'historical businesss',
                'db_table': 'business_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('fc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fc_role', models.CharField(max_length=50)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='profiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'family_composition',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='rp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_business', to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='address',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['sitio'], name='address_sitio_i_6e5289_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_id'], name='resident_pr_rp_id_5d96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['per'], name='resident_pr_per_id_8d8581_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_date_registered'], name='resident_pr_rp_date_e601dd_idx'),
        ),
    ]
