# Generated by Django 5.2 on 2025-07-21 11:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('administration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_province', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_barangay', models.CharField(max_length=50)),
                ('add_street', models.CharField(max_length=50)),
                ('add_external_sitio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='BusinessRespondent',
            fields=[
                ('br_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('br_lname', models.CharField(max_length=50)),
                ('br_fname', models.CharField(max_length=50)),
                ('br_mname', models.CharField(blank=True, max_length=50, null=True)),
                ('br_sex', models.CharField(max_length=50)),
                ('br_dob', models.DateField()),
                ('br_contact', models.CharField(max_length=20)),
                ('br_address', models.TextField()),
            ],
            options={
                'db_table': 'business_respondent',
            },
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('kyc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_document_front', models.TextField(blank=True, null=True)),
                ('id_has_face', models.BooleanField(default=False, null=True)),
                ('id_face_embedding', models.BinaryField(blank=True, null=True)),
                ('face_photo', models.TextField(blank=True, null=True)),
                ('document_info_match', models.BooleanField(default=False, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kyc_record',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('per_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='RequestRegistration',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_date', models.DateField(auto_now_add=True)),
                ('req_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'request_registration',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sitio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bus_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_gross_sales', models.FloatField()),
                ('bus_date_registered', models.DateField(default=datetime.date.today)),
                ('add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff')),
                ('br', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.businessrespondent')),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='BusinessFile',
            fields=[
                ('bf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bf_name', models.CharField(max_length=500)),
                ('bf_type', models.CharField(max_length=50)),
                ('bf_path', models.CharField(max_length=500)),
                ('bf_url', models.URLField()),
                ('bf_created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_files', to='profiling.business')),
            ],
            options={
                'db_table': 'business_file',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hh_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hh_nhts', models.CharField(max_length=50)),
                ('hh_date_registered', models.DateField(default=datetime.date.today)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fam_indigenous', models.CharField(max_length=50)),
                ('fam_building', models.CharField(max_length=50)),
                ('fam_date_registered', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff')),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_set', to='profiling.household')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('pa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
            ],
            options={
                'db_table': 'personal_address',
            },
        ),
        migrations.CreateModel(
            name='RequestRegistrationComposition',
            fields=[
                ('rrc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rrc_fam_role', models.CharField(max_length=50)),
                ('acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_composition', to='profiling.requestregistration')),
            ],
            options={
                'db_table': 'request_registration_composition',
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('rp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rp_date_registered', models.DateField(auto_now_add=True)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='profiling.personal')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profiles', to='administration.staff')),
            ],
            options={
                'db_table': 'resident_profile',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('fc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fc_role', models.CharField(max_length=50)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='profiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'family_composition',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='rp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_business', to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='address',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_id'], name='resident_pr_rp_id_5d96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['per'], name='resident_pr_per_id_8d8581_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_date_registered'], name='resident_pr_rp_date_e601dd_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['sitio'], name='address_sitio_i_6e5289_idx'),
        ),
    ]
