# Generated by Django 5.1.7 on 2025-04-10 05:24
# Generated by Django 5.2 on 2025-04-17 14:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('father_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'father',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guard_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'guardian',
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('mother_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mother',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('per_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(max_length=100, null=True)),
                ('per_suffix', models.CharField(max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_address', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sitio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bus_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_gross_sales', models.FloatField()),
                ('bus_province', models.CharField(max_length=50)),
                ('bus_city', models.CharField(max_length=50)),
                ('bus_barangay', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('bus_respondentLname', models.CharField(max_length=50)),
                ('bus_respondentFname', models.CharField(max_length=50)),
                ('bus_respondentMname', models.CharField(max_length=50)),
                ('bus_respondentSex', models.CharField(max_length=50)),
                ('bus_respondentDob', models.DateField()),
                ('bus_date_registered', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio')),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='BusinessFile',
            fields=[
                ('bf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.business')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            options={
                'db_table': 'business_file',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hh_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hh_nhts', models.CharField(max_length=50)),
                ('hh_province', models.CharField(max_length=50)),
                ('hh_city', models.CharField(max_length=50)),
                ('hh_barangay', models.CharField(max_length=50)),
                ('hh_street', models.CharField(max_length=50)),
                ('hh_date_registered', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fam_indigenous', models.CharField(max_length=50)),
                ('fam_building', models.CharField(max_length=50)),
                ('fam_date_registered', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff')),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='profiling.father')),
                ('guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='profiling.guardian')),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.household')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='profiling.mother')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='RequestRegistration',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_date', models.DateField()),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
            ],
            options={
                'db_table': 'request_registration',
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('rp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rp_date_registered', models.DateField(default=datetime.date.today)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='profiling.personal')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profiles', to='administration.staff')),
            ],
            options={
                'db_table': 'resident_profile',
            },
        ),
        migrations.AddField(
            model_name='mother',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='household',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='father',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('fc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='profiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'family_composition',
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='profiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'dependent',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
    ]
