# Generated by Django 5.2 on 2025-09-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='add',
        ),
        migrations.RemoveField(
            model_name='businessmodification',
            name='add',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness',
            name='add',
        ),
        migrations.AddField(
            model_name='business',
            name='bus_location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessmodification',
            name='bm_updated_loc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='businessrespondent',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='bus_location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitio',
            name='sitio_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PersonalModification',
            fields=[
                ('pm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pm_lname', models.CharField(max_length=50, null=True)),
                ('pm_fname', models.CharField(max_length=50, null=True)),
                ('pm_mname', models.CharField(max_length=50, null=True)),
                ('pm_suffix', models.CharField(max_length=50, null=True)),
                ('pm_dob', models.DateField(null=True)),
                ('pm_sex', models.CharField(max_length=50, null=True)),
                ('pm_status', models.CharField(max_length=50, null=True)),
                ('pm_edAttainment', models.CharField(max_length=50, null=True)),
                ('pm_religion', models.CharField(max_length=50, null=True)),
                ('pm_contact', models.CharField(max_length=50, null=True)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_modification', to='profiling.personal')),
            ],
            options={
                'db_table': 'personal_modification',
            },
        ),
    ]
