# Generated by Django 5.2 on 2025-07-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_br'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestregistration',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='requestregistration',
            name='per',
        ),
        migrations.CreateModel(
            name='RequestRegistrationComposition',
            fields=[
                ('rrc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.requestregistration')),
            ],
        ),
    ]
