# Generated by Django 5.2 on 2025-07-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='per_contact',
            field=models.CharField( max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_dob',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_edAttainment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='per_fname',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_lname',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='per_religion',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_sex',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_status',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_suffix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaladdress',
            name='per',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='personal_addresses', to='profiling.personal'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['per_lname', 'per_fname'], name='personal_per_lna_29932c_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['per_contact'], name='personal_per_con_396812_idx'),
        ),
    ]
