# Generated by Django 5.2 on 2025-04-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('rf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.requestregistration')),
            ],
            options={
                'db_table': 'request_file',
            },
        ),
    ]
