# Generated by Django 5.1.6 on 2025-03-17 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='fam_date_registered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='household',
            name='hh_date_registered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='registered',
            name='reg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
