# Generated by Django 5.2 on 2025-04-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='father',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='family',
            name='father',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='family',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother',
        ),
        migrations.AddField(
            model_name='familycomposition',
            name='fc_role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='fam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='profiling.family'),
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='profiling.residentprofile'),
        ),
        migrations.DeleteModel(
            name='Dependent',
        ),
        migrations.DeleteModel(
            name='Father',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Mother',
        ),
    ]
