# Generated by Django 5.2 on 2025-06-21 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='sitio',
        ),
        migrations.RemoveField(
            model_name='businessfile',
            name='file',
        ),
        migrations.AddField(
            model_name='business',
            name='add',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='profiling.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_is_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_name',
            field=models.CharField(max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_path',
            field=models.CharField(max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_type',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessfile',
            name='bf_url',
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
