# Generated by Django 5.2 on 2025-07-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '__first__'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestregistration',
            name='acc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
