# Generated by Django 5.1.7 on 2025-06-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='per_address',
        ),
    ]
