# Generated by Django 5.2 on 2025-07-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAddressHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
            ],
            options={
                'db_table': 'personal_address_history',
            },
        ),
    ]
