# Generated by Django 5.2 on 2025-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_requestregistration_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestregistration',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
