# Generated by Django 5.2 on 2025-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_remove_requestregistration_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestregistrationcomposition',
            name='rrc_fam_role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
