# Generated by Django 5.1.6 on 2025-03-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('profiling', '0002_alter_household_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff'),
        ),
    ]
