# Generated by Django 5.2 on 2025-07-22 04:29

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('profiling', '0002_personal_per_contact_personal_per_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonal',
            fields=[
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(max_length=100, null=True)),
                ('per_suffix', models.CharField(max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
            ],
            options={
                'verbose_name': 'historical personal',
                'verbose_name_plural': 'historical personals',
                'db_table': 'personal_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
