# Generated by Django 5.2 on 2025-07-23 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_personaladdresshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaladdresshistory',
            name='history_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
