# Generated by Django 5.2 on 2025-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_remove_business_sitio_remove_businessfile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessfile',
            name='bf_id_type',
        ),
        migrations.RemoveField(
            model_name='businessfile',
            name='bf_is_id',
        ),
        migrations.AddField(
            model_name='business',
            name='bus_respondentAddress',
            field=models.CharField(default="San Roque, Cebu City, Cebu", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='bus_respondentContact',
            field=models.CharField(default="09262355814", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='per_contact',
            field=models.CharField(max_length=20),
        ),
    ]
