# Generated by Django 5.2 on 2025-12-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_requestregistrationcomposition_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalmodification',
            name='per',
        ),
        migrations.DeleteModel(
            name='PersonalAddressModification',
        ),
        migrations.DeleteModel(
            name='PersonalModification',
        ),
    ]
