# Generated by Django 5.1.6 on 2025-03-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_alter_family_fam_date_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='hh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='profiling.household'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='fam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='profiling.family'),
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='fam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='profiling.family'),
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='profiling.personal'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='profiling.personal'),
        ),
    ]
