# Generated by Django 5.2 on 2025-05-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_business_staff_family_staff_household_staff_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='personal',
        #     name='per_address',
        # ),
    ]
