# Generated by Django 5.2 on 2025-12-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_remove_personalmodification_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonal',
            name='per_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='per_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
