# Generated by Django 5.2 on 2025-07-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_requestregistrationcomposition_rrc_fam_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestregistrationcomposition',
            table='request_registration_composition',
        ),
    ]
