# Generated by Django 5.2 on 2025-07-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_alter_personaladdresshistory_history_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaladdresshistory',
            old_name='history_date',
            new_name='pah_date',
        ),
        migrations.RenameField(
            model_name='personaladdresshistory',
            old_name='history_id',
            new_name='pah_id',
        ),
    ]
