# Generated by Django 5.2 on 2025-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_remove_personal_per_address'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='address',
        #     name='add_external_sitio',
        #     field=models.CharField(default=1, max_length=50),
        #     preserve_default=False,
        # ),
    ]
