# Generated by Django 5.2 on 2025-06-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_remove_businessfile_bf_id_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='bus_barangay',
        ),
        migrations.RemoveField(
            model_name='business',
            name='bus_city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='bus_province',
        ),
        migrations.RemoveField(
            model_name='business',
            name='bus_street',
        ),
    ]
