# Generated by Django 5.1.6 on 2025-03-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_staff_staff_assign_date_alter_assignment_assi_date'),
        ('profiling', '0003_alter_building_hh_alter_dependent_fam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
            preserve_default=False,
        ),
    ]
