# Generated by Django 5.2 on 2025-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_historicalpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonal',
            name='per_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
    ]
