# Generated by Django 5.1.6 on 2025-04-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_alter_family_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='business',
            table='business',
        ),
    ]
