# Generated by Django 5.2 on 2025-07-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_requestregistration_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestregistration',
            old_name='is_archive',
            new_name='req_is_archive',
        ),
    ]
