# Generated by Django 5.2 on 2025-07-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('profiling', '0004_rename_is_archive_requestregistration_req_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('kyc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_document_front', models.ImageField(upload_to='kyc_documents/')),
                ('face_photo', models.ImageField(upload_to='kyc_photos/')),
                ('document_info_match', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='businessfile',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_files', to='profiling.business'),
        ),
        migrations.AlterField(
            model_name='personaladdress',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_addresses', to='profiling.personal'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['sitio'], name='address_sitio_i_6e5289_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_id'], name='resident_pr_rp_id_5d96f2_idx'),
        ),
    ]
