# Generated by Django 5.1.6 on 2025-04-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('profiling', '0004_alter_business_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff'),
        ),
    ]
