# Generated by Django 5.2 on 2025-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_rename_history_date_personaladdresshistory_pah_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaladdresshistory',
            name='history_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
