# Generated by Django 5.2 on 2025-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_address_add_external_sitio'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='address',
        #     name='add_external_sitio',
        #     field=models.CharField(max_length=50, null=True),
        # ),
    ]
