# Generated by Django 5.1.6 on 2025-03-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_registered_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='per_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
