# Generated by Django 5.2 on 2025-07-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_historicalpersonal_per_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersonal',
            name='per_id',
        ),
    ]
