# Generated by Django 5.2 on 2025-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_personaladdresshistory_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaladdresshistory',
            name='pah_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
