# Generated by Django 5.1.6 on 2025-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_alter_personal_per_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='per_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
