# Generated by Django 5.2 on 2025-07-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_kycrecord_alter_businessfile_bus_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kycrecord',
            table='kyc_record',
        ),
    ]
