# Generated by Django 5.1.6 on 2025-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_alter_business_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bus_doc_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
