# Generated by Django 5.2 on 2025-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_alter_address_add_external_sitio'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='address',
        #     name='add_external_sitio',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
    ]
