# Generated by Django 5.2 on 2025-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfile',
            name='file',
        ),
        migrations.AddField(
            model_name='requestfile',
            name='rf_name',
            field=models.CharField(max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestfile',
            name='rf_path',
            field=models.CharField(max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestfile',
            name='rf_type',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestfile',
            name='rf_url',
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
