# Generated by Django 5.2 on 2025-07-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_alter_personaladdresshistory_pah_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_address',
        ),
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_contact',
        ),
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_dob',
        ),
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_fname',
        ),
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_lname',
        ),
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_mname',
        ),
        migrations.RemoveField(
            model_name='businessrespondent',
            name='br_sex',
        ),
        migrations.AddField(
            model_name='businessrespondent',
            name='per',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
            preserve_default=False,
        ),
    ]
