# Generated by Django 5.2 on 2025-07-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_remove_personal_per_address'),
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
    ]
