# Generated by Django 5.1.6 on 2025-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_business_bus_doc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bus_doc_url',
            field=models.CharField(max_length=500),
        ),
    ]
