# Generated by Django 5.2 on 2025-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_alter_kycrecord_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrecord',
            name='face_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='id_document_front',
            field=models.TextField(blank=True, null=True),
        ),
    ]
