# Generated by Django 5.2 on 2025-07-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('profiling', '0007_remove_businessrespondent_br_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bus_date_registered',
            new_name='bus_date_of_registration',
        ),
        migrations.AddField(
            model_name='business',
            name='bus_date_verified',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bus_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff'),
        ),
    ]
