# Generated by Django 5.2 on 2025-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_alter_kycrecord_face_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrecord',
            name='document_info_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
