# Generated by Django 5.1.6 on 2025-03-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_staff_staff_assign_date_alter_assignment_assi_date'),
        ('profiling', '0007_remove_household_hh_existing_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registered',
            new_name='ResidentProfile',
        ),
        migrations.RenameField(
            model_name='residentprofile',
            old_name='reg_date',
            new_name='rp_date_registered',
        ),
        migrations.RenameField(
            model_name='residentprofile',
            old_name='reg_id',
            new_name='rp_id',
        ),
        migrations.AlterField(
            model_name='building',
            name='fam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='profiling.family'),
        ),
        migrations.AlterModelTable(
            name='residentprofile',
            table='resident_profile',
        ),
    ]
