# Generated by Django 5.1.6 on 2025-04-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_alter_business_bus_doc_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestRegistration',
        ),
        migrations.AlterModelTable(
            name='requestregistration',
            table='request_registration',
        ),
    ]
