# Generated by Django 5.2 on 2025-06-19 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_remove_requestfile_file_requestfile_rf_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='rf_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestfile',
            name='rf_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestfile',
            name='rf_is_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestregistration',
            name='req_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
