# Generated by Django 5.1.6 on 2025-04-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_rename_request_requestregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bus_respondentSex',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='bus_doc_url',
            field=models.TextField(),
        ),
    ]
