# Generated by Django 5.2 on 2025-07-26 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_rename_bus_date_registered_business_bus_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrespondent',
            name='br_date_registered',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
