# Generated by Django 5.2 on 2025-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_alter_kycrecord_document_info_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
