# Generated by Django 5.1.6 on 2025-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_rename_registered_residentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='rp_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
