# Generated by Django 5.1.6 on 2025-04-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0009_business_bus_respondentsex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='sitio_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
