# Generated by Django 5.1.6 on 2025-03-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0009_remove_household_hh_existing_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='per_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
