# Generated by Django 5.2 on 2025-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0009_businessrespondent_br_date_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaladdresshistory',
            name='pah_date',
        ),
    ]
