# Generated by Django 5.1.6 on 2025-03-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_staff_staff_assign_date_alter_assignment_assi_date'),
        ('profiling', '0010_remove_household_hh_existing_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
    ]
