# Generated by Django 5.1.6 on 2025-04-04 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_assignment_staff_position_staff_alter_staff_pos'),
        ('profiling', '0010_alter_sitio_sitio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='staff',
            field=models.ForeignKey(default='00001250331', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='staff',
            field=models.ForeignKey(default='00001250331', on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='staff',
            field=models.ForeignKey(default='00001250331', on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff'),
            preserve_default=False,
        ),
    ]
