# Generated by Django 5.2 on 2025-04-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('profiling', '0011_alter_business_staff_alter_family_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='bus_doc_url',
        ),
        migrations.CreateModel(
            name='BuinessFile',
            fields=[
                ('bf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.business')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            options={
                'db_table': 'business_file',
            },
        ),
    ]
