# Generated by Django 5.2 on 2025-04-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuinessFile',
            new_name='BusinessFile',
        ),
        migrations.RemoveField(
            model_name='father',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='family',
            name='father',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='family',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother',
        ),
        migrations.AddField(
            model_name='familycomposition',
            name='fc_role',
            field=models.CharField(default='independent', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dependent',
        ),
        migrations.DeleteModel(
            name='Father',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Mother',
        ),
    ]
