# Generated by Django 5.1.6 on 2025-03-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0012_remove_household_hh_existing_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='per',
        ),
        migrations.AddField(
            model_name='household',
            name='rp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
    ]
