# Generated by Django 5.1.6 on 2025-03-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_staff_rp'),
        ('profiling', '0013_remove_household_hh_existing_no_remove_household_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='staff',
            field=models.ForeignKey(default="00001250323", on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff'),
            preserve_default=False,
        ),
    ]
