# Generated by Django 5.1.6 on 2025-03-23 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0014_remove_household_hh_existing_no_household_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='per',
        ),
        migrations.RemoveField(
            model_name='familycomposition',
            name='per',
        ),
        migrations.RemoveField(
            model_name='father',
            name='per',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='per',
        ),
        migrations.AddField(
            model_name='dependent',
            name='rp',
            field=models.ForeignKey(default='00001250323', on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familycomposition',
            name='rp',
            field=models.ForeignKey(default='00001250323', on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='father',
            name='rp_id',
            field=models.ForeignKey(default='00001250323', on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='rp_id',
            field=models.ForeignKey(default='00001250323', on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guard_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'guardian',
            },
        ),
    ]
