# Generated by Django 5.1.6 on 2025-03-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_staff_rp'),
        ('profiling', '0015_remove_dependent_per_remove_familycomposition_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='staff',
            field=models.ForeignKey(default='00001250323', on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='profiling.personal'),
        ),
    ]
