# Generated by Django 5.1.6 on 2025-03-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0017_rename_rp_id_father_rp_rename_rp_id_guardian_rp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_date', models.DateField()),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
            ],
        ),
    ]
