# Generated by Django 5.1.7 on 2025-04-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0018_remove_household_hh_existing_no_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='hh_existing_no',
        ),
    ]
