# Generated by Django 5.1.6 on 2025-03-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0018_remove_household_hh_existing_no_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='fam_building',
            field=models.CharField(default='Renter', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='guard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.guardian'),
        ),
        migrations.AddField(
            model_name='family',
            name='hh',
            field=models.ForeignKey(default='HH-00001', on_delete=django.db.models.deletion.CASCADE, to='profiling.household'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
