# Generated by Django 5.1.6 on 2025-03-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_staff_rp'),
        ('profiling', '0019_remove_household_hh_existing_no_family_fam_building_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bus_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_gross_sales', models.FloatField()),
                ('bus_province', models.CharField(max_length=50)),
                ('bus_city', models.CharField(max_length=50)),
                ('bus_barangay', models.CharField(max_length=50)),
                ('bus_street', models.CharField(max_length=50)),
                ('bus_respondentLname', models.CharField(max_length=50)),
                ('bus_respondentFname', models.CharField(max_length=50)),
                ('bus_respondentMname', models.CharField(max_length=50)),
                ('bus_date_registered', models.DateField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='administration.staff')),
            ],
        ),
    ]
