# Generated by Django 5.1.6 on 2025-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0020_remove_household_hh_existing_no_alter_request_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bus_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
