# Generated by Django 5.1.6 on 2025-03-30 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0021_remove_household_hh_existing_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bus_respondentDob',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='bus_date_registered',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
