# Generated by Django 5.2 on 2025-06-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_reporttemplate_rte_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='rte_prepaired_by',
            new_name='rte_prepared_by',
        ),
    ]
