# Generated by Django 5.1.7 on 2025-03-19 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_type', models.CharField(max_length=100)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CommodityList',
            fields=[
                ('com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commodity_list',
            },
        ),
        migrations.CreateModel(
            name='FirstAidList',
            fields=[
                ('fa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fa_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'firstaid_list',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inv_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Medicinelist',
            fields=[
                ('med_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicine_list',
            },
        ),
        migrations.CreateModel(
            name='MedicineStocks',
            fields=[
                ('minv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minv_dsg', models.IntegerField()),
                ('minv_dsg_unit', models.CharField(max_length=100)),
                ('minv_form', models.CharField(max_length=100)),
                ('minv_qty', models.IntegerField()),
                ('minv_pcs_per_box', models.IntegerField()),
                ('minv_distributed', models.IntegerField(default=0)),
                ('minv_qty_avail', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicinelist')),
            ],
            options={
                'db_table': 'medicine_stocks',
            },
        ),
    ]
