# Generated by Django 5.1.6 on 2025-06-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationSupplies',
            fields=[
                ('imz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imz_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='Immunization Supplies', max_length=100)),
            ],
            options={
                'db_table': 'immunization_supplies',
            },
        ),
        migrations.CreateModel(
            name='VaccineList',
            fields=[
                ('vac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vac_type_choices', models.CharField(max_length=100)),
                ('vac_name', models.CharField(max_length=255)),
                ('no_of_doses', models.PositiveIntegerField(default=0)),
                ('age_group', models.CharField(max_length=50)),
                ('specify_age', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='Vaccine', max_length=100)),
            ],
            options={
                'db_table': 'vaccines',
            },
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inv_name',
            new_name='inv_type',
        ),
        migrations.AddField(
            model_name='commoditylist',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstaidlist',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_Archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='med_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commoditylist',
            name='com_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstaidlist',
            name='fa_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstaidlist',
            name='fa_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicinelist',
            name='med_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CommodityInventory',
            fields=[
                ('cinv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cinv_qty', models.PositiveIntegerField(default=0)),
                ('cinv_qty_unit', models.CharField(max_length=100)),
                ('cinv_pcs', models.PositiveIntegerField(default=0)),
                ('cinv_dispensed', models.PositiveIntegerField(default=0)),
                ('cinv_recevFrom', models.CharField(default='OTHERS', max_length=100)),
                ('cinv_qty_avail', models.PositiveIntegerField(default=0)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commoditylist')),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'commodity_inventory',
            },
        ),
        migrations.CreateModel(
            name='CommodityTransaction',
            fields=[
                ('comt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comt_qty', models.CharField(max_length=100)),
                ('comt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cinv_id', models.ForeignKey(db_column='cinv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.commodityinventory')),
            ],
            options={
                'db_table': 'commodity_transaction',
            },
        ),
        migrations.CreateModel(
            name='FirstAidInventory',
            fields=[
                ('finv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finv_qty', models.PositiveIntegerField(default=0)),
                ('finv_qty_unit', models.CharField(max_length=100)),
                ('finv_pcs', models.PositiveIntegerField(default=0)),
                ('finv_used', models.PositiveIntegerField(default=0)),
                ('finv_qty_avail', models.PositiveIntegerField(default=0)),
                ('fa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.firstaidlist')),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'firstaid_inventory',
            },
        ),
        migrations.CreateModel(
            name='FirstAidTransactions',
            fields=[
                ('fat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fat_qty', models.CharField(max_length=100)),
                ('fat_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finv_id', models.ForeignKey(db_column='finv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.firstaidinventory')),
            ],
            options={
                'db_table': 'firstaid_transaction',
            },
        ),
        migrations.CreateModel(
            name='ImmunizationStock',
            fields=[
                ('imzStck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(default=' N/A', max_length=100)),
                ('imzStck_qty', models.PositiveIntegerField(default=0)),
                ('imzStck_per_pcs', models.PositiveIntegerField(default=0)),
                ('imzStck_pcs', models.PositiveIntegerField(default=0)),
                ('imzStck_unit', models.CharField(max_length=100)),
                ('imzStck_used', models.PositiveIntegerField(default=0)),
                ('wasted_items', models.PositiveIntegerField(default=0)),
                ('imzStck_avail', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.inventory')),
                ('imz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.immunizationsupplies')),
            ],
            options={
                'db_table': 'immunizationsupplies_stock',
            },
        ),
        migrations.CreateModel(
            name='ImmunizationTransaction',
            fields=[
                ('imzt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imzt_qty', models.CharField(max_length=100)),
                ('imzt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imzStck_id', models.ForeignKey(db_column='imzStck_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.immunizationstock')),
            ],
            options={
                'db_table': 'immunization_transaction',
            },
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('minv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minv_dsg', models.PositiveIntegerField(default=0)),
                ('minv_dsg_unit', models.CharField(default='N/A', max_length=100)),
                ('minv_form', models.CharField(default='N/A', max_length=100)),
                ('minv_qty', models.PositiveIntegerField(default=0)),
                ('minv_qty_unit', models.CharField(default='N/A', max_length=100)),
                ('minv_pcs', models.PositiveIntegerField(default=0)),
                ('minv_distributed', models.PositiveIntegerField(default=0)),
                ('minv_qty_avail', models.PositiveIntegerField(default=0)),
                ('inv_id', models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('med_id', models.ForeignKey(db_column='med_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.medicinelist')),
            ],
            options={
                'db_table': 'medicine_inventory',
            },
        ),
        migrations.CreateModel(
            name='MedicineTransactions',
            fields=[
                ('mdt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mdt_qty', models.CharField(max_length=100)),
                ('mdt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minv_id', models.ForeignKey(db_column='minv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.medicineinventory')),
            ],
            options={
                'db_table': 'medicine_transaction',
            },
        ),
        migrations.CreateModel(
            name='VaccineInterval',
            fields=[
                ('vacInt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_intervals',
            },
        ),
        migrations.CreateModel(
            name='RoutineFrequency',
            fields=[
                ('routineF_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine_frequency', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'routine_frequencies',
            },
        ),
        migrations.CreateModel(
            name='VaccineStock',
            fields=[
                ('vacStck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solvent', models.CharField(max_length=10)),
                ('batch_number', models.CharField(default=' N/A', max_length=100)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('dose_ml', models.PositiveIntegerField(default=0)),
                ('vacStck_used', models.PositiveIntegerField(default=0)),
                ('vacStck_qty_avail', models.PositiveIntegerField(default=0)),
                ('wasted_dose', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inv_id', models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stock', to='inventory.inventory')),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stock', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_stocks',
            },
        ),
        migrations.CreateModel(
            name='AntigenTransaction',
            fields=[
                ('antt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('antt_qty', models.CharField(max_length=100)),
                ('antt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacStck_id', models.ForeignKey(db_column='vacStck_id', on_delete=django.db.models.deletion.CASCADE, related_name='antigen_transactions', to='inventory.vaccinestock')),
            ],
            options={
                'db_table': 'antigen_transaction',
            },
        ),
        migrations.DeleteModel(
            name='MedicineStocks',
        ),
    ]
