# Generated by Django 5.1.7 on 2025-03-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('minv_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('minv_dsg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minv_dsg_unit', models.CharField(max_length=100)),
                ('minv_form', models.CharField(max_length=100)),
                ('minv_qty', models.PositiveIntegerField()),
                ('minv_qty_unit', models.CharField(max_length=100)),
                ('minv_pcs', models.PositiveIntegerField()),
                ('minv_distributed', models.PositiveIntegerField(default=0)),
                ('minv_qty_avail', models.PositiveIntegerField(default=0)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicinelist')),
            ],
            options={
                'db_table': 'medicine_inventory',
            },
        ),
        migrations.DeleteModel(
            name='MedicineStocks',
        ),
    ]
