# Generated by Django 5.1.7 on 2025-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_cat_medicineinventory_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='minv_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='minv_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
