# Generated by Django 5.1.7 on 2025-03-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_medicineinventory_minv_pcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='minv_dsg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
