# Generated by Django 5.1.6 on 2025-06-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizationstock',
            name='wasted_items',
        ),
        migrations.AlterField(
            model_name='immunizationstock',
            name='imz_id',
            field=models.ForeignKey(db_column='imz_id', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.immunizationsupplies'),
        ),
        migrations.AlterField(
            model_name='immunizationstock',
            name='inv_id',
            field=models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.inventory'),
        ),
    ]
