# Generated by Django 5.1.7 on 2025-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_inv_name_inventory_inv_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
