# Generated by Django 5.1.7 on 2025-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='minv_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
