# Generated by Django 5.1.7 on 2025-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_medicinetransaction_delete_addmedicinestocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicineTransaction',
            new_name='MedicineTransactions',
        ),
    ]
