# Generated by Django 5.1.7 on 2025-03-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_medicinetransaction_medicinetransactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineTransactions',
        ),
    ]
