# Generated by Django 5.1.7 on 2025-03-23 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20250321_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinetransactions',
            name='mdt_qty_avail',
        ),
        migrations.AlterField(
            model_name='medicinetransactions',
            name='mdt_qty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicinetransactions',
            name='minv_id',
            field=models.ForeignKey(db_column='minv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.medicineinventory'),
        ),
    ]
