# Generated by Django 5.1.7 on 2025-03-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_medicinetransactions_mdt_qty_avail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineTransactions',
        ),
    ]
