# Generated by Django 5.1.7 on 2025-03-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_delete_medicinetransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTransactions',
            fields=[
                ('mdt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mdt_qty', models.CharField(max_length=100)),
                ('mdt_action', models.CharField(max_length=100)),
                ('mdt_staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minv_id', models.ForeignKey(db_column='minv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.medicineinventory')),
            ],
            options={
                'db_table': 'medicine_transaction',
            },
        ),
    ]
