# Generated by Django 5.1.7 on 2025-03-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_medicinetransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInventory',
            fields=[
                ('cinv', models.BigAutoField(primary_key=True, serialize=False)),
                ('cinv_qty', models.PositiveIntegerField(default=0)),
                ('cinv_qty_unit', models.CharField(max_length=100)),
                ('cinv_pcs', models.PositiveIntegerField(default=0)),
                ('cinv_dispensed', models.PositiveIntegerField(default=0)),
                ('cinv_qty_avail', models.PositiveIntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commoditylist')),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'commodity_inventory',
            },
        ),
        migrations.CreateModel(
            name='CommodityTransaction',
            fields=[
                ('comt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comt_qty', models.CharField(max_length=100)),
                ('comt_action', models.CharField(max_length=100)),
                ('comt_staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cinv', models.ForeignKey(db_column='cinv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.commodityinventory')),
            ],
            options={
                'db_table': 'commodity_transaction',
            },
        ),
    ]
