# Generated by Django 5.1.7 on 2025-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_commodityinventory_commoditytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinventory',
            name='cinv_recevFrom',
            field=models.CharField(default='OTHERS', max_length=100),
        ),
    ]
