# Generated by Django 5.1.7 on 2025-03-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_commodityinventory_cinv_recevfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodityinventory',
            old_name='cinv',
            new_name='cinv_id',
        ),
        migrations.RenameField(
            model_name='commoditytransaction',
            old_name='cinv',
            new_name='cinv_id',
        ),
        migrations.AlterField(
            model_name='commodityinventory',
            name='inv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', unique=True),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='inv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', unique=True),
        ),
    ]
