# Generated by Django 5.1.7 on 2025-03-23 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_rename_cinv_commodityinventory_cinv_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditytransaction',
            old_name='comt_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='medicinetransactions',
            old_name='mdt_staff',
            new_name='staff',
        ),
        migrations.CreateModel(
            name='FirstAidInventory',
            fields=[
                ('finv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finv_qty', models.PositiveIntegerField(default=0)),
                ('finv_qty_unit', models.CharField(max_length=100)),
                ('finv_pcs', models.PositiveIntegerField(default=0)),
                ('finv_used', models.PositiveIntegerField(default=0)),
                ('finv_qty_avail', models.PositiveIntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('fa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.firstaidlist')),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', unique=True)),
            ],
            options={
                'db_table': 'firstaid_inventory',
            },
        ),
        migrations.CreateModel(
            name='FirstAidTransactions',
            fields=[
                ('fat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fat_qty', models.CharField(max_length=100)),
                ('fat_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finv_id', models.ForeignKey(db_column='finv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.firstaidinventory')),
            ],
            options={
                'db_table': 'firstaid_transaction',
            },
        ),
    ]
