# Generated by Django 5.1.7 on 2025-03-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_rename_comt_staff_commoditytransaction_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinventory',
            name='inv_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='firstaidinventory',
            name='inv_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='inv_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
