# Generated by Django 5.1.7 on 2025-03-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_commodityinventory_inv_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineList',
            fields=[
                ('vac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vac_type_choices', models.CharField(max_length=100)),
                ('vac_name', models.CharField(max_length=255)),
                ('no_of_doses', models.PositiveIntegerField(default=0)),
                ('age_group', models.CharField(max_length=50)),
                ('specify_age', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vaccines',
            },
        ),
        migrations.CreateModel(
            name='VaccineInterval',
            fields=[
                ('vacInt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_intervals',
            },
        ),
        migrations.CreateModel(
            name='RoutineFrequency',
            fields=[
                ('routineF_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'routine_frequencies',
            },
        ),
    ]
