# Generated by Django 5.1.7 on 2025-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_vaccinelist_vaccineinterval_routinefrequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinefrequency',
            name='dose_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccineinterval',
            name='dose_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
