# Generated by Django 5.1.7 on 2025-03-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_routinefrequency_dose_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationSupplies',
            fields=[
                ('imz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imz_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'immunization_supplies',
            },
        ),
        migrations.CreateModel(
            name='VaccineCategory',
            fields=[
                ('vaccat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccat_type', models.CharField(default='N/A', max_length=255)),
            ],
            options={
                'db_table': 'vaccine_category',
            },
        ),
        migrations.AddField(
            model_name='vaccineinterval',
            name='vaccat_id',
            field=models.ForeignKey(db_column='finv_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory'),
            preserve_default=False,
        ),
    ]
