# Generated by Django 5.1.7 on 2025-03-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_immunizationsupplies_vaccat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizationsupplies',
            name='vaccat_id',
        ),
        migrations.RemoveField(
            model_name='vaccineinterval',
            name='vaccat_id',
        ),
    ]
