# Generated by Django 5.1.7 on 2025-03-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_immunizationsupplies_vaccat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationsupplies',
            name='vaccat_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory'),
        ),
        migrations.AddField(
            model_name='vaccinelist',
            name='vaccat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory'),
        ),
    ]
