# Generated by Django 5.1.7 on 2025-03-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_immunizationsupplies_vaccat_id_vaccinelist_vaccat_id'),
    ]

    operations = [
    ]
