# Generated by Django 5.1.7 on 2025-03-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_add_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinefrequency',
            name='vac_id',
        ),
        migrations.RemoveField(
            model_name='vaccinelist',
            name='vaccat_id',
        ),
        migrations.RemoveField(
            model_name='vaccineinterval',
            name='vac_id',
        ),
        migrations.AlterModelTable(
            name='firstaidtransactions',
            table='routine_frequencies',
        ),
        migrations.DeleteModel(
            name='ImmunizationSupplies',
        ),
        migrations.DeleteModel(
            name='RoutineFrequency',
        ),
        migrations.DeleteModel(
            name='VaccineCategory',
        ),
        migrations.DeleteModel(
            name='VaccineInterval',
        ),
        migrations.DeleteModel(
            name='VaccineList',
        ),
    ]
