# Generated by Django 5.1.7 on 2025-03-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_routinefrequency_vac_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCategory',
            fields=[
                ('vaccat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccat_type', models.CharField(default='N/A', max_length=255)),
            ],
            options={
                'db_table': 'vaccine_category',
            },
        ),
        migrations.AlterModelTable(
            name='firstaidtransactions',
            table='firstaid_transaction',
        ),
        migrations.CreateModel(
            name='ImmunizationSupplies',
            fields=[
                ('imz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imz_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccat_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory')),
            ],
            options={
                'db_table': 'immunization_supplies',
            },
        ),
        migrations.CreateModel(
            name='VaccineList',
            fields=[
                ('vac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vac_type_choices', models.CharField(max_length=100)),
                ('vac_name', models.CharField(max_length=255)),
                ('no_of_doses', models.PositiveIntegerField(default=0)),
                ('age_group', models.CharField(max_length=50)),
                ('specify_age', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccat_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory')),
            ],
            options={
                'db_table': 'vaccines',
            },
        ),
        migrations.CreateModel(
            name='VaccineInterval',
            fields=[
                ('vacInt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_intervals',
            },
        ),
        migrations.CreateModel(
            name='RoutineFrequency',
            fields=[
                ('routineF_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'routine_frequencies',
            },
        ),
    ]
