# Generated by Django 5.1.7 on 2025-03-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_vaccinecategory_alter_firstaidtransactions_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vaccinelist',
            table='immunization_supplies',
        ),
        migrations.DeleteModel(
            name='ImmunizationSupplies',
        ),
    ]
