# Generated by Django 5.1.7 on 2025-03-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_vaccinelist_table_delete_immunizationsupplies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vaccinelist',
            table='vaccines',
        ),
        migrations.CreateModel(
            name='ImmunizationSupplies',
            fields=[
                ('imz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imz_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccat_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory')),
            ],
            options={
                'db_table': 'immunization_supplies',
            },
        ),
    ]
