# Generated by Django 5.1.7 on 2025-03-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0042_remove_medicineinventory_cat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_type', models.CharField(max_length=100)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CommodityList',
            fields=[
                ('com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commodity_list',
            },
        ),
        migrations.CreateModel(
            name='FirstAidList',
            fields=[
                ('fa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fa_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'firstaid_list',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateField()),
                ('inv_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Medicinelist',
            fields=[
                ('med_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicine_list',
            },
        ),
        migrations.CreateModel(
            name='VaccineCategory',
            fields=[
                ('vaccat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccat_type', models.CharField(default='N/A', max_length=255)),
            ],
            options={
                'db_table': 'vaccine_category',
            },
        ),
        migrations.CreateModel(
            name='CommodityInventory',
            fields=[
                ('cinv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cinv_qty', models.PositiveIntegerField(default=0)),
                ('cinv_qty_unit', models.CharField(max_length=100)),
                ('cinv_pcs', models.PositiveIntegerField(default=0)),
                ('cinv_dispensed', models.PositiveIntegerField(default=0)),
                ('cinv_recevFrom', models.CharField(default='OTHERS', max_length=100)),
                ('cinv_qty_avail', models.PositiveIntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commoditylist')),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'commodity_inventory',
            },
        ),
        migrations.CreateModel(
            name='CommodityTransaction',
            fields=[
                ('comt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comt_qty', models.CharField(max_length=100)),
                ('comt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cinv_id', models.ForeignKey(db_column='cinv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.commodityinventory')),
            ],
            options={
                'db_table': 'commodity_transaction',
            },
        ),
        migrations.CreateModel(
            name='FirstAidInventory',
            fields=[
                ('finv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finv_qty', models.PositiveIntegerField(default=0)),
                ('finv_qty_unit', models.CharField(max_length=100)),
                ('finv_pcs', models.PositiveIntegerField(default=0)),
                ('finv_used', models.PositiveIntegerField(default=0)),
                ('finv_qty_avail', models.PositiveIntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('fa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.firstaidlist')),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'firstaid_inventory',
            },
        ),
        migrations.CreateModel(
            name='FirstAidTransactions',
            fields=[
                ('fat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fat_qty', models.CharField(max_length=100)),
                ('fat_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finv_id', models.ForeignKey(db_column='finv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.firstaidinventory')),
            ],
            options={
                'db_table': 'firstaid_transaction',
            },
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('minv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minv_dsg', models.PositiveIntegerField(default=0)),
                ('minv_dsg_unit', models.CharField(max_length=100)),
                ('minv_form', models.CharField(max_length=100)),
                ('minv_qty', models.PositiveIntegerField(default=0)),
                ('minv_qty_unit', models.CharField(max_length=100)),
                ('minv_pcs', models.PositiveIntegerField(default=0)),
                ('minv_distributed', models.PositiveIntegerField(default=0)),
                ('minv_qty_avail', models.PositiveIntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicinelist')),
            ],
            options={
                'db_table': 'medicine_inventory',
            },
        ),
        migrations.CreateModel(
            name='MedicineTransactions',
            fields=[
                ('mdt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mdt_qty', models.CharField(max_length=100)),
                ('mdt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minv_id', models.ForeignKey(db_column='minv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.medicineinventory')),
            ],
            options={
                'db_table': 'medicine_transaction',
            },
        ),
        migrations.CreateModel(
            name='ImmunizationSupplies',
            fields=[
                ('imz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imz_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccat_id', models.ForeignKey(db_column='vaccat_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory')),
            ],
            options={
                'db_table': 'immunization_supplies',
            },
        ),
        migrations.CreateModel(
            name='VaccineList',
            fields=[
                ('vac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vac_type_choices', models.CharField(max_length=100)),
                ('vac_name', models.CharField(max_length=255)),
                ('no_of_doses', models.PositiveIntegerField(default=0)),
                ('age_group', models.CharField(max_length=50)),
                ('specify_age', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccat_id', models.ForeignKey(db_column='vaccat_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory')),
            ],
            options={
                'db_table': 'vaccines',
            },
        ),
        migrations.CreateModel(
            name='VaccineInterval',
            fields=[
                ('vacInt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_intervals',
            },
        ),
        migrations.CreateModel(
            name='RoutineFrequency',
            fields=[
                ('routineF_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'routine_frequencies',
            },
        ),
    ]
