# Generated by Django 5.1.7 on 2025-03-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationsupplies',
            name='vaccat_id',
            field=models.ForeignKey(db_column='vaccat_id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='immunization_supplies', to='inventory.vaccinecategory'),
        ),
        migrations.AlterField(
            model_name='routinefrequency',
            name='vac_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine_frequency', to='inventory.vaccinelist'),
        ),
        migrations.AlterField(
            model_name='vaccineinterval',
            name='vac_id',
            field=models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='inventory.vaccinelist'),
        ),
        migrations.AlterField(
            model_name='vaccinelist',
            name='vaccat_id',
            field=models.ForeignKey(db_column='vaccat_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='inventory.vaccinecategory'),
        ),
    ]
