# Generated by Django 5.1.7 on 2025-03-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_alter_immunizationsupplies_vaccat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineStock',
            fields=[
                ('vacStck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solvent', models.CharField(max_length=10)),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('volume', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('dose_number', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stocks', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_stocks',
            },
        ),
    ]
