# Generated by Django 5.1.7 on 2025-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_vaccinestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinestock',
            name='dose_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
