# Generated by Django 5.1.7 on 2025-03-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_alter_vaccinestock_dose_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinestock',
            old_name='dose_number',
            new_name='dose_ml',
        ),
    ]
