# Generated by Django 5.1.7 on 2025-03-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_rename_dose_number_vaccinestock_dose_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntigenTransaction',
            fields=[
                ('antt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('antt_qty', models.CharField(max_length=100)),
                ('antt_type', models.CharField(max_length=100)),
                ('antt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacStck_id', models.ForeignKey(db_column='vacStck_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinestock')),
            ],
            options={
                'db_table': 'antigen_transaction',
            },
        ),
    ]
