# Generated by Django 5.1.7 on 2025-03-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_remove_vaccinestock_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinestock',
            name='inv_id',
            field=models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
