# Generated by Django 5.1.7 on 2025-03-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_vaccinestock_inv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestock',
            name='vacStck_qty_avail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinestock',
            name='vacStck_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImmunizationStock',
            fields=[
                ('imzStck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imzStck_qty_box', models.PositiveIntegerField(default=0)),
                ('imzStck_pcs', models.PositiveIntegerField(default=0)),
                ('imzStck_unit', models.CharField(max_length=100)),
                ('imzStck_used', models.PositiveIntegerField(default=0)),
                ('imzStck_avail', models.PositiveIntegerField(default=0)),
                ('inv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('vac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'immunizationsupplies_stock',
            },
        ),
    ]
