# Generated by Django 5.1.7 on 2025-03-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_vaccinestock_vacstck_qty_avail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizationstock',
            name='vac_id',
        ),
        migrations.AddField(
            model_name='immunizationstock',
            name='imz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.immunizationsupplies'),
            preserve_default=False,
        ),
    ]
