# Generated by Django 5.1.7 on 2025-03-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_remove_immunizationstock_vac_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationTransaction',
            fields=[
                ('imzt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imzt_qty', models.CharField(max_length=100)),
                ('imzt_type', models.CharField(max_length=100)),
                ('imzt_action', models.CharField(max_length=100)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imzStck_id', models.ForeignKey(db_column='imzStck_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.immunizationstock')),
            ],
            options={
                'db_table': 'immunization_transaction',
            },
        ),
    ]
