# Generated by Django 5.1.7 on 2025-03-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_immunizationtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immunizationstock',
            old_name='imzStck_qty_box',
            new_name='imzStck_qty',
        ),
    ]
