# Generated by Django 5.1.7 on 2025-04-02 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_rename_imzstck_qty_box_immunizationstock_imzstck_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immunizationstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_Archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinestock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinestock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
