# Generated by Django 5.1.7 on 2025-04-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_remove_commodityinventory_cat_id_and_more'),
    ]

    operations = [
    ]
