# Generated by Django 5.1.7 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestock',
            name='wasted_dose',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
