# Generated by Django 5.1.7 on 2025-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_vaccinestock_wasted_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationstock',
            name='batch_number',
            field=models.CharField(default=' N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='batch_number',
            field=models.CharField(default=' N/A', max_length=100),
        ),
    ]
