# Generated by Django 5.1.7 on 2025-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_immunizationstock_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationstock',
            name='imzStck_per_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
