# Generated by Django 5.1.7 on 2025-04-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_immunizationstock_imzstck_per_pcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antigentransaction',
            name='antt_type',
        ),
        migrations.RemoveField(
            model_name='immunizationtransaction',
            name='imzt_type',
        ),
    ]
