# Generated by Django 5.1.6 on 2025-04-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_remove_antigentransaction_antt_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antigentransaction',
            name='vacStck_id',
            field=models.ForeignKey(db_column='vacStck_id', on_delete=django.db.models.deletion.CASCADE, related_name='antigen_transactions', to='inventory.vaccinestock'),
        ),
        migrations.AlterField(
            model_name='immunizationstock',
            name='imz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.immunizationsupplies'),
        ),
        migrations.AlterField(
            model_name='immunizationstock',
            name='inv_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='inv_id',
            field=models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stock', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='vac_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stock', to='inventory.vaccinelist'),
        ),
    ]
