# Generated by Django 5.1.6 on 2025-06-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_alter_antigentransaction_vacstck_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinelist',
            name='vaccat_id',
        ),
        migrations.RemoveField(
            model_name='immunizationsupplies',
            name='vaccat_id',
        ),
        migrations.RemoveField(
            model_name='commodityinventory',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='firstaidinventory',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='commoditylist',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstaidlist',
            name='cat_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immunizationsupplies',
            name='category',
            field=models.CharField(default='immunization_supplies', max_length=100),
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='cat_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinelist',
            name='category',
            field=models.CharField(default='vaccine', max_length=100),
        ),
        migrations.DeleteModel(
            name='VaccineCategory',
        ),
    ]
