# Generated by Django 5.1.6 on 2025-06-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_remove_vaccinelist_vaccat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelist',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='med_name',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='updated_at',
        ),
    ]
