# Generated by Django 5.1.6 on 2025-06-02 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_remove_medicinelist_cat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditylist',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='firstaidlist',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='cat',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='med_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
