# Generated by Django 5.1.6 on 2025-06-02 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_rename_cat_id_commoditylist_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelist',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='med_id',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='med_name',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
