# Generated by Django 5.1.6 on 2025-06-02 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_remove_medicinelist_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelist',
            name='id',
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='cat',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='med_id',
            field=models.BigAutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='med_name',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
