# Generated by Django 5.1.6 on 2025-06-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0080_remove_medicinelist_id_medicinelist_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelist',
            name='med_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
