# Generated by Django 5.1.6 on 2025-06-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_alter_medicinelist_med_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditylist',
            name='com_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstaidlist',
            name='fa_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
