# Generated by Django 5.1.6 on 2025-06-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_alter_commoditylist_com_id_alter_firstaidlist_fa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelist',
            name='med_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
