# Generated by Django 5.1.6 on 2025-06-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_medicinelist_med_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditylist',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='cat',
        ),
    ]
