# Generated by Django 5.1.6 on 2025-06-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_remove_commoditylist_cat_remove_firstaidlist_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditylist',
            name='cat',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstaidlist',
            name='cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
    ]
