# Generated by Django 5.1.6 on 2025-06-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0085_commoditylist_cat_firstaidlist_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditylist',
            name='cat',
            field=models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.RenameField(
            model_name='commoditylist',
            old_name='cat',
            new_name='cat_id',
        ),
        migrations.AlterField(
            model_name='firstaidlist',
            name='cat',
            field=models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.RenameField(
            model_name='firstaidlist',
            old_name='cat',
            new_name='cat_id',
        ),
    ]
