# Generated by Django 5.1.6 on 2025-06-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0086_alter_commoditylist_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditylist',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='commoditylist',
            name='com_name',
        ),
        migrations.RemoveField(
            model_name='commoditylist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commoditylist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='fa_name',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='updated_at',
        ),
    ]
