# Generated by Django 5.1.6 on 2025-06-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0088_commoditylist_com_name_commoditylist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditylist',
            name='cat',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
    ]
