# Generated by Django 5.1.6 on 2025-06-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0089_commoditylist_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelist',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
    ]
