# Generated by Django 5.1.6 on 2025-06-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_alter_medicinelist_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditylist',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
    ]
