# Generated by Django 5.1.6 on 2025-06-03 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_alter_commoditylist_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidlist',
            name='cat',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
    ]
