# Generated by Django 5.1.6 on 2025-06-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_firstaidlist_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidlist',
            name='cat',
        ),
    ]
