# Generated by Django 5.1.6 on 2025-06-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_remove_firstaidlist_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidlist',
            name='cat',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
    ]
