# Generated by Django 5.1.6 on 2025-06-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0094_firstaidlist_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidlist',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='fa_name',
        ),
        migrations.RemoveField(
            model_name='firstaidlist',
            name='updated_at',
        ),
    ]
