# Generated by Django 5.1.6 on 2025-06-03 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_remove_firstaidlist_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidlist',
            name='cat',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstaidlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstaidlist',
            name='fa_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='firstaidlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
