# Generated by Django 5.1.6 on 2025-06-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_firstaidlist_cat_firstaidlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidlist',
            name='cat',
        ),
    ]
