# Generated by Django 5.1.6 on 2025-06-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_firstaidlist_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinelist',
            name='category',
        ),
    ]
