# Generated by Django 5.1.6 on 2025-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_remove_vaccinelist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinelist',
            name='category',
            field=models.CharField(default='vaccine', max_length=100),
        ),
    ]
