# Generated by Django 5.1.6 on 2025-06-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_vaccinelist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinelist',
            name='category',
        ),
    ]
