# Generated by Django 5.1.6 on 2025-06-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_remove_vaccinelist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinelist',
            name='category',
            field=models.CharField(default='Vaccine', max_length=100),
        ),
        migrations.AlterField(
            model_name='immunizationsupplies',
            name='category',
            field=models.CharField(default='Immunization Supplies', max_length=100),
        ),
    ]
