# Generated by Django 5.1.6 on 2025-06-05 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0105_remove_medicineinventory_inv_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='inv_id',
            field=models.OneToOneField(db_column='inv_id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='med_id',
            field=models.ForeignKey(db_column='med_id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicinelist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_distributed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_dsg_unit',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_form',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_pcs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_qty_avail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minv_qty_unit',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
