# Generated by Django 5.1.6 on 2025-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_medicineinventory_inv_id_medicineinventory_med_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationstock',
            name='wasted_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
