# Generated by Django 5.1.6 on 2025-06-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0115_immunizationstock_wasted_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineinventory',
            name='inv_id',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='med_id',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_distributed',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_dsg_unit',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_form',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_pcs',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_qty',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_qty_avail',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='minv_qty_unit',
        ),
    ]
