# Generated by Django 5.2 on 2025-04-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgementReport',
            fields=[
                ('ar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar_incident_activity', models.CharField(max_length=50)),
                ('ar_location', models.TextField()),
                ('ar_sitio', models.CharField(max_length=50)),
                ('ar_date_started', models.DateField()),
                ('ar_time_started', models.TimeField()),
                ('ar_date_completed', models.DateField()),
                ('ar_time_completed', models.TimeField()),
                ('ar_action', models.TextField()),
            ],
            options={
                'db_table': 'acknowledgement_report',
            },
        ),
        migrations.CreateModel(
            name='AcknowledgementReportFile',
            fields=[
                ('arf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drr.acknowledgementreport')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
    ]
