# Generated by Django 4.2.20 on 2025-03-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_lname', models.CharField(max_length=100)),
                ('acc_fname', models.CharField(max_length=100)),
                ('acc_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('acc_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('acc_contact', models.CharField(max_length=15, unique=True)),
                ('acc_address', models.TextField()),
            ],
            options={
                'db_table': 'accused',
            },
        ),
        migrations.CreateModel(
            name='BlotterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_date', models.DateField(auto_now_add=True)),
                ('rep_occurred_date', models.DateField()),
                ('rep_reasons', models.TextField()),
                ('rep_type', models.CharField(choices=[('complaint', 'Complaint'), ('incident', 'Incident'), ('violation', 'Violation')], max_length=20)),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blotter.accused')),
            ],
            options={
                'db_table': 'blotter_report',
            },
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_lname', models.CharField(max_length=100)),
                ('comp_fname', models.CharField(max_length=100)),
                ('comp_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('comp_contact', models.CharField(max_length=15, unique=True)),
                ('comp_address', models.TextField()),
            ],
            options={
                'db_table': 'complainant',
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='supporting_documents/')),
                ('blotter_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='blotter.blotterreport')),
            ],
            options={
                'db_table': 'blotter_supporting_document',
            },
        ),
        migrations.AddField(
            model_name='blotterreport',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blotter.complainant'),
        ),
    ]
