# Generated by Django 4.2.20 on 2025-04-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_complainant', models.CharField(max_length=255)),
                ('bc_cmplnt_address', models.CharField(max_length=255)),
                ('bc_accused', models.CharField(max_length=255)),
                ('bc_accused_address', models.CharField(max_length=255)),
                ('bc_incident_type', models.CharField(max_length=100)),
                ('bc_datetime', models.CharField(max_length=100)),
                ('bc_allegation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlotterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('blotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blotter.blotter')),
            ],
        ),
    ]
