# Generated by Django 4.2.20 on 2025-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blotter',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bc_complainant', models.CharField(max_length=100)),
                ('bc_cmplnt_address', models.CharField(blank=True, max_length=100, null=True)),
                ('bc_accused', models.CharField(max_length=100)),
                ('bc_accused_address', models.CharField(blank=True, max_length=100, null=True)),
                ('bc_incident_type', models.CharField(max_length=100)),
                ('bc_allegation', models.TextField()),
                ('bc_datetime', models.DateTimeField()),
                ('bc_evidence', models.FileField(upload_to='blotter_evidence/')),
            ],
            options={
                'db_table': 'blotter',
            },
        ),
    ]
