# Generated by Django 4.2.20 on 2025-04-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blotter',
            table='blotter',
        ),
        migrations.AlterModelTable(
            name='blottermedia',
            table='blotter_media',
        ),
    ]
