# Generated by Django 4.2.20 on 2025-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blotter',
            name='bc_evidence',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
