# Generated by Django 5.2 on 2025-12-15 16:15

import apps.account.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('pv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pv_created_at', models.DateTimeField(auto_now_add=True)),
                ('pv_phone_num', models.CharField(max_length=11)),
                ('pv_otp', models.CharField(max_length=6, null=True)),
                ('pv_sent', models.BooleanField(default=False)),
                ('pv_type', models.CharField(default=False, max_length=10)),
            ],
            options={
                'db_table': 'phone_verification',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('acc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('email', models.CharField(null=True, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('profile_image', models.URLField(blank=True, default='https://isxckceeyjcwvjipndfd.supabase.co/storage/v1/object/public/profile_picture-bucket/1757783075918_c1nodq418e.png', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='Phone Number')),
                ('br', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to='profiling.businessrespondent')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='profiling.residentprofile')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'account',
            },
            managers=[
                ('objects', apps.account.models.AccountManager()),
            ],
        ),
    ]
