# Generated by Django 4.2.20 on 2025-06-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiling', '0006_alter_address_add_external_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('supabase_id', models.UUIDField(unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.URLField(blank=True, default='https://isxckceeyjcwvjipndfd.supabase.co/storage/v1/object/public/userimage//sanRoqueLogo.svg', max_length=500, null=True)),
                ('rp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
