# Generated by Django 4.2.20 on 2025-06-20 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='supabase_id',
            field=models.CharField(editable=False, help_text='Unique identifier from Supabase Auth', max_length=255, unique=True, verbose_name='Supabase User ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username is required.', 'min_length': 'Username must be at least 3 characters long.', 'null': 'Username is required.', 'unique': 'This username is already taken.'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
