# Generated by Django 5.1.6 on 2025-04-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('profiling', '0010_alter_sitio_sitio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rp',
            field=models.ForeignKey(default='00001250331', on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
            preserve_default=False,
        ),
    ]
