# Generated by Django 5.2 on 2025-07-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('profiling', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='br',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to='profiling.businessrespondent'),
        ),
    ]
