# Generated by Django 4.2.20 on 2025-04-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('account', '0002_account_rp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='administration.staff'),
        ),
    ]
