# Generated by Django 4.2.20 on 2025-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.URLField(blank=True, default='https://isxckceeyjcwvjipndfd.supabase.co/storage/v1/object/public/userimage//sanRoqueLogo.svg', max_length=500, null=True),
        ),
    ]
