# Generated by Django 5.1.6 on 2025-04-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_rp'),
        ('profiling', '0011_alter_business_staff_alter_family_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='profiling.residentprofile'),
        ),
    ]
