# Generated by Django 4.2.20 on 2025-04-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_staff'),
        ('account', '0003_alter_account_rp'),
    ]

    operations = [
    ]
