# Generated by Django 4.2.20 on 2025-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_0003_account_staff_0003_alter_account_rp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='staff',
        ),
    ]
