# Generated by Django 5.2 on 2025-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
