# Generated by Django 5.2 on 2025-06-22 21:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_province', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_barangay', models.CharField(max_length=50)),
                ('add_street', models.CharField(max_length=50)),
                ('add_external_sitio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('per_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(max_length=100, null=True)),
                ('per_suffix', models.CharField(max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sitio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fam_indigenous', models.CharField(max_length=50)),
                ('fam_building', models.CharField(max_length=50)),
                ('fam_date_registered', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('fc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fc_role', models.CharField(max_length=50)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='healthProfiling.family')),
            ],
            options={
                'db_table': 'family_composition',
            },
        ),
        migrations.CreateModel(
            name='Dependents_Under_Five',
            fields=[
                ('duf_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('duf_fic', models.CharField(max_length=50)),
                ('duf_nutritional_status', models.CharField(max_length=50)),
                ('duf_exclusive_bf', models.CharField(max_length=50)),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.familycomposition')),
            ],
            options={
                'db_table': 'dep_under_five',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hh_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hh_nhts', models.CharField(max_length=50)),
                ('hh_date_registered', models.DateField(default=datetime.date.today)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='hh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household'),
        ),
        migrations.CreateModel(
            name='HealthRelatedDetails',
            fields=[
                ('hrd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hrd_blood_type', models.CharField(max_length=5)),
                ('hrd_philhealth_id', models.CharField(max_length=50)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'health_related_details',
            },
        ),
        migrations.CreateModel(
            name='Dependents_Over_Five',
            fields=[
                ('dep_ov_five_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.familycomposition')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'dep_over_five',
            },
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('pa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'personal_address',
            },
        ),
        migrations.CreateModel(
            name='RequestRegistration',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_date', models.DateField()),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'request_registration',
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('rp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rp_date_registered', models.DateField(default=datetime.date.today)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='healthProfiling.personal')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profiles', to='administration.staff')),
            ],
            options={
                'db_table': 'resident_profile',
            },
        ),
        migrations.CreateModel(
            name='NonCommunicableDisease',
            fields=[
                ('ncd_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ncd_riskclass_age', models.CharField(max_length=100)),
                ('ncd_comorbidities', models.CharField(max_length=100)),
                ('ncd_lifestyle_risk', models.CharField(max_length=100)),
                ('ncd_maintenance_status', models.CharField(max_length=100)),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'non_communicable_disease',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='familycomposition',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='healthProfiling.residentprofile'),
        ),
        migrations.CreateModel(
            name='SanitaryFacility',
            fields=[
                ('sf_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sf_type', models.CharField(max_length=50)),
                ('sf_toilet_type', models.CharField(max_length=50)),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household')),
            ],
            options={
                'db_table': 'sanitary_facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityDetails',
            fields=[
                ('fd_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fd_description', models.CharField(max_length=200)),
                ('sf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.sanitaryfacility')),
            ],
            options={
                'db_table': 'facility_details',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.sitio'),
        ),
        migrations.CreateModel(
            name='SolidWasteMgmt',
            fields=[
                ('swm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('swn_desposal_type', models.CharField(max_length=50)),
                ('swm_desc', models.TextField(max_length=1000)),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household')),
            ],
            options={
                'db_table': 'solid_waste_mgmt',
            },
        ),
        migrations.CreateModel(
            name='TBsurveilance',
            fields=[
                ('tb_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tb_meds_source', models.CharField(max_length=100)),
                ('tb_days_taking_meds', models.IntegerField()),
                ('tb_status', models.CharField(max_length=100)),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'tb_surveillance_records',
            },
        ),
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('water_sup_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('water_sup_type', models.CharField(max_length=50)),
                ('water_sup_desc', models.TextField(max_length=1000)),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household')),
            ],
            options={
                'db_table': 'water_supply',
            },
        ),
    ]
