# Generated by Django 5.1.6 on 2025-12-15 06:54

import datetime
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_province', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_barangay', models.CharField(max_length=50)),
                ('add_street', models.CharField(max_length=50)),
                ('add_external_sitio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('kyc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_document_front', models.TextField(blank=True, null=True)),
                ('id_has_face', models.BooleanField(default=False, null=True)),
                ('id_face_embedding', models.BinaryField(blank=True, null=True)),
                ('face_photo', models.TextField(blank=True, null=True)),
                ('document_info_match', models.BooleanField(default=False, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kyc_record',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sitio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fam_indigenous', models.CharField(max_length=50)),
                ('fam_building', models.CharField(max_length=50)),
                ('fam_date_registered', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='administration.staff')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPersonal',
            fields=[
                ('per_id', models.BigIntegerField(blank=True, db_index=True)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('per_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(blank=True, max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=20)),
                ('per_disability', models.CharField(blank=True, max_length=100, null=True)),
                ('per_is_deceased', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
            ],
            options={
                'verbose_name': 'historical personal',
                'verbose_name_plural': 'historical personals',
                'db_table': 'personal_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSurveyIdentification',
            fields=[
                ('si_id', models.CharField(db_index=True, max_length=50)),
                ('si_filled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('si_informant', models.CharField(max_length=100)),
                ('si_checked_by', models.CharField(max_length=100)),
                ('si_date', models.DateField()),
                ('si_signature', models.TextField()),
                ('si_created_at', models.DateTimeField(blank=True, editable=False)),
                ('si_updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.family')),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
            ],
            options={
                'verbose_name': 'historical survey identification',
                'verbose_name_plural': 'historical survey identifications',
                'db_table': 'survey_identification_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hh_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hh_nhts', models.CharField(max_length=50)),
                ('hh_date_registered', models.DateField(default=datetime.date.today)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='administration.staff')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWaterSupply',
            fields=[
                ('water_sup_id', models.BigIntegerField(blank=True, db_index=True)),
                ('water_sup_type', models.CharField(max_length=50)),
                ('water_conn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_sup_desc', models.TextField(max_length=1000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('hh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.household')),
            ],
            options={
                'verbose_name': 'historical water supply',
                'verbose_name_plural': 'historical water supplys',
                'db_table': 'water_supply_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSolidWasteMgmt',
            fields=[
                ('swm_id', models.BigIntegerField(blank=True, db_index=True)),
                ('swn_desposal_type', models.CharField(max_length=50)),
                ('swm_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('hh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.household')),
            ],
            options={
                'verbose_name': 'historical solid waste mgmt',
                'verbose_name_plural': 'historical solid waste mgmts',
                'db_table': 'solid_waste_mgmt_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSanitaryFacility',
            fields=[
                ('sf_id', models.BigIntegerField(blank=True, db_index=True)),
                ('sf_type', models.CharField(max_length=50)),
                ('sf_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('sf_toilet_type', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('hh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.household')),
            ],
            options={
                'verbose_name': 'historical sanitary facility',
                'verbose_name_plural': 'historical sanitary facilitys',
                'db_table': 'sanitary_facility_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='family',
            name='hh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('per_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('per_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(blank=True, max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=20)),
                ('per_disability', models.CharField(blank=True, max_length=100, null=True)),
                ('per_is_deceased', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'personal',
                'indexes': [models.Index(fields=['per_lname', 'per_fname'], name='personal_per_lna_29932c_idx'), models.Index(fields=['per_contact'], name='personal_per_con_396812_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('pa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_addresses', to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'personal_address',
            },
        ),
        migrations.CreateModel(
            name='PersonalAddressHistory',
            fields=[
                ('pah_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_id', models.IntegerField()),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'personal_address_history',
            },
        ),
        migrations.CreateModel(
            name='PersonalModification',
            fields=[
                ('pm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pm_lname', models.CharField(max_length=50, null=True)),
                ('pm_fname', models.CharField(max_length=50, null=True)),
                ('pm_mname', models.CharField(max_length=50, null=True)),
                ('pm_suffix', models.CharField(max_length=50, null=True)),
                ('pm_dob', models.DateField(null=True)),
                ('pm_sex', models.CharField(max_length=50, null=True)),
                ('pm_status', models.CharField(max_length=50, null=True)),
                ('pm_edAttainment', models.CharField(max_length=50, null=True)),
                ('pm_religion', models.CharField(max_length=50, null=True)),
                ('pm_contact', models.CharField(max_length=50, null=True)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_modification', to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'personal_modification',
            },
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('rp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rp_date_registered', models.DateField(default=datetime.date.today)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='healthProfiling.personal')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profiles', to='administration.staff')),
            ],
            options={
                'db_table': 'resident_profile',
            },
        ),
        migrations.CreateModel(
            name='NonCommunicableDisease',
            fields=[
                ('ncd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ncd_riskclass_age', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_comorbidities', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_lifestyle_risk', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_maintenance_status', models.CharField(blank=True, max_length=100, null=True)),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'non_communicable_disease',
            },
        ),
        migrations.CreateModel(
            name='MotherHealthInfo',
            fields=[
                ('mhi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mhi_healthRisk_class', models.CharField(blank=True, max_length=50, null=True)),
                ('mhi_immun_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mhi_famPlan_method', models.CharField(blank=True, max_length=100, null=True)),
                ('mhi_famPlan_source', models.CharField(blank=True, max_length=100, null=True)),
                ('mhi_lmp_date', models.DateField(blank=True, null=True)),
                ('fam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_health_infos', to='healthProfiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_health_infos', to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'mother_health_info',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile'),
        ),
        migrations.CreateModel(
            name='HistoricalTBsurveilance',
            fields=[
                ('tb_id', models.BigIntegerField(blank=True, db_index=True)),
                ('tb_meds_source', models.CharField(blank=True, max_length=100, null=True)),
                ('tb_days_taking_meds', models.IntegerField(blank=True, default=0, null=True)),
                ('tb_status', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('rp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.residentprofile')),
            ],
            options={
                'verbose_name': 'historical t bsurveilance',
                'verbose_name_plural': 'historical t bsurveilances',
                'db_table': 'tb_surveillance_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNonCommunicableDisease',
            fields=[
                ('ncd_id', models.BigIntegerField(blank=True, db_index=True)),
                ('ncd_riskclass_age', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_comorbidities', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_lifestyle_risk', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_maintenance_status', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('rp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.residentprofile')),
            ],
            options={
                'verbose_name': 'historical non communicable disease',
                'verbose_name_plural': 'historical non communicable diseases',
                'db_table': 'ncd_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HealthRelatedDetails',
            fields=[
                ('per_add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_add_bloodType', models.CharField(blank=True, max_length=5, null=True)),
                ('per_add_philhealth_id', models.CharField(blank=True, max_length=50, null=True)),
                ('per_add_covid_vax_status', models.CharField(blank=True, max_length=50, null=True)),
                ('per_add_rel_to_hh_head', models.CharField(blank=True, max_length=100, null=True)),
                ('rp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'per_additional_details',
            },
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('fc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fc_role', models.CharField(max_length=50)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='healthProfiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_compositions', to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'family_composition',
            },
        ),
        migrations.CreateModel(
            name='Dependents_Under_Five',
            fields=[
                ('duf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duf_fic', models.CharField(max_length=50)),
                ('duf_nutritional_status', models.CharField(max_length=50)),
                ('duf_exclusive_bf', models.CharField(max_length=50)),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.familycomposition')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'dep_under_five',
            },
        ),
        migrations.CreateModel(
            name='Dependents_Over_Five',
            fields=[
                ('dep_ov_five_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.familycomposition')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'dep_over_five',
            },
        ),
        migrations.CreateModel(
            name='RespondentsInfo',
            fields=[
                ('ri_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondents_info', to='healthProfiling.family')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents_info', to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'respondents_info',
            },
        ),
        migrations.CreateModel(
            name='SanitaryFacility',
            fields=[
                ('sf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sf_type', models.CharField(max_length=50)),
                ('sf_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('sf_toilet_type', models.CharField(max_length=50)),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household')),
            ],
            options={
                'db_table': 'sanitary_facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityDetails',
            fields=[
                ('fd_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fd_description', models.CharField(max_length=200)),
                ('sf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.sanitaryfacility')),
            ],
            options={
                'db_table': 'facility_details',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.sitio'),
        ),
        migrations.CreateModel(
            name='SolidWasteMgmt',
            fields=[
                ('swm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('swn_desposal_type', models.CharField(max_length=50)),
                ('swm_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household')),
            ],
            options={
                'db_table': 'solid_waste_mgmt',
            },
        ),
        migrations.CreateModel(
            name='SurveyIdentification',
            fields=[
                ('si_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('si_filled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('si_informant', models.CharField(max_length=100)),
                ('si_checked_by', models.CharField(max_length=100)),
                ('si_date', models.DateField()),
                ('si_signature', models.TextField()),
                ('si_created_at', models.DateTimeField(auto_now_add=True)),
                ('si_updated_at', models.DateTimeField(auto_now=True)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_identifications', to='healthProfiling.family')),
            ],
            options={
                'db_table': 'survey_identification',
            },
        ),
        migrations.CreateModel(
            name='TBsurveilance',
            fields=[
                ('tb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tb_meds_source', models.CharField(blank=True, max_length=100, null=True)),
                ('tb_days_taking_meds', models.IntegerField(blank=True, default=0, null=True)),
                ('tb_status', models.CharField(blank=True, max_length=100, null=True)),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'tb_surveillance_records',
            },
        ),
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('water_sup_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('water_sup_type', models.CharField(max_length=50)),
                ('water_conn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_sup_desc', models.TextField(max_length=1000)),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.household')),
            ],
            options={
                'db_table': 'water_supply',
            },
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_id'], name='resident_pr_rp_id_5d96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['per'], name='resident_pr_per_id_8d8581_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_date_registered'], name='resident_pr_rp_date_e601dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motherhealthinfo',
            unique_together={('rp', 'fam')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['sitio'], name='address_sitio_i_6e5289_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyidentification',
            index=models.Index(fields=['fam'], name='survey_iden_fam_id_4647aa_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyidentification',
            index=models.Index(fields=['si_date'], name='survey_iden_si_date_8cec3e_idx'),
        ),
    ]
