# Generated by Django 5.1.6 on 2025-04-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solid_Waste_Mgmt',
            fields=[
                ('swm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('swn_desposal_type', models.CharField(max_length=50)),
                ('swm_desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterModelTable(
            name='dependents_under_five',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthrelateddetails',
            table=None,
        ),
    ]
