# Generated by Django 5.1.6 on 2025-06-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Patient',
        #     fields=[
        #         ('pat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Solid_Waste_Mgmt',
        #     fields=[
        #         ('swm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
        #         ('swn_desposal_type', models.CharField(max_length=50)),
        #         ('swm_desc', models.TextField(max_length=1000)),
        #     ],
        # ),
        migrations.RemoveField(
            model_name='household',
            name='hh_barangay',
        ),
        migrations.RemoveField(
            model_name='household',
            name='hh_city',
        ),
        migrations.RemoveField(
            model_name='household',
            name='hh_province',
        ),
        migrations.RemoveField(
            model_name='household',
            name='hh_street',
        ),
        migrations.RemoveField(
            model_name='household',
            name='sitio',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='per_address',
        ),
        # migrations.AlterModelTable(
        #     name='dependents_under_five',
        #     table=None,
        # ),
        # migrations.AlterModelTable(
        #     name='healthrelateddetails',
        #     table=None,
        # ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_province', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_barangay', models.CharField(max_length=50)),
                ('add_street', models.CharField(max_length=50)),
                ('add_external_sitio', models.CharField(blank=True, max_length=50, null=True)),
                ('sitio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.sitio')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('pa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'personal_address',
            },
        ),
    ]

# Generated by Django 5.1.6 on 2025-04-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solid_Waste_Mgmt',
            fields=[
                ('swm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('swn_desposal_type', models.CharField(max_length=50)),
                ('swm_desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterModelTable(
            name='dependents_under_five',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthrelateddetails',
            table=None,
        ),
    ]
