# Generated by Django 5.2 on 2025-07-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrelateddetails',
            name='hrd_blood_type',
        ),
        migrations.AddField(
            model_name='healthrelateddetails',
            name='hrd_bloodType',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrelateddetails',
            name='hrd_covid_vax_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthrelateddetails',
            name='hrd_philhealth_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthrelateddetails',
            name='per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal'),
        ),
        migrations.AlterModelTable(
            name='healthrelateddetails',
            table='per_additional_details',
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('rf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rf_name', models.CharField(max_length=500)),
                ('rf_type', models.CharField(max_length=50)),
                ('rf_path', models.CharField(max_length=500)),
                ('rf_url', models.URLField()),
                ('rf_is_id', models.BooleanField(default=False)),
                ('rf_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rf_created_at', models.DateTimeField(auto_now_add=True)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='healthProfiling.requestregistration')),
            ],
            options={
                'db_table': 'request_file',
            },
        ),
        migrations.CreateModel(
            name='RespondentsInfo',
            fields=[
                ('ri_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents_info', to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'respondents_info',
            },
        ),
    ]
