# Generated by Django 5.1.7 on 2025-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrelateddetails',
            name='hrd_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        # migrations.AlterModelTable(
        #     name='dependents_under_five',
        #     table='dep_under_five',
        # ),
    ]
