# Generated by Django 5.2 on 2025-07-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0002_remove_healthrelateddetails_hrd_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrelateddetails',
            name='per',
        ),
        migrations.RemoveField(
            model_name='respondentsinfo',
            name='per',
        ),
        migrations.AddField(
            model_name='healthrelateddetails',
            name='rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='respondentsinfo',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respondents_info', to='healthProfiling.residentprofile'),
            preserve_default=False,
        ),
    ]
