# Generated by Django 5.1.6 on 2025-04-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0002_patient_solid_waste_mgmt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
