# Generated by Django 5.1.7 on 2025-06-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dependents_under_five',
            table='dep_under_five',
        ),
    ]
