# Generated by Django 5.2 on 2025-07-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0003_remove_healthrelateddetails_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependents_over_five',
            name='per',
        ),
        migrations.AddField(
            model_name='dependents_over_five',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MotherHealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_risk_class', models.CharField(blank=True, max_length=50, null=True)),
                ('immunization_status', models.CharField(blank=True, max_length=50, null=True)),
                ('family_planning_method', models.CharField(blank=True, max_length=100, null=True)),
                ('family_planning_source', models.CharField(blank=True, max_length=100, null=True)),
                ('family_composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_health_infos', to='healthProfiling.familycomposition')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_health_infos', to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'mother_health_info',
                'unique_together': {('rp', 'family_composition')},
            },
        ),
    ]
