# Generated by Django 5.1.6 on 2025-06-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0003_delete_patient'),
        ('healthProfiling', '0003_patient_solid_waste_mgmt_and_more'),
    ]

    operations = [
    ]
