# Generated by Django 5.1.6 on 2025-06-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0003_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='hh_barangay',
        ),
        migrations.RemoveField(
            model_name='household',
            name='hh_city',
        ),
        migrations.RemoveField(
            model_name='household',
            name='hh_province',
        ),
        migrations.RemoveField(
            model_name='household',
            name='hh_street',
        ),
        migrations.RemoveField(
            model_name='household',
            name='sitio',
        ),
    ]
