# Generated by Django 5.2 on 2025-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0004_remove_dependents_over_five_per_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherhealthinfo',
            old_name='family_planning_method',
            new_name='mhi_famPlan_method',
        ),
        migrations.RenameField(
            model_name='motherhealthinfo',
            old_name='family_planning_source',
            new_name='mhi_famPlan_source',
        ),
        migrations.RenameField(
            model_name='motherhealthinfo',
            old_name='health_risk_class',
            new_name='mhi_healthRisk_class',
        ),
        migrations.RenameField(
            model_name='motherhealthinfo',
            old_name='immunization_status',
            new_name='mhi_immun_status',
        ),
        migrations.RemoveField(
            model_name='motherhealthinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='motherhealthinfo',
            name='mhi_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
