# Generated by Django 5.2 on 2025-07-08 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0005_rename_family_planning_method_motherhealthinfo_mhi_famplan_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherhealthinfo',
            name='family_composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_health_infos', to='healthProfiling.familycomposition'),
        ),
    ]
