# Generated by Django 5.1.6 on 2025-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0005_merge_20250607_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='per_address',
        ),
    ]
