# Generated by Django 5.1.6 on 2025-06-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0006_patient_remove_personal_per_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_province', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_barangay', models.CharField(max_length=50)),
                ('add_street', models.CharField(max_length=50)),
                ('add_external_sitio', models.CharField(blank=True, max_length=50, null=True)),
                ('sitio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.sitio')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('pa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal')),
            ],
            options={
                'db_table': 'personal_address',
            },
        ),
    ]
