# Generated by Django 5.2 on 2025-07-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0006_alter_motherhealthinfo_family_composition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motherhealthinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='motherhealthinfo',
            name='family_composition',
        ),
    ]
