# Generated by Django 5.1.6 on 2025-06-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0007_address_household_add_personaladdress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='rp_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
