# Generated by Django 5.2 on 2025-07-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0007_alter_motherhealthinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherhealthinfo',
            name='fam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_health_infos', to='healthProfiling.family'),
        ),
        migrations.AlterUniqueTogether(
            name='motherhealthinfo',
            unique_together={('rp', 'fam')},
        ),
    ]
