# Generated by Django 5.2 on 2025-07-24 20:21

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_position_pos_category'),
        ('healthProfiling', '0008_motherhealthinfo_fam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonal',
            fields=[
                ('per_id', models.BigIntegerField(blank=True, db_index=True)),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_mname', models.CharField(max_length=100, null=True)),
                ('per_suffix', models.CharField(max_length=100, null=True)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_edAttainment', models.CharField(max_length=100, null=True)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical personal',
                'verbose_name_plural': 'historical personals',
                'db_table': 'personal_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('kyc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_document_front', models.TextField(blank=True, null=True)),
                ('id_has_face', models.BooleanField(default=False, null=True)),
                ('id_face_embedding', models.BinaryField(blank=True, null=True)),
                ('face_photo', models.TextField(blank=True, null=True)),
                ('document_info_match', models.BooleanField(default=False, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kyc_record',
            },
        ),
        migrations.CreateModel(
            name='PersonalAddressHistory',
            fields=[
                ('pah_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pah_date', models.DateTimeField(auto_now_add=True)),
                ('history_id', models.IntegerField()),
            ],
            options={
                'db_table': 'personal_address_history',
            },
        ),
        migrations.RemoveField(
            model_name='requestfile',
            name='req',
        ),
        migrations.RemoveField(
            model_name='requestregistration',
            name='per',
        ),
        migrations.AlterField(
            model_name='personal',
            name='per_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['per_lname', 'per_fname'], name='personal_per_lna_29932c_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['per_contact'], name='personal_per_con_396812_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_id'], name='resident_pr_rp_id_5d96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['per'], name='resident_pr_per_id_8d8581_idx'),
        ),
        migrations.AddIndex(
            model_name='residentprofile',
            index=models.Index(fields=['rp_date_registered'], name='resident_pr_rp_date_e601dd_idx'),
        ),
        migrations.AddField(
            model_name='historicalpersonal',
            name='history_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff'),
        ),
        migrations.AddField(
            model_name='personaladdresshistory',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.address'),
        ),
        migrations.AddField(
            model_name='personaladdresshistory',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.personal'),
        ),
        migrations.DeleteModel(
            name='RequestFile',
        ),
        migrations.DeleteModel(
            name='RequestRegistration',
        ),
    ]
