# Generated by Django 5.1.7 on 2025-03-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicineinventory_delete_medicinestocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='cat',
            new_name='cat_id',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='inv',
            new_name='inv_id',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='med',
            new_name='med_id',
        ),
    ]
