# Generated by Django 5.1.7 on 2025-03-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicineinventory_minv_dsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='minv_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
