# Generated by Django 5.1.7 on 2025-03-20 08:11

from django.db import migrations

def load_triggers(apps, schema_editor):
    with open("sql/triggers.sql", "r") as file:
        schema_editor.execute(file.read())
        
class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_inv_id_and_more'),
    ]

    operations = [
    ]
