# Generated by Django 5.1.7 on 2025-03-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_immunizationsupplies_vaccinecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationsupplies',
            name='vaccat_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccineinterval',
            name='vaccat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinecategory'),
        ),
    ]
