# Generated by Django 5.1.7 on 2025-03-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_antigentransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinestock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaccinestock',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='vaccinestock',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vaccinestock',
            name='inv_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='vac_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccinelist'),
        ),
    ]
