# Generated by Django 5.1.6 on 2025-12-15 07:10

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('maternal', '0001_initial'),
        ('medicineservices', '0001_initial'),
        ('patientrecords', '0001_initial'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHealth_History',
            fields=[
                ('chhist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tt_status', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('check-up', 'Check-up'), ('immunization', 'Immunization'), ('recorded', 'Recorded')], default='recorded', max_length=20)),
                ('assigned_doc', models.ForeignKey(blank=True, db_column='assigned_doc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_histories_assigned_doc', to='administration.staff')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_histories', to='administration.staff')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_histories_created_by', to='administration.staff')),
            ],
            options={
                'db_table': 'child_health_history',
            },
        ),
        migrations.CreateModel(
            name='ChildHealthImmunizationHistory',
            fields=[
                ('imt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hasExistingVaccination', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chhist', models.ForeignKey(db_column='chhist_id', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_tracking', to='childhealthservices.childhealth_history')),
                ('vachist', models.ForeignKey(db_column='vachist_id', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_tracking', to='vaccination.vaccinationhistory')),
            ],
            options={
                'db_table': 'child_health_immunization_history',
            },
        ),
        migrations.CreateModel(
            name='ChildHealthNotes',
            fields=[
                ('chnotes_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chn_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chhist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_health_notes', to='childhealthservices.childhealth_history')),
                ('followv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_notes', to='patientrecords.followupvisit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_notes', to='administration.staff')),
            ],
            options={
                'db_table': 'child_health_notes',
            },
        ),
        migrations.CreateModel(
            name='ChildHealthrecord',
            fields=[
                ('chrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ufc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('family_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_of_feeding', models.CharField(blank=True, max_length=100, null=True)),
                ('newborn_screening', models.DateField(blank=True, null=True)),
                ('landmarks', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_delivery_type', models.CharField(default='Home', max_length=30)),
                ('birth_order', models.IntegerField(default=0)),
                ('pod_location', models.CharField(blank=True, max_length=100, null=True)),
                ('nbscreening_result', models.CharField(blank=True, choices=[('normal', 'Normal'), ('referred', 'Referred'), ('done', 'Done'), ('with_results', 'With Results'), ('with_positive_results', 'With Positive Results')], max_length=100, null=True)),
                ('newbornInitiatedbf', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_health_records', to='patientrecords.patientrecord')),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_records', to='maternal.pregnancy')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_records', to='administration.staff')),
            ],
            options={
                'db_table': 'child_healthrecord',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='childhealth_history',
            name='chrec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_health_histories', to='childhealthservices.childhealthrecord'),
        ),
        migrations.CreateModel(
            name='ChildHealthSupplements',
            fields=[
                ('chsupplement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chhist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_health_supplements', to='childhealthservices.childhealth_history')),
                ('medreq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_supplements', to='medicineservices.medicinerequest')),
            ],
            options={
                'db_table': 'child_health_supplements',
            },
        ),
        migrations.CreateModel(
            name='ChildHealthSupplementsStatus',
            fields=[
                ('chssupplementstat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('birthwt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_type', models.CharField(choices=[('birthwt', 'Birth Weight'), ('anemic', 'Anemic')])),
                ('date_seen', models.CharField(blank=True, max_length=100, null=True)),
                ('date_given_iron', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chhist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements_statuses', to='childhealthservices.childhealth_history')),
            ],
            options={
                'db_table': 'child_health_supplements_status',
            },
        ),
        migrations.CreateModel(
            name='ChildHealthVitalSigns',
            fields=[
                ('chvital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_vital_signs', to='patientrecords.bodymeasurement')),
                ('chhist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_health_vital_signs', to='childhealthservices.childhealth_history')),
                ('find', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_vital_signs', to='patientrecords.finding')),
                ('vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_health_histories', to='patientrecords.vitalsigns')),
            ],
            options={
                'db_table': 'child_health_vital_signs',
            },
        ),
        migrations.CreateModel(
            name='ExclusiveBFCheck',
            fields=[
                ('ebf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ebf_date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_feeding', models.CharField(blank=True, max_length=100, null=True)),
                ('chhist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_bf_checks', to='childhealthservices.childhealth_history')),
            ],
            options={
                'db_table': 'exclusive_bf_check',
            },
        ),
        migrations.CreateModel(
            name='HistoricalChildHealthNotes',
            fields=[
                ('chnotes_id', models.BigIntegerField(blank=True, db_index=True)),
                ('chn_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chhist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='childhealthservices.childhealth_history')),
                ('followv', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patientrecords.followupvisit')),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administration.staff')),
                ('staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.staff')),
            ],
            options={
                'verbose_name': 'historical child health notes',
                'verbose_name_plural': 'historical child health notess',
                'db_table': 'child_health_notes_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
