# Generated by Django 5.1.6 on 2025-12-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('healthProfiling', '0001_initial'),
        ('maternal', '0001_initial'),
        ('medicineservices', '0001_initial'),
        ('patientrecords', '0001_initial'),
        ('servicescheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSlots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('am_max_slots', models.IntegerField(default=20)),
                ('pm_max_slots', models.IntegerField(default=20)),
                ('am_current_bookings', models.IntegerField(default=0)),
                ('pm_current_bookings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ss_id', models.ForeignKey(blank=True, db_column='ss_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicescheduler.servicescheduler')),
            ],
            options={
                'db_table': 'date_slots',
            },
        ),
        migrations.CreateModel(
            name='MedConsultAppointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('meridiem', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('rp', models.ForeignKey(db_column='rp_id', on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'medconsult_appointment',
            },
        ),
        migrations.CreateModel(
            name='MedicalConsultation_Record',
            fields=[
                ('medrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medrec_status', models.CharField(default='pending', max_length=100)),
                ('medrec_chief_complaint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_phrecord', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(blank=True, db_column='app_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalConsultation.medconsultappointment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record_assigned', to='administration.staff')),
                ('bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='patientrecords.bodymeasurement')),
                ('find', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='patientrecords.finding')),
                ('medreq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='medicineservices.medicinerequest')),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='patientrecords.patientrecord')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='administration.staff')),
                ('vital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='patientrecords.vitalsigns')),
            ],
            options={
                'db_table': 'medical_consultation_record',
            },
        ),
        migrations.CreateModel(
            name='PhilhealthDetails',
            fields=[
                ('phil_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iswith_atc', models.BooleanField(default=False)),
                ('dependent_or_member', models.CharField(blank=True, max_length=50, null=True)),
                ('ogtt_result', models.CharField(blank=True, max_length=100, null=True)),
                ('contraceptive_used', models.CharField(blank=True, max_length=100, null=True)),
                ('smk_sticks_per_day', models.IntegerField(blank=True, null=True)),
                ('smk_years', models.IntegerField(blank=True, null=True)),
                ('is_passive_smoker', models.BooleanField(default=False)),
                ('alcohol_bottles_per_day', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=100, null=True)),
                ('medrec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='philhealth_details', to='medicalConsultation.medicalconsultation_record')),
                ('obs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='philhealth_details', to='patientrecords.obstetrical_history')),
                ('tts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='philhealth_details', to='maternal.tt_status')),
            ],
            options={
                'db_table': 'philhealth_details',
            },
        ),
    ]
