# Generated by Django 5.1.6 on 2025-04-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0001_initial'),
        ('patientrecords', '0034_alter_vitalsigns_vital_rr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalconsultation_record',
            name='find',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultation_record', to='patientrecords.finding'),
        ),
    ]
