# Generated by Django 5.1.6 on 2025-04-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0002_alter_medicalconsultation_record_find'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalconsultation_record',
            options={'verbose_name': 'Medical Consultation Record', 'verbose_name_plural': 'Medical Consultation Records'},
        ),
        migrations.AlterModelTable(
            name='medicalconsultation_record',
            table='medical_consultation_record',
        ),
    ]
