# Generated by Django 5.1.6 on 2025-04-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0003_alter_medicalconsultation_record_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalconsultation_record',
            options={},
        ),
    ]
