# Generated by Django 5.1.6 on 2025-04-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0005_medicalconsultation_record_medrec_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalconsultation_record',
            name='medrec_status',
        ),
    ]
