# Generated by Django 5.1.6 on 2025-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0006_remove_medicalconsultation_record_medrec_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconsultation_record',
            name='medrec_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
