# Generated by Django 5.1.7 on 2025-03-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('transient', models.BooleanField()),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalbites.patient')),
            ],
            options={
                'db_table': 'referral',
            },
        ),
        migrations.CreateModel(
            name='BiteDetails',
            fields=[
                ('bite_id', models.AutoField(primary_key=True, serialize=False)),
                ('exposure_type', models.CharField(max_length=50)),
                ('exposure_site', models.CharField(default='Not specified', max_length=50)),
                ('biting_animal', models.CharField(max_length=50)),
                ('actions_taken', models.CharField(max_length=50)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalbites.referral')),
            ],
            options={
                'db_table': 'bite_detail',
            },
        ),
    ]
