# Generated by Django 5.1.7 on 2025-03-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transient', models.BooleanField()),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Animalbite_Patient',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalbites.patient')),
            ],
            options={
                'db_table': 'Bite_Referral',
            },
        ),
        migrations.CreateModel(
            name='BiteDetails',
            fields=[
                ('bite_id', models.AutoField(primary_key=True, serialize=False)),
                ('exposure_type', models.CharField(max_length=50)),
                ('biting_animal', models.CharField(max_length=50)),
                ('lab_exam', models.CharField(max_length=50, null=True)),
                ('actions_taken', models.CharField(max_length=50)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalbites.referral')),
            ],
            options={
                'db_table': 'Bite_Detail',
            },
        ),
    ]
