# Generated by Django 5.1.7 on 2025-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0006_acknowledgement_alter_physicalexamination_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknowledgement',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='guardianName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='selectedMethod',
            field=models.CharField(max_length=50),
        ),
    ]
