# Generated by Django 5.1.6 on 2025-03-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_province', models.CharField(max_length=100)),
                ('add_city', models.CharField(max_length=100)),
                ('add_barangay', models.CharField(max_length=100)),
                ('add_street', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_date_registered', models.DateTimeField()),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_lname', models.CharField(max_length=100)),
                ('mother_fname', models.CharField(max_length=100)),
                ('mother_suffix', models.CharField(max_length=100)),
                ('mother_mname', models.CharField(max_length=100)),
                ('mother_dob', models.DateField()),
                ('mother_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'father',
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_lname', models.CharField(max_length=100)),
                ('father_fname', models.CharField(max_length=100)),
                ('father_suffix', models.CharField(max_length=100)),
                ('father_mname', models.CharField(max_length=100)),
                ('father_dob', models.DateField()),
                ('father_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mother',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_lname', models.CharField(max_length=100)),
                ('per_fname', models.CharField(max_length=100)),
                ('per_suffix', models.CharField(max_length=100)),
                ('per_mname', models.CharField(max_length=100)),
                ('per_dob', models.DateField()),
                ('per_sex', models.CharField(max_length=100)),
                ('per_status', models.CharField(max_length=100)),
                ('per_pob', models.CharField(max_length=200)),
                ('per_citizenship', models.CharField(max_length=100)),
                ('per_religion', models.CharField(max_length=100)),
                ('per_contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_lname', models.CharField(max_length=100)),
                ('dep_fname', models.CharField(max_length=100)),
                ('dep_suffix', models.CharField(max_length=100)),
                ('dep_mname', models.CharField(max_length=100)),
                ('dep_dob', models.DateField()),
                ('dep_sex', models.CharField(max_length=100)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.family')),
            ],
            options={
                'db_table': 'dependent',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.father'),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_date_registered', models.DateTimeField()),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.mother'),
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_type', models.CharField(max_length=100)),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.family')),
                ('hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.household')),
            ],
            options={
                'db_table': 'ownership',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.family')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal')),
            ],
            options={
                'db_table': 'family_composition',
                'unique_together': {('fam', 'per')},
            },
        ),
    ]
