# Generated by Django 5.1.6 on 2025-03-13 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='per',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
            preserve_default=False,
        ),
    ]
