# Generated by Django 5.1.6 on 2025-03-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_household_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='fam_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='hh_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
