# Generated by Django 5.1.6 on 2025-03-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_alter_family_fam_id_alter_household_hh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='hh_date_registered',
            field=models.DateField(),
        ),
    ]
