# Generated by Django 5.1.6 on 2025-03-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_alter_household_hh_date_registered'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familycomposition',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dep_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dep_fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dep_lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dep_mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dep_sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='dep_suffix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_composition', to='profiling.personal'),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_bloodtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_ed_attainment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_philhealth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_religion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_suffix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='father_vacstatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household', to='profiling.personal'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_bloodtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_ed_attainment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_philhealth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_religion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_suffix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mother_vacstatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='per_mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='per_suffix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
