# Generated by Django 5.1.6 on 2025-03-14 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_alter_familycomposition_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='hh',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiling.household'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='sitio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
        ),
        migrations.AlterField(
            model_name='household',
            name='add',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiling.address'),
        ),
        migrations.AlterField(
            model_name='household',
            name='per',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
        ),
    ]
