# Generated by Django 5.1.6 on 2025-03-15 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_family_hh_alter_address_sitio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='hh',
        ),
        migrations.AddField(
            model_name='household',
            name='hh_existing_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='hh_nhts',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AlterField(
            model_name='household',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.address'),
        ),
        migrations.AlterField(
            model_name='household',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
        ),
        migrations.AlterModelTable(
            name='building',
            table=None,
        ),
    ]
