# Generated by Django 5.1.6 on 2025-03-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_alter_personal_per_id'),
    ]

    operations = [
    ]
