# Generated by Django 5.1.6 on 2025-03-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_remove_family_hh_household_hh_existing_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='add',
        ),
        migrations.AddField(
            model_name='household',
            name='hh_barangay',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='hh_city',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='hh_province',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='hh_street',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='sitio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
