# Generated by Django 5.1.6 on 2025-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_remove_household_add_household_hh_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='per_address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='per_edAttainment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
