# Generated by Django 5.1.6 on 2025-03-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0009_personal_per_address_personal_per_edattainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='fam_indigenous',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.father'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.mother'),
        ),
    ]
