# Generated by Django 5.1.6 on 2025-03-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0010_family_fam_indigenous_alter_family_father_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='father',
            name='father_bloodtype',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_contact',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_dob',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_ed_attainment',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_fname',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_lname',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_mname',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_philhealth',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_religion',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_status',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_suffix',
        ),
        migrations.RemoveField(
            model_name='father',
            name='father_vacstatus',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_bloodtype',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_contact',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_dob',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_ed_attainment',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_fname',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_lname',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_mname',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_philhealth',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_religion',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_status',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_suffix',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='mother_vacstatus',
        ),
        migrations.AddField(
            model_name='father',
            name='per',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='per',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
            preserve_default=False,
        ),
    ]
