# Generated by Django 5.1.6 on 2025-03-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0011_remove_father_father_bloodtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='dep_dob',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='dep_fname',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='dep_lname',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='dep_mname',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='dep_sex',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='dep_suffix',
        ),
        migrations.AddField(
            model_name='dependent',
            name='per',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='profiling.personal'),
            preserve_default=False,
        ),
    ]
