# Generated by Django 5.1.6 on 2025-03-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0012_remove_dependent_dep_dob_remove_dependent_dep_fname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
    ]
