# Generated by Django 5.1.7 on 2025-06-10 04:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAD_Budget_Year',
            fields=[
                ('gbudy_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbudy_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbudy_year', models.CharField(max_length=4, unique=True)),
                ('gbudy_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gbudy_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'gad_budget_year',
            },
        ),
        migrations.CreateModel(
            name='GAD_Budget_Tracker',
            fields=[
                ('gbud_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbud_remaining_bal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbud_date', models.DateField(default=datetime.date.today)),
                ('gbud_particulars', models.CharField(max_length=100, null=True)),
                ('gbud_type', models.CharField(max_length=100, null=True)),
                ('gbud_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbud_add_notes', models.CharField(max_length=200, null=True)),
                ('gbud_receipt', models.CharField(blank=True, default='')),
                ('gbudy_num', models.ForeignKey(db_column='gbudy_num', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gad.gad_budget_year')),
            ],
            options={
                'db_table': 'gad_budget_tracker',
            },
        ),
    ]
