# Generated by Django 5.2 on 2025-07-11 04:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAD_Budget_Year',
            fields=[
                ('gbudy_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbudy_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbudy_year', models.CharField(max_length=4, unique=True)),
                ('gbudy_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gbudy_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gbudy_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gad_budget_tracker',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('dev_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dev_date', models.DateField(default=datetime.date.today)),
                ('dev_client', models.CharField(max_length=200, null=True)),
                ('dev_issue', models.CharField(max_length=200, null=True)),
                ('dev_project', models.CharField(max_length=200, null=True)),
                ('dev_res_person', models.CharField(max_length=200, null=True)),
                ('dev_indicator', models.CharField(max_length=200, null=True)),
                ('dev_gad_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'gad_development_plan',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentBudget',
            fields=[
                ('gdb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gdb_name', models.CharField(max_length=200, null=True)),
                ('gdb_pax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdb_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dev', models.ForeignKey(blank=True, db_column='dev_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gad.developmentplan')),
            ],
            options={
                'db_table': 'gad_development_budget',
            },
        ),
        migrations.CreateModel(
            name='GAD_Budget_Tracker',
            fields=[
                ('gbud_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbud_datetime', models.DateTimeField(null=True)),
                ('gbud_type', models.CharField(max_length=100, null=True)),
                ('gbud_add_notes', models.CharField(max_length=500, null=True)),
                ('gbud_inc_particulars', models.CharField(max_length=200, null=True)),
                ('gbud_inc_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gbud_exp_particulars', models.CharField(max_length=200, null=True)),
                ('gbud_proposed_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('gbud_actual_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('gbud_remaining_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('gbud_reference_num', models.CharField(max_length=200, null=True)),
                ('gbud_is_archive', models.BooleanField(default=False)),
                ('gdb', models.ForeignKey(blank=True, db_column='gdb_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gad.developmentbudget')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('gbudy', models.ForeignKey(db_column='gbudy_num', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gad.gad_budget_year')),
            ],
            options={
                'db_table': 'gad_budget_record',
            },
        ),
        migrations.CreateModel(
            name='GAD_Budget_File',
            fields=[
                ('gbf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbf_name', models.CharField()),
                ('gbf_type', models.CharField(max_length=50)),
                ('gbf_path', models.CharField()),
                ('gbf_url', models.CharField()),
                ('gbud', models.ForeignKey(db_column='gbud_num', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gad.gad_budget_tracker')),
            ],
            options={
                'db_table': 'gad_budget_file',
            },
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('gpr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gpr_title', models.CharField(max_length=200)),
                ('gpr_background', models.TextField(blank=True, null=True)),
                ('gpr_date', models.CharField(default='July 11, 2025')),
                ('gpr_venue', models.CharField(blank=True, max_length=200)),
                ('gpr_monitoring', models.TextField(blank=True)),
                ('gpr_header_img', models.TextField(blank=True, null=True)),
                ('gpr_page_size', models.CharField(default='letter', max_length=20, null=True)),
                ('gpr_objectives', models.JSONField(default=list)),
                ('gpr_participants', models.JSONField(default=list)),
                ('gpr_budget_items', models.JSONField(default=list)),
                ('gpr_signatories', models.JSONField(default=list)),
                ('gpr_created', models.DateField(default=datetime.date.today)),
                ('gpr_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'project_proposal',
            },
        ),
        migrations.CreateModel(
            name='ProjectProposalLog',
            fields=[
                ('gprl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gprl_date_approved_rejected', models.DateTimeField(null=True)),
                ('gprl_reason', models.TextField(blank=True, null=True)),
                ('gprl_date_submitted', models.DateField(default=datetime.date.today)),
                ('gprl_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed')], default='Pending', max_length=20)),
                ('gpr', models.ForeignKey(db_column='gpr_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gad.projectproposal')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'project_proposal_log',
                'ordering': ['-gprl_date_approved_rejected'],
            },
        ),
        migrations.CreateModel(
            name='ProposalSuppDoc',
            fields=[
                ('psd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('psd_is_archive', models.BooleanField(default=False)),
                ('psd_name', models.CharField(null=True)),
                ('psd_type', models.CharField(max_length=50, null=True)),
                ('psd_path', models.CharField(null=True)),
                ('psd_url', models.CharField(null=True)),
                ('gpr', models.ForeignKey(db_column='gpr_id', on_delete=django.db.models.deletion.CASCADE, related_name='support_docs', to='gad.projectproposal')),
            ],
            options={
                'db_table': 'proposal_supp_doc',
            },
        ),
    ]
