# Generated by Django 5.1.7 on 2025-04-02 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAD_Budget_Tracker',
            fields=[
                ('gbud_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbud_year', models.CharField(max_length=4)),
                ('gbud_total_amt_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbud_remaining_bal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbud_date', models.DateField(default=datetime.date.today)),
                ('gbud_particulars', models.CharField(max_length=100, null=True)),
                ('gbud_type', models.CharField(max_length=100, null=True)),
                ('gbud_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gbud_add_notes', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'GAD_Budget_Tracker',
            },
        ),
    ]
