# Generated by Django 5.1.7 on 2025-07-08 05:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('file', '0001_initial'),
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentBudget',
            fields=[
                ('gdb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gdb_name', models.CharField(max_length=200, null=True)),
                ('gdb_pax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdb_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'gad_development_budget',
            },
        ),
        migrations.RenameField(
            model_name='gad_budget_tracker',
            old_name='gbudy_num',
            new_name='gbudy',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_amount',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_date',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_particulars',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_receipt',
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_actual_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_exp_particulars',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_inc_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_inc_particulars',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_proposed_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_reference_num',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='gad_budget_year',
            name='gbudy_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gad_budget_tracker',
            name='gbud_add_notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gad_budget_tracker',
            name='gbud_remaining_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='gad_budget_tracker',
            table='gad_budget_record',
        ),
        migrations.AlterModelTable(
            name='gad_budget_year',
            table='gad_budget_tracker',
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gdb',
            field=models.ForeignKey(blank=True, db_column='gdb_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gad.developmentbudget'),
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('dev_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dev_date', models.DateField(default=datetime.date.today)),
                ('dev_client', models.CharField(max_length=200, null=True)),
                ('dev_issue', models.CharField(max_length=200, null=True)),
                ('dev_project', models.CharField(max_length=200, null=True)),
                ('dev_res_person', models.CharField(max_length=200, null=True)),
                ('dev_indicator', models.CharField(max_length=200, null=True)),
                ('dev_gad_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'gad_development_plan',
            },
        ),
        migrations.AddField(
            model_name='developmentbudget',
            name='dev',
            field=models.ForeignKey(blank=True, db_column='dev_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gad.developmentplan'),
        ),
        migrations.CreateModel(
            name='GAD_Budget_File',
            fields=[
                ('gbf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gbf_name', models.CharField(max_length=255)),
                ('gbf_type', models.CharField(max_length=100)),
                ('gbf_path', models.CharField(max_length=500)),
                ('gbf_url', models.CharField(max_length=500)),
                ('gbud', models.ForeignKey(db_column='gbud_num', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gad.gad_budget_tracker')),
            ],
            options={
                'db_table': 'gad_budget_file',
            },
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('gpr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gpr_title', models.CharField(max_length=200)),
                ('gpr_background', models.TextField(blank=True, null=True)),
                ('gpr_date', models.CharField(default='July 08, 2025')),
                ('gpr_venue', models.CharField(blank=True, max_length=200)),
                ('gpr_monitoring', models.TextField(blank=True)),
                ('gpr_header_img', models.TextField(blank=True, null=True)),
                ('gpr_page_size', models.CharField(default='letter', max_length=20, null=True)),
                ('gpr_objectives', models.JSONField(default=list)),
                ('gpr_participants', models.JSONField(default=list)),
                ('gpr_budget_items', models.JSONField(default=list)),
                ('gpr_signatories', models.JSONField(default=list)),
                ('gpr_created', models.DateField(default=datetime.date.today)),
                ('gpr_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'project_proposal',
            },
        ),
        migrations.CreateModel(
            name='ProjectProposalLog',
            fields=[
                ('gprl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gprl_date_approved_rejected', models.DateTimeField(null=True)),
                ('gprl_reason', models.TextField(blank=True, null=True)),
                ('gprl_date_submitted', models.DateField(default=datetime.date.today)),
                ('gprl_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed')], default='Pending', max_length=20)),
                ('gpr', models.ForeignKey(db_column='gpr_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gad.projectproposal')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'project_proposal_log',
                'ordering': ['-gprl_date_approved_rejected'],
            },
        ),
        migrations.CreateModel(
            name='ProposalSuppDoc',
            fields=[
                ('psd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('psd_is_archive', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('gpr', models.ForeignKey(db_column='gpr_id', on_delete=django.db.models.deletion.CASCADE, related_name='support_docs', to='gad.projectproposal')),
            ],
            options={
                'db_table': 'proposal_supp_doc',
            },
        ),
    ]
