# Generated by Django 5.2 on 2025-04-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0001_initial'),
        ('treasurer', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gad_budget_tracker',
            options={'ordering': ['-gbud_date'], 'verbose_name': 'GAD Budget Entry'},
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_remaining_bal',
        ),
        migrations.AlterField(
            model_name='gad_budget_tracker',
            name='budget_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'dtl_budget_category': 'GAD Program'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gad_entries', to='treasurer.budget_plan_detail'),
        ),
        migrations.AlterField(
            model_name='gad_budget_tracker',
            name='gbud_particulars',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GAD_Budget_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gad_budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total GAD Budget')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('budget_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gad_budget_year', to='treasurer.budget_plan')),
            ],
            options={
                'verbose_name': 'GAD Budget Year',
                'db_table': 'gad_budget_year',
                'ordering': ['-budget_plan__plan_year'],
            },
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='budget_year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='gad.gad_budget_year'),
            preserve_default=False,
        ),
    ]
