# Generated by Django 5.2 on 2025-12-14 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentplan',
            options={'managed': False},
        ),
    ]
