# Generated by Django 5.2 on 2025-07-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='gbud',
            field=models.ForeignKey(blank=True, db_column='gbud_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gad.gad_budget_tracker'),
        ),
    ]
