# Generated by Django 5.1.7 on 2025-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gad_budget_tracker',
            name='gbud_receipt',
            field=models.CharField(blank=True, default=''),
        ),
    ]
