# Generated by Django 5.2 on 2025-12-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentplan',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
    ]
