# Generated by Django 5.1.7 on 2025-04-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_remaining_bal',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_total_amt_used',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_year',
        ),
    ]
