# Generated by Django 5.2 on 2025-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0002_projectproposal_gbud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='August 05, 2025'),
        ),
    ]
