# Generated by Django 4.2.20 on 2025-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0002_projectproposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='July 17, 2025'),
        ),
    ]
