# Generated by Django 5.1.7 on 2025-04-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0002_remove_gad_budget_tracker_gbud_remaining_bal_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gad_budget_tracker',
            table='gad_budget_tracker',
        ),
    ]
