# Generated by Django 5.2 on 2025-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0003_alter_projectproposal_gpr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposallog',
            name='gprl_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed'), ('Amend', 'Amend'), ('Resubmitted', 'Resubmitted')], default='Pending', max_length=20),
        ),
    ]
