# Generated by Django 5.2 on 2025-08-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0004_alter_projectproposallog_gprl_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_proposed_budget',
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_exp_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gpr',
            field=models.ForeignKey(db_column='gpr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='gad.projectproposal'),
        ),
        migrations.AlterField(
            model_name='gad_budget_tracker',
            name='gbud_exp_particulars',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='August 06, 2025'),
        ),
    ]
