# Generated by Django 5.2 on 2025-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0005_remove_gad_budget_tracker_gbud_proposed_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gdb',
        ),
        migrations.RemoveField(
            model_name='developmentplan',
            name='staff',
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='August 07, 2025'),
        ),
        migrations.DeleteModel(
            name='DevelopmentBudget',
        ),
        migrations.DeleteModel(
            name='DevelopmentPlan',
        ),
    ]
