# Generated by Django 5.2 on 2025-08-08 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0006_remove_gad_budget_tracker_gdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gad_budget_tracker',
            name='gbud_proposed_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='August 08, 2025'),
        ),
        migrations.CreateModel(
            name='GADBudgetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbudl_amount_returned', models.FloatField(default=0, null=True)),
                ('gbudl_created_at', models.DateTimeField(auto_now_add=True)),
                ('gbudl_budget_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gad.gad_budget_tracker')),
            ],
            options={
                'db_table': 'gad_budget_log',
            },
        ),
    ]
