# Generated by Django 5.2 on 2025-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0007_gad_budget_tracker_gbud_proposed_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadbudgetlog',
            name='id',
        ),
        migrations.AddField(
            model_name='gadbudgetlog',
            name='gbudl_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gadbudgetlog',
            name='gbudl_prev_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='August 11, 2025'),
        ),
    ]
