# Generated by Django 5.2 on 2025-08-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad', '0008_remove_gadbudgetlog_id_gadbudgetlog_gbudl_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_inc_amt',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_inc_particulars',
        ),
        migrations.RemoveField(
            model_name='gad_budget_tracker',
            name='gbud_type',
        ),
        migrations.RemoveField(
            model_name='gad_budget_year',
            name='gbudy_income',
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='gpr_date',
            field=models.CharField(default='August 23, 2025'),
        ),
    ]
