# Generated by Django 5.2 on 2025-06-22 02:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('administration', '0006_alter_position_pos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temp_header', models.CharField(max_length=200)),
                ('temp_below_headerContent', models.TextField(blank=True, null=True)),
                ('temp_title', models.CharField(max_length=200)),
                ('temp_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_w_sign', models.BooleanField(default=False)),
                ('temp_w_seal', models.BooleanField(default=False)),
                ('temp_w_summon', models.BooleanField(default=False)),
                ('temp_paperSize', models.CharField(max_length=100)),
                ('temp_margin', models.CharField(max_length=100)),
                ('temp_filename', models.CharField(max_length=100)),
                ('temp_body', models.TextField(blank=True, null=True)),
                ('temp_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='CouncilScheduling',
            fields=[
                ('ce_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ce_title', models.CharField(max_length=100)),
                ('ce_place', models.CharField(max_length=100)),
                ('ce_date', models.DateField(default=datetime.date.today)),
                ('ce_time', models.TimeField()),
                ('ce_type', models.CharField(max_length=100)),
                ('ce_description', models.CharField(max_length=500)),
                ('ce_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'council_event',
            },
        ),
        migrations.CreateModel(
            name='CouncilAttendees',
            fields=[
                ('atn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atn_name', models.CharField(default='', max_length=200)),
                ('atn_designation', models.CharField(default='', max_length=200)),
                ('atn_present_or_absent', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('ce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.councilscheduling')),
            ],
            options={
                'db_table': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='CouncilAttendance',
            fields=[
                ('att_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('att_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('ce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.councilscheduling')),
            ],
            options={
                'db_table': 'attendance_sheet',
            },
        ),
        migrations.CreateModel(
            name='MinutesOfMeeting',
            fields=[
                ('mom_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('mom_date', models.DateField(default=datetime.date.today)),
                ('mom_title', models.TextField()),
                ('mom_agenda', models.TextField()),
                ('mom_is_archive', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
            ],
            options={
                'db_table': 'minutes_of_meeting',
            },
        ),
        migrations.CreateModel(
            name='MOMAreaOfFocus',
            fields=[
                ('mof_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mof_area', models.CharField()),
                ('mom', models.ForeignKey(blank=True, db_column='mom_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.minutesofmeeting')),
            ],
            options={
                'db_table': 'mom_area_of_focus',
            },
        ),
    ]
