# Generated by Django 5.2 on 2025-05-27 13:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilScheduling',
            fields=[
                ('ce_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ce_title', models.CharField(max_length=100)),
                ('ce_place', models.CharField(max_length=100)),
                ('ce_date', models.DateField(default=datetime.date.today)),
                ('ce_time', models.TimeField()),
                ('ce_type', models.CharField(max_length=100)),
                ('ce_description', models.CharField(max_length=100)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'council_event',
            },
        ),
        migrations.CreateModel(
            name='CouncilAttendees',
            fields=[
                ('atn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atn_present_or_absent', models.CharField(max_length=100)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
                ('ce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.councilscheduling')),
            ],
            options={
                'db_table': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='CouncilAttendance',
            fields=[
                ('att_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
                ('ce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.councilscheduling')),
            ],
            options={
                'db_table': 'attendance_sheet',
            },
        ),
    ]
