# Generated by Django 5.2 on 2025-12-16 04:31

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('gad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('ord_num', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ord_title', models.CharField(max_length=255)),
                ('ord_date_created', models.DateField()),
                ('ord_category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ord_details', models.TextField()),
                ('ord_year', models.IntegerField()),
                ('ord_is_archive', models.BooleanField(default=False)),
                ('ord_parent', models.CharField(blank=True, help_text='ord_num of the parent ordinance (if this is an amendment)', max_length=50, null=True)),
                ('ord_is_ammend', models.BooleanField(default=False, help_text='Whether this ordinance is an amendment to another')),
                ('ord_ammend_ver', models.IntegerField(blank=True, help_text='Version number of the amendment', null=True)),
                ('ord_repealed', models.BooleanField(default=False, help_text='Whether this ordinance is repealed')),
            ],
            options={
                'db_table': 'ordinance',
                'ordering': ['-ord_date_created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdinanceFile',
            fields=[
                ('of_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('of_name', models.CharField(max_length=255)),
                ('of_type', models.CharField(blank=True, max_length=100, null=True)),
                ('of_path', models.CharField(blank=True, max_length=500, null=True)),
                ('of_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ordinance_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MOMFile',
            fields=[
                ('momf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('momf_name', models.CharField(max_length=255)),
                ('momf_type', models.CharField(max_length=100)),
                ('momf_path', models.CharField(max_length=500)),
                ('momf_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'mom_file',
            },
        ),
        migrations.CreateModel(
            name='CouncilScheduling',
            fields=[
                ('ce_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ce_title', models.CharField(max_length=100)),
                ('ce_place', models.CharField(max_length=100)),
                ('ce_date', models.DateField(default=datetime.date.today)),
                ('ce_time', models.TimeField()),
                ('ce_description', models.CharField(max_length=500)),
                ('ce_rows', models.IntegerField(null=True)),
                ('ce_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'council_event',
            },
        ),
        migrations.CreateModel(
            name='CouncilAttendance',
            fields=[
                ('att_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('att_is_archive', models.BooleanField(default=False)),
                ('att_file_name', models.CharField(max_length=255, null=True)),
                ('att_file_path', models.CharField(max_length=512, null=True)),
                ('att_file_url', models.URLField(max_length=1024, null=True)),
                ('att_file_type', models.CharField(max_length=100, null=True)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('ce', models.ForeignKey(db_column='ce_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sheets', to='council.councilscheduling')),
            ],
            options={
                'db_table': 'attendance_sheet',
            },
        ),
        migrations.CreateModel(
            name='MinutesOfMeeting',
            fields=[
                ('mom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mom_date', models.DateField(default=datetime.date.today)),
                ('mom_title', models.TextField()),
                ('mom_agenda', models.TextField()),
                ('mom_area_of_focus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('mom_is_archive', models.BooleanField(default=False)),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('momf_id', models.ForeignKey(blank=True, db_column='momf_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.momfile')),
            ],
            options={
                'db_table': 'minutes_of_meeting',
            },
        ),
        migrations.CreateModel(
            name='MOMSuppDoc',
            fields=[
                ('momsp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('momsp_name', models.CharField(max_length=255)),
                ('momsp_type', models.CharField(max_length=100)),
                ('momsp_path', models.CharField(max_length=500)),
                ('momsp_url', models.CharField(max_length=500)),
                ('mom_id', models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='council.minutesofmeeting')),
            ],
            options={
                'db_table': 'mom_supporting_document',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('res_num', models.CharField(primary_key=True, serialize=False)),
                ('res_title', models.CharField(max_length=500)),
                ('res_date_approved', models.DateField(default=datetime.date.today)),
                ('res_area_of_focus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('res_is_archive', models.BooleanField(default=False)),
                ('gpr_id', models.ForeignKey(blank=True, db_column='gpr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gad.projectproposal')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'resolution',
            },
        ),
        migrations.CreateModel(
            name='ResolutionFile',
            fields=[
                ('rf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rf_name', models.CharField(max_length=500)),
                ('rf_type', models.CharField(max_length=500)),
                ('rf_path', models.CharField(max_length=500)),
                ('rf_url', models.CharField(max_length=500)),
                ('res_num', models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_files', to='council.resolution')),
            ],
            options={
                'db_table': 'resolution_file',
            },
        ),
        migrations.CreateModel(
            name='ResolutionSupDocs',
            fields=[
                ('rsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rsd_name', models.CharField(max_length=500)),
                ('rsd_type', models.CharField(max_length=500)),
                ('rsd_path', models.CharField(max_length=500)),
                ('rsd_url', models.CharField(max_length=500)),
                ('res_num', models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_supp', to='council.resolution')),
            ],
            options={
                'db_table': 'resolution_supp_doc',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temp_contact_num', models.CharField(max_length=200)),
                ('temp_email', models.CharField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('tf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tf_name', models.CharField(max_length=500)),
                ('tf_type', models.CharField(max_length=500)),
                ('tf_path', models.CharField(max_length=500)),
                ('tf_url', models.CharField(max_length=500)),
                ('tf_logoType', models.CharField(max_length=500)),
                ('temp_id', models.ForeignKey(blank=True, db_column='temp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_files', to='council.template')),
            ],
            options={
                'db_table': 'template_file',
            },
        ),
    ]
