# Generated by Django 5.2 on 2025-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='councilattendance',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='councilattendees',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='councilscheduling',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
