# Generated by Django 5.1.7 on 2025-06-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('council', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temp_header', models.CharField(max_length=200)),
                ('temp_below_headerContent', models.TextField(blank=True, null=True)),
                ('temp_title', models.CharField(max_length=200)),
                ('temp_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_w_sign', models.BooleanField(default=False)),
                ('temp_w_seal', models.BooleanField(default=False)),
                ('temp_w_summon', models.BooleanField(default=False)),
                ('temp_paperSize', models.CharField(max_length=100)),
                ('temp_margin', models.CharField(max_length=100)),
                ('temp_filename', models.CharField(max_length=100)),
                ('temp_body', models.TextField(blank=True, null=True)),
                ('temp_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.RemoveField(
            model_name='councilattendance',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='councilattendees',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='councilscheduling',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='councilattendance',
            name='att_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='councilattendance',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file'),
        ),
        migrations.AddField(
            model_name='councilattendance',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='councilattendees',
            name='atn_designation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='councilattendees',
            name='atn_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='councilattendees',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='councilscheduling',
            name='ce_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='councilscheduling',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='councilscheduling',
            name='ce_description',
            field=models.CharField(max_length=500),
        ),
    ]
