# Generated by Django 5.2 on 2025-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilattendance',
            name='att_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='councilattendance',
            name='att_file_path',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='councilattendance',
            name='att_file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='councilattendance',
            name='att_file_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
