# Generated by Django 5.1.7 on 2025-06-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutesofmeeting',
            old_name='mom_num',
            new_name='mom_id',
        ),
        migrations.RemoveField(
            model_name='minutesofmeeting',
            name='file',
        ),
        migrations.RemoveField(
            model_name='momareaoffocus',
            name='mom',
        ),
        migrations.AddField(
            model_name='momareaoffocus',
            name='mom_id',
            field=models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.minutesofmeeting'),
        ),
        migrations.CreateModel(
            name='MOMFile',
            fields=[
                ('momf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('momf_name', models.CharField(max_length=255)),
                ('momf_type', models.CharField(max_length=100)),
                ('momf_path', models.CharField(max_length=500)),
                ('momf_url', models.CharField(max_length=500)),
                ('mom_id', models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.minutesofmeeting')),
            ],
            options={
                'db_table': 'mom_file',
            },
        ),
        migrations.CreateModel(
            name='MOMSuppDoc',
            fields=[
                ('momsp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('momsp_is_archive', models.BooleanField(default=False)),
                ('mom_id', models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.minutesofmeeting')),
            ],
            options={
                'db_table': 'mom_supporting_document',
            },
        ),
    ]
