# Generated by Django 5.1.7 on 2025-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_rename_staff_id_councilattendance_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temp_header', models.CharField(max_length=200)),
                ('temp_below_headerContent', models.CharField(max_length=999)),
                ('temp_title', models.CharField(max_length=200)),
                ('temp_subtitle', models.CharField(max_length=200)),
                ('temp_w_sign', models.BooleanField(default=False)),
                ('temp_w_seal', models.BooleanField(default=False)),
                ('temp_w_summon', models.BooleanField(default=False)),
                ('temp_paperSize', models.CharField(max_length=100)),
                ('temp_margin', models.CharField(max_length=100)),
                ('temp_filename', models.CharField(max_length=100)),
                ('temp_body', models.CharField(max_length=999)),
            ],
            options={
                'db_table': 'template',
            },
        ),
    ]
