# Generated by Django 5.1.7 on 2025-06-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='temp_subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
