# Generated by Django 5.1.7 on 2025-06-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_create_mom_suppdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='momsuppdoc',
            name='momsp_name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='momsuppdoc',
            name='momsp_path',
            field=models.CharField(default='/path/to/file', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='momsuppdoc',
            name='momsp_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='momsuppdoc',
            name='momsp_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='momareaoffocus',
            name='mom_id',
            field=models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='council.minutesofmeeting'),
        ),
        migrations.AlterField(
            model_name='momfile',
            name='mom_id',
            field=models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='council.minutesofmeeting'),
        ),
        migrations.AlterField(
            model_name='momsuppdoc',
            name='mom_id',
            field=models.ForeignKey(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='council.minutesofmeeting'),
        ),
    ]
