# Generated by Django 5.1.7 on 2025-06-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_resolution_resolutionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionfile',
            name='res_num',
            field=models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='council.resolution'),
        ),
    ]
