# Generated by Django 5.1.7 on 2025-06-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_alter_resolutionfile_res_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionfile',
            name='res_num',
            field=models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_files', to='council.resolution'),
        ),
    ]
