# Generated by Django 5.2 on 2025-07-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_councilattendance_att_file_name_and_more'),
        ('council', '0004_momsuppdoc_momsp_name_momsuppdoc_momsp_path_and_more'),
    ]

    operations = [
    ]
