# Generated by Django 5.1.7 on 2025-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_alter_template_temp_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='temp_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
