# Generated by Django 5.2 on 2025-06-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('council', '0005_template_temp_is_archive'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilattendance',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file'),
        ),
        migrations.AddField(
            model_name='councilattendees',
            name='atn_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='councilscheduling',
            name='ce_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='councilattendance',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='councilattendees',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='councilscheduling',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
    ]
