# Generated by Django 5.1.7 on 2025-07-15 02:20

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('council', '0005_merge_20250708_1422'),
        ('treasurer', '0008_alter_budgetplan_file_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='pr_id',
            field=models.ForeignKey(blank=True, db_column='pr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='treasurer.purpose_and_rates'),
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('res_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('res_title', models.CharField(max_length=500)),
                ('res_date_approved', models.DateField(default=datetime.date.today)),
                ('res_area_of_focus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('res_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'resolution',
            },
        ),
        migrations.CreateModel(
            name='ResolutionFile',
            fields=[
                ('rf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rf_name', models.CharField(max_length=500)),
                ('rf_type', models.CharField(max_length=500)),
                ('rf_path', models.CharField(max_length=500)),
                ('rf_url', models.CharField(max_length=500)),
                ('res_num', models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_files', to='council.resolution')),
            ],
            options={
                'db_table': 'resolution_file',
            },
        ),
        migrations.CreateModel(
            name='ResolutionSupDocs',
            fields=[
                ('rsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rsfd_name', models.CharField(max_length=500)),
                ('rsfd_type', models.CharField(max_length=500)),
                ('rsd_path', models.CharField(max_length=500)),
                ('rsd_url', models.CharField(max_length=500)),
                ('res_num', models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_supp', to='council.resolution')),
            ],
            options={
                'db_table': 'resolution_supp_doc',
            },
        ),
    ]
