# Generated by Django 5.1.7 on 2025-06-17 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0005_alter_resolutionfile_res_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionSupDocs',
            fields=[
                ('rsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rsfd_name', models.CharField(max_length=500)),
                ('rsfd_type', models.CharField(max_length=500)),
                ('rsd_path', models.CharField(max_length=500)),
                ('rsd_url', models.CharField(max_length=500)),
                ('res_num', models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_supp_doc', to='council.resolution')),
            ],
            options={
                'db_table': 'resolution_supp_doc',
            },
        ),
    ]
