# Generated by Django 5.1.7 on 2025-07-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_template_pr_id_resolution_resolutionfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolutionsupdocs',
            old_name='rsfd_name',
            new_name='rsd_name',
        ),
        migrations.RenameField(
            model_name='resolutionsupdocs',
            old_name='rsfd_type',
            new_name='rsd_type',
        ),
    ]
