# Generated by Django 5.1.7 on 2025-06-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_resolutionsupdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionsupdocs',
            name='res_num',
            field=models.ForeignKey(blank=True, db_column='res_num', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_supp', to='council.resolution'),
        ),
    ]
