# Generated by Django 5.2 on 2025-06-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_councilattendance_file_councilattendees_atn_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilattendees',
            name='atn_designation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
