# Generated by Django 5.1.7 on 2025-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_councilattendees_atn_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='temp_below_headerContent',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='temp_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
