# Generated by Django 5.1.7 on 2025-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_councilattendees_atn_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilscheduling',
            name='ce_description',
            field=models.CharField(max_length=500),
        ),
    ]
