# Generated by Django 5.2 on 2025-08-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_rename_rsfd_name_resolutionsupdocs_rsd_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momsuppdoc',
            name='momsp_is_archive',
        ),
        migrations.AlterField(
            model_name='momfile',
            name='mom_id',
            field=models.OneToOneField(blank=True, db_column='mom_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='council.minutesofmeeting'),
        ),
    ]
