# Generated by Django 5.2 on 2025-06-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_alter_councilscheduling_ce_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilattendance',
            name='att_is_archive',
            field=models.BooleanField(default=False),
        ),
        # migrations.AlterField(
        #     model_name='template',
        #     name='temp_below_headerContent',
        #     field=models.CharField(blank=True, max_length=999, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='template',
        #     name='temp_subtitle',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
    ]
