# Generated by Django 5.1.7 on 2025-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_alter_template_temp_below_headercontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='temp_below_headerContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='temp_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
