# Generated by Django 5.2 on 2025-08-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_remove_momsuppdoc_momsp_is_archive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='temp_header',
            new_name='temp_contact_num',
        ),
        migrations.RemoveField(
            model_name='template',
            name='pr_id',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_below_headerContent',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_body',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_filename',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_is_archive',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_margin',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_paperSize',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_subtitle',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_title',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_w_seal',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_w_sign',
        ),
        migrations.RemoveField(
            model_name='template',
            name='temp_w_summon',
        ),
        migrations.AddField(
            model_name='template',
            name='temp_email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('tf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tf_name', models.CharField(max_length=500)),
                ('tf_type', models.CharField(max_length=500)),
                ('tf_path', models.CharField(max_length=500)),
                ('tf_url', models.CharField(max_length=500)),
                ('temp_id', models.ForeignKey(blank=True, db_column='temp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_files', to='council.template')),
            ],
            options={
                'db_table': 'template_file',
            },
        ),
    ]
