# Generated by Django 5.2 on 2025-08-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0010_template_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='staff',
        ),
    ]
