# Generated by Django 5.2 on 2025-08-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('council', '0011_remove_template_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='staff_id',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
    ]
