# Generated by Django 5.2 on 2025-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0012_template_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='tf_logoType',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
