# Generated by Django 5.2 on 2025-06-25 10:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feat_name', models.CharField(max_length=50)),
                ('feat_category', models.CharField(max_length=50)),
                ('feat_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos_title', models.CharField(max_length=100)),
                ('pos_max', models.IntegerField(default=1)),
                ('pos_category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assi_date', models.DateField(default=datetime.date.today)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.feature')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.position')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('assi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='administration.assignment')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_assign_date', models.DateField(default=datetime.date.today)),
                ('staff_type', models.CharField(default='Barangay Staff', max_length=20)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='administration.staff')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='administration.position')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='administration.staff'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='administration.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('feat', 'pos')},
        ),
    ]
