# Generated by Django 5.1.7 on 2025-04-10 05:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feat_name', models.CharField(max_length=50)),
                ('feat_category', models.CharField(max_length=50)),
                ('feat_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos_title', models.CharField(max_length=100)),
                ('pos_max', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assi_date', models.DateField(default=datetime.date.today)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.feature')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.position')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('assi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='administration.assignment')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_assign_date', models.DateField(default=datetime.date.today)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='administration.staff')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='administration.position')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
