# Generated by Django 5.2 on 2025-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pos_category',
        ),
        migrations.AddField(
            model_name='position',
            name='pos_group',
            field=models.CharField(default='Non-Grouped', max_length=100, null=True),
        ),
    ]
