# Generated by Django 5.1.7 on 2025-04-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('profiling', '0001_initial'),
    ]

    operations = [

    ]
