# Generated by Django 5.2 on 2025-12-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('profiling', '0002_requestregistrationcomposition_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='profiling.residentprofile'),
            preserve_default=False,
        ),
    ]
