# Generated by Django 5.2 on 2025-04-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='profiling.residentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('feat', 'pos')},
        ),
    ]
