# Generated by Django 5.1.6 on 2025-03-31 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='profiling.residentprofile'),
            preserve_default=False,
        ),
    ]
