# Generated by Django 5.2 on 2025-06-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_position_pos_category_position_pos_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pos_is_predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_group',
            field=models.CharField(default='NON-GROUPED', max_length=100, null=True),
        ),
    ]
