# Generated by Django 5.2 on 2025-07-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_position_pos_category_position_pos_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_group',
            field=models.CharField(default='NON-GROUPED', max_length=100, null=True),
        ),
    ]
