# Generated by Django 5.1.6 on 2025-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pos_max',
            field=models.IntegerField(default=1),
        ),
    ]
