# Generated by Django 5.2 on 2025-04-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
