# Generated by Django 5.2 on 2025-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_assign_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
