# Generated by Django 5.1.6 on 2025-04-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_position_pos_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(default='00001250331', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(default='00001250331', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='administration.position'),
        ),
    ]
