# Generated by Django 5.1.6 on 2025-03-17 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_staff_id_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_assign_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assi_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
