# Generated by Django 5.2 on 2025-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
