# Generated by Django 5.2 on 2025-06-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_position_pos_is_predefined_alter_position_pos_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pos_category',
            field=models.CharField(default='BARANGAY POSITION', max_length=100, null=True),
        ),
    ]
