# Generated by Django 5.2 on 2025-07-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('administration', '0003_alter_position_pos_group'),
    ]

    operations = [
    ]
