# Generated by Django 5.1.7 on 2025-06-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_position_pos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
