# Generated by Django 5.1.6 on 2025-04-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_assignment_staff_position_staff_alter_staff_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feat_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
