# Generated by Django 4.2.20 on 2025-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_position_pos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
