# Generated by Django 5.2 on 2025-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_position_pos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
