# Generated by Django 5.2 on 2025-06-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_position_pos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(default='Barangay Staff', max_length=20),
        ),
    ]
