# Generated by Django 5.2 on 2025-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_staff_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pos_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
