 export const initialFormData1 = {
    honorariaOfficials: "",
    cashOfficials: "",
    midBonusOfficials: "",
    endBonusOfficials: "",
    honorariaTanods: "",
    honorariaLupon: "",
    honorariaBarangay: "",
    prodEnhancement: "",
    leaveCredits: "",
    memDues: "",
    miscExpense: "",
    cleanAndGreen: "",
    streetLighting: "",
    rehabMultPurpose: "",
    skFund: "",
    qrfFund: "",
    disasterTraining: "",
    disasterSupplies: "",
    gadProg: "",
    seniorProg: "",
    disasterProg: "",
};

export const initialFormData2 = {
    travelingExpenses: "",
    trainingExpenses: "",
    officeExpenses: "",
    accountableExpenses: "",
    medExpenses: "",
    waterExpenses: "",
    electricityExpenses: "",
    telephoneExpenses: "",
    officeMaintenance: "",
    vehicleMaintenance: "",
    fidelityBond: "",
    insuranceExpense: "",
    gadProg: "",
    seniorProg: "",
    juvJustice: "",
    badacProg: "",
    nutritionProg: "",
    aidsProg: "",
    assemblyExpenses: "",
    capitalOutlays: "",
};


export type BudgetPlanPage1FormData = typeof initialFormData1;
export type BudgetPlanPage2FormData = typeof initialFormData2;
