# Generated by Django 4.2.20 on 2025-06-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('acsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acsd_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accused',
            },
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('cpnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpnt_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'complainant',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_incident_type', models.CharField(max_length=100)),
                ('comp_datetime', models.CharField(max_length=100)),
                ('comp_allegation', models.TextField()),
                ('comp_created_at', models.DateTimeField(auto_now_add=True)),
                ('comp_is_archive', models.BooleanField(default=False)),
                ('acsd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accused', to='complaint.accused')),
                ('cpnt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Complainant', to='complaint.complainant')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Complaint_File',
            fields=[
                ('cf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='complaint.complaint')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='file.file')),
            ],
            options={
                'db_table': 'complaint_file',
            },
        ),
    ]
