# Generated by Django 5.2 on 2025-12-13 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('profiling', '0002_requestregistrationcomposition_acc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('acsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acsd_name', models.CharField(max_length=100)),
                ('acsd_age', models.CharField(max_length=2)),
                ('acsd_gender', models.CharField(max_length=20)),
                ('acsd_description', models.TextField()),
                ('acsd_address', models.CharField(blank=True, max_length=255, null=True)),
                ('rp_id', models.ForeignKey(blank=True, db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'accused',
            },
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('cpnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpnt_name', models.CharField(max_length=100)),
                ('cpnt_gender', models.CharField(max_length=20)),
                ('cpnt_age', models.CharField(max_length=2)),
                ('cpnt_number', models.CharField(max_length=11)),
                ('cpnt_relation_to_respondent', models.CharField(max_length=20)),
                ('cpnt_address', models.CharField(blank=True, max_length=255, null=True)),
                ('rp_id', models.ForeignKey(blank=True, db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'complainant',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comp_location', models.CharField(max_length=255)),
                ('comp_incident_type', models.CharField(max_length=100)),
                ('comp_datetime', models.CharField(max_length=100)),
                ('comp_allegation', models.TextField()),
                ('comp_created_at', models.DateTimeField(auto_now_add=True)),
                ('comp_rejection_reason', models.TextField(blank=True, null=True)),
                ('comp_cancel_reason', models.TextField(blank=True, null=True)),
                ('comp_status', models.CharField(default='Pending', max_length=20)),
                ('comp_updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='administration.staff')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='ComplaintAccused',
            fields=[
                ('ca_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.accused')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
            ],
            options={
                'db_table': 'complaint_accused',
                'unique_together': {('comp', 'acsd')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='accused',
            field=models.ManyToManyField(related_name='complaints', through='complaint.ComplaintAccused', to='complaint.accused'),
        ),
        migrations.CreateModel(
            name='ComplaintComplainant',
            fields=[
                ('cc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
                ('cpnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complainant')),
            ],
            options={
                'db_table': 'complaint_complainant',
                'unique_together': {('comp', 'cpnt')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant',
            field=models.ManyToManyField(related_name='complaints', through='complaint.ComplaintComplainant', to='complaint.complainant'),
        ),
        migrations.CreateModel(
            name='Complaint_File',
            fields=[
                ('comp_file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_file_name', models.CharField(max_length=100)),
                ('comp_file_type', models.CharField(max_length=50)),
                ('comp_file_url', models.URLField(max_length=500)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='complaint.complaint')),
            ],
            options={
                'db_table': 'complaint_file',
                'indexes': [models.Index(fields=['comp_file_name'], name='complaint_f_comp_fi_e2e837_idx'), models.Index(fields=['comp'], name='complaint_f_comp_id_55c609_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplaintRecipient',
            fields=[
                ('comp_rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_recipients', to='complaint.complaint')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint_recipient',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='complaint_r_status_039f02_idx'), models.Index(fields=['recipient'], name='complaint_r_recipie_3622d2_idx'), models.Index(fields=['comp'], name='complaint_r_comp_id_e6fe3a_idx')],
            },
        ),
    ]
