# Generated by Django 4.2.20 on 2025-07-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('profiling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('acsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acsd_name', models.CharField(max_length=100)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused', to='profiling.address')),
            ],
            options={
                'db_table': 'accused',
            },
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('cpnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpnt_name', models.CharField(max_length=100)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant', to='profiling.address')),
            ],
            options={
                'db_table': 'complainant',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_incident_type', models.CharField(max_length=100)),
                ('comp_datetime', models.CharField(max_length=100)),
                ('comp_allegation', models.TextField()),
                ('comp_category', models.CharField(default='Low', max_length=100)),
                ('comp_created_at', models.DateTimeField(auto_now_add=True)),
                ('comp_is_archive', models.BooleanField(default=False)),
                ('cpnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaint.complainant')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='ComplaintAccused',
            fields=[
                ('ca_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.accused')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
            ],
            options={
                'db_table': 'complaint_accused',
                'unique_together': {('comp', 'acsd')},
            },
        ),
        migrations.CreateModel(
            name='Complaint_File',
            fields=[
                ('comp_file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_file_name', models.CharField(max_length=255)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_file', to='complaint.complaint')),
            ],
            options={
                'db_table': 'complaint_file',
            },
        ),
        migrations.CreateModel(
            name='ComplaintRecipient',
            fields=[
                ('comp_rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='complaint.complaintaccused')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_notifications', to='account.account')),
            ],
            options={
                'db_table': 'complaint_recipient',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='complaint_r_status_039f02_idx')],
            },
        ),
    ]
