# Generated by Django 4.2.20 on 2025-07-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_file',
            name='comp_file_path',
            field=models.URLField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_file',
            name='comp_file_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_file',
            name='file_size',
            field=models.PositiveIntegerField(default=1, help_text='File size in bytes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_file',
            name='supabase_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='complaint_file',
            index=models.Index(fields=['comp_file_type'], name='complaint_f_comp_fi_a9ae54_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint_file',
            index=models.Index(fields=['comp'], name='complaint_f_comp_id_55c609_idx'),
        ),
    ]
