# Generated by Django 5.2 on 2025-12-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['comp_created_at']},
        ),
        migrations.CreateModel(
            name='Complaint_History',
            fields=[
                ('comp_hist', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_hist_action', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_hist_details', models.JSONField(blank=True, default=dict)),
                ('comp_hist_timestamp', models.DateTimeField(auto_now_add=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_history', to='complaint.complaint')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_history', to='administration.staff')),
            ],
            options={
                'db_table': 'complaint_history',
                'ordering': ['comp_hist_timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ComplaintRecipient',
        ),
        migrations.AddIndex(
            model_name='complaint_history',
            index=models.Index(fields=['comp'], name='complaint_h_comp_id_7c3c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint_history',
            index=models.Index(fields=['comp_hist_timestamp'], name='complaint_h_comp_hi_fab01f_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint_history',
            index=models.Index(fields=['staff'], name='complaint_h_staff_i_af627c_idx'),
        ),
    ]
