# Generated by Django 4.2.20 on 2025-06-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_alter_address_add_external_sitio'),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='acsd_id',
            new_name='acsd',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='cpnt_id',
            new_name='cpnt',
        ),
        migrations.RenameField(
            model_name='complaint_file',
            old_name='comp_id',
            new_name='comp',
        ),
        migrations.RenameField(
            model_name='complaint_file',
            old_name='file_id',
            new_name='file',
        ),
        migrations.AddField(
            model_name='accused',
            name='add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accused', to='profiling.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainant',
            name='add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complainant', to='profiling.address'),
            preserve_default=False,
        ),
    ]
