# Generated by Django 5.2 on 2025-12-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '__first__'),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['comp_created_at']},
        ),
        migrations.AddField(
            model_name='complaint_history',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_history_updates', to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='complaint_history',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaint.complaint'),
        ),
        migrations.AlterField(
            model_name='complaint_history',
            name='comp_hist_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='complaint_history',
            index=models.Index(fields=['staff'], name='complaint_h_staff_i_af627c_idx'),
        ),
    ]
