# Generated by Django 4.2.20 on 2025-06-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_rename_acsd_id_complaint_acsd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='acsd',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cpnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaint.complainant'),
        ),
        migrations.CreateModel(
            name='ComplaintAccused',
            fields=[
                ('ca_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaint.accused')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_persons', to='complaint.complaint')),
            ],
            options={
                'db_table': 'complaint_accused',
                'unique_together': {('complaint', 'accused')},
            },
        ),
    ]
