# Generated by Django 4.2.20 on 2025-07-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_file_comp_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='comp_category',
        ),
        migrations.AddField(
            model_name='accused',
            name='acsd_age',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accused',
            name='acsd_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accused',
            name='acsd_gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainant',
            name='cpnt_age',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainant',
            name='cpnt_gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainant',
            name='cpnt_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainant',
            name='cpnt_relation_to_respondent',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='comp_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
