# Generated by Django 4.2.20 on 2025-06-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('complaint', '0003_remove_complaint_acsd_alter_complaint_cpnt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaintaccused',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='complaintaccused',
            name='acsd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaint.accused'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintaccused',
            name='comp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint_file',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_file', to='complaint.complaint'),
        ),
        migrations.AlterField(
            model_name='complaint_file',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_file', to='file.file'),
        ),
        migrations.AlterUniqueTogether(
            name='complaintaccused',
            unique_together={('comp', 'acsd')},
        ),
        migrations.RemoveField(
            model_name='complaintaccused',
            name='accused',
        ),
        migrations.RemoveField(
            model_name='complaintaccused',
            name='complaint',
        ),
    ]
