# Generated by Django 4.2.20 on 2025-07-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_remove_complaint_comp_category_accused_acsd_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cpnt',
        ),
        migrations.AddField(
            model_name='complaint',
            name='accused',
            field=models.ManyToManyField(related_name='complaints', through='complaint.ComplaintAccused', to='complaint.accused'),
        ),
        migrations.CreateModel(
            name='ComplaintComplainant',
            fields=[
                ('cc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
                ('cpnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complainant')),
            ],
            options={
                'db_table': 'complaint_complainant',
                'unique_together': {('comp', 'cpnt')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainants',
            field=models.ManyToManyField(related_name='complaints', through='complaint.ComplaintComplainant', to='complaint.complainant'),
        ),
    ]
