# Generated by Django 4.2.20 on 2025-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaintaccused_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comp_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
