# Generated by Django 4.2.20 on 2025-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_remove_complaint_cpnt_complaint_accused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complainants',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant',
            field=models.ManyToManyField(related_name='complaint', through='complaint.ComplaintComplainant', to='complaint.complainant'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='accused',
            field=models.ManyToManyField(related_name='complaint', through='complaint.ComplaintAccused', to='complaint.accused'),
        ),
    ]
