# Generated by Django 4.2.20 on 2025-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_alter_complaint_comp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='comp_category',
            field=models.CharField(max_length=100),
        ),
    ]
