# Generated by Django 5.2 on 2025-12-21 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notif_title', models.CharField(max_length=255)),
                ('notif_message', models.TextField()),
                ('notif_created_at', models.DateTimeField(auto_now_add=True)),
                ('notif_type', models.CharField(default='info', max_length=100)),
                ('web_route', models.CharField(blank=True, max_length=255, null=True)),
                ('web_params', models.JSONField(blank=True, null=True)),
                ('mobile_route', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-notif_created_at'],
                'indexes': [models.Index(fields=['notif_created_at'], name='notificatio_notif_c_797e26_idx')],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255)),
                ('fcm_device_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_token',
                'unique_together': {('acc', 'fcm_device_id')},
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='notification.notification')),
            ],
            options={
                'db_table': 'recipient',
                'indexes': [models.Index(fields=['acc', 'notif'], name='recipient_acc_id_c62ce1_idx')],
            },
        ),
    ]
