# Generated by Django 4.2.20 on 2025-04-24 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_recipient_type', models.CharField(choices=[('user', 'All Authenticated Users'), ('staff', 'Staff Users Only'), ('specific', 'Specific User')], default='specific', max_length=20)),
                ('notif_title', models.CharField(max_length=255)),
                ('notif_message', models.TextField()),
                ('notif_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('notif_delivery_channel', models.CharField(choices=[('web', 'Web Notification'), ('mobile', 'Mobile Notification'), ('both', 'Mobile and Web Notification')], default='both', max_length=20)),
                ('notif_is_read', models.BooleanField(default=False)),
                ('notif_sent_web', models.BooleanField(default=False)),
                ('notif_sent_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                ('fcm_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_tokens',
                'unique_together': {('user_id', 'fcm_device_id')},
            },
        ),
    ]
