# Generated by Django 4.2.20 on 2025-06-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notif_is_read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notif_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notif_type',
            new_name='notification_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notif_title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_delivery_channel',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_recipient_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_sent_mobile',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_sent_web',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='acc',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('acc', 'fcm_device_id')},
        ),
        migrations.AlterModelTable(
            name='fcmtoken',
            table='fcm_token',
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notification', to='account.account')),
            ],
            options={
                'db_table': 'recipient',
            },
        ),
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user_id',
        ),
    ]
