# Generated by Django 4.2.20 on 2025-06-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notif_is_read_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
