# Generated by Django 5.2 on 2025-09-28 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_fcmtoken_acc_alter_fcmtoken_fcm_device_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='fcm_device_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='fcm_token',
            field=models.CharField(max_length=255),
        ),
    ]
