# Generated by Django 5.2 on 2025-09-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_fcmtoken_acc_alter_fcmtoken_fcm_device_id_and_more'),
        ('profiling', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='acc',
        ),
        migrations.AddField(
            model_name='recipient',
            name='rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
    ]
