# Generated by Django 5.2 on 2025-09-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_recipient_acc_recipient_rp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(default='info', max_length=100),
        ),
    ]
