# Generated by Django 5.2 on 2025-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_metadata_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mobile_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='mobile_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
