# Generated by Django 5.2 on 2025-10-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_mobile_params_notification_mobile_route_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_content_0c2d97_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
    ]
