# Generated by Django 5.2 on 2025-12-03 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_remove_notification_notificatio_sender__29e426_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notif_created_at'], name='notificatio_notif_c_797e26_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['acc', 'notif'], name='recipient_acc_id_c62ce1_idx'),
        ),
    ]
