import { api } from "@/api/api";


// Function to get a valid resident profile ID (from caller)
const getValidResidentProfileId = async (userId?: string) => {
    if (!userId) {
        throw new Error("Error: No user ID provided");
    }
    return userId;
};

// Test function to check server connectivity
export const testServerConnection = async () => {
    try {
        console.log("Testing server connection...");
        console.log("Base URL:", api.defaults.baseURL);
        
        // Test certificate endpoint directly (skip root URL test)
        console.log("Testing certificate endpoint...");
        const certResponse = await api.get('clerk/certificate/');
        console.log("Certificate endpoint accessible:", certResponse.status);
        
        // Test business permit endpoint
        console.log("Testing business permit endpoint...");
        const permitResponse = await api.get('clerk/business-permit/');
        console.log("Business permit endpoint accessible:", permitResponse.status);
        
        console.log("All endpoints are accessible!");
        return true;
    } catch (err: any) {
        console.error("Server connection test failed:", err);
        console.error("Error details:", {
            message: err.message,
            status: err.response?.status,
            statusText: err.response?.statusText,
            config: {
                url: err.config?.url,
                method: err.config?.method,
                baseURL: err.config?.baseURL
            }
        });
        
        // If it's a 404, the server is reachable but endpoint doesn't exist
        if (err.response?.status === 404) {
            console.log("Server is reachable but endpoint returned 404");
            console.log("This might mean the endpoint doesn't exist or requires authentication");
        }
        
        return false;
    }
};

export const addCertificationRequest = async (requestInfo: Record<string, any>, staffId?: string, userId?: string) => {
    try {
        let businessExistenceFileId = null;
        let grossSalesFileId = null;

        // Upload Business Existence Image
        if (requestInfo.business_existence_image && requestInfo.business_existence_image.length > 0) {
            const fileData = requestInfo.business_existence_image[0];

            const fileUploadResponse = await api.post('file/upload/', {
                file_name: fileData.name,
                file_type: fileData.type,
                file_path: fileData.path,
                file_url: fileData.uri
            });

            if (fileUploadResponse.data && fileUploadResponse.data.file_id) {
                businessExistenceFileId = fileUploadResponse.data.file_id;
            }
        }

        // Upload Gross Sales Image
        if (requestInfo.gross_sales_image && requestInfo.gross_sales_image.length > 0) {
            const fileData = requestInfo.gross_sales_image[0];

            const fileUploadResponse = await api.post('file/upload/', {
                file_name: fileData.name,
                file_type: fileData.type,
                file_path: fileData.path,
                file_url: fileData.uri
            });

            if (fileUploadResponse.data && fileUploadResponse.data.file_id) {
                grossSalesFileId = fileUploadResponse.data.file_id;
            }
        }

        // Personal Certification (ClerkCertificate model)
        if (requestInfo.cert_type === 'personal') {
            // cr_id will be auto-generated by backend in format CR001-25
            
            // Get a valid resident profile ID
            const residentProfileId = await getValidResidentProfileId(userId);
            
            const payload = {
                // cr_id will be auto-generated by backend
                cr_req_request_date: new Date().toISOString().split('T')[0], 
                cr_req_transac_id: 'None', 
                cr_req_purpose: requestInfo.cert_category, 
                cr_req_status: 'Pending',
                cr_req_payment_status: 'Unpaid',
                pr_id: requestInfo.pr_id, 
                rp_id: residentProfileId, 
                serial_no: requestInfo.serialNo || null,
                requester: requestInfo.requester || 'Mobile User'
            };

            console.log("Personal Certification Request Payload:", payload);
            console.log("Making POST request to: clerk/certificate/");
            console.log("Full URL:", api.defaults.baseURL + "/clerk/certificate/");

            const res = await api.post('clerk/certificate/', payload);
            console.log("Response received:", res.data);
            return res.data;
        }
        // Permit Certification (BusinessPermitRequest model)
        else if (requestInfo.cert_type === 'permit') {
            // bpr_id will be auto-generated by backend in format BR001-25
            
            const payload: any = {
                // bpr_id will be auto-generated by backend
                req_request_date: new Date().toISOString().split('T')[0], // Current date
                req_status: 'Pending',
                req_payment_status: 'Unpaid',
                req_amount: requestInfo.req_amount || 0, // Required amount field
                rp_id: await getValidResidentProfileId(userId),
                ags_id: requestInfo.ags_id || null, // Annual gross sales ID (optional)
                pr_id: requestInfo.pr_id || null, // Purpose and rate ID (optional)
                bus_permit_name: requestInfo.business_name || '', // Business name field
                bus_permit_address: requestInfo.business_address || '', // Business address field
                // Image fields for business_permit_file table (handled by backend)
                previous_permit_image: requestInfo.previous_permit_image || null,
                assessment_image: requestInfo.assessment_image || null
            };

            // Always include bus_id - use null if no business exists
            payload.bus_id = requestInfo.business_id || null;

            console.log("Business Permit Request Payload:", payload);
            console.log("Making POST request to: clerk/business-clearance/");
            console.log("Full URL:", api.defaults.baseURL + "/clerk/business-clearance/");

            const res = await api.post('clerk/business-clearance/', payload);
            console.log("Response received:", res.data);
            return res.data;
        } else {
            throw new Error('Invalid certification type');
        }

    } catch (err: any) {
        console.error("Error submitting certification request:", err);
        console.error("Error details:", {
            message: err.message,
            status: err.response?.status,
            statusText: err.response?.statusText,
            data: err.response?.data,
            config: {
                url: err.config?.url,
                method: err.config?.method,
                baseURL: err.config?.baseURL,
                headers: err.config?.headers
            }
        });
        
        if (err.response) {
            
            console.error("Server responded with error:", err.response.status, err.response.data);
        } else if (err.request) {
            
            console.error("No response received from server. Request details:", err.request);
        } else {
            
            console.error("Error setting up request:", err.message);
        }
        
        throw err;
    }
};

export const addBusinessClearance = async (requestInfo: Record<string, any>, staffId?: string, userId?: string) => {
    try {
        const payload: any = {
            // bpr_id will be auto-generated by backend in format BR001-25
            req_request_date: new Date().toISOString().split('T')[0], // Current date
            req_status: 'Pending',
            req_payment_status: 'Unpaid',
            req_amount: requestInfo.req_amount || 0, // Required amount field
            rp_id: await getValidResidentProfileId(userId),
            ags_id: requestInfo.ags_id || null, // Annual gross sales ID (optional)
            pr_id: requestInfo.pr_id || null, // Purpose and rate ID (optional)
            bus_permit_name: requestInfo.business_name || '', // Business name field
            bus_permit_address: requestInfo.business_address || '', // Business address field
            // Image fields for business_permit_file table (handled by backend)
            previous_permit_image: requestInfo.previous_permit_image || null,
            assessment_image: requestInfo.assessment_image || null
        };

        // Always include bus_id - use null if no business exists
        payload.bus_id = requestInfo.business_id || null;

        console.log("Business Clearance Request Payload:", payload);
        console.log("Making POST request to: clerk/business-clearance/");
        console.log("Full URL:", api.defaults.baseURL + "/clerk/business-clearance/");

        const res = await api.post('clerk/business-clearance/', payload);
        console.log("Response received:", res.data);
        return res.data;

    } catch (err: any) {
        console.error("Error submitting business clearance request:", err);
        console.error("Error details:", {
            message: err.message,
            status: err.response?.status,
            statusText: err.response?.statusText,
            data: err.response?.data,
            config: {
                url: err.config?.url,
                method: err.config?.method,
                baseURL: err.config?.baseURL,
                headers: err.config?.headers
            }
        });
        
        if (err.response) {
            console.error("Server responded with error:", err.response.status, err.response.data);
        } else if (err.request) {
            console.error("No response received from server. Request details:", err.request);
        } else {
            console.error("Error setting up request:", err.message);
        }
        
        throw err;
    }
};


export const formatImageForUpload = (imageUri: string, fileName: string) => {
    return {
        name: fileName,
        type: 'image/jpeg', 
        path: imageUri,
        uri: imageUri
    };
};