# Generated by Django 5.1.7 on 2025-03-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObstetricalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_pregnancies', models.PositiveIntegerField(default=0)),
                ('p_pregnancies', models.PositiveIntegerField(default=0)),
                ('full_term', models.PositiveIntegerField()),
                ('premature', models.PositiveIntegerField()),
                ('abortion', models.PositiveIntegerField()),
                ('living_children', models.PositiveIntegerField()),
                ('last_delivery_date', models.DateField(blank=True, null=True)),
                ('type_of_last_delivery', models.CharField(blank=True, choices=[('Vaginal', 'Vaginal'), ('Cesarean', 'Cesarean')], max_length=10, null=True)),
                ('last_menstrual_period', models.DateField()),
                ('previous_menstrual_period', models.DateField()),
                ('menstrual_flow', models.CharField(choices=[('Scanty', 'Scanty'), ('Moderate', 'Moderate'), ('Heavy', 'Heavy')], max_length=10)),
                ('dysmenorrhea', models.BooleanField(default=False)),
                ('hydatidiform_mole', models.BooleanField(default=False)),
                ('ectopic_pregnancy_history', models.BooleanField(default=False)),
            ],
        ),
    ]
