# Generated by Django 5.1.7 on 2025-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0003_risksti_alter_obstetricalhistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskVaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpleasantRelationship', models.BooleanField(default=False)),
                ('partnerDisapproval', models.BooleanField(default=False)),
                ('domesticViolence', models.BooleanField(default=False)),
                ('referredTo', models.TextField()),
                ('otherReferral', models.TextField()),
            ],
            options={
                'db_table': 'risk_vaw',
            },
        ),
    ]
