# Generated by Django 5.1.7 on 2025-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0005_physicalexamination_alter_riskvaw_otherreferral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedMethod', models.CharField(max_length=30)),
                ('clientSignature', models.TextField()),
                ('clientSignatureDate', models.DateField()),
                ('guardianName', models.CharField(max_length=255)),
                ('guardianSignature', models.TextField()),
                ('guardianSignatureDate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'acknowledgement',
            },
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='pulseRate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='weight',
            field=models.FloatField(),
        ),
    ]
