# Generated by Django 5.1.7 on 2025-03-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0007_remove_acknowledgement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acknowledgement',
            old_name='clientSignature',
            new_name='ack_clientSignature',
        ),
        migrations.RenameField(
            model_name='acknowledgement',
            old_name='clientSignatureDate',
            new_name='ack_clientSignatureDate',
        ),
        migrations.RenameField(
            model_name='acknowledgement',
            old_name='guardianName',
            new_name='ack_selectedMethod',
        ),
        migrations.RenameField(
            model_name='acknowledgement',
            old_name='selectedMethod',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='obstetricalhistory',
            old_name='g_pregnancies',
            new_name='obs_abortion',
        ),
        migrations.RenameField(
            model_name='obstetricalhistory',
            old_name='p_pregnancies',
            new_name='obs_fetal_death',
        ),
        migrations.RemoveField(
            model_name='acknowledgement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='abortion',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='dysmenorrhea',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='ectopic_pregnancy_history',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='full_term',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='hydatidiform_mole',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='last_delivery_date',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='last_menstrual_period',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='living_children',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='menstrual_flow',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='premature',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='previous_menstrual_period',
        ),
        migrations.RemoveField(
            model_name='obstetricalhistory',
            name='type_of_last_delivery',
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='ack_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_fullterm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_gravida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_large_babies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_living_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obstetricalhistory',
            name='obs_para',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='obstetricalhistory',
            table=None,
        ),
        migrations.CreateModel(
            name='FP_ObstetricalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_pregnancies', models.PositiveIntegerField(default=0)),
                ('p_pregnancies', models.PositiveIntegerField(default=0)),
                ('full_term', models.PositiveIntegerField()),
                ('premature', models.PositiveIntegerField()),
                ('abortion', models.PositiveIntegerField()),
                ('living_children', models.PositiveIntegerField()),
                ('last_delivery_date', models.DateField(blank=True, null=True)),
                ('type_of_last_delivery', models.CharField(blank=True, choices=[('Vaginal', 'Vaginal'), ('Cesarean', 'Cesarean')], max_length=10, null=True)),
                ('last_menstrual_period', models.DateField()),
                ('previous_menstrual_period', models.DateField()),
                ('menstrual_flow', models.CharField(choices=[('Scanty', 'Scanty'), ('Moderate', 'Moderate'), ('Heavy', 'Heavy')], max_length=10)),
                ('dysmenorrhea', models.BooleanField(default=False)),
                ('hydatidiform_mole', models.BooleanField(default=False)),
                ('ectopic_pregnancy_history', models.BooleanField(default=False)),
                ('obs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.obstetricalhistory')),
            ],
            options={
                'db_table': 'obstetrical_history',
            },
        ),
    ]
