import { api } from '@/api/api';
import { MediaUploadType } from '@/components/ui/media-upload';
import supabase from '@/supabase/supabase';

// Upload file directly to ordinance bucket
export const uploadFileToOrdinanceBucket = async (mediaFile: MediaUploadType[0]) => {
    try {
        
        // Get the file object
        const file = (mediaFile as any).file;
        if (!file) {
            throw new Error('No file object found in mediaFile');
        }
        

        // Try different ways to get the filename
        const actualFileName = file.name || 
                              (mediaFile as any).name || 
                              (mediaFile as any).fileName || 
                              'file';
        

        // Convert base64 data URL to proper File object if needed
        let fileToUpload = file;
        if (typeof file === 'string' && file.startsWith('data:')) {
            const response = await fetch(file);
            const blob = await response.blob();
            fileToUpload = new File([blob], actualFileName, { type: blob.type });
        }

        // Upload directly to ordinance bucket
        const fileName = `${Date.now()}-${Math.random().toString(36).substring(2, 9)}-${actualFileName}`;
        const filePath = `ordinances/${fileName}`;
        

        const { error: uploadError } = await supabase.storage
            .from('ordinance-bucket')
            .upload(filePath, fileToUpload, {
                cacheControl: "3600",
                upsert: false,
            });

        if (uploadError) {
            console.error('Upload error:', uploadError);
            throw uploadError;
        }
        

        // Get public URL from ordinance bucket
        const { data: { publicUrl } } = supabase.storage
            .from('ordinance-bucket')
            .getPublicUrl(filePath);
            

        return { publicUrl, storagePath: filePath, fileName: actualFileName };
    } catch (error) {
        console.error('Error uploading file to ordinance bucket:', error);
        throw error;
    }
};

export const createOrdinanceFile = async (mediaFile: MediaUploadType[0]) => {
    try {
        
        // Upload file directly to ordinance bucket
        const uploadResult = await uploadFileToOrdinanceBucket(mediaFile);
        
        const fileData = {
            of_url: uploadResult.publicUrl,
            of_name: uploadResult.fileName,
            of_type: ((mediaFile as any).type || 'unknown').substring(0, 50), // Limit to 50 characters
            of_path: uploadResult.storagePath, // Use the storage path
        };
        
        const fileResponse = await api.post('council/ordinance-file/', fileData);
        
        return fileResponse.data;
    } catch (error) {
        console.error('Error creating ordinance file:', error);
        throw error;
    }
};

export const insertOrdinanceUpload = async (ordinanceInfo: Record<string, any>, mediaFiles: MediaUploadType, staffId: string) => {
    try {
        // Extract year from date
        const date = new Date(ordinanceInfo.ordinanceDate);
        const year = date.getFullYear();
        
        // Ordinance number will be auto-generated by backend in ORD000-25 format

        // 1. Handle file upload first if exists
        let fileId = null;
        
        if (mediaFiles.length > 0) {
            // Check if file is ready for upload
            const mediaFile = mediaFiles[0];
            const hasFile = !!(mediaFile as any).file;
            const isUploaded = (mediaFile as any).status === 'uploaded';
            
            if (hasFile) {
                try {
                    const fileResponse = await createOrdinanceFile(mediaFile);
                    fileId = fileResponse.of_id;
                } catch (fileError) {
                    console.error('Error uploading file:', fileError);
                    // Continue without file if upload fails
                }
            }
        }

        // 2. Create ordinance record with file
        const ordinanceData: any = {
            ord_title: ordinanceInfo.ordinanceTitle,
            ord_date_created: ordinanceInfo.ordinanceDate,
            ord_category: ordinanceInfo.ordinanceCategory,
            ord_details: ordinanceInfo.ordinanceDetails,
            ord_year: year,
            ord_is_archive: false,
            ord_repealed: Boolean(ordinanceInfo.ord_repealed),
            staff_id: staffId, // Dynamic staff ID from parameter
            of_id: fileId
        };

        // Ordinance number will be auto-generated by backend in ORD000-25 format
        // Don't set ord_num - let backend generate it

        // Add amendment-related fields if this is an amendment
        if (ordinanceInfo.ord_parent && ordinanceInfo.ord_parent !== "new") {
            ordinanceData.ord_parent = ordinanceInfo.ord_parent;
            ordinanceData.ord_is_ammend = ordinanceInfo.ord_is_ammend;
            ordinanceData.ord_ammend_ver = ordinanceInfo.ord_ammend_ver;
        }
        
        const ordinanceResponse = await api.post('council/ordinance/', ordinanceData);

        return ordinanceResponse.data;
    } catch (error) {
        console.error('Error creating Ordinance Upload:', error);
        throw error;
    }
}; 