import { api } from '@/api/api';
import { MediaUploadType } from '@/components/ui/media-upload';

export const createOrdinanceFile = async (mediaFile: MediaUploadType[0]) => {
    try {
        // Get the file object
        const file = (mediaFile as any).file;
        if (!file) {
            throw new Error('No file object found in mediaFile');
        }

        // Get the actual filename
        const actualFileName = file.name || 
                              (mediaFile as any).name || 
                              (mediaFile as any).fileName || 
                              'file';
        
        // Get the file type
        const fileType = (mediaFile as any).type || file.type || 'application/octet-stream';

        // Convert file to base64 string
        let base64String = '';
        
        if (typeof file === 'string') {
            // Already a base64 string
            base64String = file;
        } else if (file instanceof File) {
            // Convert File to base64
            base64String = await new Promise<string>((resolve, reject) => {
                const reader = new FileReader();
                reader.onload = () => {
                    const result = reader.result as string;
                    resolve(result);
                };
                reader.onerror = reject;
                reader.readAsDataURL(file);
            });
        } else {
            throw new Error('Unsupported file type');
        }

        // Send file data to backend in the expected format
        const payload = {
            files: [{
                name: actualFileName,
                type: fileType,
                file: base64String
            }]
        };
        
        console.log('Uploading ordinance file to backend...');
        const fileResponse = await api.post('council/ordinance-file/', payload);
        
        return fileResponse.data[0]; // Return the first file from the array
    } catch (error) {
        console.error('Error creating ordinance file:', error);
        throw error;
    }
};

export const insertOrdinanceUpload = async (ordinanceInfo: Record<string, any>, mediaFiles: MediaUploadType, staffId: string) => {
    try {
        // Extract year from date
        const date = new Date(ordinanceInfo.ordinanceDate);
        const year = date.getFullYear();
        
        // Ordinance number will be auto-generated by backend in ORD000-25 format

        // 1. Handle file upload first if exists
        let fileId = null;
        
        if (mediaFiles.length > 0) {
            // Check if file is ready for upload
            const mediaFile = mediaFiles[0];
            const hasFile = !!(mediaFile as any).file;
            
            if (hasFile) {
                try {
                    const fileResponse = await createOrdinanceFile(mediaFile);
                    fileId = fileResponse.of_id;
                } catch (fileError) {
                    console.error('Error uploading file:', fileError);
                    // Continue without file if upload fails
                }
            }
        }

        // 2. Create ordinance record with file
        const ordinanceData: any = {
            ord_title: ordinanceInfo.ordinanceTitle,
            ord_date_created: ordinanceInfo.ordinanceDate,
            ord_category: ordinanceInfo.ordinanceCategory,
            ord_details: ordinanceInfo.ordinanceDetails,
            ord_year: year,
            ord_is_archive: false,
            ord_repealed: Boolean(ordinanceInfo.ord_repealed),
            staff_id: staffId, // Dynamic staff ID from parameter
            of_id: fileId
        };

        // Ordinance number will be auto-generated by backend in ORD000-25 format
        // Don't set ord_num - let backend generate it

        // Add amendment-related fields if this is an amendment
        if (ordinanceInfo.ord_parent && ordinanceInfo.ord_parent !== "new") {
            ordinanceData.ord_parent = ordinanceInfo.ord_parent;
            ordinanceData.ord_is_ammend = ordinanceInfo.ord_is_ammend;
            ordinanceData.ord_ammend_ver = ordinanceInfo.ord_ammend_ver;
        }
        
        const ordinanceResponse = await api.post('council/ordinance/', ordinanceData);

        return ordinanceResponse.data;
    } catch (error) {
        console.error('Error creating Ordinance Upload:', error);
        throw error;
    }
}; 