# Generated by Django 5.1.7 on 2025-06-10 04:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('profiling', '0002_remove_personal_per_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionStaff',
            fields=[
                ('wstf_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'waste_collection_staff',
            },
        ),
        migrations.CreateModel(
            name='WasteEvent',
            fields=[
                ('we_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('we_name', models.CharField(max_length=100, null=True)),
                ('we_location', models.CharField(max_length=100, null=True)),
                ('we_date', models.DateField(null=True)),
                ('we_time', models.TimeField(null=True)),
                ('we_description', models.CharField(max_length=200, null=True)),
                ('we_organizer', models.CharField(max_length=100, null=True)),
                ('we_invitees', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'waste_event',
            },
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('rep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rep_image', models.CharField(default='none')),
                ('rep_matter', models.CharField(default='none')),
                ('rep_location', models.CharField(default='none')),
                ('rep_add_details', models.CharField(max_length=200, null=True)),
                ('rep_violator', models.CharField(default='none')),
                ('rep_complainant', models.CharField(default='none')),
                ('rep_contact', models.CharField(default='none')),
                ('rep_status', models.CharField(default='pending', max_length=100)),
                ('rep_date', models.DateField(default=datetime.date.today)),
                ('rep_date_resolved', models.DateField(null=True)),
                ('rep_resolved_img', models.CharField(null=True)),
            ],
            options={
                'db_table': 'waste_report',
            },
        ),
        migrations.CreateModel(
            name='WasteTruck',
            fields=[
                ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck_plate_num', models.CharField(max_length=20)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_capacity', models.IntegerField()),
                ('truck_status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=50)),
                ('truck_last_maint', models.DateField(default=datetime.date.today)),
                ('truck_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'truck',
            },
        ),
        migrations.CreateModel(
            name='WasteCollectionSched',
            fields=[
                ('wc_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('wc_date', models.DateField(null=True)),
                ('wc_time', models.TimeField(null=True)),
                ('wc_add_info', models.CharField(max_length=200, null=True)),
                ('wc_is_archive', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'waste_collection_sched',
            },
        ),
        migrations.CreateModel(
            name='WasteCollectionAssignment',
            fields=[
                ('was_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
                ('wc_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionsched')),
            ],
            options={
                'db_table': 'waste_collection_assignment',
            },
        ),
        migrations.CreateModel(
            name='WastePersonnel',
            fields=[
                ('wstp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'waste_personnel',
            },
        ),
        migrations.CreateModel(
            name='WasteHotspot',
            fields=[
                ('wh_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('wh_date', models.DateField(null=True)),
                ('wh_time', models.TimeField(null=True)),
                ('wh_add_info', models.CharField(max_length=200, null=True)),
                ('wh_is_archive', models.BooleanField(default=False)),
                ('sitio_id', models.ForeignKey(blank=True, db_column='sitio_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio')),
                ('wstp_id', models.ForeignKey(db_column='wstp_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel')),
            ],
            options={
                'db_table': 'waste_hotspot',
            },
        ),
        migrations.CreateModel(
            name='WasteCollector',
            fields=[
                ('wasc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionassignment')),
                ('wstp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel')),
            ],
            options={
                'db_table': 'waste_collector',
            },
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='wstp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastetruck'),
        ),
    ]
