# Generated by Django 5.2 on 2025-05-27 08:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePersonnel',
            fields=[
                ('wstp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'waste_personnel',
            },
        ),
    ]
