# Generated by Django 5.1.7 on 2025-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup_confirmation',
            name='conf_resident_conf',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='pickup_confirmation',
            name='conf_staff_conf',
            field=models.BooleanField(blank=True),
        ),
    ]
