# Generated by Django 5.1.7 on 2025-05-27 08:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('waste', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='WasteCollectionAssignment',
        #     fields=[
        #         ('was_id', models.BigAutoField(primary_key=True, serialize=False)),
        #     ],
        #     options={
        #         'db_table': 'waste_collection_assignment',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='WasteCollectionStaff',
        #     fields=[
        #         ('wstf_id', models.BigAutoField(primary_key=True, serialize=False)),
        #     ],
        #     options={
        #         'db_table': 'waste_collection_staff',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='WasteEvent',
        #     fields=[
        #         ('we_num', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('we_name', models.CharField(max_length=100, null=True)),
        #         ('we_location', models.CharField(max_length=100, null=True)),
        #         ('we_date', models.DateField(null=True)),
        #         ('we_time', models.TimeField(null=True)),
        #         ('we_description', models.CharField(max_length=200, null=True)),
        #         ('we_organizer', models.CharField(max_length=100, null=True)),
        #         ('we_invitees', models.CharField(max_length=100, null=True)),
        #     ],
        #     options={
        #         'db_table': 'waste_event',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='WasteHotspot',
        #     fields=[
        #         ('wh_num', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('wh_date', models.DateField(null=True)),
        #         ('wh_time', models.TimeField(null=True)),
        #         ('wh_add_info', models.CharField(max_length=200, null=True)),
        #     ],
        #     options={
        #         'db_table': 'waste_hotspot',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='WasteTruck',
        #     fields=[
        #         ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('truck_plate_num', models.CharField(max_length=20)),
        #         ('truck_model', models.CharField(max_length=50)),
        #         ('truck_capacity', models.IntegerField()),
        #         ('truck_status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=50)),
        #         ('truck_last_maint', models.DateField(default=datetime.date.today)),
        #     ],
        #     options={
        #         'db_table': 'truck',
        #     },
        # ),
        migrations.AlterField(
            model_name='wastereport',
            name='rep_resolved_img',
            field=models.CharField(null=True),
        ),
        # migrations.CreateModel(
        #     name='WasteCollectionSched',
        #     fields=[
        #         ('wc_num', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('wc_date', models.DateField(null=True)),
        #         ('wc_time', models.TimeField(null=True)),
        #         ('wc_add_info', models.CharField(max_length=200, null=True)),
        #         ('was_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionassignment')),
        #     ],
        #     options={
        #         'db_table': 'waste_collection_sched',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='wastecollectionassignment',
        #     name='wstf_id',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionstaff'),
        # ),
        # migrations.CreateModel(
        #     name='WastePersonnel',
        #     fields=[
        #         ('wstp_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
        #     ],
        #     options={
        #         'db_table': 'waste_personnel',
        #     },
        # ),
    ]
