# Generated by Django 4.2.20 on 2025-07-15 18:14

import apps.waste.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_requestregistration_acc'),
        ('administration', '__first__'),
        ('file', '0001_initial'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Collector',
            fields=[
                ('acl_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assignment_collector',
            },
        ),
        migrations.CreateModel(
            name='Garbage_Pickup_Request',
            fields=[
                ('garb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('garb_location', models.CharField(max_length=20)),
                ('garb_waste_type', models.CharField(max_length=20)),
                ('garb_pref_date', models.DateField(default=datetime.date.today)),
                ('garb_pref_time', models.TimeField(default=apps.waste.models.current_time)),
                ('garb_req_status', models.CharField(max_length=20)),
                ('garb_additional_notes', models.TextField()),
                ('garb_created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('rp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'garbage_pickup_request',
            },
        ),
        migrations.CreateModel(
            name='Pickup_Assignment',
            fields=[
                ('pick_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pick_date', models.DateField(default=datetime.date.today)),
                ('pick_time', models.TimeField(default=apps.waste.models.current_time)),
                ('garb_id', models.ForeignKey(db_column='garb_id', on_delete=django.db.models.deletion.CASCADE, to='waste.garbage_pickup_request')),
            ],
            options={
                'db_table': 'pickup_assignment',
            },
        ),
        migrations.CreateModel(
            name='Pickup_Confirmation',
            fields=[
                ('conf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conf_resident_conf', models.BooleanField(blank=True)),
                ('conf_staff_conf', models.BooleanField(blank=True)),
                ('conf_staff_conf_date', models.DateTimeField(default=datetime.datetime.now)),
                ('conf_resident_conf_date', models.DateTimeField(blank=True, null=True)),
                ('garb_id', models.ForeignKey(db_column='garb_id', on_delete=django.db.models.deletion.CASCADE, to='waste.garbage_pickup_request')),
            ],
            options={
                'db_table': 'pickup_confirmation',
            },
        ),
        migrations.CreateModel(
            name='Pickup_Request_Decision',
            fields=[
                ('dec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dec_rejection_reason', models.TextField(blank=True, null=True)),
                ('dec_date', models.DateTimeField(default=datetime.datetime.now)),
                ('garb_id', models.ForeignKey(db_column='garb_id', on_delete=django.db.models.deletion.CASCADE, to='waste.garbage_pickup_request')),
            ],
            options={
                'db_table': 'pickup_request_decision',
            },
        ),
        migrations.CreateModel(
            name='WasteCollector',
            fields=[
                ('wasc_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'waste_collector',
            },
        ),
        migrations.CreateModel(
            name='WastePersonnel',
            fields=[
                ('wstp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'waste_personnel',
            },
        ),
        migrations.CreateModel(
            name='WasteReport_File',
            fields=[
                ('wrf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wrf_name', models.CharField(max_length=255)),
                ('wrf_type', models.CharField(max_length=100)),
                ('wrf_path', models.CharField(max_length=500)),
                ('wrf_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'waste_report_file',
            },
        ),
        migrations.CreateModel(
            name='WasteTruck',
            fields=[
                ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck_plate_num', models.CharField(max_length=20)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_capacity', models.IntegerField()),
                ('truck_status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=50)),
                ('truck_last_maint', models.DateField(default=datetime.date.today)),
                ('truck_is_archive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'truck',
            },
        ),
        migrations.RemoveField(
            model_name='wastecollectionsched',
            name='was_id',
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='wc_is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_contact',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_date_resolved',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_location',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_matter',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_resolved_img',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rp_id',
            field=models.ForeignKey(blank=True, db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='sitio_id',
            field=models.ForeignKey(blank=True, db_column='sitio_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='staff_id',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='rep_image',
            field=models.CharField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='rep_violator',
            field=models.CharField(default='none'),
        ),
        migrations.DeleteModel(
            name='WasteCollectionAssignment',
        ),
        migrations.AddField(
            model_name='wastereport_file',
            name='rep_id',
            field=models.ForeignKey(blank=True, db_column='rep_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_report_file', to='waste.wastereport'),
        ),
        migrations.AddField(
            model_name='wastecollector',
            name='wc_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionsched'),
        ),
        migrations.AddField(
            model_name='wastecollector',
            name='wstp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
        migrations.AddField(
            model_name='pickup_assignment',
            name='truck_id',
            field=models.ForeignKey(db_column='truck_id', on_delete=django.db.models.deletion.CASCADE, to='waste.wastetruck'),
        ),
        migrations.AddField(
            model_name='pickup_assignment',
            name='wstp_id',
            field=models.ForeignKey(db_column='wstp_id', on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
        migrations.AddField(
            model_name='assignment_collector',
            name='pick_id',
            field=models.ForeignKey(db_column='pick_id', on_delete=django.db.models.deletion.CASCADE, to='waste.pickup_assignment'),
        ),
        migrations.AddField(
            model_name='assignment_collector',
            name='wstp_id',
            field=models.ForeignKey(db_column='wstp_id', on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastetruck'),
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='wstp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
    ]
