# Generated by Django 5.1.7 on 2025-05-20 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='rep_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_date_resolved',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
