# Generated by Django 5.1.7 on 2025-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wastereport_rep_date_wastereport_rep_date_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='rep_image',
            field=models.CharField(default='none'),
        ),
    ]
