# Generated by Django 5.1.7 on 2025-06-05 03:46

import apps.waste.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('file', '0001_initial'),
        ('profiling', '0002_remove_personal_per_address'),
        ('waste', '0002_wastecollectionassignment_wastecollectionstaff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionAssignment',
            fields=[
                ('was_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'waste_collection_assignment',
            },
        ),
        migrations.CreateModel(
            name='WasteCollectionStaff',
            fields=[
                ('wstf_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'waste_collection_staff',
            },
        ),
        migrations.CreateModel(
            name='WasteEvent',
            fields=[
                ('we_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('we_name', models.CharField(max_length=100, null=True)),
                ('we_location', models.CharField(max_length=100, null=True)),
                ('we_date', models.DateField(null=True)),
                ('we_time', models.TimeField(null=True)),
                ('we_description', models.CharField(max_length=200, null=True)),
                ('we_organizer', models.CharField(max_length=100, null=True)),
                ('we_invitees', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'waste_event',
            },
        ),
        migrations.CreateModel(
            name='WasteHotspot',
            fields=[
                ('wh_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('wh_date', models.DateField(null=True)),
                ('wh_time', models.TimeField(null=True)),
                ('wh_add_info', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'waste_hotspot',
            },
        ),
        migrations.CreateModel(
            name='WasteTruck',
            fields=[
                ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck_plate_num', models.CharField(max_length=20)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_capacity', models.IntegerField()),
                ('truck_status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=50)),
                ('truck_last_maint', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'truck',
            },
        ),
        migrations.CreateModel(
            name='Garbage_Pickup_Request',
            fields=[
                ('garb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('garb_location', models.CharField(max_length=20)),
                ('garb_waste_type', models.CharField(max_length=20)),
                ('garb_pref_date', models.DateField(default=datetime.date.today)),
                ('garb_pref_time', models.TimeField(default=apps.waste.models.current_time)),
                ('garv_req_status', models.CharField(max_length=20)),
                ('garb_additional_notes', models.TextField()),
                ('garb_created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('rp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
            ],
            options={
                'db_table': 'garbage_pickup_request',
            },
        ),
        migrations.CreateModel(
            name='Pickup_Confirmation',
            fields=[
                ('conf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conf_resident_conf', models.BooleanField(default=False)),
                ('conf_staff_conf', models.BooleanField(default=False)),
                ('conf_confirm_date', models.DateTimeField(default=datetime.datetime.now)),
                ('garb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.garbage_pickup_request')),
            ],
            options={
                'db_table': 'pickup_confirmation',
            },
        ),
        migrations.CreateModel(
            name='Pickup_Request_Decision',
            fields=[
                ('dec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dce_rejection_reason', models.TextField()),
                ('dec_date', models.DateField(default=datetime.datetime.now)),
                ('garb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.garbage_pickup_request')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'pickup_request_decision',
            },
        ),
        migrations.CreateModel(
            name='WasteCollectionSched',
            fields=[
                ('wc_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('wc_date', models.DateField(null=True)),
                ('wc_time', models.TimeField(null=True)),
                ('wc_add_info', models.CharField(max_length=200, null=True)),
                ('was_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionassignment')),
            ],
            options={
                'db_table': 'waste_collection_sched',
            },
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='wstf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionstaff'),
        ),
        migrations.CreateModel(
            name='WastePersonnel',
            fields=[
                ('wstp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'waste_personnel',
            },
        ),
        migrations.CreateModel(
            name='Pickup_Assignment',
            fields=[
                ('pick_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pick_date', models.DateField(default=datetime.date.today)),
                ('pick_time', models.TimeField(default=apps.waste.models.current_time)),
                ('garb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.garbage_pickup_request')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('wstp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastetruck')),
            ],
            options={
                'db_table': 'pickup_assignment',
            },
        ),
        migrations.CreateModel(
            name='Assignment_Collector',
            fields=[
                ('acl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pick_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.pickup_assignment')),
                ('wstp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel')),
            ],
            options={
                'db_table': 'assignment_collector',
            },
        ),
    ]
