# Generated by Django 5.1.7 on 2025-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_garbage_pickup_request_garb_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage_pickup_request',
            name='garb_location',
            field=models.CharField(max_length=20),
        ),
    ]
