# Generated by Django 5.1.7 on 2025-07-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_garbage_pickup_request_garb_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReportResolve_File',
            fields=[
                ('wrsf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wrsf_name', models.CharField(max_length=255)),
                ('wrsf_type', models.CharField(max_length=100)),
                ('wrsf_path', models.CharField(max_length=500)),
                ('wrsf_url', models.CharField(max_length=500)),
                ('rep_id', models.ForeignKey(blank=True, db_column='rep_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_report_rslv_file', to='waste.wastereport')),
            ],
            options={
                'db_table': 'waste_report_rslv_file',
            },
        ),
    ]
