# Generated by Django 5.1.7 on 2025-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_wastereport_rep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='rep_complainant',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_contact',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_location',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='rep_matter',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='rep_violator',
            field=models.CharField(default='none'),
        ),
    ]
