# Generated by Django 5.1.7 on 2025-06-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('profiling', '0002_remove_personal_per_address'),
        ('waste', '0003_wastecollectionassignment_wastecollectionstaff_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wastecollectionassignment',
        #     name='wstf_id',
        # ),
        migrations.RemoveField(
            model_name='wastecollectionsched',
            name='was_id',
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.sitio'),
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastetruck'),
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='wc_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionsched'),
        ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='wstp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='wastecollectionsched',
            name='wc_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
