# Generated by Django 5.1.7 on 2025-07-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_wastereportresolve_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='rep_resolved_img',
        ),
    ]
