# Generated by Django 5.2 on 2025-05-25 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_wastereport_rep_complainant_wastereport_rep_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePersonnel',
            fields=[
                ('wstp_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'waste_personnel',
            },
        ),
        migrations.CreateModel(
            name='WasteTruck',
            fields=[
                ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck_plate_num', models.CharField(max_length=20)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_capacity', models.IntegerField(max_length=500)),
                ('truck_status', models.CharField(default='operational', max_length=50)),
                ('truck_last_maint', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'truck',
            },
        ),
    ]
