# Generated by Django 5.2 on 2025-06-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_remove_wastecollectionassignment_wstf_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wastecollectionassignment',
        #     name='wstf_id',
        # ),
        migrations.AddField(
            model_name='wastetruck',
            name='truck_is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
