# Generated by Django 5.1.7 on 2025-06-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_remove_wastecollectionassignment_wstf_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wastecollectionassignment',
        #     name='wstf_id',
        # ),
        migrations.RemoveField(
            model_name='wastecollectionassignment',
            name='wstp',
        ),
        migrations.CreateModel(
            name='WasteCollector',
            fields=[
                ('wasc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecollectionassignment')),
                ('wstp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel')),
            ],
        ),
    ]
