# Generated by Django 5.2 on 2025-05-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('waste', '0005_wastepersonnel_wastetruck'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastepersonnel',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastetruck',
            name='wstp_id',
            field=models.ForeignKey(blank=True, db_column='wstp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='waste.wastepersonnel'),
        ),
        migrations.AlterField(
            model_name='wastetruck',
            name='truck_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wastetruck',
            name='truck_status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=50),
        ),
    ]
