# Generated by Django 5.1.7 on 2025-07-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_remove_wastereport_rep_resolved_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='rep_image',
        ),
    ]
