# Generated by Django 5.2 on 2025-08-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_remove_wastereport_rep_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbagePickupRequestFile',
            fields=[
                ('gprf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gprf_name', models.CharField(max_length=255)),
                ('gprf_type', models.CharField(max_length=100)),
                ('gprf_path', models.CharField(max_length=500)),
                ('gprf_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'garbage_pickup_request_file',
            },
        ),
        migrations.RemoveField(
            model_name='garbage_pickup_request',
            name='file',
        ),
        migrations.AddField(
            model_name='garbage_pickup_request',
            name='gprf',
            field=models.ForeignKey(blank=True, db_column='gprf_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.garbagepickuprequestfile'),
        ),
    ]
