# Generated by Django 5.1.7 on 2025-06-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_remove_wastecollectionassignment_wstf_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wastecollectionassignment',
        #     name='wstf_id',
        # ),
        migrations.AlterModelTable(
            name='wastecollector',
            table='waste_collector',
        ),
    ]
