# Generated by Django 5.2 on 2025-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_garbagepickuprequestfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage_pickup_request',
            name='garb_waste_type',
            field=models.CharField(max_length=250),
        ),
    ]
