# Generated by Django 5.1.7 on 2025-06-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_remove_wastecollectionassignment_wstf_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wastecollectionassignment',
        #     name='wstf_id',
        # ),
        migrations.AddField(
            model_name='wastecollectionassignment',
            name='wstp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.wastepersonnel'),
        ),
    ]
