# Generated by Django 5.2 on 2025-04-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.TextField()),
                ('file_url', models.TextField()),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
