"use client"
import { useState } from 'react';
import { SelectLayout } from "@/components/ui/select/select-layout";
import {Textarea} from '../../../../components/ui/textarea.tsx';
import {Button} from '../../../../components/ui/button/button.tsx';
import { Form,FormControl,FormField,FormItem,FormLabel,FormMessage,} from "@/components/ui/form/form.tsx";
import DialogLayout from "@/components/ui/dialog/dialog-layout";
import { ChevronLeft } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion";
import { Link, useNavigate } from 'react-router';
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import ordinanceFormSchema from '@/form-schema/ordinanceFormSchema';
import Tiptap from '@/components/ui/tiptap/tiptap.tsx';
import { createOrdinance } from './restful-api/OrdinanceGetAPI';
import { toast } from 'sonner';

function AddOrdinancePage() {
    const navigate = useNavigate();
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [_showDialog, _setShowDialog] = useState(false);

    const form = useForm<z.infer<typeof ordinanceFormSchema>>({
        resolver: zodResolver(ordinanceFormSchema),
        mode: 'onChange',
        defaultValues: {
            ordTitle: "",       
            ordTag: "",
            ordDesc: "", 
            ordDate: "",
            ordDetails: "",
            ordAreaOfFocus: [],
        },
    });

    const ordAreaOfFocus = [
        "Council", "GAD", 
        "Waste Committee", "Finance"
    ];

    async function onSubmit(values: z.infer<typeof ordinanceFormSchema>) {
        try {
            setIsSubmitting(true);
            
            // Validate required fields
            if (!values.ordDate) {
                toast.error("Date is required");
                return;
            }
            
            if (!values.ordTitle) {
                toast.error("Ordinance title is required");
                return;
            }
            
            if (!values.ordDetails) {
                toast.error("Ordinance content is required");
                return;
            }
            
            if (!values.ordAreaOfFocus || values.ordAreaOfFocus.length === 0) {
                toast.error("At least one area of focus must be selected");
                return;
            }
            
            // Transform the data for the API - match backend model fields exactly
            const ordinanceData: Partial<{
                ord_title: string;
                ord_details: string;
                ord_date_created: string;
                ord_category: string;
                ord_year: number;
            }> = {
                ord_title: values.ordTitle,
                ord_details: values.ordDetails,
                ord_date_created: values.ordDate,
                ord_category: values.ordAreaOfFocus.join(', '), // Convert array to string
                ord_year: new Date(values.ordDate).getFullYear(),
                // Let the backend generate the ordinance number
                // ord_num will be generated by the backend
            };

            console.log("Submitting ordinance data:", ordinanceData);
            
            const response = await createOrdinance(ordinanceData);
            console.log("Ordinance created successfully:", response);
            
            toast.success("Ordinance created successfully!");
            navigate('/ord-page');
            
        } catch (error) {
            console.error("Error creating ordinance:", error);
            toast.error("Failed to create ordinance. Please try again.");
        } finally {
            setIsSubmitting(false);
        }
    }

    return (
        <div className="flex p-5 w-full mx-auto h-full justify-center">
            <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                    <div className="text-[#394360] pb-2">
                        <Link to="/ord-page">
                            <Button 
                                className="text-black p-2 self-start"
                                variant={"outline"}
                            >
                                <ChevronLeft />
                            </Button>                        
                        </Link>
                    </div>

                    {/* Ordinance Description Field */}
                    <FormField
                        control={form.control}
                        name="ordDetails"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Ordinance Content</FormLabel>
                                <FormControl>
                                    <Tiptap description={field.value} onChange={field.onChange} />
                                </FormControl>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    <div className="flex items-center justify-end p-[40px]">
                        {/* Dialog with Form Inside */}
                        <DialogLayout
                            trigger={
                                <div className="bg-primary hover:bg-primary/90 text-white text-sm font-medium px-6 py-2 rounded-md cursor-pointer flex items-center">
                                    Next
                                </div>
                            }
                            className="max-w-[30%] h-[460px] flex flex-col overflow-auto scrollbar-custom"
                            title="Ordinance Details"
                            description="Add ordinance metadata."
                            mainContent={
                                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                                    {/* Ordinance Title Field */}
                                    <FormField
                                        control={form.control}
                                        name="ordTitle"
                                        render={({ field }) => (
                                            <FormItem>
                                                <FormLabel>Ordinance Title</FormLabel>
                                                <FormControl>
                                                    <Textarea
                                                        className="w-full p-2 shadow-sm h-20 mt-[12px] rounded-[5px] resize-none"
                                                        placeholder="Enter Ordinance Title"
                                                        {...field}>
                                                    </Textarea>                                                            
                                                </FormControl>
                                                <FormMessage />
                                            </FormItem>
                                        )}
                                    />

                                    <FormField
                                        control={form.control}
                                        name="ordTag"
                                        render={({ field }) => (
                                            <FormItem>
                                            <FormLabel>Amend</FormLabel>
                                            <FormControl>
                                                <SelectLayout
                                                    className="w-full"
                                                    label="Ordinances"
                                                    placeholder="Select Amended Ordinance"
                                                    options={[
                                                        {id: "001-1", name: "001-1"},
                                                        {id: "002-2", name: "002-2"}                                                   
                                                    ]}
                                                    value={field.value || ""}
                                                    onChange={field.onChange}
                                                />
                                            </FormControl>
                                            <FormMessage />
                                            </FormItem>
                                        )}
                                    />            

                                    <FormField
                                        control={form.control}
                                        name="ordDesc"
                                        render={({ field }) => (
                                            <FormItem>
                                                <FormLabel>Ordinance Description</FormLabel>
                                                <FormControl>
                                                    <Textarea
                                                        className="w-full p-2 shadow-sm h-20 mt-[12px] rounded-[5px] resize-none"
                                                        placeholder="Description"
                                                        {...field}>
                                                    </Textarea>                                                            
                                                </FormControl>
                                                <FormMessage />
                                            </FormItem>
                                        )}
                                    />                                            

                                    {/* Date Approved Field */}
                                    <FormField
                                        control={form.control}
                                        name="ordDate"
                                        render={({ field }) => (
                                            <FormItem>
                                                <FormLabel>Date Approved</FormLabel>
                                                <FormControl>
                                                    <input 
                                                        type="date" 
                                                        {...field} 
                                                        className="mt-[8px] w-full border border-[#B3B7BD] p-1.5 shadow-sm sm:text-sm focus:outline-none rounded-[3px]" 
                                                    />
                                                </FormControl>
                                                <FormMessage />
                                            </FormItem>
                                        )}
                                    />

                                    {/* Categories Field */}
                                    <Accordion type="single" collapsible>
                                        <AccordionItem value="category-list">
                                            <AccordionTrigger>Select Area of Focus</AccordionTrigger>
                                            <AccordionContent>
                                                <div className="space-y-2">
                                                    {ordAreaOfFocus.map((area, index) => (
                                                        <FormField
                                                            key={index}
                                                            control={form.control}
                                                            name="ordAreaOfFocus"
                                                            render={({ field }) => {
                                                                const selectedCategory = field.value ?? [];
                                                                return (
                                                                    <FormItem className="flex flex-row items-start space-x-3 space-y-0.5">
                                                                        <FormControl>
                                                                            <Checkbox
                                                                                id={`area-${index}`}
                                                                                className="h-5 w-5"
                                                                                checked={selectedCategory.includes(area)}
                                                                                onCheckedChange={(checked) => {
                                                                                    field.onChange(
                                                                                        checked
                                                                                            ? [...selectedCategory, area]
                                                                                            : selectedCategory.filter((name: string) => name !== area)
                                                                                    );
                                                                                }}
                                                                            />
                                                                        </FormControl>
                                                                        <FormLabel
                                                                            htmlFor={`area-${index}`}
                                                                            className="cursor-pointer whitespace-normal break-words flex-1"
                                                                            style={{ wordBreak: "break-all" }}
                                                                        >
                                                                            {area}
                                                                        </FormLabel>
                                                                    </FormItem>
                                                                );
                                                            }}
                                                        />
                                                    ))}
                                                </div>
                                            </AccordionContent>
                                        </AccordionItem>
                                    </Accordion>                                            

                                    {/* Submit Button (Inside Dialog) */}
                                    <div className="flex items-center justify-end pt-4">
                                        <Button 
                                            type="submit" 
                                            className="w-[100px]"
                                            disabled={isSubmitting}
                                        >
                                            {isSubmitting ? "Creating..." : "Create"}
                                        </Button>
                                    </div>
                                </form>
                            }
                        />
                    </div>
                </form>
            </Form>
        </div>
    );
}

export default AddOrdinancePage;
