# Generated by Django 5.2 on 2025-06-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('file', '0001_initial'),
        ('profiling', '0001_initial'),
        ('treasurer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bus_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_gross_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_province', models.CharField(max_length=100)),
                ('bus_city', models.CharField(max_length=100)),
                ('bus_barangay', models.CharField(max_length=100)),
                ('bus_street', models.CharField(max_length=200)),
                ('bus_respondentLname', models.CharField(max_length=100)),
                ('bus_respondentFname', models.CharField(max_length=100)),
                ('bus_respondentMname', models.CharField(max_length=100)),
                ('bus_respondentSex', models.CharField(max_length=10)),
                ('bus_respondentDob', models.DateField()),
                ('bus_date_registered', models.DateField()),
                ('sitio_id', models.CharField(max_length=10)),
                ('staff_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPermitRequest',
            fields=[
                ('bpr_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('req_pay_method', models.CharField(max_length=50)),
                ('req_request_date', models.DateField()),
                ('req_claim_date', models.DateField()),
                ('req_transac_id', models.CharField(default='None', max_length=100)),
                ('req_sales_proof', models.CharField(max_length=100)),
                ('req_status', models.CharField(default='Pending', max_length=100)),
                ('req_payment_status', models.CharField(default='Unpaid', max_length=100)),
                ('ags_id', models.ForeignKey(db_column='ags_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_permits', to='treasurer.annual_gross_sales')),
                ('business', models.ForeignKey(db_column='bus_id', on_delete=django.db.models.deletion.CASCADE, related_name='permit_requests', to='clerk.business')),
                ('pr_id', models.ForeignKey(db_column='pr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_permits', to='treasurer.purpose_and_rate')),
                ('ra_id', models.ForeignKey(db_column='ra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_business_permits', to='administration.staff')),
                ('staff_id', models.ForeignKey(db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_business_permits', to='administration.staff')),
            ],
            options={
                'db_table': 'business_permit_request',
            },
        ),
        migrations.CreateModel(
            name='ClerkCertificate',
            fields=[
                ('cr_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('req_pay_method', models.CharField(max_length=50)),
                ('req_request_date', models.DateField()),
                ('req_claim_date', models.DateField()),
                ('req_transac_id', models.CharField(default='None', max_length=100)),
                ('req_type', models.CharField(max_length=100)),
                ('req_status', models.CharField(default='Pending', max_length=100)),
                ('req_payment_status', models.CharField(default='Unpaid', max_length=100)),
                ('pr_id', models.ForeignKey(db_column='pr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='treasurer.purpose_and_rate')),
                ('ra_id', models.ForeignKey(db_column='ra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_certificates', to='administration.staff')),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile')),
                ('staff_id', models.ForeignKey(db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_certificates', to='administration.staff')),
            ],
            options={
                'db_table': 'certification_request',
            },
        ),
        migrations.CreateModel(
            name='IssuedBusinessPermit',
            fields=[
                ('ibp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ibp_date_of_issuance', models.DateField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('permit_request', models.ForeignKey(db_column='bpr_id', on_delete=django.db.models.deletion.CASCADE, to='clerk.businesspermitrequest')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'issued_business_permit',
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('ic_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ic_date_of_issuance', models.DateField()),
                ('certificate', models.ForeignKey(db_column='cr_id', on_delete=django.db.models.deletion.CASCADE, to='clerk.clerkcertificate')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'issued_certificate',
            },
        ),
    ]
