# Generated by Django 5.2 on 2025-12-13 19:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_staff_rp'),
        ('complaint', '0001_initial'),
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bus_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_gross_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_location', models.CharField(max_length=255)),
                ('bus_status', models.CharField(max_length=50)),
                ('bus_date_of_registration', models.DateField()),
                ('bus_date_verified', models.DateField()),
                ('staff_id', models.CharField(max_length=50, null=True)),
                ('rp_id', models.CharField(max_length=50, null=True)),
                ('br_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPermitRequest',
            fields=[
                ('bpr_id', models.CharField(primary_key=True, serialize=False)),
                ('req_request_date', models.DateField()),
                ('req_status', models.CharField(default='Pending', max_length=100)),
                ('req_date_completed', models.DateField(blank=True, null=True)),
                ('req_payment_status', models.CharField(default='Unpaid', max_length=100)),
                ('req_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_permit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bus_permit_address', models.CharField(blank=True, max_length=500, null=True)),
                ('bus_clearance_gross_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bus_nonresident_name', models.TextField(blank=True, null=True)),
                ('bus_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_permit_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClerkCertificate',
            fields=[
                ('cr_id', models.CharField(primary_key=True, serialize=False)),
                ('cr_req_request_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cr_req_status', models.CharField(default='None', max_length=100)),
                ('cr_req_payment_status', models.CharField(default='None', max_length=100)),
                ('cr_date_completed', models.DateTimeField(blank=True, null=True)),
                ('cr_date_rejected', models.DateTimeField(blank=True, null=True)),
                ('cr_reason', models.CharField(default='None', max_length=500)),
            ],
            options={
                'db_table': 'certification_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssuedBusinessPermit',
            fields=[
                ('ibp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ibp_date_of_issuance', models.DateField()),
            ],
            options={
                'db_table': 'issued_business_permit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('ic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ic_date_of_issuance', models.DateField()),
            ],
            options={
                'db_table': 'issued_certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonResidentCertificateRequest',
            fields=[
                ('nrc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nrc_req_date', models.DateTimeField(default=datetime.datetime.now)),
                ('nrc_req_status', models.CharField(default='None', max_length=100)),
                ('nrc_req_payment_status', models.CharField(default='None', max_length=100)),
                ('nrc_pay_date', models.DateTimeField(blank=True, null=True)),
                ('nrc_lname', models.CharField(max_length=500)),
                ('nrc_fname', models.CharField(max_length=500)),
                ('nrc_mname', models.CharField(max_length=500)),
                ('nrc_address', models.CharField(max_length=500)),
                ('nrc_birthdate', models.DateField(default=datetime.date.today)),
                ('nrc_date_completed', models.DateTimeField(blank=True, null=True)),
                ('nrc_date_rejected', models.DateTimeField(blank=True, null=True)),
                ('nrc_reason', models.CharField(default='None', max_length=500)),
                ('nrc_discount_reason', models.TextField(default='None')),
            ],
            options={
                'db_table': 'nonresident_cert_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummonCase',
            fields=[
                ('sc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sc_code', models.CharField(max_length=200, unique=True)),
                ('sc_mediation_status', models.CharField(max_length=500)),
                ('sc_conciliation_status', models.CharField(blank=True, max_length=500, null=True)),
                ('sc_date_marked', models.DateTimeField(blank=True, null=True)),
                ('sc_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'summon_case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummonDateAvailability',
            fields=[
                ('sd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sd_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'summon_date_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummonTimeAvailability',
            fields=[
                ('st_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_start_time', models.TimeField()),
                ('st_is_booked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'summon_time_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClerkBusinessPermit',
            fields=[
                ('busi_req_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('busi_name', models.CharField(max_length=50)),
                ('busi_add', models.CharField(max_length=50)),
                ('busi_gross_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('busi_pay_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20)),
                ('busi_date_req', models.DateField()),
                ('busi_date_claim', models.DateField()),
            ],
            options={
                'db_table': 'clerk_business_permit',
            },
        ),
        migrations.CreateModel(
            name='DocumentsPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clerk_pdf_documents',
            },
        ),
        migrations.CreateModel(
            name='BusinessPermitFile',
            fields=[
                ('bpf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bpf_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bpf_url', models.CharField(max_length=500)),
                ('bpr_id', models.ForeignKey(db_column='bpr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permit_files', to='clerk.businesspermitrequest')),
            ],
            options={
                'db_table': 'business_permit_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HearingSchedule',
            fields=[
                ('hs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hs_level', models.CharField(max_length=500)),
                ('hs_is_closed', models.BooleanField(default=False)),
                ('sc_id', models.ForeignKey(blank=True, db_column='sc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_schedules', to='clerk.summoncase')),
                ('sd_id', models.ForeignKey(blank=True, db_column='sd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_schedules', to='clerk.summondateavailability')),
                ('st_id', models.ForeignKey(blank=True, db_column='st_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_schedules', to='clerk.summontimeavailability')),
            ],
            options={
                'db_table': 'hearing_schedule',
            },
        ),
        migrations.CreateModel(
            name='HearingMinutes',
            fields=[
                ('hm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hm_name', models.CharField(max_length=255)),
                ('hm_type', models.CharField(blank=True, max_length=100, null=True)),
                ('hm_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hm_url', models.CharField(max_length=500)),
                ('hs_id', models.ForeignKey(blank=True, db_column='hs_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_minutes', to='clerk.hearingschedule')),
            ],
            options={
                'db_table': 'hearing_minutes',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('rem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rem_remarks', models.TextField()),
                ('rem_date', models.DateTimeField(default=datetime.datetime.now)),
                ('hs_id', models.OneToOneField(blank=True, db_column='hs_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remark', to='clerk.hearingschedule')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'remark',
            },
        ),
        migrations.CreateModel(
            name='RemarkSuppDocs',
            fields=[
                ('rsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rsd_name', models.CharField(max_length=255)),
                ('rsd_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rsd_path', models.CharField(blank=True, max_length=500, null=True)),
                ('rsd_url', models.CharField(max_length=500)),
                ('rem_id', models.ForeignKey(blank=True, db_column='rem_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_documents', to='clerk.remark')),
            ],
            options={
                'db_table': 'remark_supp_docs',
            },
        ),
        migrations.CreateModel(
            name='ServiceChargePaymentRequest',
            fields=[
                ('pay_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('pay_sr_type', models.CharField(max_length=200)),
                ('pay_status', models.CharField(default='Unpaid', max_length=200)),
                ('pay_date_req', models.DateTimeField(default=datetime.datetime.now)),
                ('pay_due_date', models.DateField(default=datetime.date(2025, 12, 20))),
                ('pay_req_status', models.CharField(default='Pending', max_length=200)),
                ('pay_date_paid', models.DateTimeField(blank=True, null=True)),
                ('pay_reason', models.TextField(blank=True, default=None, null=True)),
                ('comp_id', models.ForeignKey(db_column='comp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_charge_payments', to='complaint.complaint')),
                ('pr_id', models.ForeignKey(blank=True, db_column='pr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='treasurer.purpose_and_rates')),
            ],
            options={
                'db_table': 'service_charge_payment_request',
            },
        ),
    ]
