# Generated by Django 5.2 on 2025-12-20 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargepaymentrequest',
            name='pay_due_date',
            field=models.DateField(default=datetime.date(2025, 12, 27)),
        ),
    ]
