# Generated by Django 5.1.7 on 2025-06-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkBusinessPermit',
            fields=[
                ('busi_req_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('busi_name', models.CharField(max_length=50)),
                ('busi_add', models.CharField(max_length=50)),
                ('busi_gross_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('busi_pay_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20)),
                ('busi_date_req', models.DateField()),
                ('busi_date_claim', models.DateField()),
            ],
            options={
                'db_table': 'clerk_business_permit',
            },
        ),
        migrations.CreateModel(
            name='DocumentsPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clerk_pdf_documents',
            },
        ),
    ]
