# Generated by Django 5.2 on 2025-08-28 07:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('clerk', '0001_initial'),
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonResidentCertificateRequest',
            fields=[
                ('nrc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc_req_date', models.DateField()),
                ('nrc_req_status', models.CharField(default='None', max_length=100)),
                ('nrc_req_payment_status', models.CharField(default='None', max_length=100)),
                ('nrc_pay_date', models.DateTimeField(blank=True, null=True)),
                ('nrc_requester', models.CharField(max_length=500)),
                ('nrc_address', models.CharField(max_length=500)),
                ('nrc_birthdate', models.DateField(default=datetime.date.today)),
                ('pr_id', models.ForeignKey(db_column='pr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonresident_certificates', to='treasurer.purpose_and_rates')),
                ('staff_id', models.ForeignKey(db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'nonresident_cert_req',
            },
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='nonresidentcert',
            field=models.ForeignKey(db_column='nrc_id', default='', on_delete=django.db.models.deletion.CASCADE, to='clerk.nonresidentcertificaterequest'),
            preserve_default=False,
        ),
    ]
