# Generated by Django 5.2 on 2025-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('inv_serial_num', models.CharField(max_length=100)),
                ('inv_date', models.CharField(default='Pending', max_length=20)),
                ('inv_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inv_nat_of_collection', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
    ]
