# Generated by Django 5.2.3 on 2025-06-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseactivity',
            name='caf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_file', to='clerk.caseactivityfile'),
        ),
    ]
