# Generated by Django 5.2 on 2025-12-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargepaymentrequest',
            name='pr_id',
            field=models.ForeignKey(blank=True, db_column='pr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='treasurer.purpose_and_rates'),
        ),
    ]
