# Generated by Django 5.1.7 on 2025-07-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('clerk', '0001_initial'),
        ('profiling', '__first__'),
        ('treasurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkcertificate',
            name='pr_id',
            field=models.ForeignKey(db_column='pr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='treasurer.purpose_and_rates'),
        ),
        migrations.AddField(
            model_name='clerkcertificate',
            name='ra_id',
            field=models.ForeignKey(db_column='ra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_certificates', to='administration.staff'),
        ),
        migrations.AddField(
            model_name='clerkcertificate',
            name='rp_id',
            field=models.ForeignKey(db_column='rp_id', on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='comp',
            field=models.ForeignKey(db_column='comp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clerk.complaint'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='parent_summon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_file_actions', to='clerk.servicechargerequest'),
        ),
        migrations.AddField(
            model_name='caseactivity',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='clerk.servicechargerequest'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='file_action_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_action', to='clerk.servicechargerequestfile'),
        ),
        migrations.AddField(
            model_name='caseactivity',
            name='srf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_file', to='clerk.servicechargerequestfile'),
        ),
    ]
