# Generated by Django 5.2 on 2025-12-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='businesspermitfile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='businesspermitrequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clerkcertificate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issuedbusinesspermit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issuedcertificate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nonresidentcertificaterequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='summoncase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='summondateavailability',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='summontimeavailability',
            options={'managed': False},
        ),
    ]
