# Generated by Django 5.2 on 2025-12-21 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_alter_servicechargepaymentrequest_pay_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargepaymentrequest',
            name='pay_due_date',
            field=models.DateField(default=datetime.date(2025, 12, 28)),
        ),
    ]
