# Generated by Django 5.2 on 2025-08-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_nonresidentcertificaterequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcertificate',
            name='certificate',
            field=models.ForeignKey(blank=True, db_column='cr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clerk.clerkcertificate'),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='nonresidentcert',
            field=models.ForeignKey(blank=True, db_column='nrc_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clerk.nonresidentcertificaterequest'),
        ),
    ]
