# Generated by Django 5.1.7 on 2025-06-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_clerkbusinesspermit_documentspdf'),
        ('profiling', '0002_remove_personal_per_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkcertificate',
            name='rp_id',
            field=models.ForeignKey(db_column='rp_id', on_delete=django.db.models.deletion.CASCADE, to='profiling.residentprofile'),
        ),
    ]
