# Generated by Django 5.2.3 on 2025-07-13 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSuppDoc',
            fields=[
                ('csd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('csd_name', models.CharField(max_length=255)),
                ('csd_type', models.CharField(max_length=100)),
                ('csd_path', models.CharField(max_length=500)),
                ('csd_url', models.CharField(max_length=500)),
                ('csd_description', models.TextField()),
                ('csd_upload_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ca_id', models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clerk.caseactivity')),
            ],
            options={
                'db_table': 'case_activity_supp_doc',
            },
        ),
    ]
