# Generated by Django 5.2.3 on 2025-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_alter_caseactivity_caf'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
