# Generated by Django 5.1.7 on 2025-06-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('clerk', '0003_alter_clerkcertificate_rp_id'),
        ('treasurer', '0027_alter_disbursement_image_disf_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkcertificate',
            name='pr_id',
            field=models.ForeignKey(db_column='pr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='treasurer.purpose_and_rates'),
        ),
        migrations.AddField(
            model_name='clerkcertificate',
            name='ra_id',
            field=models.ForeignKey(db_column='ra_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_certificates', to='administration.staff'),
        ),
    ]
