# Generated by Django 5.2.3 on 2025-07-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0003_casesuppdoc'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='accused',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complainant',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaint',
        #     options={},
        # ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        # migrations.AlterField(
        #     model_name='casesuppdoc',
        #     name='ca_id',
        #     field=models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='clerk.caseactivity'),
        # ),
    ]
