# Generated by Django 5.2 on 2025-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0003_alter_issuedcertificate_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkcertificate',
            name='cr_date_completed',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
