# Generated by Django 5.2.3 on 2025-07-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0003_servicechargerequest_sr_decision_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseActivityFile',
            new_name='ServiceChargeRequestFile',
        ),
        migrations.RenameField(
            model_name='caseactivity',
            old_name='caf',
            new_name='srf',
        ),
        migrations.RenameField(
            model_name='servicechargerequestfile',
            old_name='caf_id',
            new_name='srf_id',
        ),
        migrations.RenameField(
            model_name='servicechargerequestfile',
            old_name='caf_name',
            new_name='srf_name',
        ),
        migrations.RenameField(
            model_name='servicechargerequestfile',
            old_name='caf_path',
            new_name='srf_path',
        ),
        migrations.RenameField(
            model_name='servicechargerequestfile',
            old_name='caf_type',
            new_name='srf_type',
        ),
        migrations.RenameField(
            model_name='servicechargerequestfile',
            old_name='caf_url',
            new_name='srf_url',
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='parent_summon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_file_actions', to='clerk.servicechargerequest'),
        ),
        migrations.AlterField(
            model_name='servicechargerequest',
            name='file_action_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_action', to='clerk.servicechargerequestfile'),
        ),
        migrations.AlterModelTable(
            name='servicechargerequestfile',
            table='service_charge_request_file',
        ),
    ]
