# Generated by Django 5.2 on 2025-07-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_invoice'),
        ('clerk', '0004_remove_clerkcertificate_req_bsnss_address_and_more'),
        ('clerk', '0004_rename_caseactivityfile_servicechargerequestfile_and_more'),
    ]

    operations = [
    ]
