# Generated by Django 4.2.20 on 2025-07-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_remove_complaint_comp_category_accused_acsd_age_and_more'),
        ('clerk', '0004_rename_caseactivityfile_servicechargerequestfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargerequest',
            name='comp',
            field=models.ForeignKey(db_column='comp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint.complaint'),
        ),
    ]
