# Generated by Django 5.2 on 2025-08-28 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0004_clerkcertificate_cr_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkcertificate',
            name='cr_date_rejected',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='clerkcertificate',
            name='cr_reason',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='nonresidentcertificaterequest',
            name='nrc_date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonresidentcertificaterequest',
            name='nrc_date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonresidentcertificaterequest',
            name='nrc_reason',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='clerkcertificate',
            name='cr_req_request_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='nonresidentcertificaterequest',
            name='nrc_req_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
