# Generated by Django 5.2.3 on 2025-07-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0004_alter_accused_options_alter_complainant_options_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='accused',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complainant',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaint',
        #     options={},
        # ),
        # migrations.AlterField(
        #     model_name='casesuppdoc',
        #     name='ca_id',
        #     field=models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='clerk.caseactivity'),
        # ),
        migrations.AlterField(
            model_name='servicechargerequestfile',
            name='srf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicechargerequestfile',
            name='srf_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
