# Generated by Django 4.2.20 on 2025-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0005_alter_servicechargerequest_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
