# Generated by Django 5.2 on 2025-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0005_clerkcertificate_cr_date_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkcertificate',
            name='cr_date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
