# Generated by Django 5.2 on 2025-08-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0006_alter_clerkcertificate_cr_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkcertificate',
            name='cr_pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
