# Generated by Django 5.2.3 on 2025-07-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0006_alter_accused_options_alter_complainant_options_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='accused',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complainant',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaint',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaint_file',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaintaccused',
        #     options={},
        # ),
        migrations.RemoveField(
            model_name='caseactivity',
            name='ca_pdf_file',
        ),
        # migrations.AlterField(
        #     model_name='casesuppdoc',
        #     name='ca_id',
        #     field=models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='clerk.caseactivity'),
        # ),
        # migrations.CreateModel(
        #     name='ComplaintComplainant',
        #     fields=[
        #         ('cc_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.complaint')),
        #         ('cpnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.complainant')),
        #     ],
        #     options={
        #         'db_table': 'complaint_complainant',
        #         'unique_together': {('comp', 'cpnt')},
        #     },
        # ),
    ]
