# Generated by Django 5.2 on 2025-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0007_clerkcertificate_cr_pay_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerkcertificate',
            old_name='cr_pay_date',
            new_name='cr_date_accepted',
        ),
        migrations.RemoveField(
            model_name='clerkcertificate',
            name='cr_req_payment_status',
        ),
        migrations.AddField(
            model_name='clerkcertificate',
            name='cr_date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clerkcertificate',
            name='cr_date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
