# Generated by Django 5.2.3 on 2025-07-31 04:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0008_alter_accused_options_alter_complainant_options_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ComplaintComplainant',
        #     fields=[
        #         ('cc_id', models.BigAutoField(primary_key=True, serialize=False)),
        #     ],
        #     options={
        #         'db_table': 'complaint_complainant',
        #     },
        # ),
        migrations.CreateModel(
            name='SummonDateAvailability',
            fields=[
                ('sd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sd_date', models.DateField(default=datetime.date.today)),
                ('sd_is_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'summon_date_availability',
            },
        ),
        # migrations.DeleteModel(
        #     name='Complaint_File',
        # ),
        # migrations.AlterModelOptions(
        #     name='accused',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complainant',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaint',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaintaccused',
        #     options={},
        # ),
        # migrations.AlterField(
        #     model_name='casesuppdoc',
        #     name='ca_id',
        #     field=models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='clerk.caseactivity'),
        # ),
        # migrations.AddField(
        #     model_name='complaintcomplainant',
        #     name='comp',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.complaint'),
        # ),
        # migrations.AddField(
        #     model_name='complaintcomplainant',
        #     name='cpnt',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.complainant'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='complaintcomplainant',
        #     unique_together={('comp', 'cpnt')},
        # ),
    ]
