# Generated by Django 5.2 on 2025-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0008_rename_cr_pay_date_clerkcertificate_cr_date_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerkcertificate',
            name='cr_date_accepted',
        ),
        migrations.RemoveField(
            model_name='clerkcertificate',
            name='cr_date_cancelled',
        ),
        migrations.RemoveField(
            model_name='clerkcertificate',
            name='cr_date_rejected',
        ),
        migrations.RemoveField(
            model_name='clerkcertificate',
            name='cr_reason',
        ),
        migrations.RemoveField(
            model_name='nonresidentcertificaterequest',
            name='nrc_date_completed',
        ),
        migrations.RemoveField(
            model_name='nonresidentcertificaterequest',
            name='nrc_date_rejected',
        ),
        migrations.RemoveField(
            model_name='nonresidentcertificaterequest',
            name='nrc_reason',
        ),
        migrations.AddField(
            model_name='clerkcertificate',
            name='cr_req_payment_status',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='clerkcertificate',
            name='cr_date_completed',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='clerkcertificate',
            name='cr_req_request_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nonresidentcertificaterequest',
            name='nrc_req_date',
            field=models.DateField(),
        ),
    ]
