# Generated by Django 5.2 on 2025-08-11 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0011_complaintcomplainant_delete_complaint_file_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ComplaintComplainant',
        #     fields=[
        #         ('cc_id', models.BigAutoField(primary_key=True, serialize=False)),
        #     ],
        #     options={
        #         'db_table': 'complaint_complainant',
        #     },
        # ),
        migrations.CreateModel(
            name='SummonTimeAvailability',
            fields=[
                ('st_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_start_time', models.TimeField()),
                ('st_end_time', models.TimeField()),
            ],
            options={
                'db_table': 'summon_time_availability',
            },
        ),
        # migrations.DeleteModel(
        #     name='Complaint_File',
        # ),
        # migrations.AlterModelOptions(
        #     name='accused',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complainant',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaint',
        #     options={},
        # ),
        # migrations.AlterModelOptions(
        #     name='complaintaccused',
        #     options={},
        # ),
        migrations.RemoveField(
            model_name='summondateavailability',
            name='sd_time',
        ),
        # migrations.AlterField(
        #     model_name='casesuppdoc',
        #     name='ca_id',
        #     field=models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='clerk.caseactivity'),
        # ),
        # migrations.AddField(
        #     model_name='complaintcomplainant',
        #     name='comp',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.complaint'),
        # ),
        # migrations.AddField(
        #     model_name='complaintcomplainant',
        #     name='cpnt',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.complainant'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='complaintcomplainant',
        #     unique_together={('comp', 'cpnt')},
        # ),
    ]
