# Generated by Django 5.2 on 2025-08-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0012_complaintcomplainant_summontimeavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summontimeavailability',
            name='sd_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='clerk.summondateavailability'),
            preserve_default=False,
        ),
    ]
