# Generated by Django 5.2 on 2025-08-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0013_complaintcomplainant_delete_complaint_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summontimeavailability',
            name='st_is_booked',
            field=models.BooleanField(default=False),
        ),
        
    ]
