# Generated by Django 5.2 on 2025-08-15 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0014_complaintcomplainant_delete_complaint_file_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='summondateavailability',
            name='sd_is_checked',
            field=models.BooleanField(default=True),
        ),
    ]
