# Generated by Django 5.2 on 2025-08-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0015_complaintcomplainant_delete_complaint_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summondateavailability',
            name='sd_is_checked',
        ),
    ]
