# Generated by Django 5.2 on 2025-08-26 10:09

import datetime
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def _current_time():
    return timezone.now().time()


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('clerk', '0016_complaintcomplainant_delete_complaint_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReschedLogSuppDoc',
            fields=[
                ('rsd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rsd_name', models.CharField(max_length=255)),
                ('rsd_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rsd_path', models.CharField(blank=True, max_length=500, null=True)),
                ('rsd_url', models.CharField(max_length=500)),
                ('rsd_description', models.CharField(default='None', max_length=500)),
                ('rsd_upload_date', models.DateTimeField(default=datetime.date(2025, 8, 26))),
            ],
            options={
                'db_table': 'reschedule_log_supp_doc',
            },
        ),
        migrations.CreateModel(
            name='RescheduleLog',
            fields=[
                ('rsl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rsl_prev_date', models.DateField(default=datetime.date(2025, 8, 26))),
                ('rsl_prev_time', models.TimeField(default=_current_time)),
                ('rsl_reason', models.CharField(default='None')),
                ('rsl_date_marked', models.DateTimeField(default=datetime.date(2025, 8, 26))),
            ],
            options={
                'db_table': 'reschedule_log',
            },
        ),
        migrations.CreateModel(
            name='ServiceChargePaymentRequest',
            fields=[
                ('pay_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_status', models.CharField(default='Unpaid')),
                ('pay_due_date', models.DateField(default=datetime.date(2025, 8, 26))),
                ('pay_date_paid', models.DateTimeField(default=datetime.datetime(2025, 8, 26, 18, 7, 48, 143919))),
            ],
            options={
                'db_table': 'service_charge_payment_request',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('ses_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ses_case_status', models.CharField(default='Ongoing')),
                ('sd_id', models.ForeignKey(blank=True, db_column='sd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clerk.summondateavailability')),
                ('st_id', models.ForeignKey(blank=True, db_column='st_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clerk.summontimeavailability')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.RemoveField(
            model_name='caseactivity',
            name='sr',
        ),
        migrations.RemoveField(
            model_name='caseactivity',
            name='srf',
        ),
        migrations.RemoveField(
            model_name='casesuppdoc',
            name='ca_id',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='file_action_file',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='parent_summon',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='sr_code',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='sr_payment_status',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='sr_req_date',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='sr_status',
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='comp_id',
            field=models.ForeignKey(db_column='comp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clerk.complaint'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_descision_reason',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_req_status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='staff_id',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AlterField(
            model_name='servicechargerequest',
            name='sr_decision_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 18, 7, 48, 141920)),
        ),
        migrations.AlterField(
            model_name='servicechargerequest',
            name='sr_type',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='reschedlogsuppdoc',
            name='rsl_id',
            field=models.ForeignKey(db_column='rsl_id', on_delete=django.db.models.deletion.CASCADE, to='clerk.reschedulelog'),
        ),
        migrations.AddField(
            model_name='servicechargepaymentrequest',
            name='sr_id',
            field=models.ForeignKey(blank=True, db_column='sr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clerk.servicechargerequest'),
        ),
        migrations.AddField(
            model_name='reschedulelog',
            name='ses_id',
            field=models.ForeignKey(db_column='ses_id', on_delete=django.db.models.deletion.CASCADE, to='clerk.session'),
        ),
        migrations.DeleteModel(
            name='CaseActivity',
        ),
        migrations.DeleteModel(
            name='CaseSuppDoc',
        ),
        migrations.DeleteModel(
            name='ServiceChargeRequestFile',
        ),
    ]
