# Generated by Django 5.2 on 2025-08-26 10:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('clerk', '0017_complaintcomplainant_reschedlogsuppdoc_reschedulelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sr_id',
            field=models.ForeignKey(blank=True, db_column='sr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clerk.servicechargerequest'),
        ),
        migrations.AlterField(
            model_name='reschedlogsuppdoc',
            name='rsd_upload_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reschedulelog',
            name='rsl_date_marked',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reschedulelog',
            name='rsl_prev_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicechargepaymentrequest',
            name='pay_date_paid',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='servicechargepaymentrequest',
            name='pay_due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicechargerequest',
            name='sr_decision_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
