# Generated by Django 5.2 on 2025-08-27 08:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_position_pos_group'),
        ('clerk', '0018_complaintcomplainant_delete_complaint_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('ca_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ca_reason', models.CharField(max_length=100)),
                ('ca_hearing_date', models.DateField()),
                ('ca_hearing_time', models.TimeField()),
                ('ca_mediation', models.CharField()),
                ('ca_date_of_issuance', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'case_activity',
            },
        ),
        migrations.CreateModel(
            name='CaseSuppDoc',
            fields=[
                ('csd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('csd_name', models.CharField(max_length=255)),
                ('csd_type', models.CharField(max_length=100)),
                ('csd_path', models.CharField(max_length=500)),
                ('csd_url', models.CharField(max_length=500)),
                ('csd_description', models.TextField()),
                ('csd_upload_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'case_activity_supp_doc',
            },
        ),
        migrations.CreateModel(
            name='ServiceChargeRequestFile',
            fields=[
                ('srf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('srf_name', models.CharField(max_length=255)),
                ('srf_type', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('srf_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'service_charge_request_file',
            },
        ),
        migrations.RemoveField(
            model_name='reschedlogsuppdoc',
            name='rsl_id',
        ),
        migrations.RemoveField(
            model_name='reschedulelog',
            name='ses_id',
        ),
        migrations.RemoveField(
            model_name='servicechargepaymentrequest',
            name='sr_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sd_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sr_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='st_id',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='sr_descision_reason',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='sr_req_status',
        ),
        migrations.RemoveField(
            model_name='servicechargerequest',
            name='staff_id',
        ),

        migrations.AddField(
            model_name='servicechargerequest',
            name='comp',
            field=models.ForeignKey(db_column='comp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clerk.complaint'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='parent_summon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_file_actions', to='clerk.servicechargerequest'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_payment_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_req_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='sr_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicechargerequest',
            name='sr_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicechargerequest',
            name='sr_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseactivity',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='clerk.servicechargerequest'),
        ),
        migrations.AddField(
            model_name='casesuppdoc',
            name='ca_id',
            field=models.ForeignKey(db_column='ca_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='clerk.caseactivity'),
        ),
        migrations.AddField(
            model_name='caseactivity',
            name='srf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_file', to='clerk.servicechargerequestfile'),
        ),
        migrations.AddField(
            model_name='servicechargerequest',
            name='file_action_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_action', to='clerk.servicechargerequestfile'),
        ),
        migrations.DeleteModel(
            name='ReschedLogSuppDoc',
        ),
        migrations.DeleteModel(
            name='RescheduleLog',
        ),
        migrations.DeleteModel(
            name='ServiceChargePaymentRequest',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
