# Generated by Django 5.1.6 on 2025-12-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('inventory', '__first__'),
        ('patientrecords', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidRecord',
            fields=[
                ('farec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField(blank=True, default='', null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('finv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_aid_records', to='inventory.firstaidinventory')),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_aid_records', to='patientrecords.patientrecord')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_aid_records', to='administration.staff')),
            ],
            options={
                'db_table': 'firstaid_record',
            },
        ),
    ]
