# Generated by Django 5.1.6 on 2025-12-15 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('healthProfiling', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('medreq_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='walk-in', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('patrec', models.ForeignKey(blank=True, db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to='patientrecords.patientrecord')),
                ('rp_id', models.ForeignKey(blank=True, db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to='healthProfiling.residentprofile')),
                ('trans_id', models.ForeignKey(blank=True, db_column='trans_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to='patientrecords.transient')),
            ],
            options={
                'db_table': 'medicine_request',
            },
        ),
        migrations.CreateModel(
            name='Medicine_File',
            fields=[
                ('medf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medf_name', models.CharField(max_length=255)),
                ('medf_type', models.CharField(max_length=100)),
                ('medf_path', models.CharField(max_length=500)),
                ('medf_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medreq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_files', to='medicineservices.medicinerequest')),
            ],
            options={
                'db_table': 'medicine_file',
            },
        ),
        migrations.CreateModel(
            name='FindingsPlanTreatment',
            fields=[
                ('fpt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings_plan_treatments', to='patientrecords.finding')),
                ('medreq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings_plan_treatments', to='medicineservices.medicinerequest')),
            ],
            options={
                'db_table': 'findings_plan_treatment',
            },
        ),
        migrations.CreateModel(
            name='MedicineRequestItem',
            fields=[
                ('medreqitem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_rejected_reffered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, db_column='action_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_request_items_action', to='administration.staff')),
                ('completed_by', models.ForeignKey(blank=True, db_column='completed_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_request_items_completed', to='administration.staff')),
                ('med', models.ForeignKey(blank=True, db_column='med_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_request_items', to='inventory.medicinelist')),
                ('medreq_id', models.ForeignKey(db_column='medreq_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicineservices.medicinerequest')),
            ],
            options={
                'db_table': 'medicine_request_item',
            },
        ),
        migrations.CreateModel(
            name='MedicineAllocation',
            fields=[
                ('alloc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allocated_qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicineinventory')),
                ('medreqitem', models.ForeignKey(db_column='medreqitem_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='medicineservices.medicinerequestitem')),
            ],
            options={
                'db_table': 'medicine_request_allocation',
            },
        ),
        migrations.CreateModel(
            name='MedicineRecord',
            fields=[
                ('medrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medrec_qty', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('minv_id', models.ForeignKey(db_column='minv_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='inventory.medicineinventory')),
                ('patrec_id', models.ForeignKey(blank=True, db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='patientrecords.patientrecord')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='administration.staff')),
                ('medreq_id', models.ForeignKey(blank=True, db_column='medreq_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='medicineservices.medicinerequest')),
                ('medreqitem_id', models.ForeignKey(blank=True, db_column='medreqitem_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='medicineservices.medicinerequestitem')),
            ],
            options={
                'db_table': 'medicine_record',
                'indexes': [models.Index(fields=['patrec_id'], name='medicine_re_patrec__f24bdd_idx'), models.Index(fields=['minv_id'], name='medicine_re_minv_id_ceb850_idx')],
            },
        ),
    ]
