# Generated by Django 5.2 on 2025-11-24 17:40

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '__first__'),
        ('healthProfiling', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('ill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('illname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ill_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ill_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'illness',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('lab_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_cbc', models.BooleanField(default=False, verbose_name='Complete Blood Count')),
                ('is_urinalysis', models.BooleanField(default=False, verbose_name='Urinalysis')),
                ('is_fecalysis', models.BooleanField(default=False, verbose_name='Fecalysis')),
                ('is_sputum_microscopy', models.BooleanField(default=False, verbose_name='Sputum Microscopy')),
                ('is_creatine', models.BooleanField(default=False, verbose_name='Creatinine')),
                ('is_hba1c', models.BooleanField(default=False, verbose_name='HbA1c')),
                ('is_chestxray', models.BooleanField(default=False, verbose_name='Chest X-ray')),
                ('is_papsmear', models.BooleanField(default=False, verbose_name='Pap Smear')),
                ('is_fbs', models.BooleanField(default=False, verbose_name='Fasting Blood Sugar')),
                ('is_oralglucose', models.BooleanField(default=False, verbose_name='Oral Glucose Tolerance Test')),
                ('is_lipidprofile', models.BooleanField(default=False, verbose_name='Lipid Profile')),
                ('is_fecal_occult_blood', models.BooleanField(default=False, verbose_name='Fecal Occult Blood')),
                ('is_ecg', models.BooleanField(default=False)),
                ('others', models.TextField(blank=True, null=True, verbose_name='Other Laboratory Tests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laboratory',
                'db_table': 'laboratory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListOfDisabilities',
            fields=[
                ('disability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disability_name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'list_of_disabilities',
                'ordering': ['disability_name'],
            },
        ),
        migrations.CreateModel(
            name='PEOption',
            fields=[
                ('pe_option_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'physical_exam_option',
            },
        ),
        migrations.CreateModel(
            name='PESection',
            fields=[
                ('pe_section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'physical_exam_section',
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('spouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spouse_type', models.CharField(max_length=10)),
                ('spouse_lname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('spouse_fname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('spouse_mname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spouse',
            },
        ),
        migrations.CreateModel(
            name='Transient',
            fields=[
                ('trans_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tran_lname', models.CharField(max_length=100)),
                ('tran_fname', models.CharField(max_length=100)),
                ('tran_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('tran_dob', models.DateField()),
                ('tran_sex', models.CharField(max_length=10)),
                ('tran_status', models.CharField(max_length=50)),
                ('tran_ed_attainment', models.CharField(max_length=100)),
                ('tran_religion', models.CharField(max_length=100)),
                ('tran_contact', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('philhealth_id', models.CharField(blank=True, max_length=12, null=True)),
                ('mother_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_age', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_dob', models.DateField(blank=True, null=True)),
                ('father_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_age', models.CharField(blank=True, max_length=100, null=True)),
                ('father_dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transient',
            },
        ),
        migrations.CreateModel(
            name='TransientAddress',
            fields=[
                ('tradd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tradd_province', models.CharField(max_length=50)),
                ('tradd_city', models.CharField(max_length=50)),
                ('tradd_barangay', models.CharField(max_length=50)),
                ('tradd_street', models.CharField(max_length=50)),
                ('tradd_sitio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'transient_address',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('find_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assessment_summary', models.TextField(blank=True, default='', null=True)),
                ('obj_summary', models.TextField(default='')),
                ('subj_summary', models.TextField(default='')),
                ('plantreatment_summary', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='patientrecords.laboratory')),
            ],
            options={
                'db_table': 'finding',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('medhist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ill_date', models.CharField(blank=True, default=2025, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('is_for_surveillance', models.BooleanField(default=False)),
                ('is_from_famhistory', models.BooleanField(default=False)),
                ('ill', models.ForeignKey(db_column='ill_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patientrecords.illness')),
            ],
            options={
                'db_table': 'medical_history',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('find', models.ForeignKey(db_column='find_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.finding')),
                ('medhist', models.ForeignKey(db_column='medhist_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.medicalhistory')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('pat_type', models.CharField(choices=[('Resident', 'Resident'), ('Transient', 'Transient')], default='Resident', max_length=100)),
                ('pat_status', models.CharField(default='Active', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_transferred_from', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rp_id', models.ForeignKey(blank=True, db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.residentprofile')),
                ('trans_id', models.ForeignKey(blank=True, db_column='trans_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patientrecords.transient')),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('bm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('wfa', models.CharField(blank=True, max_length=100, null=True)),
                ('lhfa', models.CharField(blank=True, max_length=100, null=True)),
                ('wfl', models.CharField(blank=True, max_length=100, null=True)),
                ('muac', models.CharField(blank=True, max_length=100, null=True)),
                ('edemaSeverity', models.CharField(default='None', max_length=100)),
                ('muac_status', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_opt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='administration.staff')),
                ('pat', models.ForeignKey(blank=True, db_column='pat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='patientrecords.patient')),
            ],
            options={
                'db_table': 'body_measurement',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('app_status', models.CharField(default='Pending', max_length=100)),
                ('app_reason', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('res_id', models.ForeignKey(blank=True, db_column='res_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='healthProfiling.residentprofile')),
                ('pat_id', models.ForeignKey(blank=True, db_column='pat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patientrecords.patient')),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['-app_date', '-app_time'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('patrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patrec_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pat_id', models.ForeignKey(db_column='pat_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='patientrecords.patient')),
            ],
            options={
                'db_table': 'patient_record',
                'ordering': ['-patrec_id'],
            },
        ),
        migrations.CreateModel(
            name='PatientDisablity',
            fields=[
                ('pd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolve', 'Resolve')], default='active', max_length=20)),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_disabilities', to='patientrecords.listofdisabilities')),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_disabilities', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'patient_disability_history',
            },
        ),
        migrations.CreateModel(
            name='Obstetrical_History',
            fields=[
                ('obs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obs_ch_born_alive', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_living_ch', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_abortion', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_still_birth', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_lg_babies', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_lg_babies_str', models.BooleanField(blank=True, null=True)),
                ('obs_gravida', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_para', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_fullterm', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_preterm', models.PositiveIntegerField(blank=True, null=True)),
                ('obs_lmp', models.DateField(blank=True, null=True)),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='obstetrical_history', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'obstetrical_history',
            },
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patrec',
            field=models.ForeignKey(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patientrecords.patientrecord'),
        ),
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('followv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('followv_date', models.DateField(blank=True, null=True)),
                ('followv_status', models.CharField(max_length=100)),
                ('followv_description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_visits', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'follow_up_visit',
            },
        ),
        migrations.CreateModel(
            name='PEResult',
            fields=[
                ('peres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('find', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pe_result', to='patientrecords.finding')),
                ('pe_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pe_result', to='patientrecords.peoption')),
            ],
            options={
                'db_table': 'physical_exam_result',
            },
        ),
        migrations.AddField(
            model_name='peoption',
            name='pe_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='patientrecords.pesection'),
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('pat_id', models.CharField(db_index=True, editable=False, max_length=15)),
                ('pat_type', models.CharField(choices=[('Resident', 'Resident'), ('Transient', 'Transient')], default='Resident', max_length=100)),
                ('pat_status', models.CharField(default='Active', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_transferred_from', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rp_id', models.ForeignKey(blank=True, db_column='rp_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='healthProfiling.residentprofile')),
                ('trans_id', models.ForeignKey(blank=True, db_column='trans_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patientrecords.transient')),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='transient',
            name='tradd_id',
            field=models.ForeignKey(blank=True, db_column='tradd_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transients', to='patientrecords.transientaddress'),
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vital_bp_systolic', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vital_bp_diastolic', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vital_temp', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vital_RR', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vital_o2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vital_pulse', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patrec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patientrecords.patientrecord')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='administration.staff')),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
    ]
