# Generated by Django 5.2.3 on 2025-06-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('healthProfiling', '0002_solid_waste_mgmt_remove_household_hh_barangay_and_more'),
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Finding',
        #     fields=[
        #         ('find_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('obj_description', models.TextField(default='')),
        #         ('subj_description', models.TextField(default='')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        #     options={
        #         'db_table': 'finding',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Illness',
        #     fields=[
        #         ('ill_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('illname', models.CharField(default='', max_length=100)),
        #         ('ill_description', models.CharField(default='N/A', max_length=200)),
        #         ('ill_code', models.CharField(default='N/A', max_length=100)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        #     options={
        #         'db_table': 'illness',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PhysicalExamList',
        #     fields=[
        #         ('pel_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('pel_system', models.CharField(default='', max_length=100)),
        #         ('pel_finding', models.TextField(default='')),
        #         ('is_other', models.BooleanField(default=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        #     options={
        #         'db_table': 'physical_exam_list',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='VitalSigns',
        #     fields=[
        #         ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('vital_bp_systolic', models.CharField(max_length=100)),
        #         ('vital_bp_diastolic', models.CharField(default='N/A', max_length=100)),
        #         ('vital_temp', models.CharField(default='N/A', max_length=100)),
        #         ('vital_RR', models.CharField(default='N/A', max_length=100)),
        #         ('vital_o2', models.CharField(default='N/A', max_length=100)),
        #         ('vital_pulse', models.CharField(default='N/A', max_length=100)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        #     options={
        #         'db_table': 'vital_signs',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='FollowUpVisit',
        #     fields=[
        #         ('followv_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('followv_date', models.DateField()),
        #         ('followv_status', models.CharField(max_length=100)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_visits', to='patientrecords.patientrecord')),
        #     ],
        #     options={
        #         'db_table': 'follow_up_visit',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Diagnosis',
        #     fields=[
        #         ('diag_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('find', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.finding')),
        #         ('ill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.illness')),
        #     ],
        #     options={
        #         'db_table': 'diagnosis',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Obstetrical_History',
        #     fields=[
        #         ('obs_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('obs_ch_born_alive', models.PositiveIntegerField()),
        #         ('obs_living_ch', models.PositiveIntegerField()),
        #         ('obs_abortion', models.PositiveIntegerField()),
        #         ('obs_still_birth', models.PositiveIntegerField()),
        #         ('obs_lg_babies', models.PositiveIntegerField()),
        #         ('obs_gravida', models.PositiveIntegerField()),
        #         ('obs_para', models.PositiveIntegerField()),
        #         ('obs_fullterm', models.PositiveIntegerField()),
        #         ('obs_preterm', models.PositiveIntegerField()),
        #         ('obs_record_from', models.CharField(max_length=100)),
        #         ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='obstetrical_history', to='patientrecords.patientrecord')),
        #     ],
        #     options={
        #         'db_table': 'obstetrical_history',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Patient',
        #     fields=[
        #         ('pat_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
        #         ('pat_type', models.CharField(default='Resident', max_length=100)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('pat_status', models.CharField(default='Active', max_length=100)),
        #         ('rp_id', models.ForeignKey(db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.residentprofile')),
        #     ],
        #     options={
        #         'db_table': 'patient',
        #         'ordering': ['-created_at'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='BodyMeasurement',
        #     fields=[
        #         ('bm_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('age', models.CharField(default='', max_length=100)),
        #         ('height', models.IntegerField()),
        #         ('weight', models.IntegerField()),
        #         ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
        #         ('bmi_category', models.CharField(max_length=100)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='patientrecords.patient')),
        #     ],
        #     options={
        #         'db_table': 'body_measurement',
        #     },
        # ),
        # migrations.AlterField(
        #     model_name='patientrecord',
        #     name='pat_id',
        #     field=models.ForeignKey(db_column='pat_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='patientrecords.patient'),
        # ),
        # migrations.CreateModel(
        #     name='PhysicalExamination',
        #     fields=[
        #         ('pe_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('find', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_examinations', to='patientrecords.finding')),
        #         ('pel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_examinations', to='patientrecords.physicalexamlist')),
        #     ],
        #     options={
        #         'db_table': 'physical_examination',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Spouse',
        #     fields=[
        #         ('spouse_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('spouse_type', models.CharField(max_length=10)),
        #         ('spouse_lname', models.CharField(default='', max_length=50)),
        #         ('spouse_fname', models.CharField(default='', max_length=50)),
        #         ('spouse_mnane', models.CharField(default='', max_length=50)),
        #         ('spouse_occupation', models.CharField(max_length=50)),
        #         ('spouse_dob', models.DateField()),
        #         ('rp_id', models.ForeignKey(db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='healthProfiling.residentprofile')),
        #     ],
        #     options={
        #         'db_table': 'spouse',
        #     },
        # ),
        # migrations.DeleteModel(
        #     name='Patients',
        # ),
    ]
