# Generated by Django 5.1.6 on 2025-04-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientRecord',
        ),
    ]
