# Generated by Django 5.2.3 on 2025-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0002_finding_illness_physicalexamlist_vitalsigns_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='spouse',
        #     name='spouse_mnane',
        # ),
        # migrations.AddField(
        #     model_name='spouse',
        #     name='spouse_mname',
        #     field=models.CharField(default='', max_length=50),
        # ),
    ]
