# Generated by Django 5.1.6 on 2025-06-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0002_solid_waste_mgmt_remove_household_hh_barangay_and_more'),
        ('patientrecords', '0002_finding_illness_physicalexamlist_vitalsigns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transient',
            fields=[
                ('trans_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tran_lname', models.CharField(max_length=100)),
                ('tran_fname', models.CharField(max_length=100)),
                ('tran_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('tran_dob', models.DateField()),
                ('tran_sex', models.CharField(max_length=10)),
                ('tran_status', models.CharField(max_length=50)),
                ('tran_ed_attainment', models.CharField(max_length=100)),
                ('tran_religion', models.CharField(max_length=100)),
                ('tran_contact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'transient',
            },
        ),
        migrations.CreateModel(
            name='TransientAddress',
            fields=[
                ('tradd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tradd_province', models.CharField(max_length=50)),
                ('tradd_city', models.CharField(max_length=50)),
                ('tradd_barangay', models.CharField(max_length=50)),
                ('tradd_street', models.CharField(max_length=50)),
                ('tradd_sitio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'transient_address',
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rp_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='resident_profile',
            field=models.ForeignKey(blank=True, db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.residentprofile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_type',
            field=models.CharField(choices=[('Resident', 'Resident'), ('Transient', 'Transient')], default='Resident', max_length=100),
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
        migrations.AddField(
            model_name='patient',
            name='trans_id',
            field=models.ForeignKey(blank=True, db_column='trans_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patientrecords.transient'),
        ),
        migrations.AddField(
            model_name='transient',
            name='tradd_id',
            field=models.ForeignKey(blank=True, db_column='tradd_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transients', to='patientrecords.transientaddress'),
        ),
    ]
