# Generated by Django 5.1.6 on 2025-06-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupvisit',
            old_name='follow_description',
            new_name='followv_description',
        ),
    ]
