# Generated by Django 5.1.6 on 2025-06-08 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0008_delete_patient_alter_residentprofile_rp_id'),
        ('patientrecords', '0002_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='per_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='rp_id',
            field=models.ForeignKey(db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.residentprofile'),
        ),
    ]
