# Generated by Django 5.1.6 on 2025-04-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0002_delete_patientrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('patrec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patrec_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='patientrecords.patients')),
            ],
            options={
                'db_table': 'patient_record',
                'ordering': ['-patrec_id'],
            },
        ),
    ]
