# Generated by Django 5.1.6 on 2025-06-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0003_transient_transientaddress_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
