# Generated by Django 5.1.6 on 2025-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0003_rename_follow_description_followupvisit_followv_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]