# Generated by Django 5.1.6 on 2025-04-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0003_patientrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='per_id',
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
