# Generated by Django 5.1.6 on 2025-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0004_alter_patient_options_alter_patient_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='resident_profile',
            new_name='rp_id',
        ),
    ]
