# Generated by Django 5.2.3 on 2025-06-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0002_solid_waste_mgmt_remove_household_hh_barangay_and_more'),
        ('patientrecords', '0004_finding_illness_physicalexamlist_spouse_vitalsigns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='rp_id',
            field=models.ForeignKey(db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='healthProfiling.residentprofile'),
        ),
    ]
