# Generated by Django 5.1.6 on 2025-04-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patients',
            table='patient',
        ),
    ]
