# Generated by Django 5.2.3 on 2025-06-12 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0005_spouse_rp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='pat_id',
            field=models.ForeignKey(db_column='pat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='patientrecords.patient'),
        ),
    ]
