# Generated by Django 5.2.3 on 2025-06-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0006_spouse_pat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spouse',
            name='pat_id',
        ),
    ]
