# Generated by Django 5.1.6 on 2025-04-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('healthProfiling', '0003_delete_patient'),
        ('patientrecords', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='per_id',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.personal'),
        ),
    ]
