# Generated by Django 5.1.6 on 2025-04-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0009_alter_patient_per_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='per_id',
            new_name='per',
        ),
    ]
