# Generated by Django 5.1.6 on 2025-04-19 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0003_delete_patient'),
        ('patientrecords', '0010_rename_per_id_patient_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.personal'),
        ),
    ]
