# Generated by Django 5.1.6 on 2025-04-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0013_alter_patient_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='per',
            new_name='per_id',
        ),
    ]
