# Generated by Django 5.1.6 on 2025-04-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0014_rename_per_patient_per_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='per_id',
        ),
    ]
