# Generated by Django 5.1.6 on 2025-04-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0003_delete_patient'),
        ('patientrecords', '0015_remove_patient_per_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='per_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.personal'),
            preserve_default=False,
        ),
    ]
