# Generated by Django 5.1.6 on 2025-04-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0017_alter_patient_per_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='pat_id',
            field=models.ForeignKey(db_column='pat_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='patientrecords.patient'),
        ),
    ]
