# Generated by Django 5.1.6 on 2025-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0018_alter_patientrecord_pat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vital_bp_systolic', models.CharField(max_length=100)),
                ('vital_bp_diastolic', models.CharField(max_length=100)),
                ('vital_temp', models.CharField(max_length=100)),
                ('vital_RR', models.CharField(max_length=100)),
                ('vital_o2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
    ]
