# Generated by Django 5.1.6 on 2025-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0019_vitalsigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('followv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('followv_date', models.DateTimeField()),
                ('followv_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'follow_up_visit',
            },
        ),
    ]
