# Generated by Django 5.1.6 on 2025-04-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0020_obstetrical_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obstetrical_History',
        ),
    ]
