# Generated by Django 5.1.6 on 2025-04-23 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0021_delete_obstetrical_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstetrical_History',
            fields=[
                ('obs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obs_ch_born_alive', models.PositiveIntegerField()),
                ('obs_living_ch', models.PositiveIntegerField()),
                ('obs_abortion', models.PositiveIntegerField()),
                ('obs_still_birth', models.PositiveIntegerField()),
                ('obs_lg_babies', models.PositiveIntegerField()),
                ('obs_gravida', models.PositiveIntegerField()),
                ('obs_para', models.PositiveIntegerField()),
                ('obs_fullterm', models.PositiveIntegerField()),
                ('obs_preterm', models.PositiveIntegerField()),
                ('obs_record_from', models.CharField(max_length=100)),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='obstetrical_history', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'obstetrical_history',
            },
        ),
    ]
