# Generated by Django 5.1.6 on 2025-04-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0021_followupvisit_patrec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupvisit',
            name='patrec',
        ),
    ]
