# Generated by Django 5.1.6 on 2025-04-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0022_remove_followupvisit_patrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupvisit',
            name='patrec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_visits', to='patientrecords.patientrecord'),
            preserve_default=False,
        ),
    ]
