# Generated by Django 5.1.6 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0023_followupvisit_patrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupvisit',
            name='followv_date',
            field=models.DateField(),
        ),
    ]
