# Generated by Django 5.1.6 on 2025-04-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0023_spouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spouse',
        ),
    ]
