# Generated by Django 5.1.6 on 2025-04-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0024_delete_spouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_dob', models.DateField()),
            ],
            options={
                'db_table': 'spouse',
            },
        ),
    ]
