<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-04-24 03:21
=======
# Generated by Django 5.1.6 on 2025-04-24 08:25
>>>>>>> backend/feature/healthinventory

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('patientrecords', '0024_delete_spouse'),
=======
        ('patientrecords', '0024_alter_followupvisit_followv_date'),
>>>>>>> backend/feature/healthinventory
    ]

    operations = [
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('spouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spouse_type', models.CharField(max_length=10)),
                ('spouse_lname', models.CharField(default='', max_length=50)),
                ('spouse_fname', models.CharField(default='', max_length=50)),
                ('spouse_mnane', models.CharField(default='', max_length=50)),
                ('spouse_occupation', models.CharField(max_length=50)),
                ('spouse_dob', models.DateField()),
            ],
            options={
                'db_table': 'spouse',
            },
        ),
    ]
