# Generated by Django 5.1.6 on 2025-04-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0025_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='pat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouses', to='patientrecords.patient'),
        ),
    ]
