# Generated by Django 5.2.3 on 2025-06-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0026_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='patient',
        #     # name='per_id',
        # ),
        # migrations.RemoveField(
        #     model_name='spouse',
        #     name='pat',
        # ),
        migrations.AddField(
            model_name='spouse',
            name='pat_id',
            field=models.ForeignKey(db_column='pat_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='patientrecords.patient'),
            preserve_default=False,
        ),
    ]
