# Generated by Django 5.1.6 on 2025-04-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0026_spouse_pat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spouse',
        ),
    ]
