# Generated by Django 5.1.6 on 2025-04-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0027_delete_spouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('spouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spouse_type', models.CharField(max_length=10)),
                ('spouse_lname', models.CharField(default='', max_length=50)),
                ('spouse_fname', models.CharField(default='', max_length=50)),
                ('spouse_mnane', models.CharField(default='', max_length=50)),
                ('spouse_occupation', models.CharField(max_length=50)),
                ('spouse_dob', models.DateField()),
                ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouses', to='patientrecords.patient')),
            ],
            options={
                'db_table': 'spouse',
            },
        ),
    ]
