# Generated by Django 5.1.6 on 2025-04-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0028_spouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('find_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('find_description', models.TextField()),
                ('obj_description', models.TextField()),
                ('subj_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finding',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('ill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('illname', models.CharField(max_length=100)),
                ('ill_description', models.CharField(default='N/A', max_length=200)),
                ('ill_code', models.CharField(default='N/A', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'illness',
            },
        ),
        migrations.CreateModel(
            name='PhysicalExamList',
            fields=[
                ('pel_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pel_system', models.CharField(max_length=100)),
                ('pel_finding', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'physical_exam_list',
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('bm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(default='', max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi_category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'body_measurement',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.finding')),
                ('ill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.illness')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('pe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_other', models.BooleanField(default=False)),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_examinations', to='patientrecords.finding')),
                ('pel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_examinations', to='patientrecords.physicalexamlist')),
            ],
            options={
                'db_table': 'physical_examination',
            },
        ),
    ]
