# Generated by Django 5.1.6 on 2025-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0029_finding_illness_physicalexamlist_bodymeasurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalexamination',
            name='is_other',
        ),
        migrations.AddField(
            model_name='physicalexamlist',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
    ]
