# Generated by Django 5.1.6 on 2025-04-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0030_remove_physicalexamination_is_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalexamination',
            name='find',
        ),
        migrations.RemoveField(
            model_name='physicalexamination',
            name='pel',
        ),
        migrations.RemoveField(
            model_name='physicalexamlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='physicalexamlist',
            name='is_other',
        ),
        migrations.RemoveField(
            model_name='physicalexamlist',
            name='pel_finding',
        ),
        migrations.RemoveField(
            model_name='physicalexamlist',
            name='pel_system',
        ),
    ]
