# Generated by Django 5.1.6 on 2025-04-24 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0031_remove_physicalexamination_find_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='find_description',
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='find',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_examinations', to='patientrecords.finding'),
        ),
        migrations.AddField(
            model_name='physicalexamination',
            name='pel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_examinations', to='patientrecords.physicalexamlist'),
        ),
        migrations.AddField(
            model_name='physicalexamlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalexamlist',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalexamlist',
            name='pel_finding',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='physicalexamlist',
            name='pel_system',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='find',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.finding'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='ill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patientrecords.illness'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='obj_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='finding',
            name='subj_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='illness',
            name='illname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
