# Generated by Django 5.1.6 on 2025-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0032_remove_finding_find_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='vital_pulse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_RR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_o2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_temp',
            field=models.IntegerField(default=0),
        ),
    ]
