# Generated by Django 5.1.6 on 2025-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0033_vitalsigns_vital_pulse_alter_vitalsigns_vital_rr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_RR',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_diastolic',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_bp_systolic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_o2',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_pulse',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='vital_temp',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
