# Generated by Django 5.1.6 on 2025-04-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0035_remove_bodymeasurement_patrec_bodymeasurement_pat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='pat',
        ),
    ]
