# Generated by Django 5.1.6 on 2025-04-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0036_remove_bodymeasurement_pat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='pat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='patientrecords.patient'),
        ),
    ]
