# Generated by Django 5.1.6 on 2025-06-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthProfiling', '0003_delete_patient'),
        ('patientrecords', '0037_bodymeasurement_pat'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='patient',
        #     name='per_id',
        # ),
        migrations.AddField(
            model_name='patient',
            name='rp_id',
            field=models.ForeignKey(db_column='rp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='healthProfiling.residentprofile'),
        ),
    ]
