# Generated by Django 5.1.6 on 2025-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0038_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pat_id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
