# Generated by Django 5.2.3 on 2025-06-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0027_remove_patient_per_id_remove_spouse_pat_and_more'),
        ('patientrecords', '0039_alter_patient_pat_id'),
    ]

    operations = [
    ]
