# Generated by Django 5.2 on 2025-06-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=50, unique=True)),
                ('ord_title', models.CharField(max_length=255)),
                ('ord_date_created', models.DateField()),
                ('ord_category', models.CharField(max_length=100)),
                ('ord_details', models.TextField()),
                ('ord_year', models.IntegerField()),
                ('ord_is_archive', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
            options={
                'db_table': 'ordinance',
                'ordering': ['-ord_date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrdinanceSupplementaryDoc',
            fields=[
                ('osd_id', models.AutoField(primary_key=True, serialize=False)),
                ('osd_title', models.CharField(max_length=255)),
                ('osd_is_archive', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file')),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_docs', to='secretary.ordinance')),
            ],
            options={
                'db_table': 'ordinance_supp_doc',
                'ordering': ['osd_id'],
            },
        ),
    ]
