# Generated by Django 5.1.6 on 2025-06-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('administration', '0004_staff_rp'),
        # ('patientrecords', '0003_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FP_Record',
            fields=[
                ('fprecord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nhts', models.BooleanField(default=False)),
                ('four_ps', models.BooleanField(default=False)),
                ('plan_more_children', models.BooleanField(default=False)),
                ('avg_monthly_income', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patrec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'famplan_record',
            },
        ),
        migrations.CreateModel(
            name='FP_pregnancy_check',
            fields=[
                ('fp_pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('breastfeeding', models.BooleanField(default=False)),
                ('abstained', models.BooleanField(default=False)),
                ('recent_baby', models.BooleanField(default=False)),
                ('recent_period', models.BooleanField(default=False)),
                ('recent_abortion', models.BooleanField(default=False)),
                ('using_contraceptive', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_pregnancy_check',
            },
        ),
        migrations.CreateModel(
            name='FP_Physical_Exam',
            fields=[
                ('fp_pe_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(default='0', max_length=3)),
                ('height', models.CharField(default='0', max_length=3)),
                ('bloodpressure', models.CharField(default='0', max_length=3)),
                ('pulserate', models.CharField(default='0', max_length=3)),
                ('skinExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish'), ('hematoma', 'Hematoma')], max_length=20)),
                ('conjunctivaExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish')], max_length=20)),
                ('neckExamination', models.CharField(choices=[('normal', 'Normal'), ('neck_mass', 'Neck Mass'), ('enlarged_lymph_nodes', 'Enlarged Lymph Nodes')], max_length=30)),
                ('breastExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('nipple_discharge', 'Nipple Discharge')], max_length=30)),
                ('abdomenExamination', models.CharField(choices=[('normal', 'Normal'), ('abdominal_mass', 'Abdominal Mass'), ('varicosities', 'Varicosities')], max_length=30)),
                ('extremitiesExamination', models.CharField(choices=[('normal', 'Normal'), ('edema', 'Edema'), ('varicosities', 'Varicosities')], max_length=30)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_physical_exam',
            },
        ),
        migrations.CreateModel(
            name='FP_Pelvic_Exam',
            fields=[
                ('pelvic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pelvicExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('abnormal_discharge', 'Abnormal Discharge'), ('cervical_abnormalities', 'Cervical Abnormalities'), ('warts', 'Warts'), ('polyp_or_cyst', 'Polyp or Cyst'), ('inflammation_or_erosion', 'Inflammation or Erosion'), ('bloody_discharge', 'Bloody Discharge')], max_length=30)),
                ('cervicalConsistency', models.CharField(choices=[('firm', 'Firm'), ('soft', 'Soft')], max_length=20)),
                ('cervicalTenderness', models.BooleanField(default=False)),
                ('cervicalAdnexal', models.BooleanField(default=False)),
                ('uterinePosition', models.CharField(choices=[('mid', 'Mid'), ('anteflexed', 'Anteflexed'), ('retroflexed', 'Retroflexed')], max_length=20)),
                ('uterineDepth', models.CharField(blank=True, max_length=10, null=True)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_pelvic_exam',
            },
        ),
        migrations.CreateModel(
            name='FP_Obstetrical_History',
            fields=[
                ('fpob_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpob_last_delivery', models.DateField(blank=True, null=True)),
                ('fpob_type_last_delivery', models.CharField(blank=True, max_length=30, null=True)),
                ('fpob_last_period', models.DateField(blank=True, null=True)),
                ('fpob_previous_period', models.DateField(blank=True, null=True)),
                ('fpob_mens_flow', models.CharField(max_length=20)),
                ('fpob_dysme', models.BooleanField(default=False)),
                ('fpob_hydatidiform', models.BooleanField(default=False)),
                ('fpob_ectopic_pregnancy', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_obs_history',
            },
        ),
        migrations.CreateModel(
            name='FP_Medical_History',
            fields=[
                ('fp_medhistory_id', models.AutoField(primary_key=True, serialize=False)),
                ('severeHeadaches', models.BooleanField(default=False)),
                ('strokeHeartAttackHypertension', models.BooleanField(default=False)),
                ('hematomaBruisingBleeding', models.BooleanField(default=False)),
                ('breastCancerHistory', models.BooleanField(default=False)),
                ('severeChestPain', models.BooleanField(default=False)),
                ('coughMoreThan14Days', models.BooleanField(default=False)),
                ('jaundice', models.BooleanField(default=False)),
                ('unexplainedVaginalBleeding', models.BooleanField(default=False)),
                ('abnormalVaginalDischarge', models.BooleanField(default=False)),
                ('phenobarbitalOrRifampicin', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('disability', models.BooleanField(default=False)),
                ('disabilityDetails', models.TextField(blank=True, null=True)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_medical_history',
            },
        ),
        migrations.CreateModel(
            name='FP_Acknowledgement',
            fields=[
                ('ack_id', models.AutoField(primary_key=True, serialize=False)),
                ('ack_clientSignature', models.TextField(blank=True, null=True)),
                ('ack_clientSignatureDate', models.DateField()),
                ('client_name', models.CharField(max_length=50)),
                ('guardian_signature', models.TextField(blank=True, null=True)),
                ('guardian_signature_date', models.DateField(blank=True, null=True)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_acknowledgement',
            },
        ),
        migrations.CreateModel(
            name='FP_RiskSti',
            fields=[
                ('sti_id', models.AutoField(primary_key=True, serialize=False)),
                ('abnormalDischarge', models.BooleanField(default=False)),
                ('dischargeFrom', models.CharField(blank=True, max_length=10, null=True)),
                ('sores', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_risk_sti',
            },
        ),
        migrations.CreateModel(
            name='FP_RiskVaw',
            fields=[
                ('vaw_id', models.AutoField(primary_key=True, serialize=False)),
                ('unpleasant_relationship', models.BooleanField(default=False)),
                ('partner_disapproval', models.BooleanField(default=False)),
                ('domestic_violence', models.BooleanField(default=False)),
                ('referredTo', models.CharField(max_length=30)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_risk_vaw',
            },
        ),
        migrations.CreateModel(
            name='FP_type',
            fields=[
                ('fpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpt_client_type', models.CharField(max_length=20)),
                ('fpt_subtype', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_reason_fp', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_method_used', models.CharField(max_length=30)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'famplan_type',
            },
        ),
        migrations.CreateModel(
            name='FP_Assessment_Record',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('as_provider_signature', models.CharField()),
                ('as_provider_name', models.CharField(max_length=35)),
                ('as_findings', models.CharField(default='None', max_length=100)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
                ('fp_pe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_physical_exam')),
                ('fpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
            ],
            options={
                'db_table': 'famplan_assessment',
            },
        ),
    ]
