# Generated by Django 5.1.6 on 2025-04-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthProfiling', '0003_delete_patient'),
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FP_Acknowledgement',
            fields=[
                ('ack_id', models.AutoField(primary_key=True, serialize=False)),
                ('ack_clientSignature', models.TextField()),
                ('ack_clientSignatureDate', models.DateField()),
                ('client_name', models.CharField(max_length=50)),
                ('guardian_signature', models.TextField()),
                ('guardian_signature_date', models.DateField()),
                ('patient_ack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'fp_acknowledgement',
            },
        ),
        migrations.CreateModel(
            name='FP_Record',
            fields=[
                ('fprecord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, null=True)),
                ('nhts', models.BooleanField(default=False)),
                ('four_ps', models.BooleanField(default=False)),
                ('plan_more_children', models.BooleanField(default=False)),
                ('avg_monthly_income', models.CharField(max_length=15)),
                ('transient', models.BooleanField(default=False)),
                ('hrd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthProfiling.healthrelateddetails')),
                ('patrec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'fp_record',
            },
        ),
        migrations.CreateModel(
            name='FP_Physical_Exam',
            fields=[
                ('fp_pe_id', models.AutoField(primary_key=True, serialize=False)),
                ('skinExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish'), ('hematoma', 'Hematoma')], max_length=20)),
                ('conjunctivaExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish')], max_length=20)),
                ('neckExamination', models.CharField(choices=[('normal', 'Normal'), ('neck_mass', 'Neck Mass'), ('enlarged_lymph_nodes', 'Enlarged Lymph Nodes')], max_length=30)),
                ('breastExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('nipple_discharge', 'Nipple Discharge')], max_length=30)),
                ('abdomenExamination', models.CharField(choices=[('normal', 'Normal'), ('abdominal_mass', 'Abdominal Mass'), ('varicosities', 'Varicosities')], max_length=30)),
                ('extremitiesExamination', models.CharField(choices=[('normal', 'Normal'), ('edema', 'Edema'), ('varicosities', 'Varicosities')], max_length=30)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'fp_physical_exam',
            },
        ),
        migrations.CreateModel(
            name='FP_Obstetrical_History',
            fields=[
                ('fpob_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpob_last_delivery', models.CharField(max_length=30)),
                ('fpob_type_last_delivery', models.CharField(max_length=30, null=True)),
                ('fpob_last_period', models.CharField(max_length=30, null=True)),
                ('fpob_previous_period', models.CharField(max_length=30, null=True)),
                ('fpob_mens_flow', models.CharField(max_length=20)),
                ('fpob_dysme', models.BooleanField(default=False)),
                ('fpob_hydatidiform', models.BooleanField(default=False)),
                ('fpob_ectopic_pregnancy', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'fp_obs_history',
            },
        ),
        migrations.CreateModel(
            name='FP_Medical_history',
            fields=[
                ('medic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.illness')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'fp_medical_history',
            },
        ),
        migrations.CreateModel(
            name='FP_RiskSti',
            fields=[
                ('sti_id', models.AutoField(primary_key=True, serialize=False)),
                ('abnormalDischarge', models.BooleanField(default=False)),
                ('dischargeFrom', models.CharField(blank=True, max_length=10, null=True)),
                ('sores', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'fp_risk_sti',
            },
        ),
        migrations.CreateModel(
            name='FP_RiskVaw',
            fields=[
                ('vaw_id', models.AutoField(primary_key=True, serialize=False)),
                ('unpleasant_relationship', models.BooleanField(default=False)),
                ('partner_disapproval', models.BooleanField(default=False)),
                ('domestic_violence', models.BooleanField(default=False)),
                ('referredTo', models.CharField(max_length=30)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'fp_risk_vaw',
            },
        ),
        migrations.CreateModel(
            name='FP_type',
            fields=[
                ('fpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpt_client_type', models.CharField(max_length=20)),
                ('fpt_subtype', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_reason_fp', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_method_used', models.CharField(max_length=30)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'fp_type',
            },
        ),
        migrations.CreateModel(
            name='FP_pregnancy_check',
            fields=[
                ('fp_pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('breastfeeding', models.BooleanField(default=False)),
                ('abstained', models.BooleanField(default=False)),
                ('recent_baby', models.BooleanField(default=False)),
                ('recent_period', models.BooleanField(default=False)),
                ('recent_abortion', models.BooleanField(default=False)),
                ('using_contraceptive', models.BooleanField(default=False)),
                ('pregnancy_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
                ('fpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
            ],
            options={
                'db_table': 'fp_pregnancy_check',
            },
        ),
        migrations.CreateModel(
            name='FP_Pelvic_Exam',
            fields=[
                ('pelvic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pelvicExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('abnormal_discharge', 'Abnormal Discharge'), ('cervical_abnormalities', 'Cervical Abnormalities'), ('warts', 'Warts'), ('polyp_or_cyst', 'Polyp or Cyst'), ('inflammation_or_erosion', 'Inflammation or Erosion'), ('bloody_discharge', 'Bloody Discharge')], max_length=30)),
                ('cervicalConsistency', models.CharField(choices=[('firm', 'Firm'), ('soft', 'Soft')], max_length=20)),
                ('cervicalTenderness', models.BooleanField(default=False)),
                ('cervicalAdnexal', models.BooleanField(default=False)),
                ('uterinePosition', models.CharField(choices=[('mid', 'Mid'), ('anteflexed', 'Anteflexed'), ('retroflexed', 'Retroflexed')], max_length=20)),
                ('uterineDepth', models.CharField(blank=True, max_length=10, null=True)),
                ('fpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
            ],
            options={
                'db_table': 'fp_pelvic_exam',
            },
        ),
        migrations.CreateModel(
            name='FP_Assessment_Record',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('as_provider_signature', models.CharField()),
                ('as_provider_name', models.CharField(max_length=35)),
                ('as_followup_date', models.CharField(max_length=15)),
                ('medical_findings', models.CharField(default='None', max_length=100)),
                ('ack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_acknowledgement')),
                ('fpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
            ],
            options={
                'db_table': 'fp_assessment',
            },
        ),
        migrations.AddField(
            model_name='fp_acknowledgement',
            name='fpt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type'),
        ),
    ]
