# Generated by Django 5.1.6 on 2025-06-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0004_staff_rp'),
        ('healthProfiling', '0002_solid_waste_mgmt_remove_household_hh_barangay_and_more'),
        ('inventory', '0001_initial'),
        # ('patientrecords', '0003_transient_transientaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FP_Record',
            fields=[
                ('fprecord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fourps', models.BooleanField(default=False)),
                ('plan_more_children', models.BooleanField(default=False)),
                ('avg_monthly_income', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='healthProfiling.healthrelateddetails')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='patientrecords.patient')),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='patientrecords.patientrecord')),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='patientrecords.spouse')),
            ],
            options={
                'verbose_name': 'Family Planning Record',
                'verbose_name_plural': 'Family Planning Records',
                'db_table': 'famplan_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FP_pregnancy_check',
            fields=[
                ('fp_pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('breastfeeding', models.BooleanField(default=False)),
                ('abstained', models.BooleanField(default=False)),
                ('recent_baby', models.BooleanField(default=False)),
                ('recent_period', models.BooleanField(default=False)),
                ('recent_abortion', models.BooleanField(default=False)),
                ('using_contraceptive', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name_plural': 'FP Pregnancy Checks',
                'db_table': 'famplan_pregnancy_check',
            },
        ),
        migrations.CreateModel(
            name='FP_Physical_Exam',
            fields=[
                ('fp_pe_id', models.AutoField(primary_key=True, serialize=False)),
                ('bloodpressure', models.CharField(default='0/0', max_length=10)),
                ('pulserate', models.CharField(default='0', max_length=5)),
                ('skinExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish'), ('hematoma', 'Hematoma')], max_length=20)),
                ('conjunctivaExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish')], max_length=20)),
                ('neckExamination', models.CharField(choices=[('normal', 'Normal'), ('neck_mass', 'Neck Mass'), ('enlarged_lymph_nodes', 'Enlarged Lymph Nodes')], max_length=30)),
                ('breastExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('nipple_discharge', 'Nipple Discharge')], max_length=30)),
                ('abdomenExamination', models.CharField(choices=[('normal', 'Normal'), ('abdominal_mass', 'Abdominal Mass'), ('varicosities', 'Varicosities')], max_length=30)),
                ('extremitiesExamination', models.CharField(choices=[('normal', 'Normal'), ('edema', 'Edema'), ('varicosities', 'Varicosities')], max_length=30)),
                ('bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.bodymeasurement')),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name_plural': 'FP Physical Exams',
                'db_table': 'famplan_physical_exam',
            },
        ),
        migrations.CreateModel(
            name='FP_Pelvic_Exam',
            fields=[
                ('pelvic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pelvicExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('abnormal_discharge', 'Abnormal Discharge'), ('cervical_abnormalities', 'Cervical Abnormalities'), ('warts', 'Warts'), ('polyp_or_cyst', 'Polyp or Cyst'), ('inflammation_or_erosion', 'Inflammation or Erosion'), ('bloody_discharge', 'Bloody Discharge')], max_length=30)),
                ('cervicalConsistency', models.CharField(choices=[('firm', 'Firm'), ('soft', 'Soft')], max_length=20)),
                ('cervicalTenderness', models.BooleanField(default=False)),
                ('cervicalAdnexal', models.BooleanField(default=False)),
                ('uterinePosition', models.CharField(choices=[('mid', 'Mid'), ('anteflexed', 'Anteflexed'), ('retroflexed', 'Retroflexed')], max_length=20)),
                ('uterineDepth', models.CharField(blank=True, max_length=10, null=True)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name_plural': 'FP Pelvic Exams',
                'db_table': 'famplan_pelvic_exam',
            },
        ),
        migrations.CreateModel(
            name='FP_Obstetrical_History',
            fields=[
                ('fpob_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpob_last_delivery', models.DateField(blank=True, null=True)),
                ('fpob_type_last_delivery', models.CharField(blank=True, max_length=30, null=True)),
                ('fpob_last_period', models.DateField(blank=True, null=True)),
                ('fpob_previous_period', models.DateField(blank=True, null=True)),
                ('fpob_mens_flow', models.CharField(max_length=20)),
                ('fpob_dysme', models.BooleanField(default=False)),
                ('fpob_hydatidiform', models.BooleanField(default=False)),
                ('fpob_ectopic_pregnancy', models.BooleanField(default=False)),
                ('obs_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientrecords.obstetrical_history')),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name_plural': 'FP Obstetrical Histories',
                'db_table': 'famplan_obs_history',
            },
        ),
        migrations.CreateModel(
            name='FP_RiskSti',
            fields=[
                ('sti_id', models.AutoField(primary_key=True, serialize=False)),
                ('abnormalDischarge', models.BooleanField(default=False)),
                ('dischargeFrom', models.CharField(blank=True, max_length=20, null=True)),
                ('sores', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_risk_stis', to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name_plural': 'FP Risk STIs',
                'db_table': 'famplan_risk_sti',
            },
        ),
        migrations.CreateModel(
            name='FP_RiskVaw',
            fields=[
                ('vaw_id', models.AutoField(primary_key=True, serialize=False)),
                ('unpleasant_relationship', models.BooleanField(default=False)),
                ('partner_disapproval', models.BooleanField(default=False)),
                ('domestic_violence', models.BooleanField(default=False)),
                ('referredTo', models.CharField(max_length=40)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_risk_vaws', to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name_plural': 'FP Risk VAWs',
                'db_table': 'famplan_risk_vaw',
            },
        ),
        migrations.CreateModel(
            name='FP_type',
            fields=[
                ('fpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpt_client_type', models.CharField(max_length=20)),
                ('fpt_subtype', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_reason_fp', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('fpt_method_used', models.CharField(max_length=50)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'verbose_name': 'Family Planning Type',
                'verbose_name_plural': 'Family Planning Types',
                'db_table': 'famplan_type',
                'ordering': ['fpt_client_type'],
            },
        ),
        migrations.CreateModel(
            name='FP_Assessment_Record',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('as_provider_signature', models.CharField()),
                ('as_provider_name', models.CharField(max_length=35)),
                ('as_findings', models.CharField(default='None', max_length=100)),
                ('dispensed_item_name_for_report', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dispensed Item Name (for report)')),
                ('bm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.bodymeasurement')),
                ('dispensed_commodity_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_dispensed_assessments_com', to='inventory.commoditylist', verbose_name='Dispensed Commodity Item')),
                ('dispensed_medicine_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_dispensed_assessments_med', to='inventory.medicinelist', verbose_name='Dispensed Medicine Item')),
                ('dispensed_vaccine_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_dispensed_assessments_vac', to='inventory.vaccinelist', verbose_name='Dispensed Vaccine Item')),
                ('followv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.followupvisit')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
                ('vital_signs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fp_assessments', to='patientrecords.vitalsigns', verbose_name='Vital Signs Record for Assessment')),
                ('fpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
            ],
            options={
                'verbose_name_plural': 'FP Assessment Records',
                'db_table': 'famplan_assessment',
            },
        ),
        migrations.CreateModel(
            name='FP_Acknowledgement',
            fields=[
                ('ack_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('ack_clientSignature', models.TextField(blank=True, null=True)),
                ('guardian_signature', models.TextField(blank=True, null=True)),
                ('ack_clientSignatureDate', models.DateField(auto_now_add=True)),
                ('guardian_signature_date', models.DateField(blank=True, null=True)),
                ('fprecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
            ],
            options={
                'verbose_name_plural': 'FP Acknowledgements',
                'db_table': 'famplan_acknowledgement',
            },
        ),
    ]
