# Generated by Django 5.1.6 on 2025-04-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_record',
            name='medical_findings',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='fp_pregnancy_check',
            fields=[
                ('fp_pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('breastfeeding', models.BooleanField(default=False)),
                ('abstained', models.BooleanField(default=False)),
                ('recent_baby', models.BooleanField(default=False)),
                ('recent_period', models.BooleanField(default=False)),
                ('recent_abortion', models.BooleanField(default=False)),
                ('using_contraceptive', models.BooleanField(default=False)),
                ('fpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_type')),
                ('pregnancy_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record')),
            ],
            options={
                'db_table': 'FP_pregnancy_check',
            },
        ),
        migrations.DeleteModel(
            name='FP_finding',
        ),
    ]
