# Generated by Django 5.1.6 on 2025-06-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0001_initial'),
        # ('patientrecords', '0003_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp_record',
            name='spouse_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patientrecords.spouse'),
            preserve_default=False,
        ),
    ]
