# Generated by Django 5.1.6 on 2025-04-18 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0001_initial'),
        ('vaccination', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp_record',
            name='serv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicesrecords'),
            preserve_default=False,
        ),
    ]
