# Generated by Django 5.1.6 on 2025-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('familyplanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp_type',
            name='fp_subtype_of_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
