# Generated by Django 5.1.6 on 2025-04-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0001_initial'),
        ('patientrecords', '0019_vitalsigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp_record',
            name='per_id',
        ),
        migrations.AddField(
            model_name='fp_record',
            name='patrec_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fp_acknowledgement',
            name='patient_ack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord'),
        ),
    ]
