# Generated by Django 5.1.7 on 2025-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0002_alter_obstetricalhistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormalDischarge', models.BooleanField(default=False)),
                ('dischargeFrom', models.CharField(max_length=10)),
                ('sores', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'risk_sti',
            },
        ),
        migrations.AlterModelTable(
            name='obstetricalhistory',
            table='obstetrical_history',
        ),
    ]
