# Generated by Django 5.1.6 on 2025-06-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0002_fp_type_fp_subtype_of_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fp_type',
            name='fpt_subtype',
        ),
    ]
