# Generated by Django 5.1.6 on 2025-06-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0003_remove_fp_type_fpt_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fp_type',
            old_name='fp_subtype_of_client',
            new_name='fpt_subtype',
        ),
    ]
