# Generated by Django 5.1.6 on 2025-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskvaw',
            name='other_referral',
        ),
        migrations.AlterField(
            model_name='fp_obstetrical_history',
            name='fpob_dysme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fp_obstetrical_history',
            name='fpob_ectopic_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fp_obstetrical_history',
            name='fpob_hydatidiform',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fp_obstetrical_history',
            name='fpob_last_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fp_obstetrical_history',
            name='fpob_previous_period',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fp_obstetrical_history',
            name='fpob_type_last_delivery',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fp_type',
            name='fpt_reason',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fp_type',
            name='fpt_reason_fp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fp_type',
            name='fpt_subtype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riskvaw',
            name='referredTo',
            field=models.CharField(max_length=30),
        ),
    ]
