# Generated by Django 5.1.6 on 2025-06-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0004_rename_fp_subtype_of_client_fp_type_fpt_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fp_type',
            old_name='fpt_subtype',
            new_name='subtype_of_client',
        ),
    ]
