# Generated by Django 5.1.7 on 2025-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0004_riskvaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('bloodPressure', models.CharField(max_length=20)),
                ('pulseRate', models.CharField(max_length=10)),
                ('skinExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish'), ('hematoma', 'Hematoma')], max_length=20)),
                ('conjunctivaExamination', models.CharField(choices=[('normal', 'Normal'), ('pale', 'Pale'), ('yellowish', 'Yellowish')], max_length=20)),
                ('neckExamination', models.CharField(choices=[('normal', 'Normal'), ('neck_mass', 'Neck Mass'), ('enlarged_lymph_nodes', 'Enlarged Lymph Nodes')], max_length=30)),
                ('breastExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('nipple_discharge', 'Nipple Discharge')], max_length=30)),
                ('abdomenExamination', models.CharField(choices=[('normal', 'Normal'), ('abdominal_mass', 'Abdominal Mass'), ('varicosities', 'Varicosities')], max_length=30)),
                ('extremitiesExamination', models.CharField(choices=[('normal', 'Normal'), ('edema', 'Edema'), ('varicosities', 'Varicosities')], max_length=30)),
                ('pelvicExamination', models.CharField(choices=[('normal', 'Normal'), ('mass', 'Mass'), ('abnormal_discharge', 'Abnormal Discharge'), ('cervical_abnormalities', 'Cervical Abnormalities'), ('warts', 'Warts'), ('polyp_or_cyst', 'Polyp or Cyst'), ('inflammation_or_erosion', 'Inflammation or Erosion'), ('bloody_discharge', 'Bloody Discharge')], max_length=30)),
                ('cervicalConsistency', models.CharField(choices=[('firm', 'Firm'), ('soft', 'Soft')], max_length=20)),
                ('cervicalTenderness', models.BooleanField(default=False)),
                ('cervicalAdnexalMassTenderness', models.BooleanField(default=False)),
                ('uterinePosition', models.CharField(choices=[('mid', 'Mid'), ('anteflexed', 'Anteflexed'), ('retroflexed', 'Retroflexed')], max_length=20)),
                ('uterineDepth', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'physical_examination',
            },
        ),
        migrations.AlterField(
            model_name='riskvaw',
            name='otherReferral',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='riskvaw',
            name='referredTo',
            field=models.CharField(max_length=10),
        ),
    ]
