# Generated by Django 5.1.6 on 2025-04-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0004_remove_riskvaw_other_referral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='abstained_since_last_period',
            new_name='abstained_last_period',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='baby_breastfeeding_no_menses',
            new_name='bf_no_menses',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='had_baby_last_4_weeks',
            new_name='had_baby',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='miscarriage_or_abortion_7_days',
            new_name='miscarriage_or_abortion',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='period_within_7_days',
            new_name='period_within',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='using_contraceptive_consistently',
            new_name='using_contraceptive',
        ),
    ]
