# Generated by Django 5.1.6 on 2025-04-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0005_rename_abstained_since_last_period_pregnancycheck_abstained_last_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='abstained_last_period',
            new_name='abstained',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='bf_no_menses',
            new_name='breastfeeding',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='had_baby',
            new_name='recent_abortion',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='miscarriage_or_abortion',
            new_name='recent_baby',
        ),
        migrations.RenameField(
            model_name='pregnancycheck',
            old_name='period_within',
            new_name='recent_period',
        ),
    ]
