# Generated by Django 5.1.6 on 2025-06-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0005_rename_fpt_subtype_fp_type_subtype_of_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fp_type',
            old_name='subtype_of_client',
            new_name='fpt_subtype',
        ),
    ]
