# Generated by Django 5.1.6 on 2025-04-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0006_rename_abstained_last_period_pregnancycheck_abstained_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acknowledgement',
        ),
        migrations.DeleteModel(
            name='Assessment_Record',
        ),
        migrations.DeleteModel(
            name='FP_finding',
        ),
        migrations.DeleteModel(
            name='FP_Obstetrical_History',
        ),
        migrations.DeleteModel(
            name='FP_Record',
        ),
        migrations.DeleteModel(
            name='FP_type',
        ),
        migrations.DeleteModel(
            name='Pelvic_Exam',
        ),
        migrations.DeleteModel(
            name='Physical_Exam',
        ),
        migrations.DeleteModel(
            name='PregnancyCheck',
        ),
        migrations.DeleteModel(
            name='RiskSti',
        ),
        migrations.DeleteModel(
            name='RiskVaw',
        ),
    ]
