# Generated by Django 5.1.6 on 2025-06-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0006_rename_abstained_last_period_pregnancycheck_abstained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_record',
            name='as_followup_date',
        ),
        migrations.AddField(
            model_name='fp_record',
            name='client_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp_record',
            name='philhhealth_id',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp_type',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='familyplanning.fp_record'),
            preserve_default=False,
        ),
    ]
