# Generated by Django 5.1.6 on 2025-06-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0006_rename_subtype_of_client_fp_type_fpt_subtype'),
        ('healthProfiling', '0002_solid_waste_mgmt_remove_household_hh_barangay_and_more'),
        # ('patientrecords', '0003_transient_transientaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp_record',
            name='hrd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='healthProfiling.healthrelateddetails'),
        ),
        migrations.AlterField(
            model_name='fp_record',
            name='pat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='patientrecords.patient'),
        ),
        migrations.AlterField(
            model_name='fp_record',
            name='spouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fp_records', to='patientrecords.spouse'),
        ),
    ]
