# Generated by Django 5.1.6 on 2025-06-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0007_alter_fp_record_hrd_alter_fp_record_pat_and_more'),
        ('patientrecords', '0003_transient_transientaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp_physical_exam',
            name='bm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientrecords.bodymeasurement'),
        ),
    ]
