# Generated by Django 5.1.7 on 2025-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyplanning', '0008_rename_clientsignature_acknowledgement_ack_clientsignature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='ack_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
