# Generated by Django 5.1.6 on 2025-06-08 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('patientrecords', '0002_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBite_Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('transient', models.BooleanField(default=False)),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'animalbite_referral',
            },
        ),
        migrations.CreateModel(
            name='AnimalBite_Details',
            fields=[
                ('bite_id', models.AutoField(primary_key=True, serialize=False)),
                ('exposure_type', models.CharField(max_length=50)),
                ('actions_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('referredby', models.CharField(max_length=100)),
                ('biting_animal', models.CharField(default='', max_length=255)),
                ('exposure_site', models.CharField(default='', max_length=255)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bite_details', to='animalbites.animalbite_referral')),
            ],
            options={
                'db_table': 'animalbite_detail',
            },
        ),
    ]
