# Generated by Django 5.1.6 on 2025-06-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_staff_rp'),
        # ('patientrecords', '0002_remove_patient_per_id_patient_rp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitingAnimal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'animalbite_biting_animal',
            },
        ),
        migrations.CreateModel(
            name='ExposureSite',
            fields=[
                ('exposure_site_id', models.AutoField(primary_key=True, serialize=False)),
                ('exposure_site', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'animalbite_exposure_site',
            },
        ),
        migrations.CreateModel(
            name='AnimalBite_Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('transient', models.BooleanField(default=False)),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'animalbite_referral',
            },
        ),
        migrations.CreateModel(
            name='AnimalBite_Details',
            fields=[
                ('bite_id', models.AutoField(primary_key=True, serialize=False)),
                ('exposure_type', models.CharField(max_length=50)),
                ('actions_taken', models.CharField(max_length=255)),
                ('referredby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bite_details', to='animalbites.animalbite_referral')),
                ('biting_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animalbites.bitinganimal')),
                ('exposure_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animalbites.exposuresite')),
            ],
            options={
                'db_table': 'animalbite_detail',
            },
        ),
    ]
