# Generated by Django 5.1.6 on 2025-04-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientrecords', '0019_vitalsigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBite_Record',
            fields=[
                ('animalbite_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('patrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'animalbite_record',
            },
        ),
        migrations.CreateModel(
            name='AnimalBite_Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('transient', models.BooleanField(default=False)),
                ('animalbite_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalbites.animalbite_record')),
            ],
            options={
                'db_table': 'animalbite_referral',
            },
        ),
        migrations.CreateModel(
            name='AnimalBite_Details',
            fields=[
                ('bite_id', models.AutoField(primary_key=True, serialize=False)),
                ('exposure_type', models.CharField(max_length=50)),
                ('exposure_site', models.CharField(default='Not specified', max_length=50)),
                ('biting_animal', models.CharField(max_length=50)),
                ('actions_taken', models.CharField(max_length=50)),
                ('referredby', models.CharField(max_length=50)),
                ('referral_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalbites.animalbite_referral')),
            ],
            options={
                'db_table': 'animalbite_detail',
            },
        ),
    ]
