# Generated by Django 5.1.6 on 2025-06-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalbite_details',
            name='referredby',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
