# Generated by Django 5.1.6 on 2025-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalbite_record',
            old_name='patrec',
            new_name='patrec_id',
        ),
    ]
