# Generated by Django 5.1.6 on 2025-04-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BiteDetails',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
