# Generated by Django 5.1.6 on 2025-06-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalbite_referral',
            name='transient',
        ),
    ]
