# Generated by Django 5.1.6 on 2025-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0002_remove_animalbite_referral_transient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalbite_details',
            options={'ordering': ['-created_at', '-bite_id']},
        ),
        migrations.AlterModelOptions(
            name='animalbite_referral',
            options={'ordering': ['-date', '-referral_id']},
        ),
        migrations.AddField(
            model_name='animalbite_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalbite_referral',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
