# Generated by Django 5.1.6 on 2025-04-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0002_rename_patrec_animalbite_record_patrec_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalbite_record',
            old_name='patrec_id',
            new_name='patrec',
        ),
    ]
