# Generated by Django 5.1.6 on 2025-04-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0003_rename_patrec_id_animalbite_record_patrec'),
        ('patientrecords', '0019_vitalsigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalbite_referral',
            name='animalbite_record_id',
        ),
        migrations.AddField(
            model_name='animalbite_referral',
            name='patrec_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patientrecords.patientrecord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnimalBite_Record',
        ),
    ]
