# Generated by Django 5.1.6 on 2025-04-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0004_remove_animalbite_referral_animalbite_record_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalbite_details',
            old_name='referral_id',
            new_name='referral',
        ),
        migrations.RenameField(
            model_name='animalbite_referral',
            old_name='patrec_id',
            new_name='patrec',
        ),
    ]
