# Generated by Django 5.1.6 on 2025-04-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0005_rename_referral_id_animalbite_details_referral_and_more'),
        ('patientrecords', '0019_vitalsigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalbite_details',
            name='referral',
            field=models.ForeignKey(db_column='referral_id', on_delete=django.db.models.deletion.CASCADE, to='animalbites.animalbite_referral'),
        ),
        migrations.AlterField(
            model_name='animalbite_referral',
            name='patrec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patientrecords.patientrecord'),
        ),
    ]
