# Generated by Django 5.1.6 on 2025-04-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalbites', '0006_alter_animalbite_details_referral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalbite_details',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bite_details', to='animalbites.animalbite_referral'),
        ),
    ]
