# Generated by Django 5.2 on 2025-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agegroup',
            fields=[
                ('agegrp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agegroup_name', models.CharField(default='N/A', max_length=100)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('max_age', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(default='N/A', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'age_group',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_type', models.CharField(max_length=100)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ImmunizationSupplies',
            fields=[
                ('imz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imz_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='Immunization Supplies', max_length=100)),
            ],
            options={
                'db_table': 'immunization_supplies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommodityList',
            fields=[
                ('com_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('Current user', 'Current user'), ('New acceptor', 'New acceptor'), ('Both', 'Both')], max_length=20)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=10)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'commodity_list',
            },
        ),
        migrations.CreateModel(
            name='CommodityInventory',
            fields=[
                ('cinv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cinv_qty', models.PositiveIntegerField(default=0)),
                ('cinv_qty_unit', models.CharField(max_length=100)),
                ('cinv_pcs', models.PositiveIntegerField(default=0)),
                ('cinv_recevFrom', models.CharField(default='OTHERS', max_length=100)),
                ('cinv_qty_avail', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wasted', models.PositiveIntegerField(default=0)),
                ('com_id', models.ForeignKey(db_column='com_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.commoditylist')),
            ],
            options={
                'db_table': 'commodity_inventory',
            },
        ),
        migrations.CreateModel(
            name='CommodityTransaction',
            fields=[
                ('comt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comt_qty', models.CharField(max_length=100)),
                ('comt_action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cinv_id', models.ForeignKey(db_column='cinv_id', on_delete=django.db.models.deletion.PROTECT, related_name='commodity_transaction', to='inventory.commodityinventory')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_transaction', to='administration.staff')),
            ],
            options={
                'db_table': 'commodity_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirstAidList',
            fields=[
                ('fa_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('fa_name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.staff')),
            ],
            options={
                'db_table': 'firstaid_list',
            },
        ),
        migrations.CreateModel(
            name='FirstAidInventory',
            fields=[
                ('finv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finv_qty', models.PositiveIntegerField(default=0)),
                ('finv_qty_unit', models.CharField(default='N/A', max_length=100)),
                ('finv_pcs', models.PositiveIntegerField(default=0)),
                ('finv_used', models.PositiveIntegerField(default=0)),
                ('finv_qty_avail', models.PositiveIntegerField(default=0)),
                ('wasted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fa_id', models.ForeignKey(db_column='fa_id', on_delete=django.db.models.deletion.PROTECT, related_name='firstaid_inventory', to='inventory.firstaidlist')),
            ],
            options={
                'db_table': 'firstaid_inventory',
            },
        ),
        migrations.CreateModel(
            name='FirstAidTransactions',
            fields=[
                ('fat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fat_qty', models.CharField(max_length=100)),
                ('fat_action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finv_id', models.ForeignKey(db_column='finv_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.firstaidinventory')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstaid_transaction', to='administration.staff')),
            ],
            options={
                'db_table': 'firstaid_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inv_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_Archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['inv_type'], name='inventory_inv_typ_766aaa_idx'), models.Index(fields=['expiry_date'], name='inventory_expiry__6e8fe4_idx'), models.Index(fields=['is_Archived'], name='inventory_is_Arch_db1743_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImmunizationStock',
            fields=[
                ('imzStck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(default=' N/A', max_length=100)),
                ('imzStck_qty', models.PositiveIntegerField(default=0)),
                ('imzStck_per_pcs', models.PositiveIntegerField(default=0)),
                ('imzStck_pcs', models.PositiveIntegerField(default=0)),
                ('imzStck_unit', models.CharField(max_length=100)),
                ('imzStck_used', models.PositiveIntegerField(default=0)),
                ('imzStck_avail', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wasted', models.PositiveIntegerField(default=0)),
                ('imz_id', models.ForeignKey(db_column='imz_id', on_delete=django.db.models.deletion.PROTECT, related_name='immunization_stock', to='inventory.immunizationsupplies')),
                ('inv_id', models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_stock', to='inventory.inventory')),
            ],
            options={
                'db_table': 'immunizationsupplies_stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='firstaidinventory',
            name='inv_id',
            field=models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_firstaid', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='commodityinventory',
            name='inv_id',
            field=models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.CreateModel(
            name='Medicinelist',
            fields=[
                ('med_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=100)),
                ('med_type', models.CharField(default='', max_length=100)),
                ('med_dsg', models.PositiveIntegerField(default=0)),
                ('med_dsg_unit', models.CharField(default='', max_length=100)),
                ('med_form', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
            ],
            options={
                'db_table': 'medicine_list',
            },
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('minv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minv_qty', models.PositiveIntegerField(default=0)),
                ('minv_qty_unit', models.CharField(default='N/A', max_length=100)),
                ('minv_pcs', models.PositiveIntegerField(default=0)),
                ('minv_qty_avail', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wasted', models.PositiveIntegerField(default=0)),
                ('temporary_deduction', models.PositiveIntegerField(default=0)),
                ('inv_id', models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_inventories', to='administration.staff')),
                ('med_id', models.ForeignKey(db_column='med_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.medicinelist')),
            ],
            options={
                'db_table': 'medicine_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineTransactions',
            fields=[
                ('mdt_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('mdt_qty', models.CharField(max_length=100)),
                ('mdt_action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minv_id', models.ForeignKey(db_column='minv_id', on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transaction', to='inventory.medicineinventory')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_transaction', to='administration.staff')),
            ],
            options={
                'db_table': 'medicine_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccineList',
            fields=[
                ('vac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vac_type_choices', models.CharField(max_length=100)),
                ('vac_name', models.CharField(max_length=255)),
                ('no_of_doses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='Vaccine', max_length=100)),
                ('ageGroup', models.ForeignKey(blank=True, db_column='ageGroup', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccines', to='inventory.agegroup')),
            ],
            options={
                'db_table': 'vaccines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccineInterval',
            fields=[
                ('vacInt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.PROTECT, related_name='intervals', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_intervals',
            },
        ),
        migrations.CreateModel(
            name='RoutineFrequency',
            fields=[
                ('routineF_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('dose_number', models.PositiveIntegerField(default=0)),
                ('time_unit', models.CharField(max_length=100)),
                ('vac_id', models.OneToOneField(db_column='vac_id', on_delete=django.db.models.deletion.PROTECT, related_name='routine_frequency', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'routine_frequencies',
            },
        ),
        migrations.CreateModel(
            name='ConditionalVaccine',
            fields=[
                ('condvac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.PROTECT, related_name='conditional_vaccines', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'conditional_vaccine',
            },
        ),
        migrations.CreateModel(
            name='VaccineStock',
            fields=[
                ('vacStck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solvent', models.CharField(max_length=10)),
                ('batch_number', models.CharField(default=' N/A', max_length=100)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('dose_ml', models.PositiveIntegerField(default=0)),
                ('vacStck_qty_avail', models.PositiveIntegerField(default=0)),
                ('wasted_dose', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv_id', models.OneToOneField(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stock', to='inventory.inventory')),
                ('vac_id', models.ForeignKey(db_column='vac_id', on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_stock', to='inventory.vaccinelist')),
            ],
            options={
                'db_table': 'vaccine_stocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AntigenTransaction',
            fields=[
                ('antt_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('antt_qty', models.CharField(max_length=100)),
                ('antt_action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antigen_transactions', to='administration.staff')),
                ('imzStck_id', models.ForeignKey(blank=True, db_column='imzStck_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antigen_transactions', to='inventory.immunizationstock')),
                ('vacStck_id', models.ForeignKey(blank=True, db_column='vacStck_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antigen_transactions', to='inventory.vaccinestock')),
            ],
            options={
                'db_table': 'antigen_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
