# Generated by Django 5.1.6 on 2025-12-15 07:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('healthProfiling', '0001_initial'),
        ('medicineservices', '0001_initial'),
        ('patientrecords', '0001_initial'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('lab_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_type', models.CharField(blank=True, choices=[('urinalysis', 'Urinalysis'), ('cbc', 'CBC'), ('sgot_sgpt', 'SGOT/SGPT'), ('creatinine_serum', 'Creatinine Serum'), ('bua_bun', 'BUA/BUN'), ('syphilis', 'Syphilis'), ('hiv_test', 'HIV Test'), ('hepa_b', 'Hepatitis B'), ('blood_typing', 'Blood Typing'), ('ogct_50gms', 'OGCT 50gms'), ('ogct_100gms', 'OGCT 100gms')], default='', max_length=50)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('to_be_followed', models.BooleanField(blank=True, default=False)),
                ('document_path', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_result',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryResultImg',
            fields=[
                ('lab_img_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField(default='')),
                ('image_name', models.TextField(default='')),
                ('image_type', models.CharField(default='', max_length=50)),
                ('image_size', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_id', models.ForeignKey(db_column='lab_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_result_img', to='maternal.laboratoryresult')),
            ],
            options={
                'db_table': 'lab_result_img',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostpartumRecord',
            fields=[
                ('ppr_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ppr_lochial_discharges', models.CharField(max_length=100)),
                ('ppr_num_of_pads', models.PositiveIntegerField()),
                ('ppr_date_of_bf', models.DateField()),
                ('ppr_time_of_bf', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('forwarded_status', models.CharField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_postpartum_records', to='administration.staff')),
                ('followv_id', models.ForeignKey(db_column='followv_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='patientrecords.followupvisit')),
                ('medreq_id', models.ForeignKey(db_column='medreq_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='medicineservices.medicinerequest')),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='patientrecords.patientrecord')),
                ('spouse_id', models.ForeignKey(db_column='spouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='patientrecords.spouse')),
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='administration.staff')),
                ('vital_id', models.ForeignKey(db_column='vital_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='patientrecords.vitalsigns')),
            ],
            options={
                'db_table': 'postpartum_record',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostpartumDeliveryRecord',
            fields=[
                ('ppdr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppdr_date_of_delivery', models.DateField()),
                ('ppdr_time_of_delivery', models.TimeField(blank=True, null=True)),
                ('ppdr_place_of_delivery', models.CharField(max_length=50)),
                ('ppdr_attended_by', models.CharField(max_length=50)),
                ('ppdr_outcome', models.CharField(max_length=50)),
                ('ppr_id', models.ForeignKey(db_column='ppr_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_delivery_record', to='maternal.postpartumrecord')),
            ],
            options={
                'db_table': 'postpartum_delivery_record',
            },
        ),
        migrations.CreateModel(
            name='PostpartumAssessment',
            fields=[
                ('ppa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppa_date_of_visit', models.DateField()),
                ('ppa_feeding', models.CharField(max_length=50)),
                ('ppa_findings', models.TextField()),
                ('ppa_nurses_notes', models.TextField()),
                ('ppr_id', models.ForeignKey(db_column='ppr_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_assessment', to='maternal.postpartumrecord')),
            ],
            options={
                'db_table': 'postpartum_assessment',
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('pregnancy_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pregnancy loss', 'Pregnancy Loss')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prenatal_end_date', models.DateField(blank=True, null=True)),
                ('postpartum_end_date', models.DateField(blank=True, null=True)),
                ('pregnancyloss_reason', models.TextField(blank=True, null=True)),
                ('pat_id', models.ForeignKey(db_column='pat_id', on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy', to='patientrecords.patient')),
            ],
            options={
                'db_table': 'pregnancy',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='postpartumrecord',
            name='pregnancy_id',
            field=models.ForeignKey(blank=True, db_column='pregnancy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='maternal.pregnancy'),
        ),
        migrations.CreateModel(
            name='Prenatal_Form',
            fields=[
                ('pf_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pf_edc', models.DateField(blank=True, null=True)),
                ('pf_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_complications', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('forwarded_status', models.CharField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_prenatal_forms', to='administration.staff')),
                ('bm_id', models.ForeignKey(db_column='bm_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.bodymeasurement')),
                ('followv_id', models.ForeignKey(db_column='followv_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.followupvisit')),
                ('medreq_id', models.ForeignKey(db_column='medreq_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='medicineservices.medicinerequest')),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord')),
                ('pregnancy_id', models.ForeignKey(db_column='pregnancy_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='maternal.pregnancy')),
                ('spouse_id', models.ForeignKey(db_column='spouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.spouse')),
                ('staff', models.ForeignKey(db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='administration.staff')),
                ('vacrec_id', models.ForeignKey(db_column='vacrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='vaccination.vaccinationrecord')),
                ('vital_id', models.ForeignKey(db_column='vital_id', on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.vitalsigns')),
            ],
            options={
                'db_table': 'prenatal_form',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObstetricRiskCode',
            fields=[
                ('pforc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pforc_prev_c_section', models.BooleanField(default=False, help_text='Previous C-section')),
                ('pforc_3_consecutive_miscarriages', models.BooleanField(blank=True, default=False, help_text='3 consecutive miscarriages of stillborn baby')),
                ('pforc_postpartum_hemorrhage', models.BooleanField(blank=True, default=False, help_text='Previous postpartum hemorrhage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_obstetric_risk_code', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_obstetric_risk_codes',
            },
        ),
        migrations.AddField(
            model_name='laboratoryresult',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_result', to='maternal.prenatal_form'),
        ),
        migrations.CreateModel(
            name='Guide4ANCVisit',
            fields=[
                ('pfav_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfav_1st_tri', models.DateField(blank=True, null=True)),
                ('pfav_2nd_tri', models.DateField(blank=True, null=True)),
                ('pfav_3rd_tri_one', models.DateField(blank=True, null=True)),
                ('pfav_3rd_tri_two', models.DateField(blank=True, null=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_anc_visit', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_anc_visit',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('pfc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('increased_bp', models.BooleanField(blank=True, default=False)),
                ('nausea', models.BooleanField(blank=True, default=False)),
                ('edema', models.BooleanField(blank=True, default=False)),
                ('abno_vaginal_disch', models.BooleanField(blank=True, default=False)),
                ('chills_fever', models.BooleanField(blank=True, default=False)),
                ('varicosities', models.BooleanField(blank=True, default=False)),
                ('epigastric_pain', models.BooleanField(blank=True, default=False)),
                ('blurring_vision', models.BooleanField(blank=True, default=False)),
                ('severe_headache', models.BooleanField(blank=True, default=False)),
                ('vaginal_bleeding', models.BooleanField(blank=True, default=False)),
                ('diff_in_breathing', models.BooleanField(blank=True, default=False)),
                ('abdominal_pain', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_checklist', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_checklist',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthPlan',
            fields=[
                ('pfbp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_of_delivery_plan', models.CharField(blank=True, default='', max_length=100)),
                ('newborn_screening_plan', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_birth_plan', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_birth_plan',
            },
        ),
        migrations.CreateModel(
            name='PrenatalCare',
            fields=[
                ('pfpc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfpc_date', models.DateField(blank=True, null=True)),
                ('pfpc_aog_wks', models.IntegerField(blank=True, help_text='Age of Gestation in weeks', null=True)),
                ('pfpc_aog_days', models.IntegerField(blank=True, help_text='Age of Gestation in days', null=True)),
                ('pfpc_fundal_ht', models.DecimalField(blank=True, decimal_places=2, help_text='Fundal height measurement', max_digits=5, null=True)),
                ('pfpc_fetal_hr', models.IntegerField(blank=True, help_text='Fetal heart rate', null=True)),
                ('pfpc_fetal_pos', models.CharField(blank=True, default='', help_text='Fetal position', max_length=50)),
                ('pfpc_complaints', models.TextField(blank=True, default='')),
                ('pfpc_advises', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_prenatal_care', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_prenatal_care',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Previous_Hospitalization',
            fields=[
                ('pfph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prev_hospitalization', models.CharField(blank=True, default='', max_length=250)),
                ('prev_hospitalization_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_hospitalization', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_previous_hospitalization',
            },
        ),
        migrations.CreateModel(
            name='Previous_Pregnancy',
            fields=[
                ('pfpp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('type_of_delivery', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('babys_wt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gender', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ballard_score', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_score', models.PositiveIntegerField(blank=True, null=True)),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_pregnancy', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'previous_pregnancy',
            },
        ),
        migrations.CreateModel(
            name='TT_Status',
            fields=[
                ('tts_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tts_status', models.CharField(blank=True, default='', max_length=10)),
                ('tts_date_given', models.DateField(blank=True, null=True)),
                ('tts_tdap', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pat_id', models.ForeignKey(db_column='pat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tt_status', to='patientrecords.patient')),
            ],
            options={
                'db_table': 'tt_status',
            },
        ),
        migrations.AddField(
            model_name='postpartumrecord',
            name='tts_id',
            field=models.ForeignKey(blank=True, db_column='tts_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='maternal.tt_status'),
        ),
        migrations.CreateModel(
            name='PrenatalAppointmentRequest',
            fields=[
                ('par_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('rejected_at', models.DateField(blank=True, null=True)),
                ('missed_at', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('pat_id', models.ForeignKey(db_column='pat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pa_request', to='patientrecords.patient')),
                ('rp_id', models.ForeignKey(db_column='rp_id', on_delete=django.db.models.deletion.CASCADE, related_name='pa_request', to='healthProfiling.residentprofile')),
            ],
            options={
                'db_table': 'prenatal_appointment_request',
                'indexes': [models.Index(fields=['status', 'requested_date'], name='prenatal_ap_status_289e5d_idx'), models.Index(fields=['pat_id', 'status'], name='prenatal_ap_pat_id_be379c_idx')],
            },
        ),
    ]
