# Generated by Django 5.1.6 on 2025-04-25 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenatal_Form',
            fields=[
                ('pf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pf_lmp', models.DateField()),
                ('pf_edc', models.DateField()),
                ('patrec_id', models.OneToOneField(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'prenatal_form',
            },
        ),
        migrations.CreateModel(
            name='Lab_Result_Dates',
            fields=[
                ('pflr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pflr_urinalysis', models.DateField()),
                ('pflr_cbc', models.DateField()),
                ('pflr_sgot_sgpt', models.DateField()),
                ('pflr_creatinine_serum', models.DateField()),
                ('pflr_bua_bun', models.DateField()),
                ('pflr_syphillis', models.DateField()),
                ('pflr_hiv_test', models.DateField()),
                ('pflr_hepa_b', models.DateField()),
                ('pflr_ogct_50', models.DateField()),
                ('pflr_ogct_100', models.DateField()),
                ('pflr_lab_remarks', models.CharField(max_length=250)),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_lab_result_dates', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_lab_result_dates',
            },
        ),
        migrations.CreateModel(
            name='Guide4ANCVisit',
            fields=[
                ('pfav_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfav_1st_tri', models.DateField()),
                ('pfav_2nd_tri', models.DateField()),
                ('pfav_3rd_tri', models.DateField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_anc_visit', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_anc_visit',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('pfc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfc_increased_bp', models.BooleanField()),
                ('pfc_nausea', models.BooleanField()),
                ('pfc_edema', models.BooleanField()),
                ('pfc_abno_vaginal_disch', models.BooleanField()),
                ('pfc_chills_fever', models.BooleanField()),
                ('pfc_varicosities', models.BooleanField()),
                ('pfc_epigastric_pain', models.BooleanField()),
                ('pfc_blurring_vision', models.BooleanField()),
                ('pfc_severe_headache', models.BooleanField()),
                ('pfc_vaginal_bleeding', models.BooleanField()),
                ('pfc_diff_in_bleeding', models.BooleanField()),
                ('pfc_abdominal_pain', models.BooleanField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_checklist', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_checklist',
            },
        ),
        migrations.CreateModel(
            name='Previous_Hospitalization',
            fields=[
                ('pfph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfph_prev_hospi', models.CharField(max_length=250)),
                ('pfph_prev_hospi_year', models.PositiveIntegerField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_hospitalization', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_previous_hospitalization',
            },
        ),
        migrations.CreateModel(
            name='Previous_Pregnancy',
            fields=[
                ('pfpp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfpp_date_of_delivery', models.DateField()),
                ('pfpp_outcome', models.CharField(max_length=50)),
                ('pfpp_type_of_delivery', models.CharField(max_length=50)),
                ('pfpp_babys_wt', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('pfpp_gender', models.CharField(max_length=10)),
                ('pfpp_ballard_score', models.PositiveIntegerField()),
                ('pfpp_apgar_score', models.PositiveIntegerField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_pregnancy', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_previous_pregnancy',
            },
        ),
        migrations.CreateModel(
            name='TT_Status',
            fields=[
                ('pfts_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfts_vaccine_type', models.CharField(max_length=100)),
                ('pfts_status', models.CharField(max_length=10)),
                ('pfts_date_given', models.DateField()),
                ('pfts_fim', models.BooleanField()),
                ('pfts_tdap', models.BooleanField(default=False)),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_tt_status', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_tt_status',
            },
        ),
    ]
