# Generated by Django 5.1.6 on 2025-04-21 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obstetrical_History',
            fields=[
                ('obs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obs_ch_born_alive', models.PositiveIntegerField()),
                ('obs_living_ch', models.PositiveIntegerField()),
                ('obs_abortion', models.PositiveIntegerField()),
                ('obs_still_birth', models.PositiveIntegerField()),
                ('obs_lg_babies', models.PositiveIntegerField()),
                ('obs_gravida', models.PositiveIntegerField()),
                ('obs_para', models.PositiveIntegerField()),
                ('obs_fullterm', models.PositiveIntegerField()),
                ('obs_preterm', models.PositiveIntegerField()),
                ('obs_record_from', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'obstetrical_history',
            },
        ),
        migrations.CreateModel(
            name='Prenatal_Form',
            fields=[
                ('pf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pf_h_lname', models.CharField(max_length=100)),
                ('pf_h_fname', models.CharField(max_length=100)),
                ('pf_h_mname', models.CharField(max_length=100)),
                ('pf_lmp', models.DateField()),
                ('pf_edc', models.DateField()),
            ],
            options={
                'db_table': 'prenatal_form',
            },
        ),
        migrations.CreateModel(
            name='Lab_Result_Dates',
            fields=[
                ('pflr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pflr_urinalysis', models.DateField()),
                ('pflr_cbc', models.DateField()),
                ('pflr_sgot_sgpt', models.DateField()),
                ('pflr_creatinine_serum', models.DateField()),
                ('pflr_bua_bun', models.DateField()),
                ('pflr_syphillis', models.DateField()),
                ('pflr_hiv_test', models.DateField()),
                ('pflr_hepa_b', models.DateField()),
                ('pflr_ogct_50', models.DateField()),
                ('pflr_ogct_100', models.DateField()),
                ('pflr_lab_remarks', models.CharField(max_length=250)),
                ('pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_lab_result',
            },
        ),
        migrations.CreateModel(
            name='Previous_Hospitalization',
            fields=[
                ('pfph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfph_prev_hospi', models.CharField(max_length=250)),
                ('pfph_prev_hospi_year', models.PositiveIntegerField()),
                ('pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_previous_hospitalization',
            },
        ),
        migrations.CreateModel(
            name='Previous_Pregnancy',
            fields=[
                ('pfpp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfpp_date_of_delivery', models.DateField()),
                ('pfpp_outcome', models.CharField(max_length=50)),
                ('pfpp_type_of_delivery', models.CharField(max_length=50)),
                ('pfpp_babys_wt', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('pfpp_gender', models.CharField(max_length=10)),
                ('pfpp_ballard_score', models.PositiveIntegerField()),
                ('pfpp_apgar_score', models.PositiveIntegerField()),
                ('pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_previous_pregnancy',
            },
        ),
        migrations.CreateModel(
            name='TT_Status',
            fields=[
                ('pfts_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfts_vaccine_type', models.CharField(max_length=100)),
                ('pfts_status', models.CharField(max_length=10)),
                ('pfts_date_given', models.DateField()),
                ('pfts_fim', models.BooleanField()),
                ('pfts_tdap', models.BooleanField(default=False)),
                ('pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_tt_status',
            },
        ),
    ]
