# Generated by Django 5.1.6 on 2025-06-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0001_initial'),
        ('patientrecords', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('pfc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfc_increased_bp', models.BooleanField()),
                ('pfc_nausea', models.BooleanField()),
                ('pfc_edema', models.BooleanField()),
                ('pfc_abno_vaginal_disch', models.BooleanField()),
                ('pfc_chills_fever', models.BooleanField()),
                ('pfc_varicosities', models.BooleanField()),
                ('pfc_epigastric_pain', models.BooleanField()),
                ('pfc_blurring_vision', models.BooleanField()),
                ('pfc_severe_headache', models.BooleanField()),
                ('pfc_vaginal_bleeding', models.BooleanField()),
                ('pfc_diff_in_bleeding', models.BooleanField()),
                ('pfc_abdominal_pain', models.BooleanField()),
            ],
            options={
                'db_table': 'pf_checklist',
            },
        ),
        migrations.CreateModel(
            name='Guide4ANCVisit',
            fields=[
                ('pfav_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfav_1st_tri', models.DateField()),
                ('pfav_2nd_tri', models.DateField()),
                ('pfav_3rd_tri_one', models.DateField()),
                ('pfav_3rd_tri_two', models.DateField()),
            ],
            options={
                'db_table': 'pf_anc_visit',
            },
        ),
        migrations.CreateModel(
            name='PostpartumAssessment',
            fields=[
                ('ppa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppa_date_of_visit', models.DateField()),
                ('ppa_systolic', models.PositiveIntegerField()),
                ('ppa_diastolic', models.PositiveIntegerField()),
                ('ppa_feeding', models.CharField(max_length=50)),
                ('ppa_findings', models.TextField()),
                ('ppa_nurses_notes', models.TextField()),
            ],
            options={
                'db_table': 'postpartum_assessment',
            },
        ),
        migrations.CreateModel(
            name='PostpartumDeliveryRecord',
            fields=[
                ('ppdr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppdr_date_of_delivery', models.DateField()),
                ('ppdr_time_of_delivery', models.TimeField()),
                ('ppdr_place_of_delivery', models.CharField(max_length=50)),
                ('ppdr_attended_by', models.CharField(max_length=50)),
                ('ppdr_outcome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'postpartum_delivery_record',
            },
        ),
        migrations.CreateModel(
            name='PostpartumRecord',
            fields=[
                ('ppr_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ppr_transferred_fr', models.CharField(default='Not Applicable', max_length=100)),
                ('ppr_tor', models.CharField(default='Not Applicable', max_length=100)),
                ('ppr_lochial_discharges', models.CharField(max_length=100)),
                ('ppr_vit_a_date_given', models.DateField()),
                ('ppr_num_of_pads', models.PositiveIntegerField()),
                ('ppr_mebendazole_date_given', models.DateField()),
                ('ppr_date_of_bf', models.DateField()),
                ('ppr_time_of_bf', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patrec_id', models.ForeignKey(db_column='patrec_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='patientrecords.patientrecord')),
            ],
            options={
                'db_table': 'postpartum_record',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='lab_result_dates',
            name='pf_id',
        ),
        migrations.DeleteModel(
            name='Obstetrical_History',
        ),
        migrations.AlterModelOptions(
            name='prenatal_form',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='prenatal_form',
            name='pf_h_fname',
        ),
        migrations.RemoveField(
            model_name='prenatal_form',
            name='pf_h_lname',
        ),
        migrations.RemoveField(
            model_name='prenatal_form',
            name='pf_h_mname',
        ),
        migrations.AddField(
            model_name='prenatal_form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenatal_form',
            name='patrec_id',
            field=models.ForeignKey(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord'),
        ),
        migrations.AddField(
            model_name='prenatal_form',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prenatal_form',
            name='pf_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='previous_hospitalization',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_hospitalization', to='maternal.prenatal_form'),
        ),
        migrations.AlterField(
            model_name='previous_pregnancy',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_pregnancy', to='maternal.prenatal_form'),
        ),
        migrations.AlterField(
            model_name='tt_status',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_tt_status', to='maternal.prenatal_form'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_checklist', to='maternal.prenatal_form'),
        ),
        migrations.AddField(
            model_name='guide4ancvisit',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_anc_visit', to='maternal.prenatal_form'),
        ),
        migrations.AddField(
            model_name='postpartumrecord',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='maternal.prenatal_form'),
        ),
        migrations.AddField(
            model_name='postpartumdeliveryrecord',
            name='ppr_id',
            field=models.ForeignKey(db_column='ppr_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_delivery_record', to='maternal.postpartumrecord'),
        ),
        migrations.AddField(
            model_name='postpartumassessment',
            name='ppr_id',
            field=models.ForeignKey(db_column='ppr_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_assessment', to='maternal.postpartumrecord'),
        ),
        migrations.DeleteModel(
            name='Lab_Result_Dates',
        ),
    ]
