# Generated by Django 5.1.6 on 2025-04-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0002_rename_lab_result_lab_result_dates_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obstetrical_history',
            table='obstetrical_history',
        ),
    ]
