# Generated by Django 5.1.6 on 2025-04-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0003_obstetrical_history'),
        ('patientrecords', '0020_obstetrical_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obstetrical_History',
        ),
        migrations.AddField(
            model_name='prenatal_form',
            name='patrec_id',
            field=models.ForeignKey(db_column='patrec_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab_result_dates',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_lab_result_dates', to='maternal.prenatal_form'),
        ),
        migrations.AlterField(
            model_name='previous_hospitalization',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_hospitalization', to='maternal.prenatal_form'),
        ),
        migrations.AlterField(
            model_name='previous_pregnancy',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_previous_pregnancy', to='maternal.prenatal_form'),
        ),
        migrations.AlterField(
            model_name='tt_status',
            name='pf_id',
            field=models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_tt_status', to='maternal.prenatal_form'),
        ),
        migrations.AlterModelTable(
            name='lab_result_dates',
            table='pf_lab_result_dates',
        ),
    ]
