# Generated by Django 5.1.6 on 2025-04-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0004_delete_obstetrical_history_prenatal_form_patrec_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatal_form',
            name='patrec_id',
        ),
    ]
