# Generated by Django 5.1.6 on 2025-04-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0006_prenatal_form_patrec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatal_form',
            name='pf_h_fname',
        ),
        migrations.RemoveField(
            model_name='prenatal_form',
            name='pf_h_lname',
        ),
        migrations.RemoveField(
            model_name='prenatal_form',
            name='pf_h_mname',
        ),
    ]
