# Generated by Django 5.1.6 on 2025-04-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0007_remove_prenatal_form_pf_h_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatal_form',
            name='patrec_id',
        ),
    ]
