# Generated by Django 5.1.6 on 2025-04-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0009_prenatal_form_patrec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatal_form',
            name='patrec_id',
        ),
    ]
