# Generated by Django 5.1.6 on 2025-04-24 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0010_remove_prenatal_form_patrec_id'),
        ('patientrecords', '0023_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenatal_form',
            name='patrec_id',
            field=models.ForeignKey(db_column='patrec_id', default=138, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord'),
        ),
    ]
