# Generated by Django 5.1.6 on 2025-04-24 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0011_prenatal_form_patrec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatal_form',
            name='patrec_id',
        ),
        migrations.CreateModel(
            name='BirthPlan',
            fields=[
                ('pfbp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfbp_pob_plan', models.DateField()),
                ('pfbp_newborn_s_plan', models.DateField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_birth_plan', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_birth_plan',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('pfc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfc_increased_bp', models.BooleanField()),
                ('pfc_nausea', models.BooleanField()),
                ('pfc_edema', models.BooleanField()),
                ('pfc_abno_vaginal_disch', models.BooleanField()),
                ('pfc_chills_fever', models.BooleanField()),
                ('pfc_varicosities', models.BooleanField()),
                ('pfc_epigastric_pain', models.BooleanField()),
                ('pfc_blurring_vision', models.BooleanField()),
                ('pfc_severe_headache', models.BooleanField()),
                ('pfc_vaginal_bleeding', models.BooleanField()),
                ('pfc_diff_in_bleeding', models.BooleanField()),
                ('pfc_abdominal_pain', models.BooleanField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_checklist', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_checklist',
            },
        ),
        migrations.CreateModel(
            name='Guide4ANCVisit',
            fields=[
                ('pfav_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfav_1st_tri', models.DateField()),
                ('pfav_2nd_tri', models.DateField()),
                ('pfav_3rd_tri', models.DateField()),
                ('pf_id', models.ForeignKey(db_column='pf_id', on_delete=django.db.models.deletion.CASCADE, related_name='pf_anc_visit', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'pf_anc_visit',
            },
        ),
    ]
