# Generated by Django 5.1.6 on 2025-04-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0012_remove_prenatal_form_patrec_id_birthplan_checklist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthPlan',
        ),
    ]
