# Generated by Django 5.1.6 on 2025-04-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0013_delete_birthplan'),
        ('patientrecords', '0025_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenatal_form',
            name='patrec_id',
            field=models.ForeignKey(db_column='patrec_id', default=138, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord'),
        ),
    ]
