# Generated by Django 5.1.6 on 2025-04-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0015_remove_prenatal_form_patrec_id'),
        ('patientrecords', '0025_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenatal_form',
            name='patrec_id',
            field=models.OneToOneField(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord'),
        ),
    ]
