# Generated by Django 5.1.6 on 2025-06-07 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0016_prenatal_form_patrec_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide4ancvisit',
            old_name='pfav_3rd_tri',
            new_name='pfav_3rd_tri_one',
        ),
        migrations.AddField(
            model_name='guide4ancvisit',
            name='pfav_3rd_tri_two',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenatal_form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenatal_form',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Lab_Result_Dates',
        ),
    ]
