# Generated by Django 5.2.3 on 2025-06-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal', '0017_rename_pfav_3rd_tri_guide4ancvisit_pfav_3rd_tri_one_and_more'),
        ('patientrecords', '0027_remove_patient_per_id_remove_spouse_pat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenatal_form',
            name='patrec_id',
            field=models.ForeignKey(db_column='patrec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_form', to='patientrecords.patientrecord'),
        ),
        migrations.AlterField(
            model_name='prenatal_form',
            name='pf_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PostpartumRecord',
            fields=[
                ('ppr_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ppr_transferred_fr', models.CharField(default='Not Applicable', max_length=100)),
                ('ppr_tor', models.CharField(default='Not Applicable', max_length=100)),
                ('ppr_lochial_discharges', models.CharField(max_length=100)),
                ('ppr_vit_a_date_given', models.DateField()),
                ('ppr_num_of_pads', models.PositiveIntegerField()),
                ('ppr_mebendazole_date_given', models.DateField()),
                ('ppr_date_of_bf', models.DateField()),
                ('ppr_time_of_bf', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pf_id', models.ForeignKey(db_column='pf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_record', to='maternal.prenatal_form')),
            ],
            options={
                'db_table': 'postpartum_record',
            },
        ),
        migrations.CreateModel(
            name='PostpartumDeliveryRecord',
            fields=[
                ('ppdr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppdr_date_of_delivery', models.DateField()),
                ('ppdr_time_of_delivery', models.TimeField()),
                ('ppdr_place_of_delivery', models.CharField(max_length=50)),
                ('ppdr_attended_by', models.CharField(max_length=50)),
                ('ppdr_outcome', models.CharField(max_length=50)),
                ('ppr_id', models.ForeignKey(db_column='ppr_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_delivery_record', to='maternal.postpartumrecord')),
            ],
            options={
                'db_table': 'postpartum_delivery_record',
            },
        ),
        migrations.CreateModel(
            name='PostpartumAssessment',
            fields=[
                ('ppa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppa_date_of_visit', models.DateField()),
                ('ppa_systolic', models.PositiveIntegerField()),
                ('ppa_diastolic', models.PositiveIntegerField()),
                ('ppa_feeding', models.CharField(max_length=50)),
                ('ppa_findings', models.TextField()),
                ('ppa_nurses_notes', models.TextField()),
                ('ppr_id', models.ForeignKey(db_column='ppr_id', on_delete=django.db.models.deletion.CASCADE, related_name='postpartum_assessment', to='maternal.postpartumrecord')),
            ],
            options={
                'db_table': 'postpartum_assessment',
            },
        ),
    ]
