"use client"

import { api2 } from "@/api/api"
import axios from "axios"


export interface PrenatalRecord {
  pat_id: string
  patrec_type: string
  pf_occupation: string
  pf_edc: string | null
  assessed_by: string
  previous_complications: string | null
  spouse_data?: {
    spouse_type: string
    spouse_lname: string
    spouse_fname: string
    spouse_mname: string
    spouse_occupation: string
    spouse_dob: string | null
  }
  body_measurement: {
    // age: string | null
    weight: number | null
    height: number | null
    // bmi: number | null
  }
  obstetrical_history?: {
    obs_ch_born_alive: number | null
    obs_living_ch: number | null
    obs_abortion: number | null
    obs_still_birth: number | null
    obs_lg_babies: number | null
    obs_lg_babies_str: boolean | null
    obs_gravida: number | null
    obs_para: number | null
    obs_fullterm: number | null
    obs_preterm: number | null
    obs_lmp: string | null
  }
  medical_history?: Array<{
    year: number | null
    ill: number | null
  }>
  previous_hospitalizations: Array<{
    prev_hospitalization: string
    prev_hospitalization_year: number | null
  }>
  previous_pregnancy_data?: {
    date_of_delivery: string | null
    outcome: string | null
    type_of_delivery: string | null
    babys_wt: number | null
    gender: string | null
    ballard_score: number | null
    apgar_score: number | null
  }
  tt_statuses: Array<{
    tts_status: string | null
    tts_date_given: string | null
    vaccineType?: string  // Vaccine stock information for creating vaccination records
  }>
  lab_results_data: Array<{
    lab_type: string
    result_date: string | null
    to_be_followed: boolean
    document_path: string
    remarks: string
    images: Array<{
      image_url: string | ''
      image_name: string | ''
      image_type: string | ""
      image_size: number | undefined
    }>
  }>
  anc_visit_data?: {
    pfav_1st_tri: string | null
    pfav_2nd_tri: string | null
    pfav_3rd_tri_one: string | null
    pfav_3rd_tri_two: string | null
  }
  followup_date: string | null
  followup_description: string
  checklist_data: {
    increased_bp: boolean | false
    epigastric_pain: boolean | false
    nausea: boolean | false
    blurring_vision: boolean | false
    edema: boolean | false
    severe_headache: boolean | false
    abno_vaginal_disch: boolean | false
    vaginal_bleeding: boolean | false
    chills_fever: boolean | false
    diff_in_breathing: boolean | false
    varicosities: boolean | false
    abdominal_pain: boolean | false
  }
  birth_plan_data: {
    place_of_delivery_plan: string | ""
    newborn_screening_plan: boolean
  }
  obstetric_risk_code_data: {
    pforc_prev_c_section: boolean
    pforc_3_consecutive_miscarriages: boolean
    pforc_postpartum_hemorrhage: boolean
  }
  prenatal_care_data: Array<{
    pfpc_date: string
    pfpc_aog_wks: number | null
    pfpc_aog_days: number | null
    pfpc_fundal_ht: string | null
    pfpc_fetal_hr: string | null
    pfpc_fetal_pos: string | ""
    pfpc_complaints: string | null
    pfpc_advises: string | null
  }>
  vital_bp_systolic: number | null
  vital_bp_diastolic: number | null
  selected_medicines?: Array<{
    minv_id: string
    medrec_qty: number
    reason: string
  }>
  vacrec_totaldose?: number | null 
}

export const addPrenatalRecord = async (data: PrenatalRecord) => {
  try {
    console.log("Sending Prenatal Record Data: ", data)
    const res = await api2.post("maternal/prenatal-record/", data)

    return res.data.pf_id
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Prenatal Records Error: ", error.response?.data || error.message)
    } else {
      console.error("Unexpected Error: ", error)
    }
    throw error
  }
}

// illness post method in prenatal
export interface IllnessData {
  illname: string
}

export const addIllnessData = async (data: IllnessData) => {
  try {
    const res = await api2.post("maternal/prenatal/illness/create/", data)
    return res.data
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Add Illness Data Error: ", error.response?.data || error.message)
    } else {
      console.error("Unexpected Error: ", error)
    }
    throw error
  }
} 

export interface PostpartumCompleteData {
  pat_id: string
  patrec_type: string
  patrec_id?: number // Make optional since it will be generated by API
  ppr_lochial_discharges: string
  // ppr_vit_a_date_given: string
  ppr_num_of_pads: number
  // ppr_mebendazole_date_given: string
  ppr_date_of_bf: string
  ppr_time_of_bf: string
  delivery_record: {
    ppdr_date_of_delivery: string
    ppdr_time_of_delivery: string
    ppdr_place_of_delivery: string
    ppdr_attended_by: string
    ppdr_outcome: string
  }
  assessments: Array<{
    ppa_date_of_visit: string
    ppa_feeding: string
    ppa_findings: string
    ppa_nurses_notes: string
  }>
  spouse_data?: {
    spouse_type: string
    spouse_lname: string
    spouse_fname: string
    spouse_mname: string
    spouse_occupation: string
    spouse_dob: string
  }
  vital_bp_systolic: string
  vital_bp_diastolic: string
  followup_date: string
  followup_description: string
}

// Response interface for what the API returns
export interface PostpartumResponse {
  ppr_id: number
  patrec_id: number
  message: string
}

export const addPostpartumRecord = async (data: PostpartumCompleteData): Promise<PostpartumResponse> => {
  try {
    console.log("Sending postpartum data to API:", data)

    const res = await api2.post("maternal/postpartum_record/", data)

    console.log("Postpartum record created successfully:", res.data)

    return res.data
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Postpartum Records Error: ", error.response?.data || error.message)
    } else {
      console.error("Unexpected Error: ", error)
    }
    throw error
  }
}


// for marking pregnancy as complete
export interface CompletePregnancyData {
  pat_id: string;
  pregnancy_id: string;
}

export const addCompletePregnancy = async (data: CompletePregnancyData) => {
  try {
    const res = await api2.post("maternal/pregnancy/complete/", data);
    return res.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Complete Pregnancy Error: ", error.response?.data || error.message);
    } else {
      console.error("Unexpected Error: ", error);
    }
    throw error;
  }
};

// for marking pregnancy as loss
export interface PregnancyLossData {
  pat_id: string;
  pregnancy_id: string;
}

export const addPregnancyLoss = async (data: PregnancyLossData) => {
  try {
    const res = await api2.post("maternal/pregnancy/loss/", data);
    return res.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Pregnancy Loss Error: ", error.response?.data || error.message);
    } else {
      console.error("Unexpected Error: ", error);
    }
    throw error;
  }
}