import { api2 } from "@/api/api"
import axios from "axios"

interface PrenatalRecord {
  pf_lmp: string
  pf_edc: string
  patrec_id: number
}

export const addPrenatalRecord = async (data: PrenatalRecord) => {
  try {
    if (!data.patrec_id) {
      console.error("Missing Patient Record ID (patrec_id) in form data")
      throw new Error("Patient Record ID is required")
    }

    console.log("Sending Prenatal Record Data: ", data)
    const res = await api2.post("maternal/prenatal_record/", data)

    return res.data.pf_id
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Prenatal Records Error: ", error.response?.data || error.message)
    } else {
      console.error("Unexpected Error: ", error)
    }
    throw error
  }
}

export interface PostpartumCompleteData {
  pat_id: string
  patrec_type: string
  patrec_id?: number // Make optional since it will be generated by API
  // REMOVED ppr_transferred_fr since it's deleted from model
  ppr_lochial_discharges: string
  ppr_vit_a_date_given: string
  ppr_num_of_pads: string
  ppr_mebendazole_date_given: string
  ppr_date_of_bf: string
  ppr_time_of_bf: string
  delivery_record: {
    ppdr_date_of_delivery: string
    ppdr_time_of_delivery: string
    ppdr_place_of_delivery: string
    ppdr_attended_by: string
    ppdr_outcome: string
  }
  assessments: Array<{
    ppa_date_of_visit: string
    ppa_feeding: string
    ppa_findings: string
    ppa_nurses_notes: string
  }>
  spouse_data?: {
    spouse_type: string
    spouse_lname: string
    spouse_fname: string
    spouse_mname: string
    spouse_occupation: string
    spouse_dob: string
  }
  vital_bp_systolic: string
  vital_bp_diastolic: string
  followup_date: string
  followup_description: string
}

// Response interface for what the API returns
export interface PostpartumResponse {
  ppr_id: number
  patrec_id: number
  message: string
}

export const addPostpartumRecord = async (data: PostpartumCompleteData): Promise<PostpartumResponse> => {
  try {
    console.log("Sending postpartum data to API:", data)

    const res = await api2.post("maternal/postpartum_record/", data)

    console.log("Postpartum record created successfully:", res.data)

    return res.data
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Postpartum Records Error: ", error.response?.data || error.message)
    } else {
      console.error("Unexpected Error: ", error)
    }
    throw error
  }
}

export const getPostpartumRecords = async () => {
  try {
    const res = await api2.get("maternal/postpartum_records/")
    return res.data
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Get Postpartum Records Error: ", error.response?.data || error.message)
    }
    throw error
  }
}

export const getPostpartumRecordDetail = async (ppr_id: string) => {
  try {
    const res = await api2.get(`maternal/postpartum_record/${ppr_id}/`)
    return res.data
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error("Get Postpartum Record Detail Error: ", error.response?.data || error.message)
    }
    throw error
  }
}
